objects/ASI_CRM_Promotion_Plan__c.object
<CustomObject>
    <label>Promotion Plan</label>
    <nameField>
        <label>Promotion Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Voucher_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Promotion_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Detail</label>
        <referenceTo>ASI_HK_CRM_Promotion_Detail__c</referenceTo>
        <relationshipLabel>Voucher Details</relationshipLabel>
        <relationshipName>Voucher_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotion_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Plan</label>
        <referenceTo>ASI_CRM_Promotion_Plan__c</referenceTo>
        <relationshipLabel>Voucher Details</relationshipLabel>
        <relationshipName>Voucher_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Voucher_Header__c</fullName>
        <label>Voucher Header</label>
        <referenceTo>ASI_CRM_Voucher__c</referenceTo>
        <relationshipLabel>Voucher Details</relationshipLabel>
        <relationshipName>Voucher_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Voucher Detail</label>
    <nameField>
        <displayFormat>VD-{000000}</displayFormat>
        <label>Voucher Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion</description>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion Detail</description>
    <fields>
        <fullName>ASI_HK_CRM_Promotion__c</fullName>
        <label>Promotion Code</label>
        <referenceTo>ASI_HK_CRM_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Details</relationshipLabel>
        <relationshipName>ASI_HK_CRM_Promotion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Promotion Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_VoucherSummaryCtrl.cls
/*********************************************************************************
 * Name: ASI_CRM_SG_VoucherSummaryCtrl
 * Description: Controller class for ASI_CRM_SG_PaymentSummaryPage 
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 2018-04-15    	Laputa: Vincent      	Create
 */


public without sharing class ASI_CRM_SG_VoucherSummaryCtrl extends ASI_CRM_SG_PageControllerBase {
    
	public set<string> set_promotionName {get;set;}
	public list<ASI_CRM_Voucher_Detail__c> childs {get;set;}
	public integer promotionSize {get;set;}
	
    public ASI_CRM_SG_VoucherSummaryCtrl(ApexPages.StandardController standardController){
		set_promotionName = new set<string>();
		childs = getChilds(standardController.getId());
		set_promotionName = getPromotionName(childs);
		promotionSize = set_promotionName.size();
	}
	
	private list<ASI_CRM_Voucher_Detail__c> getChilds(String headerId){
		return [
			select ASI_CRM_Promotion_Detail__c, ASI_CRM_Promotion_Detail__r.ASI_HK_CRM_Promotion__r.ASI_CRM_Promotion_Plan__r.Name
			from ASI_CRM_Voucher_Detail__c
			where
			ASI_CRM_Voucher_Header__c = :headerId
		];
	}
	
	private set<string> getPromotionName(list<ASI_CRM_Voucher_Detail__c> childs){
		set<string> s = new set<string>();
		for(ASI_CRM_Voucher_Detail__c l : childs){
			if(l.ASI_CRM_Promotion_Detail__c != null){
				s.add(l.ASI_CRM_Promotion_Detail__r.ASI_HK_CRM_Promotion__r.ASI_CRM_Promotion_Plan__r.Name);
			}
		}
		return s;
	}
	
}