objects/ASI_CRM_Item_Group_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Commercial_Team__c</fullName>
        <label>Commercial Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prestige</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>HQ/Hotel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cut Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Item Group Allocations</relationshipLabel>
        <relationshipName>Item_Group_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_MTD_Order_Quantity__c</fullName>
        <label>MTD Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>ASI_CRM_Region__c</referenceTo>
        <relationshipLabel>Item Group Allocations</relationshipLabel>
        <relationshipName>Item_Group_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Group Allocation</label>
    <nameField>
        <displayFormat>IGA-{MM}{YY}{0000}</displayFormat>
        <label>Item Group Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Group Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Region__c.object
<CustomObject>
    <description>ASI_CRM_Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Sales Order Requests (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR-{00000000}</displayFormat>
        <label>Sales Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Sales Order Request Items</relationshipLabel>
        <relationshipName>Sales_Order_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Order_Qty_Bottle__c</fullName>
        <formula>IF(ASI_CRM_CN_UOM__c == &quot;CA&quot;, ASI_KOR_Order_Qty__c *  ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_Pack_Value__c, ASI_KOR_Order_Qty__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Qty(Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Sales_Order_Request__c</fullName>
        <label>Sales Order Request</label>
        <referenceTo>ASI_KOR_Sales_Order_Request__c</referenceTo>
        <relationshipName>ASI_KOR_Sales_Order_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Request Item</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Sales Order Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_ItemGp_Allocation_TriggerCls.cls
Public without Sharing class ASI_CRM_CN_ItemGp_Allocation_TriggerCls {

    Public Static void beforeInsertFunction(List<ASI_CRM_Item_Group_Allocation__c> triggerNew){
        
        calculateRemainingQty(triggerNew, Null);
    }
    
    Public Static void beforeUpdateFunction(List<ASI_CRM_Item_Group_Allocation__c> triggerNew, Map<Id, ASI_CRM_Item_Group_Allocation__c> triggerOldMap){
        
        calculateRemainingQty(triggerNew, triggerOldMap);
    }
    
    Public Static void calculateRemainingQty(List<ASI_CRM_Item_Group_Allocation__c> triggerNew, Map<Id, ASI_CRM_Item_Group_Allocation__c> triggerOldMap){
        
        Set<Id> regionSet = new Set<Id>();
        Set<Id> allocatedItemGroup = new Set<Id>();
        Set<String> commercialTeamSet = new Set<String>();
        Map<String, ASI_CRM_Item_Group_Allocation__c> allocationMap = new Map<String, ASI_CRM_Item_Group_Allocation__c>();
        Date startDate;
        Date endDate;
        
        for(ASI_CRM_Item_Group_Allocation__c obj : triggerNew){
            
            if( (!obj.ASI_CRM_Inactive__c && triggerOldMap == Null || !(obj.ASI_CRM_Inactive__c && triggerOldMap.get(obj.id).ASI_CRM_Inactive__c ))){
                regionSet.add(obj.ASI_CRM_Region__c);
                allocatedItemGroup.add(obj.ASI_CRM_Item_Group__c);
                commercialTeamSet.add(obj.ASI_CRM_Commercial_Team__c);
                
                if(startDate == Null || startDate > obj.ASI_CRM_Effective_Date__c)
                    startDate = obj.ASI_CRM_Effective_Date__c;
                
                if(endDate == Null || endDate < obj.ASI_CRM_Effective_Date__c)
                    endDate = obj.ASI_CRM_Effective_Date__c;
                
                String Key = '' + obj.ASI_CRM_Item_Group__c + obj.ASI_CRM_Region__c + obj.ASI_CRM_Commercial_Team__c + String.valueOf(date.newInstance(obj.ASI_CRM_Effective_Date__c.year(), obj.ASI_CRM_Effective_Date__c.month(), 1));
                
                obj.ASI_CRM_MTD_Order_Quantity__c = 0;
                
                allocationMap.put(Key, obj);
            }
        }
        
        endDate = endDate == Null ? date.today() : endDate;
        
        startDate = date.newInstance(endDate.year(), endDate.month(), 1);
        endDate = date.newInstance(endDate.year(), endDate.month(), date.daysInMonth(endDate.year(), endDate.month()));
        
        for(ASI_KOR_Sales_Order_Transaction__c obj : [SELECT id
                                                      , ASI_CRM_CN_Product_Name__c
                                                      , ASI_CRM_CN_Product_Name__r.Name
                                                      , ASI_CRM_Order_Qty_Bottle__c
                                                      , ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c
                                                      , ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c
                                                      , ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c
                                                      , ASI_KOR_Sales_Order_Request__c
                                                      FROM ASI_KOR_Sales_Order_Transaction__c
                                                      WHERE ASI_CRM_CN_Product_Name__c IN : allocatedItemGroup
                                                      AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c IN : regionSet
                                                      AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c IN : commercialTeamSet
                                                      AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c >= : startDate
                                                      AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c <= : endDate
                                                      AND (NOT ASI_KOR_Sales_Order_Request__r.ASI_KOR_Order_Status__c Like 'Open')
                                                      AND RecordType.developerName Like '%_CN_%']){
                                                          
                                                          String key = '' + obj.ASI_CRM_CN_Product_Name__c + obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c + obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c + String.valueOf(date.newInstance(obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c.year(), obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c.month(), 1));
                                                          
                                                          if(allocationMap.containsKey(key)){
                                                              
                                                              ASI_CRM_Item_Group_Allocation__c tmp = allocationMap.get(key);
                                                              tmp.ASI_CRM_MTD_Order_Quantity__c = tmp.ASI_CRM_MTD_Order_Quantity__c + obj.ASI_CRM_Order_Qty_Bottle__c;
                                                              allocationMap.put(key, tmp);
                                                          }
                                                      }
    }
}