objects/ASI_DFPM_Project_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Project_Milestone__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>ASI_DFPM_Project_Milestone__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ASI_DFPM_Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Promotional_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Promotional_Project__c.object
<CustomObject>
    <label>Promotional Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_DFPM_PromotionalTaskParentSummaryUP.cls
public without sharing class ASI_DFPM_PromotionalTaskParentSummaryUP extends ASI_DFPM_TriggerAbstract {
	
	public ASI_DFPM_PromotionalTaskParentSummaryUP() {
		super('ASI_DFPM_PromotionalTaskParentSummaryUP');
	}
	
	public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
		if (tAction == TriggerAction.AFTER_INSERT || tAction == TriggerAction.AFTER_UPDATE
			|| tAction == TriggerAction.AFTER_DELETE || tAction == TriggerAction.AFTER_UNDELETE) {
			Set<ID> parentPjIdSet = new Set<ID>();
			Set<ID> parentMstIdSet = new Set<ID>();
			List<ASI_DFPM_Project_Task__c> taskList = (List<ASI_DFPM_Project_Task__c>)sObjList;
			for (ASI_DFPM_Project_Task__c theTask : taskList) {
				if (theTask.ASI_DFPM_Promotional_Project__c != null) {
					parentPjIdSet.add(theTask.ASI_DFPM_Promotional_Project__c);
				}
				if (theTask.ASI_DFPM_Project_Milestone__c != null) {
					parentMstIdSet.add(theTask.ASI_DFPM_Project_Milestone__c);
				}
			}
			System.Savepoint sp = database.setSavepoint();
			try {
				if (parentPjIdSet.size() > 0) {
					ASI_DFPM_PromotionalPjStatisticManager pjStatisticManager = new ASI_DFPM_PromotionalPjStatisticManager();
					List<ASI_DFPM_Promotional_Project__c> parentPjList = pjStatisticManager.getRefreshedProjects(parentPjIdSet);
					update parentPjList;
				}
				if (parentMstIdSet.size() > 0) {
					ASI_DFPM_PromotionalMstStatisticManager mstStatisticManager = new ASI_DFPM_PromotionalMstStatisticManager();
					List<ASI_DFPM_Project_Milestone__c> parentMstList = mstStatisticManager.getRefreshedMilestones(parentMstIdSet);
					update parentMstList;
				}
			} catch (Exception e) {
				database.rollback(sp);
				throw e;
			}
		}
	}
}