objects/ASI_DFPM_Project_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Has_Attachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Project_Milestone__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>ASI_DFPM_Project_Milestone__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ASI_DFPM_Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Promotional_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Promotional_Project__c.object
<CustomObject>
    <label>Promotional Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_DFPM_AttachmentTriggerTest.cls
@isTest
private class ASI_DFPM_AttachmentTriggerTest {

    static testMethod void test_ASI_DFPM_AttachParentIndicatorHandler() {
        ASI_DFPM_PromotionalProjectGenerator pjGen = new ASI_DFPM_PromotionalProjectGenerator();
        ASI_DFPM_PromotionalMilestoneGenerator mstGen = new ASI_DFPM_PromotionalMilestoneGenerator();
        ASI_DFPM_PromotionalTaskGenerator taskGen = new ASI_DFPM_PromotionalTaskGenerator();
        
        ASI_DFPM_Promotional_Project__c testPj = pjGen.generateProject(ASI_DFPM_PromotionalProjectGenerator.RT_Standard);
        insert testPj;
        ASI_DFPM_Project_Milestone__c testMst = mstGen.generateMilestone(testPj);
        insert testMst;
        ASI_DFPM_Project_Task__c testTask = taskGen.generateTask(testMst, ASI_DFPM_PromotionalTaskGenerator.RT_Standard);
        insert testTask;
        
        Test.startTest();
        
        testTask = [SELECT Id, ASI_DFPM_Has_Attachment__c FROM ASI_DFPM_Project_Task__c WHERE Id = :testTask.Id];
        System.assertEquals(false, testTask.ASI_DFPM_Has_Attachment__c);
        Attachment attach = new Attachment(
            Name = 'Test'
            , ParentId = testTask.Id
            , Body = Blob.toPdf('Test')
        );
        insert attach;
        testTask = [SELECT Id, ASI_DFPM_Has_Attachment__c FROM ASI_DFPM_Project_Task__c WHERE Id = :testTask.Id];
        System.assertEquals(true, testTask.ASI_DFPM_Has_Attachment__c);
        
        attach = [SELECT Id, Name FROM Attachment WHERE Id = :attach.Id];
        attach.Name = 'Test 2';
        update attach;
        testTask = [SELECT Id, ASI_DFPM_Has_Attachment__c FROM ASI_DFPM_Project_Task__c WHERE Id = :testTask.Id];
        System.assertEquals(true, testTask.ASI_DFPM_Has_Attachment__c);
        
        delete attach;
        testTask = [SELECT Id, ASI_DFPM_Has_Attachment__c FROM ASI_DFPM_Project_Task__c WHERE Id = :testTask.Id];
        System.assertEquals(false, testTask.ASI_DFPM_Has_Attachment__c);
        
        undelete attach;
        testTask = [SELECT Id, ASI_DFPM_Has_Attachment__c FROM ASI_DFPM_Project_Task__c WHERE Id = :testTask.Id];
        System.assertEquals(true, testTask.ASI_DFPM_Has_Attachment__c);
        
        Test.stopTest();
    }
}