objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prefix</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Prefix__c.ASI_MFM_Module__c</field>
                <operation>equals</operation>
                <value>Plan</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <recordTypes>
        <fullName>ASI_MFM_CAP_Plan</fullName>
        <active>true</active>
        <label>CAP Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_CAP_TW_Plan</fullName>
        <active>true</active>
        <label>CAP TW Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_CN_Plan</fullName>
        <active>true</active>
        <label>CN Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_JP_Plan</fullName>
        <active>true</active>
        <label>JP Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_MY_Plan</fullName>
        <active>true</active>
        <label>MY Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_PH_DF_Plan</fullName>
        <active>true</active>
        <label>PH DF Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_PH_DP_Plan</fullName>
        <active>true</active>
        <label>PH DP Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_SG_Plan</fullName>
        <active>true</active>
        <description>Record type for SG MFM Plans</description>
        <label>SG Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_TH_Plan</fullName>
        <active>true</active>
        <description>Record type for TH MFM Plans</description>
        <label>TH Plan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Prefix__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check when do not want to show in the select prefix page.</description>
        <inlineHelpText>Check the box when do not want to show in the select prefix page.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>Direct Payment</fullName>
                </value>
                <value>
                    <fullName>Direct PO</fullName>
                </value>
                <value>
                    <fullName>Dummy Payment</fullName>
                </value>
                <value>
                    <fullName>Dummy PO</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Budget</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Payment</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Accrual</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Rental Payment</fullName>
                </value>
                <value>
                    <fullName>Accrual PO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_country_name__c</fullName>
        <formula>text(Owner:User.ASI_MFM_Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>ASI MFM Prefix</label>
    <nameField>
        <label>Prefix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI MFM Prefixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Role_Prefix_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <label>Prefix</label>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>ASI MFM Role Prefix Relationships</relationshipLabel>
        <relationshipName>ASI_MFM_Role_Prefix_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_MFM_Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI MFM Role Prefix Relationship</label>
    <nameField>
        <displayFormat>RPR{000000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI MFM Role Prefix Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>ASI MFM Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_MFM_SelectPlanPrefixController.cls
public with sharing class ASI_MFM_SelectPlanPrefixController {
    map<string, asi_mfm_role_prefix_relationship__c> px_map = new map<string, asi_mfm_role_prefix_relationship__c>();   
    
    public list<selectOption> available_prefixes {get; private set;}
    public string selected_prefix {get; set;}

    public ASI_MFM_SelectPlanPrefixController(apexpages.standardController sc) {
    }
    
    public pageReference getPrefixes() {
        user u = [select userRole.developerName, asi_mfm_country__c from user where id = :userInfo.getUserId()];
        if (u.userRole.developerName == null) {
            apexpages.message err = new apexpages.message(apexpages.severity.error, 'The role of the user is not defined yet');
            apexpages.addmessage(err); 
        }
        else if (u.asi_mfm_country__c == null) {
            apexpages.message err = new apexpages.message(apexpages.severity.error, 'The country of the user is not defined yet');
            apexpages.addmessage(err); 
        }
        else {
            list<asi_mfm_role_prefix_relationship__c> px_list = new list<asi_mfm_role_prefix_relationship__c>();
            for (asi_mfm_role_prefix_relationship__c px:[select asi_mfm_prefix__c, asi_mfm_prefix__r.name,asi_mfm_prefix__r.RecordType.DeveloperName from asi_mfm_role_prefix_relationship__c
                where asi_mfm_prefix__r.ASI_MFM_Inactive__c = false and asi_mfm_prefix__r.asi_mfm_module__c = 'Plan' and asi_mfm_role_name__c = :u.userRole.developerName and asi_mfm_prefix__r.asi_mfm_country_name__c = :u.asi_mfm_country__c order by asi_mfm_prefix__r.name]) {
                px_map.put(px.asi_mfm_prefix__c, px);
                px_list.add(px);    
            }
             if(u.asi_mfm_country__c=='KR'){//For KR User only
                return new pageReference('/apex/ASI_MFM_KR_SelectProjectCodePage?Module=Plan'); 
            }
            
            if (px_list.size() == 0) {
                apexpages.message err = new apexpages.message(apexpages.severity.error, 'The user is not entitled to input plans');
                apexpages.addmessage(err); 
            }
            else if (px_list.size() == 1) {
                selected_prefix = px_list[0].asi_mfm_prefix__c;
                return proceed();
            }
            else if(u.asi_mfm_country__c=='PH' && px_list.size()>1){ 
                String Recordtypeid = ApexPages.currentPage().getParameters().get('RecordType');
                System.debug('Recordtypeid = ' +ApexPages.currentPage().getParameters());
                Map<String, id> MPlanRecType = new Map<String,id>();
                for(Recordtype r : Global_recordTypeCache.getRtList('ASI_MFM_Plan__c')){
                    MPlanRecType.put(r.developername,r.id);
                }
                if(MPlanRecType.get('ASI_MFM_PH_DP_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DP')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                  }
                    
                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }
                    
                }
                 if(MPlanRecType.get('ASI_MFM_PH_DF_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DF')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                  }
                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }
                }
                
                if(MPlanRecType.get('ASI_MFM_PH_DF_Plan')!=Recordtypeid && MPlanRecType.get('ASI_MFM_PH_DP_Plan')!=Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                    }
                }
                
            }
            else {
                available_prefixes = new list<selectOption>();
                available_prefixes.add(new selectOption('', '-- None --'));
                for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                    available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                }
            }
        }       
        return null;
    }
    
    public pageReference proceed() {
        /* Added by Michael Yip (Introv) 6Jan2013
                Override Plan id with "System generated" for CN Plan record type
        */
        String Recordtypeid = ApexPages.currentPage().getParameters().get('RecordType');
        System.debug('Recordtypeid = ' +ApexPages.currentPage().getParameters());
        // Modified by Michael Yip (Introv) 2May2014 for reduce SOQL for recordtype
        //Map<String, id> MPlanRecType = ASI_MFM_function.getRecordTypeId('ASI_MFM_Plan__c');
        Map<String, id> MPlanRecType = new Map<String,id>();
        for(Recordtype r : Global_recordTypeCache.getRtList('ASI_MFM_Plan__c')){
            MPlanRecType.put(r.developername,r.id);
        }
        System.debug(' ----- MPlanRecType ----- : ' + MPlanRecType);
        Boolean overRidePlanID = false;
        System.debug(Recordtypeid + '/' + MPlanRecType.get('ASI_MFM_CN_Plan'));
        Set<id> SCNProf = new Set<id>();
        for(Profile p : [Select id from profile where name like 'ASI CN%']){
            SCNProf.add(p.id);
        }
        System.debug(SCNProf);
        System.debug(UserInfo.getProfileId());
        if((MPlanRecType.containsKey('ASI_MFM_CN_Plan') && ((String)MPlanRecType.get('ASI_MFM_CN_Plan')).substring(0,15) == Recordtypeid) || 
           (MPlanRecType.containsKey('ASI_MFM_JP_Plan') && ((String)MPlanRecType.get('ASI_MFM_JP_Plan')).substring(0,15) == Recordtypeid) || 
       // ((String)MPlanRecType.get('ASI_MFM_MY_Plan')).substring(0,15) == Recordtypeid ||
        SCNProf.contains(UserInfo.getProfileId())){
            overRidePlanID = true;
        }
        // Added by Michael Yip (Introv) 6Jan2013
        if (selected_prefix == null || selected_prefix == '') {
            apexpages.message err = new apexpages.message(apexpages.severity.error, 'Please select prefix first');
            apexpages.addmessage(err); 
            return null;            
        }
        else {
            string prefix_name = px_map.get(selected_prefix).asi_mfm_prefix__r.name;
            string obj_id = sObjectType.ASI_MFM_Plan__c.getKeyPrefix();
            string field_id = ASI_MFM_Function.getFieldId('ASI_MFM_Plan__c', 'ASI_MFM_Prefix__c');
            system.debug(overRidePlanID);
            // Added by Michael Yip (Introv) 6Jan2013
            if(overRidePlanID){             
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + 'Automated, Do not change';
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            // Added by Conrad Pantua (Laputa) 3Jul2013
            else if (MPlanRecType.containsKey('ASI_MFM_CAP_Plan') && ((String)MPlanRecType.get('ASI_MFM_CAP_Plan')).substring(0,15) == Recordtypeid)
            {
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }       
             // Added by Alan Wong (Elufa) 3Feb2015
	            else if ((MPlanRecType.containsKey('ASI_MFM_SG_Plan') && ((String)MPlanRecType.get('ASI_MFM_SG_Plan')).substring(0,15) == Recordtypeid)||(MPlanRecType.containsKey('ASI_MFM_TH_Plan') && ((String)MPlanRecType.get('ASI_MFM_TH_Plan')).substring(0,15) == Recordtypeid))
            {
                System.debug('Entered!');
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            else if (MPlanRecType.containsKey('ASI_MFM_PH_DP_Plan') && ((String)MPlanRecType.get('ASI_MFM_PH_DP_Plan')).substring(0,15) == Recordtypeid)
            {
                
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            else if (MPlanRecType.containsKey('ASI_MFM_PH_DF_Plan') && ((String)MPlanRecType.get('ASI_MFM_PH_DF_Plan')).substring(0,15) == Recordtypeid)
            {
                
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            
            // added by Tony Ren  (Elufa) 16Feb2015
            /*
            else if (MPlanRecType.containsKey('ASI_MFM_TH_Plan') && ((String)MPlanRecType.get('ASI_MFM_TH_Plan')).substring(0,15) == Recordtypeid)
            {
                System.debug('Entered!');
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }*/
            else if (MPlanRecType.containsKey('ASI_MFM_MY_Plan') && ((String)MPlanRecType.get('ASI_MFM_MY_Plan')).substring(0,15) == Recordtypeid)
            {
                System.debug('Entered!');
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            // Added by DC (Eternus) 25Nov2015
            else if (MPlanRecType.containsKey('ASI_MFM_CAP_TW_Plan') && ((String)MPlanRecType.get('ASI_MFM_CAP_TW_Plan')).substring(0,15) == Recordtypeid)
            {
	                System.debug('Entered!');			
                string url = '/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name;
                        
                if(Recordtypeid != null && Recordtypeid != ''){
                    url += '&RecordType=' + Recordtypeid;
                }
                return new pageReference(url ); 
            }
            else{               
                return new pageReference('/' + obj_id + '/e?retURL=%2F' + obj_id + '%2Fo&nooverride=1&CF' + field_id + '_lkid=' + selected_prefix + '&CF' + field_id + '=' + prefix_name + '&Name=' + prefix_name);         
            }
        }
    } 
}