objects/ASI_CRM_Product_Warehouse_Photo__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipName>Product_Warehouse_Photos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Photo_Category__c</fullName>
        <label>Photo Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bottle Back</fullName>
                </value>
                <value>
                    <fullName>Bottle Front</fullName>
                </value>
                <value>
                    <fullName>BQS Back</fullName>
                </value>
                <value>
                    <fullName>BQS Front</fullName>
                </value>
                <value>
                    <fullName>Cap Collection</fullName>
                </value>
                <value>
                    <fullName>Case (FA)</fullName>
                </value>
                <value>
                    <fullName>Case Inside</fullName>
                </value>
                <value>
                    <fullName>Case Outside</fullName>
                </value>
                <value>
                    <fullName>Giftbox (FA)</fullName>
                </value>
                <value>
                    <fullName>Giftbox Inside</fullName>
                </value>
                <value>
                    <fullName>Giftbox Outside</fullName>
                </value>
                <value>
                    <fullName>Label Back CH (FA)</fullName>
                </value>
                <value>
                    <fullName>Label Back EN (FA)</fullName>
                </value>
                <value>
                    <fullName>Label Front EN (FA)</fullName>
                </value>
                <value>
                    <fullName>QR Code Sticker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Photo_Version__c</fullName>
        <label>Photo Version</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Preview_URL__c</fullName>
        <formula>HYPERLINK(if(
CASE(LOWER( ASI_File_Extension__c )
, &apos;png&apos;, 1
, &apos;jpg&apos;, 1
, &apos;gif&apos;, 1
, &apos;jpeg&apos;, 1
, &apos;jfif&apos;, 1
, &apos;tiff&apos;, 1
,0) = 1
, &apos;/sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB720BY480&amp;versionId=&apos; &amp; ASI_FileID__c &amp; &apos;&amp;operationContext=CHATTER&apos;
, NULL
), &apos;Link&apos;)</formula>
        <label>Preview URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FileID__c</fullName>
        <label>FileID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_File_Extension__c</fullName>
        <label>File Extension</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_Image_URL__c</fullName>
        <formula>if(
CASE(LOWER( ASI_File_Extension__c )
, &apos;png&apos;, 1
, &apos;jpg&apos;, 1
, &apos;gif&apos;, 1
, &apos;jpeg&apos;, 1
, &apos;jfif&apos;, 1
, &apos;tiff&apos;, 1
,0) = 1
, &apos;/sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB120BY90&amp;versionId=&apos; &amp; ASI_FileID__c &amp; &apos;&amp;operationContext=CHATTER&apos;
, NULL
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; ASI_FileID__c, ASI_File_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_Preview__c</fullName>
        <formula>IF(ISBLANK(ASI_Image_URL__c), ASI_File_Name__c, IMAGE(ASI_Image_URL__c, ASI_File_Name__c))</formula>
        <label>Preview</label>
        <type>Text</type>
    </fields>
    <label>Item Group Photo Mapping</label>
    <nameField>
        <displayFormat>PW-{YY}-{00000000}</displayFormat>
        <label>Product Warehouse Photo NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Group Photo Mappings</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Product_Warehouse_Photo</fullName>
        <active>true</active>
        <label>CN Product Warehouse Photo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_SKU_Photo__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Attachment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attachment</label>
        <referenceTo>ASI_CRM_Product_Warehouse_Photo__c</referenceTo>
        <relationshipName>SKU_Photo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Comments__c</fullName>
        <formula>ASI_CRM_Attachment__r.ASI_CRM_Comments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comments</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Photo_Category__c</fullName>
        <formula>TEXT(ASI_CRM_Attachment__r.ASI_CRM_Photo_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Photo Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Photo_Version__c</fullName>
        <formula>ASI_CRM_Attachment__r.ASI_CRM_Photo_Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Photo Version</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipName>SKU_Photo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU Photo Mapping</label>
    <nameField>
        <displayFormat>SKUA-{0000000}</displayFormat>
        <label>SKU attachment no.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SKU Photo Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_MFM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>SKUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_ProductWarehouse_ListCTRL.cls
public with sharing class ASI_CRM_CN_ProductWarehouse_ListCTRL {
    
    Public List<ASI_CRM_Product_Warehouse_Photo__c> attachmentList{Get; Set;}
    Public List<ASI_CRM_SKU_Photo__c> attachmentList_SKU{Get; Set;}
    //Public Map<Id, String> mapFile{Get; Set;}
    
    Public ASI_CRM_CN_ProductWarehouse_ListCTRL(ApexPages.StandardController controller){
        
        Id headerId = controller.getId();
        
        String sObjType = headerId.getSObjectType().getDescribe().getName();
        
        if(sObjType == 'ASI_MFM_Item_Group__c'){
            
            //Set<Id> fileIdSet = new Set<Id>();
            //mapFile = new Map<Id, String>();
            attachmentList = new List<ASI_CRM_Product_Warehouse_Photo__c>();
            
            List<ASI_CRM_Product_Warehouse_Photo__c> tmpAttachmentList = [SELECT Id
                                                                          , ASI_Name__c
                                                                          , ASI_Preview__c
                                                                          , ASI_CRM_Photo_Category__c
                                                                          , ASI_CRM_Photo_Version__c
                                                                          , ASI_CRM_Comments__c
                                                                          , ASI_CRM_Preview_URL__c
                                                                          , ASI_Image_URL__c
                                                                          , ASI_FileID__c
                                                                          , ASI_File_Extension__c
                                                                          FROM ASI_CRM_Product_Warehouse_Photo__c
                                                                          WHERE ASI_CRM_Item_Group__c = : headerId
                                                                          AND ASI_CRM_Photo_Version__c != NULL
                                                                          AND RecordType.DeveloperName = 'ASI_CRM_CN_Product_Warehouse_Photo'
                                                                          ORDER BY ASI_CRM_Photo_Category__c ASC
                                                                          , ASI_CRM_Photo_Version__c DESC
                                                                          , ASI_Name__c ASC
                                                                         ];
            
            
                /*for(ASI_CRM_Product_Warehouse_Photo__c obj : tmpAttachmentList){
                    fileIdSet.add(obj.ASI_FileID__c);
                }

				List<ContentVersion> fileList = new List<ContentVersion>([SELECT VersionData FROM ContentVersion WHERE ID IN : fileIdSet]);
                    
				for(ContentVersion obj : fileList){
                    
                        String data = EncodingUtil.base64Encode(obj.VersionData);
                        
                        mapFile.put(obj.id, data);
            	}*/
            
            Map<String, ASI_CRM_Product_Warehouse_Photo__c> tmpMap = new Map<String, ASI_CRM_Product_Warehouse_Photo__c>();
            for(ASI_CRM_Product_Warehouse_Photo__c obj : tmpAttachmentList){
                
                if(!tmpMap.containsKey(obj.ASI_CRM_Photo_Category__c)){
                    
                    tmpMap.put(obj.ASI_CRM_Photo_Category__c, obj);
                }else if(tmpMap.containsKey(obj.ASI_CRM_Photo_Category__c)){
                    
                    if(tmpMap.get(obj.ASI_CRM_Photo_Category__c).ASI_CRM_Photo_Version__c < obj.ASI_CRM_Photo_Version__c){
                        tmpMap.put(obj.ASI_CRM_Photo_Category__c, obj);
                    }else if(tmpMap.get(obj.ASI_CRM_Photo_Category__c).ASI_CRM_Photo_Version__c == obj.ASI_CRM_Photo_Version__c){
                        tmpMap.put('' + obj.ASI_CRM_Photo_Category__c + obj.Id, obj);
                    }
                }
            }
            attachmentList = tmpMap.values();
        }else if(sObjType == 'ASI_MFM_SKU_Code__c'){
            attachmentList_SKU = new List<ASI_CRM_SKU_Photo__c>([SELECT Id
                                                                 , ASI_CRM_Attachment__c
                                                                 , ASI_CRM_Attachment__r.ASI_Name__c
                                                                 , ASI_CRM_Attachment__r.ASI_Preview__c
                                                                 , ASI_CRM_Attachment__r.ASI_CRM_Photo_Category__c
                                                                 , ASI_CRM_Attachment__r.ASI_CRM_Photo_Version__c
                                                                 , ASI_CRM_Attachment__r.ASI_CRM_Comments__c
                                                                 , ASI_CRM_Attachment__r.ASI_CRM_Preview_URL__c
                                                                 , ASI_CRM_Attachment__r.ASI_Image_URL__c
                                                                 , ASI_CRM_Attachment__r.ASI_FileID__c
                                                                 , ASI_CRM_Attachment__r.ASI_File_Extension__c
                                                                 FROM ASI_CRM_SKU_Photo__c
                                                                 WHERE ASI_CRM_SKU__c = : headerId
                                                                 ORDER BY ASI_CRM_Attachment__r.ASI_CRM_Photo_Category__c ASC
                                                                 , ASI_CRM_Photo_Version__c DESC
                                                                 , ASI_CRM_Attachment__r.ASI_Name__c ASC
                                                                ]);
        }
    }
}