objects/ASI_CRM_TOV__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Free_Goods_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Free Goods Request</label>
        <referenceTo>ASI_FOC_Free_Goods_Request__c</referenceTo>
        <relationshipLabel>TOVs</relationshipLabel>
        <relationshipName>TOVs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SF_SO_Request_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF SO Request Number</label>
        <referenceTo>ASI_KOR_Sales_Order_Request__c</referenceTo>
        <relationshipLabel>TOVs</relationshipLabel>
        <relationshipName>TOVs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SO_Number__c</fullName>
        <label>SO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TOV</label>
    <nameField>
        <displayFormat>TOV-{YY}{0000000}</displayFormat>
        <label>TOV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TOVs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_TOV_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <label>Item Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Order_QTY__c</fullName>
        <label>Order QTY</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Pack_Description__c</fullName>
        <formula>IF( CONTAINS(RecordType.DeveloperName, &quot;ASI_CRM_CN_CN_TOV_Detail&quot; ),  IF(NOT(ISBLANK(ASI_CRM_SF_SO_Request_Line_Number__c )),  ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_pack__c, IF( NOT(ISBLANK( ASI_CRM_SF_FOC_Request_Line_Number__c )),  ASI_CRM_SF_FOC_Request_Line_Number__r.ASI_FOC_CN_Packing_Description__c, &quot;&quot;)),&quot;&quot;)</formula>
        <label>Pack Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SF_FOC_Request_Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF FOC Request Line Number</label>
        <referenceTo>ASI_FOC_Request_Item__c</referenceTo>
        <relationshipLabel>TOV Line Items</relationshipLabel>
        <relationshipName>TOV_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SF_SO_Request_Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF SO Request Line Number</label>
        <referenceTo>ASI_KOR_Sales_Order_Transaction__c</referenceTo>
        <relationshipName>TOV_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU_Description__c</fullName>
        <label>SKU Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <label>SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_TOV__c</fullName>
        <label>TOV</label>
        <referenceTo>ASI_CRM_TOV__c</referenceTo>
        <relationshipName>TOV_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_UOM__c</fullName>
        <label>UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TOV Line Item</label>
    <nameField>
        <displayFormat>TOVD-{YY}{000000}</displayFormat>
        <label>TOV Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TOV Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_SG_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Date_of_Delivery__c</fullName>
        <label>Request Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Deliver_to_Address_Line_1__c</fullName>
        <label>Deliver to Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Receiptor_Mobile__c</fullName>
        <label>Recipient Mobile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Receiptor_Name__c</fullName>
        <label>Recipient Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_FOC_Request_Item__c.object
<CustomObject>
    <description>used for PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Customer_Code__c</fullName>
        <formula>ASI_CRM_Plan_Line_Item__r.ASI_MFM_Customer_Name__r.ASI_HK_CRM_Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_CN_Packing_Description__c</fullName>
        <label>Packing Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_SKU_Chinese_Description__c</fullName>
        <formula>ASI_FOC_SKU__r.ASI_FOC_SKU_Chinese_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SKU Chinese Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_SKU__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SKU</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 6) OR (3 AND 4 AND 6) OR 5</booleanFilter>
            <errorMessage>SKU: Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW FOC Request Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_SKU_Code__c.ASI_HK_CRM_IsPOSProduct__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW POSM Request Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_SKU_Code__c.ASI_HK_CRM_IsPOSProduct__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM TW FOC Request Item, ASI CRM TW POSM Request Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_SKU_Code__c.ASI_HK_CRM_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>ASI_FOC_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>LN-{000000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Sales Order Requests (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Other_Requirement__c</fullName>
        <label>Other Requirement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Tel_Mobile__c</fullName>
        <label>Tel/Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR-{00000000}</displayFormat>
        <label>Sales Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Sales Order Request Items</relationshipLabel>
        <relationshipName>Sales_Order_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Request Item</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Sales Order Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_FOC_SKU_Chinese_Description__c</fullName>
        <label>SKU Chinese Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_TOV_PDF_Controller.cls
public without sharing class ASI_CRM_CN_TOV_PDF_Controller {
    public Boolean dummyVar { get { if (dummyVar != true) {dummyVar = init();} return dummyVar; } set; }
    public String currentHeaderID {set;get;}
    public List<ASI_FOC_Request_Item__c> lineItemFGR{get;set;}
    public ASI_CRM_TOV__c TOCurrent{get;set;}
    public list<ASI_CRM_TOV_Detail__c> lineItem{get;set;}
    Public Double totalQty {get;set;}
    public boolean init(){
        {
            TOCurrent = [select id
                         ,ASI_CRM_Customer_Code__c
                         ,ASI_CRM_SO_Number__c
                         ,ASI_CRM_Order_Date__c
                         ,ASI_CRM_SF_SO_Request_Number__r.name
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_CN_Address__c
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Legal_Name__c
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CRM_Code__c
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_CN_Tel_Mobile__c
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_SG_Order_Date__c
                         ,ASI_CRM_SF_SO_Request_Number__r.ASI_CRM_CN_Other_Requirement__c
                         ,ASI_CRM_Free_Goods_Request__r.name
                         ,ASI_CRM_Free_Goods_Request__r.ASI_FOC_Receiptor_Name__c
                         ,ASI_CRM_Free_Goods_Request__r.ASI_FOC_Deliver_to_Address_Line_1__c
                         ,ASI_CRM_Free_Goods_Request__r.ASI_FOC_Date_of_Delivery__c
                         ,ASI_CRM_Free_Goods_Request__r.ASI_FOC_Receiptor_Mobile__c
                         from ASI_CRM_TOV__c 
                         where id = : currentHeaderID
                        ]; 
            lineItem = new list<ASI_CRM_TOV_Detail__c>();
            lineItem = [select id,ASI_CRM_SKU__c
                        ,ASI_CRM_Order_QTY__c
                        ,ASI_CRM_UOM__c 
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_pack__c
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.name
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_Pack_Value__c
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_BT_Size_C__c
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_MFM_Item_Group_Code__c
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_Chinese_Name__c
                        ,ASI_CRM_SF_SO_Request_Line_Number__r.ASI_CRM_CN_Product_Name__r.ASI_CRM_CN_Eng_Name__c
                        ,ASI_CRM_SF_FOC_Request_Line_Number__r.ASI_FOC_CN_Packing_Description__c
                        ,ASI_CRM_SF_FOC_Request_Line_Number__r.ASI_FOC_SKU_Chinese_Description__c
                        ,ASI_CRM_SF_FOC_Request_Line_Number__r.ASI_FOC_SKU__r.Name
                        ,ASI_CRM_Item_Group__c
                        ,ASI_CRM_Pack_Description__c
                        ,ASI_CRM_SKU_Description__c
                        from ASI_CRM_TOV_Detail__c 
                        where ASI_CRM_TOV__c = : currentHeaderID];   
            
            for(ASI_CRM_TOV_Detail__c obj : lineItem){
                if(totalQty == NULL)
                    totalQty = 0;
                if(obj.ASI_CRM_Order_QTY__c != NULL)
                    totalQty += obj.ASI_CRM_Order_QTY__c;
            }
            return true;
        }
    }
}