objects/ASI_eForm_HR_MDM__c.object
<CustomObject>
    <label>HR MDM</label>
    <nameField>
        <label>Local Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR MDMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_GnH_Request__c.object
<CustomObject>
    <label>G&amp;H Request</label>
    <nameField>
        <displayFormat>GH-{yy}-{00000}</displayFormat>
        <label>G&amp;H Request No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>G&amp;H Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_JP_TnE_Expense_Category__c.object
<CustomObject>
    <label>ASI TnE Expense Category</label>
    <nameField>
        <label>Expense Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI TnE Expense Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_JP_TnE_Expense_Classification__c.object
<CustomObject>
    <fields>
        <fullName>ASI_JP_TnE_Expense_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Category</label>
        <referenceTo>ASI_JP_TnE_Expense_Category__c</referenceTo>
        <relationshipName>TnE_JP_Expense_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ASI TnE Expense Classification</label>
    <nameField>
        <label>Expense Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI TnE Expense Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Brand__c.object
<CustomObject>
    <description>ASI KOR</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_KOR_Sub_Brand__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>ASI_KOR_Brand__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Sub_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Sub-Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_TnE_Account_Mapping__c.object
<CustomObject>
    <label>ASI TnE Account Mapping</label>
    <nameField>
        <displayFormat>TnE-ACC-{0000}</displayFormat>
        <label>ASI TnE Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI TnE Account Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimDetail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_ClaimHeader__c</fullName>
        <label>Travel &amp; Entertainment Claim</label>
        <referenceTo>ASI_TnE_ClaimHeader__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>ASI_TnE_ClaimDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Status__c</fullName>
        <formula>TEXT(ASI_TnE_ClaimHeader__r.ASI_TnE_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Travel &amp; Entertainment Claim Detail</label>
    <nameField>
        <displayFormat>TED-{YY}-{00000}</displayFormat>
        <label>Claim Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimHeader__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Waiting for Department Head Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Verification</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Director Review</fullName>
                </value>
                <value>
                    <fullName>Finance Director Approved</fullName>
                </value>
                <value>
                    <fullName>Release</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Verified</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>PRA Final Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Travel &amp; Entertainment Claim</label>
    <nameField>
        <displayFormat>TE-{YY}-{00000}</displayFormat>
        <label>Travel &amp; Entertainment Claim Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_TnE_KR_changeGnHRequestStatusTest.cls
@isTest
public class ASI_TnE_KR_changeGnHRequestStatusTest{


    @testSetup static void setupData(){
        List<User> tempUsers = ASI_TnE_KR_TestClassHelper.createTestUser(); //user list
        List<ASI_eForm_HR_MDM__c> tempMDMs = ASI_TnE_KR_TestClassHelper.createMDMRecords(); //MDM list
        List<ASI_TnE_Account_Mapping__c> tempACMaps = ASI_TnE_KR_TestClassHelper.createAcMapRecords(); //accounting mapping list
        List<ASI_JP_TnE_Expense_Category__c> tempCats = ASI_TnE_KR_TestClassHelper.createExCatRecords(); //expense category list
        List<ASI_JP_TnE_Expense_Classification__c> tempClasses = ASI_TnE_KR_TestClassHelper.createExClassRecords(tempCats,tempACMaps); //expense classficiation list
        List<ASI_KOR_Brand__c> tempBrands = ASI_TnE_KR_TestClassHelper.createBrandRecords(); //brand list
        List<ASI_KOR_Sub_Brand__c> tempSubBrands = ASI_TnE_KR_TestClassHelper.createSubBrandRecords(tempBrands); //sub-brand list
        List<ASI_CRM_AccountsAdditionalField__c> tempCustomers = ASI_TnE_KR_TestClassHelper.createCustomerRecords(tempUsers); //customer list

        List<ASI_GnH_Request__c> gnhRequestList = ASI_TnE_KR_TestClassHelper.createGnHRequest(tempUsers);
        List<ASI_TnE_ClaimHeader__c> tempHeaders = ASI_TnE_KR_TestClassHelper.createGeneralHeaderRecord(tempUsers); //claim header list
        List<ASI_TnE_ClaimDetail__c> tempDetails = ASI_TnE_KR_TestClassHelper.createGeneralDetailRecord(tempHeaders,tempSubBrands,tempCats,tempClasses,tempCustomers,tempUsers,gnhRequestList); //claim detail list        

    }

    static testMethod void changeStatusSubmitted(){

        List<ASI_TnE_ClaimHeader__c> draftHeaderList = [select Id, ASI_TnE_Status__c from ASI_TnE_ClaimHeader__c where ASI_TnE_Status__c = 'Draft' or ASI_TnE_Status__c = 'Submitted'];
        List<ASI_TnE_ClaimHeader__c> updateList = new List<ASI_TnE_ClaimHeader__c>();
        for (ASI_TnE_ClaimHeader__c draftHeader : draftHeaderList){
            if (draftHeader.ASI_TnE_Status__c == 'Draft'){ 
                draftHeader.ASI_TnE_Status__c = 'Submitted';
            }else if (draftHeader.ASI_TnE_Status__c == 'Submitted'){
                draftHeader.ASI_TnE_Status__c = 'Rejected';
            }
            updateList.add(draftHeader);        
        }
        update updateList;
    }

}