objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_TH_CRM_Promotion_Type__c</fullName>
        <label>Promotion Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PRT - Contract</fullName>
                    <default>true</default>
                    <label>PRT - Contract</label>
                </value>
                <value>
                    <fullName>New Contract ON</fullName>
                </value>
                <value>
                    <fullName>New Contract OFF</fullName>
                </value>
                <value>
                    <fullName>RTD ON</fullName>
                </value>
                <value>
                    <fullName>RTD OFF</fullName>
                </value>
                <value>
                    <fullName>New Contract E-Commerce</fullName>
                </value>
                <value>
                    <fullName>NCO KTV</fullName>
                </value>
                <value>
                    <fullName>NCO RTV</fullName>
                </value>
                <value>
                    <fullName>NCO F-KTV</fullName>
                </value>
                <value>
                    <fullName>NCO Bar</fullName>
                </value>
                <value>
                    <fullName>NCO Chinese Restaurant</fullName>
                </value>
                <value>
                    <fullName>NCO Hotel</fullName>
                </value>
                <value>
                    <fullName>NCO Inter Hotel/Bar/Restaurant</fullName>
                </value>
                <value>
                    <fullName>NCO RTD ON</fullName>
                </value>
                <value>
                    <fullName>NCO MOT</fullName>
                </value>
                <value>
                    <fullName>NCO TOT</fullName>
                </value>
                <value>
                    <fullName>NCO Bulk Purchase</fullName>
                </value>
                <value>
                    <fullName>NCO E-Commerce</fullName>
                </value>
                <value>
                    <fullName>NCO RTD OFF</fullName>
                </value>
                <value>
                    <fullName>Promoter Costs</fullName>
                </value>
                <value>
                    <fullName>Trade Marketing</fullName>
                </value>
                <value>
                    <fullName>Outlet Promotion</fullName>
                </value>
                <value>
                    <fullName>Wholesaler Promotion</fullName>
                </value>
                <value>
                    <fullName>Consumer Promotion</fullName>
                </value>
                <value>
                    <fullName>Gift/Sponsor/Reward Trip</fullName>
                </value>
                <value>
                    <fullName>WS/Outlet Rest. Entertainment</fullName>
                </value>
                <value>
                    <fullName>Trade Fair</fullName>
                </value>
                <value>
                    <fullName>Market Visit</fullName>
                </value>
                <value>
                    <fullName>VAT Deemed Sales</fullName>
                </value>
                <value>
                    <fullName>POP - Warehouse &amp; Delivery (only for HQ/MM)</fullName>
                </value>
                <value>
                    <fullName>Heavy Contract On</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Contract</fullName>
        <active>true</active>
        <label>CN Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_MO_Contract</fullName>
        <active>true</active>
        <label>ASI CRM MO Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_MY_Contract</fullName>
        <active>true</active>
        <label>ASI CRM MY Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_TH_CRM_Contract</fullName>
        <active>true</active>
        <label>ASI TH CRM Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_RedirectContractView_Ctr.cls
/*
    - This Controller controls the Page Traffic of the Contract Standard View Action.
*/

public class ASI_CRM_RedirectContractView_Ctr {
    private ASI_TH_CRM_Contract__c contract{get;set;}
    private String recordTypeId{get;set;}
    private String recordId{get;set;}
    private String recordTypeName{get;set;}
    public PageReference redirectPage {get;set;}
    private String paramList {get;set;}
    
    public ASI_CRM_RedirectContractView_Ctr (ApexPages.StandardController controller) {
        
        Map<String, String> pageParam = ApexPages.currentPage().getParameters(); 
        paramList='';
        if(pageParam!=null){
            for(String param : pageParam.keySet()){
                if(pageParam.get(param)==null){
                    paramList +='&'+param+'=null';
                }else{
                    if(!param.contains('save_new')&&!param.contains('sfdc.override'))
                    paramList +='&'+param+'='+pageParam.get(param);
                }
            }
        }
        
        contract = (ASI_TH_CRM_Contract__c)controller.getRecord();
        recordTypeId = ((ASI_TH_CRM_Contract__c)controller.getRecord()).RecordTypeId;
        recordId = ((ASI_TH_CRM_Contract__c)controller.getRecord()).Id;
        recordTypeName = 'null';
        for(RecordType rt:[select id,DeveloperName from RecordType where id = :recordTypeId limit 1])
             recordTypeName = rt.DeveloperName;
    }
    public PageReference redirect(){
        //if RecordTypeName = 'ASI_TH_CRM_Contract', redirect to its default view page. if 'ASI_CRM_CN_Contract', redirect to page 'ASI_CRM_CN_MainContractPage'

        if(recordTypeName == 'ASI_TH_CRM_Contract')
        {
            Schema.DescribeSObjectResult contractObj = ASI_TH_CRM_Contract__c.sObjectType.getDescribe();
            redirectPage =  new PageReference('/'+ this.contract.id + '?nooverride=1'+ paramList);
            redirectPage.setRedirect(true);
        }
        else if(recordTypeName == 'ASI_CRM_CN_Contract') 
        {
            if(recordId!=null){ //Added by Laputa 20170525 for CRM 4.2 
                ASI_TH_CRM_Contract__c ContractSelected =[select Id,ASI_TH_CRM_Promotion_Type__c from ASI_TH_CRM_Contract__c where id=:recordId];
                if(ContractSelected.ASI_TH_CRM_Promotion_Type__c!=null &&  ContractSelected.ASI_TH_CRM_Promotion_Type__c=='Heavy Contract On'){ redirectPage =  new PageReference('/apex/ASI_CRM_CN_ViewHeavyContractPage?id='+ recordId); 
                }else{
                    redirectPage =  new PageReference('/apex/ASI_CRM_CN_MainContractPage?id='+ recordId);
                }
            }
            //redirectPage =  new PageReference('/apex/ASI_CRM_CN_MainContractPage?id='+ recordId);
        }
        //Added by Laputa
        else if(recordTypeName == 'ASI_SG_CRM_Contract') {Schema.DescribeSObjectResult contractObj = ASI_TH_CRM_Contract__c.sObjectType.getDescribe(); redirectPage = new PageReference('/'+ this.contract.id + '?nooverride=1'+ paramList); redirectPage.setRedirect(true);}
        else if(recordTypeName.startsWith('ASI_CRM_MY_Contract')) {Schema.DescribeSObjectResult contractObj = ASI_TH_CRM_Contract__c.sObjectType.getDescribe(); redirectPage = new PageReference('/apex/ASI_CRM_Contract_Standard?id='+ this.contract.id + paramList); redirectPage.setRedirect(true);}
        else if(recordTypeName.startsWith('ASI_CRM_MO_Contract')) { Schema.DescribeSObjectResult contractObj = ASI_TH_CRM_Contract__c.sObjectType.getDescribe(); redirectPage = new PageReference('/apex/ASI_CRM_Contract_Standard?id='+ this.contract.id + paramList); redirectPage.setRedirect(true); } else { Schema.DescribeSObjectResult contractObj = ASI_TH_CRM_Contract__c.sObjectType.getDescribe(); redirectPage = new PageReference('/'+ this.contract.id + '?nooverride=1'+ paramList); redirectPage.setRedirect(true); }
       
        return redirectPage;
    }

}