objects/ASI_CRM_Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>ASI_CRM_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Receipt_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ASI_CRM_Invoice__c</referenceTo>
        <relationshipLabel>Receipt Line Items</relationshipLabel>
        <relationshipName>Receipt_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line Item</label>
    <nameField>
        <displayFormat>RCPTL-{000000}</displayFormat>
        <label>Receipt Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_GenPromptPayment_Test.cls
/*********************************************************************************
 * Name: ASI_CRM_SG_GenPromptPayment_Test
 * Description: Test Class for ASI_CRM_SG_GenPromptPaymentBatch_V2
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 16/05/2017       Hugo Cheung             Created          
*/
@isTest
public class ASI_CRM_SG_GenPromptPayment_Test {
    
    @TestSetup
    public static void setupData() {
        ASI_CRM_SG_TestClassHelper.createDataSettings();
        ASI_CRM_SG_TestClassHelper.createSubBrandData();
        
        List<ASI_MFM_SKU_Code__c> skuList = ASI_CRM_SG_TestClassHelper.createSKUandPRiceData();
        
        ASI_CRM_SG_TestClassHelper.wholesalesCustomerData wholesales = new ASI_CRM_SG_TestClassHelper.wholesalesCustomerData(true);
        
        ASI_CRM_SG_TestClassHelper.receiptData receiptData = new ASI_CRM_SG_TestClassHelper.receiptData(true, wholesales.customer);
        
        List<ASI_CRM_Invoice__c> invoiceList = new List<ASI_CRM_Invoice__c>();
        for(Integer i = 0 ; i < 5 ; i++) {
            ASI_CRM_SG_TestClassHelper.invoiceData invoiceData = new ASI_CRM_SG_TestClassHelper.invoiceData(false, wholesales.customer);
            invoiceList.add(invoiceData.invoice);
        }
        insert invoiceList;
        
        List<ASI_CRM_Invoice_Line_Item__c> invoiceLineItemList = new List<ASI_CRM_Invoice_Line_Item__c>();
        for(Integer i = 0 ; i < 5 ; i++) {
        	for(ASI_CRM_Invoice__c invoice : invoiceList) {
                ASI_CRM_SG_TestClassHelper.invoiceLineItemData invoiceLineItemData = new ASI_CRM_SG_TestClassHelper.invoiceLineItemData(false, invoice);
                invoiceLineItemList.add(invoiceLineItemData.invoiceLineItem);
            }
        }
        insert invoiceLineItemList;
        
        List<ASI_CRM_Receipt_Line_Item__c> receiptLineItemList = new List<ASI_CRM_Receipt_Line_Item__c>();
        for(Integer i = 0 ; i < 5 ; i++) {
        	ASI_CRM_SG_TestClassHelper.receiptLineItemData receiptLineItemData = new ASI_CRM_SG_TestClassHelper.receiptLineItemData(false, receiptData.receipt, invoiceList.get(i));
            receiptLineItemList.add(receiptLineItemData.receiptLineItem);
        }
        insert receiptLineItemList;
    }
    
    public static testMethod void testBatch() {
        Datetime startDate = Date.today().addMonths(-1);
        Datetime endDate   = Date.today().addMonths(1);
       
        Database.executeBatch(new ASI_CRM_SG_GenPromptPaymentBatch_V2(startDate.format('yyyy-MM-dd'), endDate.format('yyyy-MM-dd')));
    }
}