objects/ASI_HK_CRM_Visitation_Plan__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan</description>
    <fields>
        <fullName>ASI_HK_CRM_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                    <default>true</default>
                    <label>January</label>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Visitation Plan</label>
    <nameField>
        <label>Visitation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Visitation_Plan_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan Detail</description>
    <fields>
        <fullName>ASI_HK_CRM_Visitation_Plan__c</fullName>
        <label>Visitation Plan</label>
        <referenceTo>ASI_HK_CRM_Visitation_Plan__c</referenceTo>
        <relationshipName>ASI_HK_CRM_Visitation_Plan_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visitation Plan Detail</label>
    <nameField>
        <displayFormat>VPD-{00000}</displayFormat>
        <label>Visitation Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitation Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_VisitationConfirmTest.cls
@isTest
public with sharing class ASI_CRM_SG_VisitationConfirmTest {
    
    
    public static testMethod void test_main() {
        ASI_HK_CRM_AccountGenerator acctGen = new ASI_HK_CRM_AccountGenerator();
        ASI_HK_CRM_VisitationPlanGenerator visitGen = new ASI_HK_CRM_VisitationPlanGenerator();
        ASI_CRM_SG_VisitationPlanDetailGenerator visitDetailGen = new ASI_CRM_SG_VisitationPlanDetailGenerator();
        
        final Integer numOfAcct = 3;
        List<Account> acctList = new List<Account>();
        for (Integer i = 0; i < numOfAcct; i++) {
          acctList.add(acctGen.generateAccount(ASI_HK_CRM_AccountGenerator.RT_JDE_CREDIT));
        }
        List<ASI_CRM_AccountsAdditionalField__c> customers= new List<ASI_CRM_AccountsAdditionalField__c>();
        if(acctList.size()>0){
            customers = ASI_CRM_SG_TestDummyData.generateCustomers(acctList.size(),acctList,true,'ASI_CRM_SG_Outlet','ASI_CRM_AccountsAdditionalField__c');
        }

        ASI_HK_CRM_Visitation_Plan__c visit = visitGen.generateVisitationPlan();
        insert visit;
        visit = [SELECT Id, Name, ASI_HK_CRM_Year__c, ASI_HK_CRM_Month__c, ASI_HK_CRM_Confirmed__c FROM ASI_HK_CRM_Visitation_Plan__c WHERE Id = :visit.Id];
        Integer visitYear = Integer.valueOf(visit.ASI_HK_CRM_Year__c);
        Integer visitMonth = ASI_HK_CRM_VisitationPlanGenerator.convertMonthPLValueToInteger(visit.ASI_HK_CRM_Month__c);
        
        List<ASI_HK_CRM_Visitation_Plan_Detail__c> visitDetails = new List<ASI_HK_CRM_Visitation_Plan_Detail__c>();
        Integer countDay = 1;
        for (ASI_CRM_AccountsAdditionalField__c cus : customers) {
          Date visitDate = Date.newInstance(visitYear, visitMonth, countDay);
          ASI_HK_CRM_Visitation_Plan_Detail__c visitDetail = visitDetailGen.generateVisitationPlanDetail(visit, cus, visitDate);
          visitDetails.add(visitDetail);
          countDay++;
        }
        insert visitDetails;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(visit);
        
        Test.startTest();
        
        PageReference testPage = Page.ASI_CRM_SG_VisitationConfirmPage;
        Test.setCurrentPageReference(testPage);
        ASI_CRM_SG_VisitationConfirmController testCon = new ASI_CRM_SG_VisitationConfirmController(stdController);
        
        PageReference initRedirectPage = testCon.initPage();
        System.assertEquals('/' + visit.Id, initRedirectPage.getUrl());
        
        // Test error
        visit = [SELECT Id, Name, ASI_HK_CRM_Year__c, ASI_HK_CRM_Month__c, ASI_HK_CRM_Confirmed__c FROM ASI_HK_CRM_Visitation_Plan__c WHERE Id = :visit.Id];
        stdController = new ApexPages.StandardController(visit);
        testCon = new ASI_CRM_SG_VisitationConfirmController(stdController);
        
        initRedirectPage = testCon.initPage();
        System.assertEquals(null, initRedirectPage);
        
        visit = [SELECT Id, Name, ASI_HK_CRM_Year__c, ASI_HK_CRM_Month__c, ASI_HK_CRM_Confirmed__c FROM ASI_HK_CRM_Visitation_Plan__c WHERE Id = :visit.Id];
        System.assertEquals(true, visit.ASI_HK_CRM_Confirmed__c);
        
        List<Event> visitEvents = [SELECT Id FROM Event WHERE WhatId IN :customers];
        System.assertEquals(visitDetails.size(), visitEvents.size());
        
        Test.stopTest();
    }
}