objects/ASI_DFPM_Project_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Complete_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Complete Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Overdue_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Overdue Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Overdue__c</fullName>
        <formula>IF( NOT( ASI_DFPM_Complete__c ) &amp;&amp; ASI_DFPM_End_Date__c - TODAY() &lt; 0, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Overdue?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Promotional_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Promotional_Project__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Total_Complete_Milestone__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Complete Milestone</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Complete_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Complete Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Milestone__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Milestone</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Overdue_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Overdue Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotional Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_DFPM_PromotionalPjStatisticManager.cls
public without sharing class ASI_DFPM_PromotionalPjStatisticManager {
	
	private ASI_DFPM_ChildRecordSummaryHelper summaryHelper;
	
	public ASI_DFPM_PromotionalPjStatisticManager() {
		this.summaryHelper = new ASI_DFPM_ChildRecordSummaryHelper('ASI_DFPM_Promotional_Project__c');
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Milestone__c', 'Milestones__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Complete_Milestone__c', 'Milestones__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT, null
			, 'ASI_DFPM_Complete__c', true
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Task__c', 'Promotional_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Complete_Task__c', 'Promotional_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT, null
			, 'ASI_DFPM_Complete__c', true
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Overdue_Task__c', 'Promotional_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT, null
			, 'ASI_DFPM_Overdue__c', 'Yes'
		));
	}
	
	public List<ASI_DFPM_Promotional_Project__c> getRefreshedProjects(Set<ID> pjIdSet) {
		Map<ID, ASI_DFPM_Promotional_Project__c> pjMap = new Map<ID, ASI_DFPM_Promotional_Project__c>([SELECT Id
			, ASI_DFPM_Total_Milestone__c
			, ASI_DFPM_Total_Complete_Milestone__c
			, ASI_DFPM_Total_Task__c
			, ASI_DFPM_Total_Complete_Task__c
			, ASI_DFPM_Total_Overdue_Task__c
			FROM ASI_DFPM_Promotional_Project__c WHERE Id IN :pjIdSet
		]);
		List<ASI_DFPM_Promotional_Project__c> pjList = pjMap.values();
		Set<ID> updatedIdSet = this.summaryHelper.refreshSummaryValues(pjList);
		List<ASI_DFPM_Promotional_Project__c> updatedPjList = new List<ASI_DFPM_Promotional_Project__c>();
		for (ID updatedId : updatedIdSet) {
			ASI_DFPM_Promotional_Project__c tempPj = pjMap.get(updatedId);
			if (tempPj != null)
				updatedPjList.add(tempPj);
		}
		return updatedPjList;
	}
}