objects/ASI_KOR_POSM_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_KR_EmailSentTime__c</fullName>
        <label>Email Sent Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_KR_POSM_Order_Request_Name__c</fullName>
        <externalId>true</externalId>
        <label>POSM Order Request Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_External_ID1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO External ID</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>POSM Order Requests</relationshipLabel>
        <relationshipName>POSM_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Total_Amount__c</fullName>
        <label>Total Amount</label>
        <summarizedField>ASI_KOR_POSM_Order_Detail__c.ASI_KOR_TotalAmount__c</summarizedField>
        <summaryForeignKey>ASI_KOR_POSM_Order_Detail__c.ASI_KOR_POSM_Order_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>POSM Order Request</label>
    <nameField>
        <displayFormat>POSM-{0000}</displayFormat>
        <label>POSM Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POSM Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Budget__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY1011</fullName>
                </value>
                <value>
                    <fullName>FY1112</fullName>
                </value>
                <value>
                    <fullName>FY1213</fullName>
                </value>
                <value>
                    <fullName>FY1314</fullName>
                </value>
                <value>
                    <fullName>FY1415</fullName>
                </value>
                <value>
                    <fullName>FY1516</fullName>
                </value>
                <value>
                    <fullName>FY1617</fullName>
                </value>
                <value>
                    <fullName>FY1718</fullName>
                </value>
                <value>
                    <fullName>FY1819</fullName>
                </value>
                <value>
                    <fullName>FY1920</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_P10_Amount__c</fullName>
        <label>P10 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Total_Amount__c</fullName>
        <formula>ASI_MFM_P1_Amount__c +  ASI_MFM_P2_Amount__c +  ASI_MFM_P3_Amount__c +  ASI_MFM_P4_Amount__c +  ASI_MFM_P5_Amount__c +  ASI_MFM_P6_Amount__c +  ASI_MFM_P7_Amount__c +  ASI_MFM_P8_Amount__c +  ASI_MFM_P9_Amount__c +  ASI_MFM_P10_Amount__c +  ASI_MFM_P11_Amount__c +  ASI_MFM_P12_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Original Budget</fullName>
                </value>
                <value>
                    <fullName>LE1</fullName>
                </value>
                <value>
                    <fullName>LE2</fullName>
                </value>
                <value>
                    <fullName>LE3</fullName>
                </value>
                <value>
                    <fullName>LE4</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BGT{000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Fiscal_Year__c.object
<CustomObject>
    <description>Used in MFM plan to control the available FY that can be selected by user</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Fiscal_Year__c</fullName>
        <formula>TEXT(ASI_MFM_Plan__r.ASI_MFM_Fiscal_year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>PO External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>VAP PO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_User_Branch_Code__c</fullName>
        <label>User Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>ASI MFM Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CRM_KR_MassUploadCtrl_TestClass.cls
@isTest
public class ASI_CRM_KR_MassUploadCtrl_TestClass {
    
    public static string getFiscalYear(){
        Integer orgFiscalMonth = [SELECT FiscalYearStartMonth FROM Organization].FiscalYearStartMonth;  //i.e. 7
        Date orgFiscalYear = Date.newinstance(system.today().year(), orgFiscalMonth, 1);    
        Datetime GMTdate = Datetime.now();
        String yearA1 = GMTdate.format('YY');
        Integer yearA0 = Integer.valueOf(yearA1) -1;
        Integer yearA2 = Integer.valueOf(yearA1) +1;
        String Current_Fiscal_year;
        
        if(system.today()< orgFiscalYear){
            Current_Fiscal_year = 'FY' + yearA0 + yearA1 ;
        }else{
            Current_Fiscal_year = 'FY' + yearA1 + yearA2 ;
        }
        
        return Current_Fiscal_year;
    }
    
    static testMethod void ASI_MFM_MassUploadByBatch_Test(){
        Account a = new Account(name='test', recordTypeId = Global_RecordTypeCache.getRtId('AccountASI_GF_Customer'));
        insert a;
        Contact c = new Contact(accountid=a.id,firstname='James',lastname='test', recordTypeId = Global_RecordTypeCache.getRtId('ContactASI_HK_CRM_Wholesalers_Outlets'));
        insert c;
        
        
        test.startTest();
        ASI_CRM_KR_MassUploadByBatchController controller = new ASI_CRM_KR_MassUploadByBatchController();
        controller.emailNotification = true;
        controller.ObjAPIName = 'Contact';
        controller.parentID = String.valueof(a.id);
        controller.parentField = 'AccountID';  
        controller.recordtypeName = 'contactType1';
        controller.fields = 'firstname,lastname,description,reportstoid,DoNotCall,Birthdate,reportstoid';
        controller.fieldsLabel = 'firstname,lastname,description,reportsto,DoNotCall,Birthdate,reportsto';
        controller.lookupEXID = 'contact/reportstoid:reportsto-lastname';
        controller.template = 'ASI_MFM_PlanLineItemTemplate';
        controller.currentPageURL = String.valueof(a.id);
        controller.inlineVF = true;
        controller.DefaultValues = 'birthdate:2013-01-01';
        controller.upsertMode = false;
        controller.parentObjectAPIName = 'Account';
        controller.ParentObjectUploadMsg = 'Description';
        
        controller.init();
        controller.filesize = 2000;
        controller.namefile = 'test.csv';
        controller.contentFile = blob.valueOf('firstname,lastname,description,DoNotCall,Birthdate,reportsto\rJohn,Test,desc,Y,2013-08-01,test\rJohn,Test,desc,N,2013-08-01,test');
        controller.uploadCSVByBatch();
        
        
        controller.ObjAPIName = 'Account';
        controller.parentID = String.valueof(a.id);
        controller.parentField = 'ParentId';
        controller.recordtypeName = '';
        //controller.fields = 'name,NumberOfEmployees,AnnualRevenue,PersonDoNotCall,PersonBirthdate,PersonMobilePhone';
        controller.fields = 'PersonDoNotCall,PersonBirthdate,PersonMobilePhone';
        controller.fieldsLabel = 'DoNotCall,Birthdate,mobile';
        controller.lookupEXID = 'account/ParentId:ParentId-par';
        controller.template = 'ASI_MFM_PlanLineItemTemplate';
        controller.currentPageURL = String.valueof(a.id);
        controller.inlineVF = true;
        controller.DefaultValues = '';
        controller.upsertMode = false;
        controller.parentObjectAPIName = 'Account';
        controller.ParentObjectUploadMsg = 'Description';
        controller.contentFile = blob.valueOf('True,,NumberOfEmployeesAnnualRevenue\rJohn,1,3');
        controller.emailNotification = true;
        controller.uploadCSVByBatch();
        
        controller.uploadCSV();
        controller.refreshPage();
        controller.refreshPage2();
        
        controller.ObjAPIName = 'Account';
        controller.parentID = String.valueof(a.id);
        controller.parentField = 'ParentId';
        controller.recordtypeName = '';
        controller.fields = 'name,NumberOfEmployees,AnnualRevenue';
        controller.fieldsLabel = 'name,NumberOfEmployees,AnnualRevenue';
        controller.lookupEXID = 'account/ParentId:ParentId-par';
        controller.template = 'ASI_MFM_PlanLineItemTemplate';
        controller.currentPageURL = String.valueof(a.id);
        controller.inlineVF = true;
        controller.DefaultValues = '';
        controller.upsertMode = true;
        controller.parentObjectAPIName = 'Account';
        controller.ParentObjectUploadMsg = 'Description';
        controller.contentFile = blob.valueOf('name,,NumberOfEmployeesAnnualRevenue\rJohn,1,3');
        controller.emailNotification = true;
        controller.uploadCSVByBatch();
        
        controller.uploadCSV();
        controller.refreshPage();
        controller.refreshPage2();
        
        //Kammy starts:
        controller.ObjAPIName = 'Account';
        controller.parentID = String.valueof(a.id);
        controller.parentField = 'ParentId';
        controller.recordtypeName = '';
        controller.fields = 'PersonDoNotCall,PersonBirthdate,PersonMobilePhone';
        controller.fieldsLabel = 'DoNotCall,Birthdate,mobile';
        controller.lookupEXID = 'account/ParentId:ParentId-par';
        controller.template = 'ASI_MFM_PlanLineItemTemplate';
        controller.currentPageURL = String.valueof(a.id);
        controller.inlineVF = true;
        controller.DefaultValues = '';
        controller.upsertMode = false;
        controller.parentObjectAPIName = 'Account';
        controller.ParentObjectUploadMsg = 'Description';
        controller.contentFile = blob.valueOf('True,NumberOfEmployeesAnnualRevenue\rJohn,1,3');
        controller.emailNotification = true;
        controller.uploadCSVByBatch();
        
        controller.uploadCSV();
        controller.refreshPage();
        controller.refreshPage2();
        
        //Kammy starts:
        controller.ObjAPIName = 'Account';
        controller.parentID = String.valueof(a.id);
        controller.parentField = 'ParentId';
        controller.recordtypeName = '';
        controller.fields = 'PersonDoNotCall,AnnualRevenue,PersonMobilePhone,ASI_KOR_Venue_PR_Market_Share__c';
        controller.fieldsLabel = 'DoNotCall,Annual Revenue,mobile,PRK_MS';
        controller.lookupEXID = 'account/ParentId:ParentId-par';
        controller.template = 'ASI_MFM_PlanLineItemTemplate';
        controller.currentPageURL = String.valueof(a.id);
        controller.inlineVF = true;
        controller.DefaultValues = '';
        controller.upsertMode = false;
        controller.parentObjectAPIName = 'Account';
        controller.ParentObjectUploadMsg = 'Description';
        controller.contentFile = blob.valueOf('1,19,3,10');
        controller.emailNotification = true;
        controller.uploadCSVByBatch();
        
        controller.uploadCSV();
        controller.refreshPage();
        controller.refreshPage2();
        
        //Kammy starts:  KR Budget 
        controller.emailNotification = true;
        controller.ObjAPIName = 'ASI_MFM_Budget__c';
        controller.recordtypeName = 'KR Budget';
        controller.fields = 'asi_mfm_type__c,ASI_MFM_P10_Amount__c,ASI_MFM_Total_Amount__c,ASI_MFM_Fiscal_Year__c';       //API Name
        controller.fieldsLabel = 'Type,P10 Amount,Total Amount,Fiscal Year';  //Label 
        controller.template = 'ASI_KR_Budget_Tempalte';
        controller.inlineVF = true;
        controller.DefaultValues = '';
        controller.upsertMode = false;
        controller.contentFile = blob.valueOf('LE10,100,100,FY1516');
        controller.uploadCSVByBatch();
        
        controller.uploadCSV();
        controller.refreshPage();
        controller.refreshPage2();
        test.stopTest();
    }
    
    static testMethod void ASI_MFM_MassUploadByBatch_Test_2(){
        
        userrole Role_Test= new userrole(Name='XXXTrade Marketing',developerName='test');
        insert Role_Test;
        
        user u = [select userRole.developerName, ASI_MFM_Country__c,UserRoleid,CompanyName,ASI_KOR_User_Branch_Code__c from user where id = :userInfo.getUserId() limit 1]; 
        u.UserRoleid =Role_Test.id;
        u.CompanyName = 'Pernod Ricard Korea';
        u.ASI_MFM_Country__c  = 'KR';
        update u;
        
        System.runAs(u){ 
            
            Account a = new Account(name='test', recordTypeId = Global_RecordTypeCache.getRtId('AccountASI_GF_Customer'));
            insert a;
            Contact c = new Contact(accountid=a.id,firstname='James',lastname='test', recordTypeId = Global_RecordTypeCache.getRtId('ContactASI_HK_CRM_Wholesalers_Outlets'));
            insert c;
            
            Account b = new Account(recordTypeId = Global_RecordTypeCache.getRtId('AccountASI_KOR_Venue'),name = 'Venue');
            insert b;
            
            ASI_CRM_KR_MassUploadByBatchController controller = new ASI_CRM_KR_MassUploadByBatchController();
            controller.emailNotification = true;
            controller.batchMode = false;
            controller.ObjAPIName = 'Contact';
            controller.parentID = String.valueof(a.id);
            controller.parentField = 'AccountID';  
            controller.recordtypeName = 'contactType1';
            controller.fields = 'firstname,lastname,description,reportstoid,DoNotCall,Birthdate,reportstoid';
            controller.fieldsLabel = 'firstname,lastname,description,reportsto,DoNotCall,Birthdate,reportsto';
            controller.lookupEXID = 'contact/reportstoid:reportsto-lastname';
            controller.template = 'ASI_MFM_PlanLineItemTemplate';
            controller.currentPageURL = String.valueof(a.id);
            controller.inlineVF = true;
            controller.DefaultValues = 'birthdate:2013-01-01';
            controller.upsertMode = false;
            controller.parentObjectAPIName = 'Account';
            controller.ParentObjectUploadMsg = 'Description';
            
            controller.init();
            controller.filesize = 2000;
            controller.namefile = 'test.csv';
            controller.contentFile = blob.valueOf('firstname,lastname,description,DoNotCall,Birthdate,reportsto\rJohn,Test,desc,Y,2013-08-01,test\rJohn,Test,desc,N,2013-08-01,test');
            controller.uploadCSVByBatch();
            
            //Kammy starts:  POSM
            controller.currentPageURLOutput = '12';
            controller.template2 = 'string';
            controller.report = 'report';
            controller.batchMode = true;
            controller.dummyVar = true;
            controller.objName = 'ObjectName';
            controller.emailNotification = false;
            controller.ObjAPIName = 'ASI_KOR_POSM_Order_Request__c';
            controller.recordtypeName = 'New POSM Request';
            controller.fields = 'ASI_MFM_KR_POSM_Order_Request_Name__c,ASI_MFM_Total_Amount__c,ASI_MFM_KR_EmailSentTime__c';       //API Name
            controller.fieldsLabel = 'POSM Order Request Name,Total Amount,Email Sent Time';  //Label 
            controller.template = 'ASI_KR_POSM_Tempalte';
            controller.inlineVF = true;
            controller.DefaultValues = '';
            controller.upsertMode = false;
            controller.recEXID = 'POSM Order Request Name';
            controller.recEXIDcol = 'ASI_MFM_KR_POSM_Order_Request_Name__c';
            controller.contentFile = blob.valueOf('1234500000000067,100,2015-08-01:T08:00:00');
            controller.uploadCSVByBatch();
            
            
            controller.uploadCSV();
            controller.refreshPage();
            controller.refreshPage2();
            
            controller.emailNotification = false;
            controller.ObjAPIName = 'ASI_KOR_POSM_Order_Request__c';
            controller.recordtypeName = 'New POSM Request';
            controller.fields = 'ASI_MFM_KR_POSM_Order_Request_Name__c,ASI_MFM_Total_Amount__c';       //API Name
            controller.fieldsLabel = 'POSM Order Request Name,Total Amount';  //Label 
            controller.template = 'ASI_KR_POSM_Tempalte';
            controller.inlineVF = true;
            controller.DefaultValues = '';
            controller.upsertMode = false;
            controller.recEXIDcol = 'ASI_MFM_KR_POSM_Order_Request_Name__c';
            controller.filesize = 5242881;
            controller.namefile = 'test.csv';
            controller.contentFile = blob.valueOf('"1234567",100');
            controller.currentPageURL ='';
            controller.uploadCSVByBatch();
            
            controller.uploadCSV();
            controller.refreshPage();
            controller.refreshPage2();
            
            test.startTest();     
            
            controller.emailNotification = false;
            controller.ObjAPIName = 'ASI_KOR_POSM_Order_Request__c';
            controller.recordtypeName = 'New POSM Request';
            controller.fields = 'ASI_MFM_KR_POSM_Order_Request_Name__c,ASI_MFM_Total_Amount__c,ASI_MFM_PO_External_ID1__c';       //API Name
            controller.fieldsLabel = 'POSM Order Request Name,Total Amount,PO External ID';  //Label 
            controller.template = 'ASI_KR_POSM_Tempalte';
            controller.lookupEXID = 'ASI_MFM_PO__c/ASI_MFM_PO_External_ID1__c:PO External ID&ASI_MFM_PO_External_ID__c';
            controller.inlineVF = true;
            controller.DefaultValues = '';
            controller.upsertMode = false;  
            controller.recEXIDcol = 'ASI_MFM_KR_POSM_Order_Request_Name__c';
            controller.filesize = 100;
            controller.namefile = 'test.doc';
            controller.contentFile = blob.valueOf('1234567,100');
            controller.currentPageURL ='';
            controller.uploadCSVByBatch();
            
            controller.uploadCSV();
            controller.refreshPage();
            controller.refreshPage2();
            
            
            test.stopTest();
        } 
    }
    
    
}