objects/ASI_CRM_Outlet_Type__c.object
<CustomObject>
    <description>ASI PROS Outlet Type</description>
    <label>Outlet Type</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Outlet Type No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_VN_Contract__c.object
<CustomObject>
    <description>This contract object is only for PRVN</description>
    <fields>
        <fullName>ASI_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_No_Of_Months__c</fullName>
        <formula>IF(NOT(ISBLANK(ASI_CRM_End_Date__c) || ISBLANK(ASI_CRM_Start_Date__c))
,(((YEAR(ASI_CRM_End_Date__c) - YEAR(ASI_CRM_Start_Date__c) - 1) *12) + (12 - MONTH(ASI_CRM_Start_Date__c) +1) + MONTH(ASI_CRM_End_Date__c))
, null
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>No. of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Address__c</fullName>
        <formula>ASI_CRM_Outlet_WS__r.ASI_CRM_CN_Address__c</formula>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Image__c</fullName>
        <formula>TEXT(ASI_CRM_Outlet_WS__r.ASI_CRM_Check_Image__c)</formula>
        <label>Check Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Region__c</fullName>
        <formula>TEXT(ASI_CRM_Outlet_WS__r.ASI_CRM_VN_Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Role__c</fullName>
        <label>Outlet Role</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Type__c</fullName>
        <formula>TEXT(ASI_CRM_Outlet_WS__r.ASI_CRM_VN_OutletType__c)</formula>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_WS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet/WS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (VN)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.ASI_CRM_CN_Parent_Outlet__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Contracts (VN)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Spirit_Volume_Potential__c</fullName>
        <label>Spirit Volume Potential</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Wine_Volume_Potential__c</fullName>
        <label>Wine Volume Potential</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Contract (VN)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts (VN)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_GiftBox_Request_Header__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (VN)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Gift_Box_POSM_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Outlet_Region__c</fullName>
        <formula>TEXT(ASI_CRM_Customer__r.ASI_CRM_VN_Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Time__c</fullName>
        <label>Payment Time</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Amount__c</fullName>
        <label>Amount (VND)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Channel__c</fullName>
        <label>Channel</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Contract_Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Contract_Ending_Date__c</fullName>
        <label>Ending Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Contract_Start_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Contract_Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract (VN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Can only select the approved MCF record</errorMessage>
            <filterItems>
                <field>ASI_CRM_VN_Contract__c.ASI_CRM_Contract_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Closed, Closed(Terminated), Submit for Termination</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_VN_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM VN Contract</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_VN_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM VN Capsule Agreement Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_VN_Contract__c</referenceTo>
        <relationshipLabel>All Payment Requests</relationshipLabel>
        <relationshipName>Gift_Box_POSM_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Image_Level__c</fullName>
        <label>Image Level</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Outlet_Role__c</fullName>
        <label>Outlet Role</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Spirit_Volume_Potential__c</fullName>
        <label>Spirit Volume Potential</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_VN_Wine_Volume_Potential__c</fullName>
        <label>Wine Volume Potential</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_GiftBox_Delivery_Address__c</fullName>
        <label>Address</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_GiftBox_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>All Payment Request</label>
    <nameField>
        <displayFormat>GBR-{0000000}</displayFormat>
        <label>Request Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_VN_CapsuleCS_addPaymentTime.cls
/*********************************************************************************
 * Name: ASI_CRM_VN_CapsuleCS_addPaymentTime
 * Description: 
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    ----------------------------------------
 * 23/11/2017       Kevin Choi             Created          
***********************************************************************************/
public class ASI_CRM_VN_CapsuleCS_addPaymentTime{
    public ASI_CRM_VN_CapsuleCS_addPaymentTime(){

    }

    public void executeTrigger(List<sObject> newList, Map<Id, sObject> oldMap) {
        system.debug('Execute ASI_CRM_VN_CapsuleCS_addPaymentTime()');
        List<ASI_GiftBox_Request_Header__c> requestList = (List<ASI_GiftBox_Request_Header__c>) newList;
        Map<Id, ASI_GiftBox_Request_Header__c> requestOldMap = (Map<Id, ASI_GiftBox_Request_Header__c>)oldMap;

        Set<Id> contractIdSet = new Set<Id>();

        for (ASI_GiftBox_Request_Header__c request : requestList){
            contractIdSet.add(request.ASI_CRM_VN_Contract__c);
        }
        Map<Id,ASI_CRM_VN_Contract__c> contractIdMap = new Map<Id,ASI_CRM_VN_Contract__c>([select ASI_CRM_Outlet_WS__c, ASI_CRM_Outlet_Address__c,
                                                                                           ASI_CRM_Outlet_Type__c, ASI_CRM_Type__c, ASI_CRM_Start_Date__c,
                                                                                           ASI_CRM_End_Date__c, ASI_CRM_No_Of_Months__c, ASI_CRM_Outlet_Image__c,
                                                                                           ASI_CRM_Spirit_Volume_Potential__c, ASI_CRM_Wine_Volume_Potential__c, 
                                                                                           ASI_CRM_Outlet_Role__c ,ASI_CRM_Outlet_Region__c
                                                                                           from ASI_CRM_VN_Contract__c
                                                                                           where Id IN: contractIdSet]);

        Map<Id, AggregateResult> requestHeaderCountResult = new  Map<Id, AggregateResult>([select ASI_CRM_VN_Contract__c Id, count(Id) total 
                                                                                           from ASI_GiftBox_Request_Header__c
                                                                                           where ASI_CRM_VN_Contract__c IN: contractIdSet GROUP BY ASI_CRM_VN_Contract__c]);

        system.debug('requestHeaderCountResult:'+requestHeaderCountResult);

        for (ASI_GiftBox_Request_Header__c request : requestList){
            request = copyDataFromContract(request, contractIdMap.get(request.ASI_CRM_VN_Contract__c));

            if (requestHeaderCountResult.get(request.ASI_CRM_VN_Contract__c) != null){
                Decimal paymentTime = (Decimal) (requestHeaderCountResult.get(request.ASI_CRM_VN_Contract__c)).get('total');
                request.ASI_CRM_Payment_Time__c = paymentTime + 1; 
            }else {
                request.ASI_CRM_Payment_Time__c = 1; 
            }

            if (String.isBlank(String.Valueof(request.ASI_CRM_VN_Amount__c)))
                request.ASI_CRM_VN_Amount__c = 0;               
        }
    }

    private ASI_GiftBox_Request_Header__c copyDataFromContract(ASI_GiftBox_Request_Header__c request, ASI_CRM_VN_Contract__c contract) {
        request.ASI_CRM_Customer__c                   = contract.ASI_CRM_Outlet_WS__c;
        request.ASI_GiftBox_Delivery_Address__c       = contract.ASI_CRM_Outlet_Address__c;
        request.ASI_CRM_VN_Channel__c                 = contract.ASI_CRM_Outlet_Type__c;
        request.ASI_CRM_VN_Contract_Type__c           = contract.ASI_CRM_Type__c;
        request.ASI_CRM_VN_Contract_Start_Date__c     = contract.ASI_CRM_Start_Date__c;
        request.ASI_CRM_VN_Contract_Ending_Date__c    = contract.ASI_CRM_End_Date__c;
        request.ASI_CRM_VN_Contract_Duration__c       = contract.ASI_CRM_No_Of_Months__c;
        request.ASI_CRM_VN_Image_Level__c             = contract.ASI_CRM_Outlet_Image__c;
        request.ASI_CRM_VN_Spirit_Volume_Potential__c = contract.ASI_CRM_Spirit_Volume_Potential__c;
        request.ASI_CRM_VN_Wine_Volume_Potential__c   = contract.ASI_CRM_Wine_Volume_Potential__c;
        request.ASI_CRM_VN_Outlet_Role__c             = contract.ASI_CRM_Outlet_Role__c;
        request.ASI_GiftBox_Region__c                 = contract.ASI_CRM_Outlet_Region__c;
        return request;
    }
}