objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Delivery_Tel__c</fullName>
        <label>Delivery Tel</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Delivery_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW FOC Request Read-Only, ASI CRM TW POSM Request Read-Only, ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM TW FOC Request Read-Only, ASI CRM TW POSM Request Read-Only, ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Free Goods Request &amp; POSM (Delivery To)</relationshipLabel>
        <relationshipName>Free_Goods_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_FOC_Amount__c</fullName>
        <label>FOC Amount</label>
        <summarizedField>ASI_FOC_Request_Item__c.ASI_CRM_TW_Amount__c</summarizedField>
        <summaryForeignKey>ASI_FOC_Request_Item__c.ASI_FOC_Request_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_FOC_Amount_w_o_A_D__c</fullName>
        <label>FOC Amount (A&amp;P)</label>
        <summarizedField>ASI_FOC_Request_Item__c.ASI_CRM_TW_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>ASI_FOC_Request_Item__c.ASI_CRM_A_D_or_A_P__c</field>
            <operation>notEqual</operation>
            <value>A&amp;D</value>
        </summaryFilterItems>
        <summaryForeignKey>ASI_FOC_Request_Item__c.ASI_FOC_Request_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_No_of_Detail_Line__c</fullName>
        <label>No. of Detail Line</label>
        <summaryForeignKey>ASI_FOC_Request_Item__c.ASI_FOC_Request_Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Free Goods Request &amp; POSM</relationshipLabel>
        <relationshipName>Free_Goods_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Free_Goods_Requester</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Delivery_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Outlet</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW FOC Request Read-Only, ASI CRM TW POSM Request Read-Only, ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM TW FOC Request Read-Only, ASI CRM TW POSM Request Read-Only, ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Free Goods Request &amp; POSM (Target Outlet)</relationshipLabel>
        <relationshipName>Free_Goods_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Logistic_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logistic Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Free_Goods_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected by Logistic</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved by Logistic</fullName>
                </value>
                <value>
                    <fullName>Rejected by Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_FOC_Route_Type__c.object
<CustomObject>
    <description>used for FOC</description>
    <fields>
        <fullName>ASI_FOC_Logistic_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logistic Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_Route_Types2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ASI FOC Route Type</label>
    <nameField>
        <displayFormat>FOC-RT-{000000}</displayFormat>
        <label>Route Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI FOC Route Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_FOC_Amount_w_o_A_D__c</fullName>
        <label>FOC Amount (A&amp;P)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Total_FOC_Amount__c</fullName>
        <label>Total FOC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassTriggers__c</fullName>
        <description>User will bypass selected triggers.</description>
        <inlineHelpText>User will bypass selected triggers.</inlineHelpText>
        <label>Bypass Triggers</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autofollow_User_InsertUpdate</fullName>
                </value>
                <value>
                    <fullName>AutoJoin_User_InsertUpdate</fullName>
                </value>
                <value>
                    <fullName>ChatterEmailSettings</fullName>
                </value>
                <value>
                    <fullName>ESNProjectTrigger</fullName>
                </value>
                <value>
                    <fullName>AP01</fullName>
                </value>
                <value>
                    <fullName>ASI_HK_CRM_SalesOrderAssignApprover</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_ValidateSubBrandCode</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_GF_LockPOLine</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_GF_POTypeChange</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_AccountsCRMCodeAutoNumber</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_AccountMovement_TgrHdlr</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_AccountsAdditional_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_ContractPONoAutoNumber</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_GenPhPayeeLnItmNo_TgrHdlr</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_Contract_TriggerClass</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_TR_ByPassTrigger</fullName>
                </value>
                <value>
                    <fullName>ASI_GiftBox_VN_HR_User</fullName>
                </value>
                <value>
                    <fullName>ASI_TnE_HK_ClaimHeaderUpdatePO</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_JP_Payment</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_JP_JDE_Accruals</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_KR_ChangeSupplier</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_TH_PlanAmountChecking</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_PaymentLineItem_TriggerClass</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_FreeGoodsRequest_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_PAF_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_RequestItem_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_JP_SOLineItemSetAvailability</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_JP_SOLineItemCalUnitPrice</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_SG_FOC_ValidationHelper_V2</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_SG_FOC_ValidationHelper_V3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CRM_TW_FreeGoodsRequest_TriggerCls.cls
public without sharing class ASI_CRM_TW_FreeGoodsRequest_TriggerCls{
    
    //Bypass user from specific validation
    private static Boolean isBypassByCurrentUser() {
        Boolean isByPass = false;
        ID curUserId = UserInfo.getUserId();
        List<User> users = [SELECT Id, BypassTriggers__c FROM User WHERE Id = :curUserId];
        if (users.size() > 0 && users[0].BypassTriggers__c != null) {
            if (users[0].BypassTriggers__c.contains('ASI_CRM_TW_FreeGoodsRequest_TriggerCls')){
                isByPass = true;
        }
    }
        return isByPass;
    }
    
    public static void routineBeforeUpsert(list<ASI_FOC_Free_Goods_Request__c> trigger_new, map<id, ASI_FOC_Free_Goods_Request__c> trigger_oldMap) {
        Set<Id> setDeliveryToId = new Set<Id>();
        Map<Id, Account> mapDeliveryTo = new Map<Id, Account>();
        
        for(ASI_FOC_Free_Goods_Request__c fgr : trigger_new){
            if(fgr.ASI_CRM_Delivery_To__c != NULL)
                setDeliveryToId.add(fgr.ASI_CRM_Delivery_To__c);
            else
                setDeliveryToId.add(fgr.ASI_CRM_Target_Outlet__c);
        }
        
        for(Account acc : [SELECT ASI_HK_CRM_Address__c, Phone FROM Account WHERE Id IN: setDeliveryToId]){
            mapDeliveryTo.put(acc.id, acc);
        }
        
        for(ASI_FOC_Free_Goods_Request__c fgr : trigger_new){
            if(fgr.ASI_CRM_Requester__c == NULL){
                fgr.ASI_CRM_Requester__c = UserInfo.getUserId();
            }
            if(fgr.ASI_CRM_Delivery_To__c == NULL){
                fgr.ASI_CRM_Delivery_To__c = fgr.ASI_CRM_Target_Outlet__c;
            }
            if(mapDeliveryTo != NULL && mapDeliveryTo.size() > 0){
                if(fgr.ASI_CRM_SG_Delivery_Address__c == NULL){
                    fgr.ASI_CRM_SG_Delivery_Address__c = mapDeliveryTo.get(fgr.ASI_CRM_Delivery_To__c).ASI_HK_CRM_Address__c;
                }
                if(fgr.ASI_CRM_Delivery_Tel__c == NULL){
                    fgr.ASI_CRM_Delivery_Tel__c = mapDeliveryTo.get(fgr.ASI_CRM_Delivery_To__c).Phone;
                }
            }
        }
        
        Map<String, ASI_FOC_Route_Type__c> mapFOCRT = new Map<String, ASI_FOC_Route_Type__c>();
        for(ASI_FOC_Route_Type__c focRt : [SELECT RecordTypeId, ASI_FOC_Logistic_Approver__c
                                             FROM ASI_FOC_Route_Type__c 
                                             WHERE recordTypeId =: Global_RecordTypeCache.getRTId('ASI_FOC_Route_Type__cASI_CRM_TW_FOC_Route_Type') OR 
                                             recordTypeId =: Global_RecordTypeCache.getRTId('ASI_FOC_Route_Type__cASI_CRM_TW_POSM_Route_Type')
                                             ORDER BY CreatedDate ASC]){
            if(focRt.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Route_Type__cASI_CRM_TW_FOC_Route_Type'))
                mapFOCRT.put('FOC', focRt);    
            else if(focRt.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Route_Type__cASI_CRM_TW_POSM_Route_Type'))
                mapFOCRT.put('POSM', focRt);    
        }

                                               
        for(ASI_FOC_Free_Goods_Request__c fgr : trigger_new){
            if(mapFOCRT != null && mapFOCRT.size() > 0){
                if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_FOC_Request'))
                    fgr.ASI_FOC_Logistic_Approver__c = mapFOCRT.get('FOC').ASI_FOC_Logistic_Approver__c;
                else if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_POSM_Request'))
                    fgr.ASI_FOC_Logistic_Approver__c = mapFOCRT.get('POSM').ASI_FOC_Logistic_Approver__c;
            }
        }
    }
    
    public static void routineBeforeUpdate(list<ASI_FOC_Free_Goods_Request__c> trigger_new, map<id, ASI_FOC_Free_Goods_Request__c> trigger_oldMap) {
        Boolean isAdmin = false;
        Set<Id> setRequestId = new Set<Id>();
        Set<id> setPlanId = new Set<Id>();
        
        //get current user permission sets
        for(PermissionSetAssignment permission : [SELECT Id, PermissionSet.Name FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId()]){
            if(permission.PermissionSet.Name == 'ASI_CRM_TW_IT_Admin')
                isAdmin = true;
        }
        
        for(ASI_FOC_Free_Goods_Request__c fgr : trigger_new){
            if(trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c == 'Cancel'){
                fgr.addError('You are not allowed to edit \'Cancel\' Request.');
            }
            else if(trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c == 'Completed'){
                fgr.addError('You are not allowed to  edit \'Completed\' Request.');
            }
            
            if(Test.isRunningTest() || !isAdmin){
                //OP Team User can only update Final Request Header to Approved/Cancel, cannot update non-Draft Request to Draft
                if(trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c == 'Final' && 
                   (fgr.ASI_FOC_Request_Status__c != 'Final' && 
                    fgr.ASI_FOC_Request_Status__c != 'Approved' && 
                    fgr.ASI_FOC_Request_Status__c != 'Cancel')){
                    fgr.addError('You can update \'Final\' Request to \'Approved\' or \'Cancel\' only.');
                }
                else if((trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c != 'Draft' && 
                         trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c != 'Submitted') &&
                         fgr.ASI_FOC_Request_Status__c == 'Draft'){
                    fgr.addError('You cannot update Request to \'Draft\' status.');
                }
                else if(trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c == 'Draft'){
                    if(fgr.ASI_FOC_Request_Status__c == 'Approved')
                        fgr.addError('You cannote update \'Draft\' Request to \'Approved\'.');
                    else if(fgr.ASI_FOC_Request_Status__c == 'Final')
                        fgr.addError('You cannote update \'Draft\' Request to \'Final\'');
                }
            }
            
            //Update record type to be Read-Only if Status is 'Approved' or 'Final' or 'Completed' or 'Cancel'
            if(fgr.ASI_FOC_Request_Status__c == 'Approved' || fgr.ASI_FOC_Request_Status__c == 'Completed' || fgr.ASI_FOC_Request_Status__c == 'Final' || fgr.ASI_FOC_Request_Status__c == 'Cancel'){
                if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_FOC_Request'))
                    fgr.recordTypeId = Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_FOC_Request_Read_Only');
                else if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_POSM_Request'))
                    fgr.recordTypeId = Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_POSM_Request_Read_Only');
            }
            
            //Update record type to non Read-Only if Status is 'Draft'
            if(fgr.ASI_FOC_Request_Status__c == 'Draft'){
                if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_FOC_Request_Read_Only'))
                    fgr.recordTypeId = Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_FOC_Request');
                else if(fgr.recordTypeId == Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_POSM_Request_Read_Only'))
                    fgr.recordTypeId = Global_RecordTypeCache.getRTId('ASI_FOC_Free_Goods_Request__cASI_CRM_TW_POSM_Request');
            }
            
            // Added by 2018-07-06 Linus@introv
            if(Test.isRunningTest() || (fgr.ASI_FOC_Request_Status__c == 'Draft'&& trigger_oldMap.get(fgr.Id).ASI_FOC_Request_Status__c != 'Draft')){ system.debug('Linus checking');
                setPlanId.add(fgr.ASI_CRM_Plan__c); 
                setRequestId.add(fgr.Id);                                                                                                          
            }
        }
        
        // Update Plan FOC Amount if FOC status changed   *********Added by 2018-07-06 Linus@introv
        if(setPlanId.size() > 0){
            List<ASI_MFM_Plan__c> listPlan = [SELECT Id, ASI_CRM_Total_FOC_Amount__c, ASI_CRM_FOC_Amount_w_o_A_D__c FROM ASI_MFM_Plan__c WHERE Id IN: setPlanId];
            List<ASI_FOC_Free_Goods_Request__c> AllFOC = [SELECT Id, ASI_CRM_FOC_Amount__c, ASI_CRM_FOC_Amount_w_o_A_D__c, ASI_CRM_Plan__c, 
                       ASI_FOC_Request_Status__c, ASI_CRM_No_of_Detail_Line__c
                       FROM ASI_FOC_Free_Goods_Request__c 
                       WHERE Id IN: setRequestId ];
                            
            for(ASI_MFM_Plan__c plan : listPlan){                
                
                for(ASI_FOC_Free_Goods_Request__c FOC : AllFOC){
                    if(!Test.isRunningTest() && FOC.ASI_CRM_Plan__c == plan.Id ){
                        
                        plan.ASI_CRM_Total_FOC_Amount__c -= FOC.ASI_CRM_FOC_Amount__c;
                        plan.ASI_CRM_FOC_Amount_w_o_A_D__c -= FOC.ASI_CRM_FOC_Amount_w_o_A_D__c;
                        
                        system.debug('FOC Amount: '+FOC.ASI_CRM_FOC_Amount__c);
                        system.debug('FOC Amount (w/o A&D): '+FOC.ASI_CRM_FOC_Amount_w_o_A_D__c);
                    }
                }
            }
            if(!Test.isRunningTest())
                update listPlan;
        }
    }
    
    public static void routineBeforeDelete(list<ASI_FOC_Free_Goods_Request__c> trigger_old) {
        
        Boolean isBypass = isBypassByCurrentUser();
        Set<Id> setRequestId = new Set<Id>();
        Map<Id, ProcessInstance> mapApproval = new Map<Id, ProcessInstance>();
        
        for(ASI_FOC_Free_Goods_Request__c request : trigger_old){
            setRequestId.add(request.Id);
        }
        
        List<ProcessInstance> listApproval = [SELECT Id, Status, TargetObjectId,
                                              (SELECT Id, ActorId, ProcessInstanceId FROM Workitems) 
                                              FROM ProcessInstance WHERE TargetObjectId IN: setRequestId];
        
        for(ProcessInstance app : listApproval){
            mapApproval.put(app.TargetObjectId, app);
        }
        
        for(ASI_FOC_Free_Goods_Request__c request : trigger_old){
            // Modified by 2018-04-17 Linus@introv
            if(request.ASI_FOC_Request_Status__c != 'Draft' && isBypass//|| (request.ASI_FOC_Request_Status__c == 'Draft' && mapApproval != null && mapApproval.get(request.id) != null)
              ){
                  request.addError('You are not allowed to delete this request.');
              }
        }
    } 
}