objects/ASI_CRM_TOV__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Free_Goods_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Free Goods Request</label>
        <referenceTo>ASI_FOC_Free_Goods_Request__c</referenceTo>
        <relationshipLabel>TOVs</relationshipLabel>
        <relationshipName>TOVs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SF_SO_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF SO Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TOVs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SF_SO_Request_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF SO Request Number</label>
        <referenceTo>ASI_KOR_Sales_Order_Request__c</referenceTo>
        <relationshipLabel>TOVs</relationshipLabel>
        <relationshipName>TOVs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TOV</label>
    <nameField>
        <displayFormat>TOV-{YY}{0000000}</displayFormat>
        <label>TOV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TOVs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Not Converted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Submit for Cancel</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_FOC_Delivery_Status__c</fullName>
        <label>Delivery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Request__c.object
<CustomObject>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR-{00000000}</displayFormat>
        <label>Sales Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_TOV_TriggerClass.cls
public without sharing class ASI_CRM_CN_TOV_TriggerClass {
    
    public static void routineAfterUpdate (list<ASI_CRM_TOV__c> trigger_new, map<id, ASI_CRM_TOV__c> trigger_oldMap) {
        Set<id> FOC_Set = new Set<id>();
        for(ASI_CRM_TOV__c tov: trigger_new){
            if(tov.ASI_CRM_Free_Goods_Request__c != null){
                FOC_Set.add(tov.ASI_CRM_Free_Goods_Request__c);
            }
        }
        if(FOC_Set.size() > 0) {
            for (ASI_CRM_TOV__c tov : [select ASI_CRM_Free_Goods_Request__c, ASI_CRM_Free_Goods_Request__r.ASI_FOC_Delivery_Status__c , ASI_CRM_Status__c FROM ASI_CRM_TOV__c WHERE ASI_CRM_Free_Goods_Request__c IN : FOC_Set]){
                if(tov.ASI_CRM_Status__c != 'Received' || tov.ASI_CRM_Free_Goods_Request__r.ASI_FOC_Delivery_Status__c == 'Delivered'){
                    if (FOC_Set.contains(tov.ASI_CRM_Free_Goods_Request__c)){
                        FOC_Set.remove(tov.ASI_CRM_Free_Goods_Request__c);
                    }
                }
            }
            if (FOC_Set.size() > 0) {
                List<ASI_FOC_Free_Goods_Request__c> focList = [SELECT id FROM ASI_FOC_Free_Goods_Request__c WHERE id IN: FOC_Set];
                for (ASI_FOC_Free_Goods_Request__c foc :  focList){
                    foc.ASI_FOC_Delivery_Status__c = 'Delivered';
                }
                update focList;
            }
        }
        
    }
    Public Static void routineBeforeInsert(List<ASI_CRM_TOV__c> triggerNew){
        
        Set<String> soID = new Set<String>();
        
        for(ASI_CRM_TOV__c obj : triggerNew){
            if(obj.ASI_CRM_SF_SO_Request_Number__c != NULL)
                soID.add(obj.ASI_CRM_SF_SO_Request_Number__c);
        }
        
        Map<id, ASI_KOR_Sales_Order_Request__c> mapSO = new Map<id, ASI_KOR_Sales_Order_Request__c>([SELECT id, ownerID FROM ASI_KOR_Sales_Order_Request__c WHERE Id IN : soID]);
        
        for(ASI_CRM_TOV__c obj : triggerNew){
            if(obj.ASI_CRM_SF_SO_Request_Number__c != NULL)
                obj.ASI_CRM_SF_SO_Owner__c = mapSO.get(obj.ASI_CRM_SF_SO_Request_Number__c).ownerID;
        }
    }
}