objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>SKU_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Actual_Offtake__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Actual Offtake</relationshipLabel>
        <relationshipName>ASI_CRM_Actual_Offtake</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_FromWS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From WS</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Actual Offtake (From WS)</relationshipLabel>
        <relationshipName>Actual_Offtake</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Actual Offtake</relationshipLabel>
        <relationshipName>Actual_Offtake</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Offtake_G_L_Date__c</fullName>
        <label>Offtake G/L Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Quantity__c</fullName>
        <label>Offtake</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Actual Offtake</label>
    <nameField>
        <displayFormat>AO{YY}{MM}-{0000}</displayFormat>
        <label>Actual Offtake Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Offtake</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c.object
<CustomObject>
    <description>ASI_TH_CRM_Stock_In_Trade_Detail</description>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Offtake/Stock-in-Trade Details</relationshipLabel>
        <relationshipName>Offtake_Stock_in_Trade_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Offtake/Stock-in-Trade Details</relationshipLabel>
        <relationshipName>Offtake_Stock_in_Trade_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Offtake/Stock-in-Trade Details</relationshipLabel>
        <relationshipName>Offtake_Stock_in_Trade_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_FOC__c</fullName>
        <label>FOC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Sell_In__c</fullName>
        <label>Sell-In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Total_Offtake_Final__c</fullName>
        <label>Total Offtake</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Offtake/Stock-in-Trade Detail</label>
    <nameField>
        <displayFormat>SIT-{00000}-TH</displayFormat>
        <label>SITD No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offtake/Stock-in-Trade Details</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_SG_WS_Depletion</fullName>
        <active>true</active>
        <label>ASI_CRM_SG_WS_Depletion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Sell_in__c.object
<CustomObject>
    <label>Sell-in</label>
    <nameField>
        <displayFormat>SI{YY}{MM}{0000}</displayFormat>
        <label>Sell-in Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sell-ins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_Company_Name__c</fullName>
        <label>ASI Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_RecalculateWSDepletion_Test.cls
/*********************************************************************************
 * Name: ASI_CRM_SG_RecalculateWSDepletion_Test
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 12/05/2016       Laputa:Hugo             Created
 * 03/08/2016		Laputa:Hugo				Updated. Add test setup function 
 *              
*/

@isTest
private class ASI_CRM_SG_RecalculateWSDepletion_Test {
	
    @TestSetup
    public static void setupTestData() {
        
    }
    
    public static testmethod void testRecalculateWSDepletion() {

        ASI_CRM_SG_TestClassHelper.createDataSettings();
        
        List<ASI_MFM_Sub_brand__c> subBrandList = ASI_CRM_SG_TestClassHelper.createSubBrandData();
        List<ASI_MFM_SKU_Code__c> skuList = ASI_CRM_SG_TestClassHelper.createSKUwithSubrand(subBrandList); 

        Profile p = [SELECT Id FROM Profile WHERE Name = 'ASI SG External User'];
        
        User newUser = new User(
          profileId = p.Id,
            username = 'newUser1234@newUser1234.com',
            email = 'newUser@newUser.com',
            emailencodingkey = 'UTF-8',
            localesidkey = 'en_US',
            languagelocalekey = 'en_US',
            timezonesidkey = 'America/Los_Angeles',
            alias = 'nuser',
            lastname = 'user',
            ASI_Company_Name__c = 'TestCustomer'
        );
        insert newUser;

        ASI_CRM_SG_TestClassHelper.wholesalesCustomerData customerD = new ASI_CRM_SG_TestClassHelper.wholesalesCustomerData(true, 'TestCustomer');
        ASI_CRM_SG_TestClassHelper.contractData contractD = new ASI_CRM_SG_TestClassHelper.contractData(true);

        Id wsDepletionRecTypeId = Schema.SObjectType.ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c.getRecordTypeInfosByName().get('ASI_CRM_SG_WS_Depletion').getRecordTypeId();

        List<ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c> testWsDepletionList = new List<ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c>();

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion1 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = customerD.customer.Id,
                ASI_CRM_SKU__c = skuList.get(0).Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1),
                ASI_TH_CRM_Sell_In__c = 10,
                ASI_TH_CRM_Total_Offtake_Final__c = 25,
                ASI_TH_CRM_FOC__c = 43
            );
        testWsDepletionList.add(testWsDepletion1);
            
        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion2 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = customerD.customer.Id,
                ASI_CRM_SKU__c = skuList.get(1).Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1),
                ASI_TH_CRM_Sell_In__c = 21,
                ASI_TH_CRM_Total_Offtake_Final__c = 43,
                ASI_TH_CRM_FOC__c = 51
            );
        testWsDepletionList.add(testWsDepletion2);

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion3 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = customerD.customer.Id,
                ASI_CRM_SKU__c = skuList.get(2).Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1),
                ASI_TH_CRM_Sell_In__c = 72,
                ASI_TH_CRM_Total_Offtake_Final__c = 62,
                ASI_TH_CRM_FOC__c = 12
            );
        testWsDepletionList.add(testWsDepletion3);

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion4 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = customerD.customer.Id,
                ASI_CRM_SKU__c = skuList.get(0).Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-2),
                ASI_TH_CRM_Sell_In__c = 87,
                ASI_TH_CRM_Total_Offtake_Final__c = 34,
                ASI_TH_CRM_FOC__c = 41
            );
        testWsDepletionList.add(testWsDepletion4);

        insert testWsDepletionList;

        Id actualOfftakeRecTypeId = Schema.SObjectType.ASI_TH_CRM_Actual_Offtake__c.getRecordTypeInfosByName().get('ASI CRM SG Actual Offtake').getRecordTypeId();

        List<ASI_TH_CRM_Actual_Offtake__c> testActualOfftakeList = new List<ASI_TH_CRM_Actual_Offtake__c>();

        ASI_TH_CRM_Actual_Offtake__c testActualOfftake1 = new ASI_TH_CRM_Actual_Offtake__c(
            RecordTypeId = actualOfftakeRecTypeId,
            ASI_CRM_Contract__c = contractD.contract.Id,
            ASI_CRM_FromWS__c = customerD.customer.Id,
            ASI_CRM_SKU__c = skuList.get(0).Id,
            ASI_TH_CRM_Quantity__c = 10,
            ASI_TH_CRM_Offtake_G_L_Date__c = Date.today().addMonths(-2)
        );

        testActualOfftakeList.add(testActualOfftake1);

        ASI_TH_CRM_Actual_Offtake__c testActualOfftake2 = new ASI_TH_CRM_Actual_Offtake__c(
            RecordTypeId = actualOfftakeRecTypeId,
            ASI_CRM_Contract__c = contractD.contract.Id,
            ASI_CRM_FromWS__c = customerD.customer.Id,
            ASI_CRM_SKU__c = skuList.get(1).Id,
            ASI_TH_CRM_Quantity__c = 9,
            ASI_TH_CRM_Offtake_G_L_Date__c = Date.today().addMonths(-1)
        );

        testActualOfftakeList.add(testActualOfftake2);

        insert testActualOfftakeList;
        
        testWsDepletion4.ASI_TH_CRM_Sell_In__c = 187;

        System.Test.startTest();
            update testWsDepletion4;
            Database.executeBatch(new ASI_CRM_SG_RecalculateWSDepletion_Batch());
        System.Test.stopTest();

    }

}