objects/ASI_CRM_Promotion_Mechanic__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Ad_hoc_Cash__c</fullName>
        <label>Ad-hoc ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Additional_SKU_Bottle_Qty__c</fullName>
        <label>Additional SKU (Bottle Qty)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Additional_SKU_POSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional SKU / POSM</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Promotion Mechanics (Additional SKU / POSM)</relationshipLabel>
        <relationshipName>Promotion_Mechanics1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Buy_Qty__c</fullName>
        <label>Buy (Qty)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Buy_Unit__c</fullName>
        <label>Buy (Unit)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Gift_Voucher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gift Voucher</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Promotion Mechanics (Gift Voucher)</relationshipLabel>
        <relationshipName>Promotion_Mechanics2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Other_in_Kind_Cash__c</fullName>
        <label>Other in Kind ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotion_Plan__c</fullName>
        <label>Promotion Plan</label>
        <referenceTo>ASI_CRM_Promotion_Plan__c</referenceTo>
        <relationshipLabel>Promotion Mechanics</relationshipLabel>
        <relationshipName>Promotion_Mechanics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotional_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotional SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Promotion Mechanics</relationshipLabel>
        <relationshipName>Promotion_Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Remark__c</fullName>
        <label>Remark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_Qty_Bottle__c</fullName>
        <label>Target Qty (Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Trade_Deal_Bottle_Qty__c</fullName>
        <label>Trade Deal (Bottle Qty)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Promotion Mechanic</label>
    <nameField>
        <displayFormat>PM-{YY}{MM}-{0000}</displayFormat>
        <label>Promotion Mechanic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Mechanics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Promotion_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Promotion Plan</label>
    <nameField>
        <label>Promotion Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion</description>
    <fields>
        <fullName>ASI_CRM_Promotion_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Plan</label>
        <referenceTo>ASI_CRM_Promotion_Plan__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion Detail</description>
    <fields>
        <fullName>ASI_CRM_Promotion_Mechanic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Mechanic</label>
        <referenceTo>ASI_CRM_Promotion_Mechanic__c</referenceTo>
        <relationshipLabel>Promotion Details</relationshipLabel>
        <relationshipName>Promotion_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Promotion Details</relationshipLabel>
        <relationshipName>Promotion_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_Qty_Bottle__c</fullName>
        <label>Target Qty (Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Promotion__c</fullName>
        <label>Promotion Code</label>
        <referenceTo>ASI_HK_CRM_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Details</relationshipLabel>
        <relationshipName>ASI_HK_CRM_Promotion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Promotion Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_CRM_Short_Description__c</fullName>
        <formula>IF(ASI_HK_CRM_English_Name__c = &quot;.&quot;, &quot;.&quot;, ASI_HK_CRM_English_Name__c + &quot; - &quot; +  ASI_MFM_SKU_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Short Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_IsPOSProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPOSProduct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Packaging_Size__c</fullName>
        <label>Packaging Size</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Std_Bottle_Size__c</fullName>
        <label>Std. Bottle Size (Cl)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>SKU_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_PromotionLetterPDF_Ctrl.cls
/*********************************************************************************
 * Name:ASI_CRM_SG_PromotionLetterPDF_Ctrl
 * Description: Controller for promotion letter PDF (ASI_CRM_SG_PromotionLetterPDF_Com)
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 04/04/2018       Hugo Cheung             Created
*********************************************************************************/
public class ASI_CRM_SG_PromotionLetterPDF_Ctrl {
    
    //Component Parameters
    public String promotionId        {get; set;}
    public String customerId         {get; set;}
    public String contactName        {get; set;}
    public String contactDesignation {get; set;}
    public String contactNumber      {get; set;}
    
    //Public Data Storage Parameters
    public ASI_CRM_AccountsAdditionalField__c customer               {get; set;}
    public ASI_HK_CRM_Promotion__c promotion                         {get; set;}
    public List<ASI_CRM_Promotion_Mechanic__c> promotionMechanicList {get; set;}
    public List<ASI_HK_CRM_Promotion_Detail__c> promotionDetailList {get; set;}
    
    //Page parameter
    public Boolean isPageInit { get { if(isPageInit != true) {isPageInit = init();} return isPageInit;} set;}
    
    public ASI_CRM_SG_PromotionLetterPDF_Ctrl() {
    }
    
    public Boolean init() {
        customer  = retrieveCustomer(customerId);
        promotion = retrievePromotion(promotionId);
        promotionMechanicList = retrievePromotionMechanicList(promotion.ASI_CRM_Promotion_Plan__c);
        promotionDetailList = retrievePromotionDetailList(promotionId, customerId);
    	return true;
    }
    
    /***************
    Data Retrievement Function
    ***************/
    private ASI_CRM_AccountsAdditionalField__c retrieveCustomer(Id customerId) {
    	String query = 'SELECT Id, ASI_CRM_Legal_Outlet_Name__c, ASI_CRM_Business_Registration_Number__c '
                     + ', ASI_CRM_JP_City_Ward__c, ASI_CRM_JP_Town__c, ASI_CRM_Street_Number__c '
                     + 'FROM ASI_CRM_AccountsAdditionalField__c '
                     + 'WHERE Id = :customerId ';
       	
        List<ASI_CRM_AccountsAdditionalField__c> customerList = (List<ASI_CRM_AccountsAdditionalField__c>) Database.query(query);
        return customerList.size() > 0 ? customerList.get(0) : null;
    }
    
    private ASI_HK_CRM_Promotion__c retrievePromotion(Id promotionId) {
    	String query = 'SELECT Id, ASI_CRM_Promotion_Plan__c, ASI_CRM_Promotion_Plan__r.Name, '
                     + 'ASI_CRM_Promotion_Plan__r.ASI_CRM_Start_Date__c, ASI_CRM_Promotion_Plan__r.ASI_CRM_End_Date__c '
                     + 'FROM ASI_HK_CRM_Promotion__c '
                     + 'WHERE Id = :promotionId ';
        
        List<ASI_HK_CRM_Promotion__c> promotionPlanList = (List<ASI_HK_CRM_Promotion__c>) Database.query(query);
        return promotionPlanList.size() > 0 ? promotionPlanList.get(0) : null;
    }
    
    private List<ASI_CRM_Promotion_Mechanic__c> retrievePromotionMechanicList(Id promotionPlanId) {
        String query = 'SELECT Id, ASI_CRM_Target_Qty_Bottle__c, ASI_CRM_Buy_Qty__c, ASI_CRM_Buy_Unit__c, ASI_CRM_Additional_SKU_POSM__c, '
                     + 'ASI_CRM_Promotional_SKU__r.ASI_CRM_Short_Description__c, ASI_CRM_Trade_Deal_Bottle_Qty__c, '
                     + 'ASI_CRM_Additional_SKU_Bottle_Qty__c, ASI_CRM_Additional_SKU_POSM__r.ASI_CRM_Short_Description__c, '
                     + 'ASI_CRM_Ad_hoc_Cash__c, '
                     + 'ASI_CRM_Gift_Voucher__r.ASI_CRM_Short_Description__c, ASI_CRM_Gift_Voucher__r.Name, '
                     + 'ASI_CRM_Other_in_Kind_Cash__c '
                     + 'FROM ASI_CRM_Promotion_Mechanic__c '
                     + 'WHERE ASI_CRM_Promotion_Plan__c = :promotionPlanId ';
        
        return (List<ASI_CRM_Promotion_Mechanic__c>) Database.query(query);
    }
    
    private List<ASI_HK_CRM_Promotion_Detail__c> retrievePromotionDetailList(Id promotionId, Id customerId) {
        String query = 'SELECT Id, ASI_CRM_Target_Qty_Bottle__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Buy_Qty__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Buy_Unit__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__c, '
                     + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Promotional_SKU__r.ASI_CRM_Short_Description__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Trade_Deal_Bottle_Qty__c, '
                     + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_Bottle_Qty__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__r.ASI_CRM_Short_Description__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__r.ASI_HK_CRM_IsPOSProduct__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Promotional_SKU__r.ASI_HK_CRM_Packaging_Size__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Promotional_SKU__r.ASI_HK_CRM_Std_Bottle_Size__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Promotional_SKU__r.ASI_MFM_Sub_brand__r.ASI_MFM_Sub_brand_Description__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__r.ASI_HK_CRM_Packaging_Size__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__r.ASI_HK_CRM_Std_Bottle_Size__c, '
            		 + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Additional_SKU_POSM__r.ASI_MFM_Sub_brand__r.ASI_MFM_Sub_brand_Description__c, '
                     + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Ad_hoc_Cash__c, '
                     + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Gift_Voucher__r.ASI_CRM_Short_Description__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Gift_Voucher__r.Name, '
                     + 'ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Other_in_Kind_Cash__c, ASI_CRM_Promotion_Mechanic__r.ASI_CRM_Remark__c '
                     + 'FROM ASI_HK_CRM_Promotion_Detail__c '
                     + 'WHERE ASI_HK_CRM_Promotion__c = :promotionId '
                     + 'AND ASI_CRM_SG_Customer__c = :customerId ';
        
        return (List<ASI_HK_CRM_Promotion_Detail__c>) Database.query(query);
    }
}