objects/ASI_DFPM_Project_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Promotional_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotional Project</label>
        <referenceTo>ASI_DFPM_Promotional_Project__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Promotional_Project__c.object
<CustomObject>
    <label>Promotional Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_DFPM_PromotionalMstParentSummaryUP.cls
public without sharing class ASI_DFPM_PromotionalMstParentSummaryUP extends ASI_DFPM_TriggerAbstract {
	
	public ASI_DFPM_PromotionalMstParentSummaryUP() {
		super('ASI_DFPM_PromotionalMstParentSummaryUP');
	}
	
	public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
		if (tAction == TriggerAction.AFTER_INSERT || tAction == TriggerAction.AFTER_UPDATE
			|| tAction == TriggerAction.AFTER_DELETE || tAction == TriggerAction.AFTER_UNDELETE) {
			Set<ID> parentPjIdSet = new Set<ID>();
			List<ASI_DFPM_Project_Milestone__c> mstList = (List<ASI_DFPM_Project_Milestone__c>)sObjList;
			for (ASI_DFPM_Project_Milestone__c mst : mstList) {
				if (mst.ASI_DFPM_Promotional_Project__c != null) {
					parentPjIdSet.add(mst.ASI_DFPM_Promotional_Project__c);
				}
			}
			if (parentPjIdSet.size() > 0) {
				ASI_DFPM_PromotionalPjStatisticManager pjStatisticManager = new ASI_DFPM_PromotionalPjStatisticManager();
				List<ASI_DFPM_Promotional_Project__c> parentPjList = pjStatisticManager.getRefreshedProjects(parentPjIdSet);
				update parentPjList;
			}
		}
	}
}