objects/ASI_MFM_A_C_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <label>A/C Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>A/C Code</label>
    <nameField>
        <label>A/C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/C Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_TH_CRM_Sub_brand_Code__c</fullName>
        <formula>ASI_MFM_Sub_brand__r.ASI_MFM_Sub_brand_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-brand Code</label>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_PaymentRequestLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_AC_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>Payment Request Line Items</relationshipLabel>
        <relationshipName>Payment_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Actual_Vol__c</fullName>
        <label>Actual Vol (Std. Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Target_BT__c</fullName>
        <label>Target (Std. Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_MY_Adjusted_Amount__c</fullName>
        <label>Adjusted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Payment Request Line Items</relationshipLabel>
        <relationshipName>Payment_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SetupCode__c</fullName>
        <label>Setup Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Payment_Request__c</fullName>
        <label>Payment Request</label>
        <referenceTo>ASI_TH_CRM_PaymentRequest__c</referenceTo>
        <relationshipLabel>Payment Request Line Items</relationshipLabel>
        <relationshipName>ASI_TH_CRM_PRLI_PaymentRequest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Request Line Item</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Payment Request Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_MY_PaymentRequestReportCtl.cls
/*********************************************************************************
 * Name: ASI_CRM_MY_PaymentRequestReportCtl
 * Description: Controller class for ASI_CRM_MY_PaymentRequestReportPage
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 2015-01-06       Daniel WONG             Created 
 */


public with sharing class ASI_CRM_MY_PaymentRequestReportCtl{
        
    private ApexPages.StandardController standardController {get;set;}
    private Id PaymentRequestId{
        get{
            if (this.standardController!=null){
                return this.standardController.getId();                                 
            }
            return null;
        }
    }
    
    public decimal total{get; set;} {total = 0;}
    public decimal nettotal{get; set;} {nettotal = 0;}
    public decimal taxtotal{get; set;} {taxtotal = 0;}
    
    public list<ASI_TH_CRM_PaymentRequestLineItem__c> getPaymentLineItem(){    
        List<ASI_TH_CRM_PaymentRequestLineItem__c> lstSalesTarget = [
            SELECT id, ASI_CRM_SKU__r.Name, ASI_CRM_SKU__r.ASI_TH_CRM_Sub_brand_Code__c, ASI_CRM_CN_Actual_Vol__c, ASI_CRM_CN_Target_BT__c, ASI_TH_CRM_Amount__c,
                   ASI_CRM_SetupCode__c, ASI_CRM_CN_AC_Code__r.ASI_MFM_A_C_Code__c,
                   ASI_CRM_Net_Amount__c, ASI_CRM_Tax_Amount__c, ASI_CRM_MY_Adjusted_Amount__c
            FROM ASI_TH_CRM_PaymentRequestLineItem__c
            WHERE ASI_TH_CRM_Payment_Request__c = :PaymentRequestId
            ORDER BY ASI_CRM_SKU__r.Name
        ];
        
        for(ASI_TH_CRM_PaymentRequestLineItem__c i : lstSalesTarget ){
            if(i.ASI_TH_CRM_Amount__c != NULL) {
                total = total + i.ASI_TH_CRM_Amount__c;
                //total += i.ASI_CRM_MY_Adjusted_Amount__c;
            }
            if(i.ASI_CRM_MY_Adjusted_Amount__c != NULL) {
                //nettotal += i.ASI_CRM_Net_Amount__c;
                nettotal += i.ASI_CRM_MY_Adjusted_Amount__c;
            }
            if(i.ASI_CRM_Tax_Amount__c != NULL) {
                taxtotal += i.ASI_CRM_Tax_Amount__c;
            }
        }
          
        return lstSalesTarget;
    }
        
    public ASI_CRM_MY_PaymentRequestReportCtl(ApexPages.StandardController standardController){
        this.standardController = standardController;
    }
}