objects/ASI_MFM_PO__c.object
<CustomObject>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimDetail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_ClaimHeader__c</fullName>
        <label>Travel &amp; Entertainment Claim</label>
        <referenceTo>ASI_TnE_ClaimHeader__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>ASI_TnE_ClaimDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travel &amp; Entertainment Claim Detail</label>
    <nameField>
        <displayFormat>TED-{YY}-{00000}</displayFormat>
        <label>Claim Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimHeader__c.object
<CustomObject>
    <label>Travel &amp; Entertainment Claim</label>
    <nameField>
        <displayFormat>TE-{YY}-{00000}</displayFormat>
        <label>Travel &amp; Entertainment Claim Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_TnE_TW_ClaimHeaderTriggerClass_Test.cls
/**********************************************************************************
 * Name : ASI_CRM_SG_ContractCloneController
 * Created : DC @02/02/2016 12:58 PM
 * Revision History:
 * 1. 02/02/2016 - [DC 1.0] Created
 **********************************************************************************/

@isTest
private class ASI_TnE_TW_ClaimHeaderTriggerClass_Test {
 
    private static TestMethod void testDeletionWithoutDetails() {

        ASI_MFM_PO__c testPo = ASI_TnE_TW_TestClassHelper.createPO();
        System.Test.startTest();
        ASI_TnE_ClaimHeader__c testHeader =
            ASI_TnE_TW_TestClassHelper.createClaimHeader('Inv-0001', 'ASI_TnE_ClaimHeader__cASI_TnE_TW_Claim_Header');

        insert testHeader;
        delete testHeader;
        System.Test.stopTest();

    }

    private static TestMethod void testDeletionWithDetails() {

        ASI_MFM_PO__c testPo = ASI_TnE_TW_TestClassHelper.createPO();
        System.Test.startTest();
        ASI_TnE_ClaimHeader__c testHeader =
            ASI_TnE_TW_TestClassHelper.createClaimHeader('Inv-0001', 'ASI_TnE_ClaimHeader__cASI_TnE_TW_Claim_Header');

        insert testHeader;
        ASI_TnE_ClaimDetail__c testDetail =
            ASI_TnE_TW_TestClassHelper.createClaimDetail(
                testHeader.Id,
                'ASI_TnE_ClaimDetail__cASI_TnE_TW_Claim_Detail',
                testPo.Id
            );

        insert testDetail;
        delete testHeader;
        System.Test.stopTest();

    }
}