objects/ASI_FOC_Expensive_Items__c.object
<CustomObject>
    <fields>
        <fullName>ASI_FOC_SRP0__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI FOC Expensive Item</label>
    <nameField>
        <displayFormat>FOC-EI-{0000}</displayFormat>
        <label>FOC Expensive Items Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI FOC Expensive Items</pluralLabel>
    <recordTypes>
        <fullName>HK_FOC_Expensive_Items</fullName>
        <active>true</active>
        <label>HK FOC Expensive Items</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_FOC_Is_Premium__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Premium</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_SRP0__c</fullName>
        <label>Fastar for CCC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_FOC_HK_SKU_TriggerClass.cls
public class ASI_FOC_HK_SKU_TriggerClass {

    public static void routineBeforeUpsert(list<ASI_MFM_SKU_Code__c> trigger_new, map<id, ASI_MFM_SKU_Code__c> trigger_oldMap) {
// Check for Is Premium Item
        RecordType hkExpRT = [select id from RecordType where DeveloperName = 'HK_FOC_Expensive_Items' and SobjectType = 'ASI_FOC_Expensive_Items__c' limit 1];
        List<ASI_FOC_Expensive_Items__c> expList = [select ASI_FOC_SRP0__c from ASI_FOC_Expensive_Items__c where RecordTypeId = :hkExpRT.Id];
        set<String> exp_set = new set<String>();
        
        for (ASI_FOC_Expensive_Items__c exp :expList){
            exp_set.add(exp.ASI_FOC_SRP0__c);
        }
        
        if (trigger_new != null) {
            for (ASI_MFM_SKU_Code__c sku:trigger_new) {
                if (exp_set.contains(sku.ASI_FOC_SRP0__c)){
                    sku.ASI_FOC_Is_Premium__c = true;
                }
            }
        }
    }
}