objects/ASI_CRM_CN_PH_Payee_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Payee_Name_T1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee Name (T1)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler (CN)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Payee</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Payment Header Payee Line Item (Payee Name (T1))</relationshipLabel>
        <relationshipName>Payment_Header_Payee_Line_Itme</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Payee_Name_T2_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee Name (T2)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler (CN)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Payee</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Payment Header Payee Line Item (Payee Name (T2))</relationshipLabel>
        <relationshipName>Payment_Header_Payee_Line_Itme1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Payee_T1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payee (T1)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Outlet, Wholesales (CN)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Header Payee Line Item (Payee (T1))</relationshipLabel>
        <relationshipName>Payment_Header_Payee_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Payee_T2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payee (T2)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Outlet, Wholesales (CN)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Header Payee Line Item (Payee (T2))</relationshipLabel>
        <relationshipName>Payment_Header_Payee_Line_Item1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Header Payee Line Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payment Header Payee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Header Payee Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_Payee_TriggerClass.cls
public without sharing class ASI_CRM_CN_Payee_TriggerClass {
public ASI_CRM_CN_Payee_TriggerClass (){}
    
    public static void routineBeforeUpsert(list<ASI_CRM_CN_PH_Payee_Line_Item__c> trigger_new, map<id, ASI_CRM_CN_PH_Payee_Line_Item__c> trigger_oldMap) {
		Set<ID> AccountID = new Set<ID>();
		for(ASI_CRM_CN_PH_Payee_Line_Item__c p: trigger_new) {
            if(p.ASI_CRM_CN_Payee_T2__c != null)
            {
                if(!AccountID.contains(p.ASI_CRM_CN_Payee_T2__c))
                    AccountID.add(p.ASI_CRM_CN_Payee_T2__c);
            }
			if(p.ASI_CRM_CN_Payee_T1__c != null)
            {
                if(!AccountID.contains(p.ASI_CRM_CN_Payee_T1__c))
                    AccountID.add(p.ASI_CRM_CN_Payee_T1__c);
            }
        }
        Map<id, id> AccountMap = new Map<id, id>();
        for(ASI_CRM_AccountsAdditionalField__c c : [SELECT id, ASI_CRM_Account__c FROM ASI_CRM_AccountsAdditionalField__c WHERE ASI_CRM_Account__c in: AccountID])
        {
            if(!AccountMap.containsKey(c.ASI_CRM_Account__c))
                AccountMap.put(c.ASI_CRM_Account__c, c.id);
        }
    
		for(ASI_CRM_CN_PH_Payee_Line_Item__c p: trigger_new) {
            if(p.ASI_CRM_CN_Payee_T2__c != null && AccountMap.containsKey(p.ASI_CRM_CN_Payee_T2__c))
            {
				p.ASI_CRM_CN_Payee_Name_T2_lookup__c = AccountMap.get(p.ASI_CRM_CN_Payee_T2__c);
            }
			if(p.ASI_CRM_CN_Payee_T1__c != null && AccountMap.containsKey(p.ASI_CRM_CN_Payee_T1__c))
            {
				p.ASI_CRM_CN_Payee_Name_T1__c = AccountMap.get(p.ASI_CRM_CN_Payee_T1__c);
            }
        }
    }    
}