objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_FOC_Account_DA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (DA)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Please select correct Account (DA)</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (HK), JDE Salesman Cash Account (HK)</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_IsDeliveryAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Location__c</field>
                <operation>notEqual</operation>
                <value>#_MACDPLOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Free Goods Request &amp; POSM</relationshipLabel>
        <relationshipName>Free_Goods_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Trade A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Structure Cost</fullName>
                </value>
                <value>
                    <fullName>Logistic Cost</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Wine/Spirits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_FOC_Route_Type__c.object
<CustomObject>
    <description>used for FOC</description>
    <fields>
        <fullName>ASI_FOC_Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For HK FOC, HS/MKT Director</description>
        <inlineHelpText>For HK FOC, HS/MKT Director</inlineHelpText>
        <label>Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_Route_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Finance_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_Finance_Director</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_LUX_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LUX Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_LUX_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Line_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For HK FOC</description>
        <inlineHelpText>For HK FOC</inlineHelpText>
        <label>Line Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_Route_Types1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Sales_POS_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales POS Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_FOC_Sales_POS_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ASI FOC Route Type</label>
    <nameField>
        <displayFormat>FOC-RT-{000000}</displayFormat>
        <label>Route Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI FOC Route Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_ThresholdValues__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All threshold values for HK CRM</description>
    <fields>
        <fullName>ASI_HK_CRM_SO_Urgent_Cutoff_Time_1__c</fullName>
        <defaultValue>&apos;00:00&apos;</defaultValue>
        <description>The cut-off time of urgent order limit</description>
        <inlineHelpText>Format: hh:mm</inlineHelpText>
        <label>SO: Urgent Order Cut-off Time 1 (GMT)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_SO_Urgent_Cutoff_Time_2__c</fullName>
        <label>SO: Urgent Order Cut-off Time 2 (GMT)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Threshold Values (HK CRM)</label>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Is_FOC_PO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FOC PO?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_JDE_FOC_Return_Amount__c</fullName>
        <label>JDE FOC Return Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Net_off_FOC_PO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Net off FOC PO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prefix</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Prefix__c.ASI_MFM_Module__c</field>
                <operation>equals</operation>
                <value>PO, Direct PO, Dummy PO</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Partial Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sys_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sys_Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Prefix__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>Direct Payment</fullName>
                </value>
                <value>
                    <fullName>Direct PO</fullName>
                </value>
                <value>
                    <fullName>Dummy Payment</fullName>
                </value>
                <value>
                    <fullName>Dummy PO</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Budget</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Payment</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Accrual</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Rental Payment</fullName>
                </value>
                <value>
                    <fullName>Accrual PO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ASI MFM Prefix</label>
    <nameField>
        <label>Prefix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI MFM Prefixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Role_Prefix_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <label>Prefix</label>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>ASI MFM Role Prefix Relationships</relationshipLabel>
        <relationshipName>ASI_MFM_Role_Prefix_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_MFM_Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI MFM Role Prefix Relationship</label>
    <nameField>
        <displayFormat>RPR{000000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI MFM Role Prefix Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_FOC_Inventory__c</fullName>
        <label>FOC Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Stock_Price__c</fullName>
        <label>Stock Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_FOC_HK_TestClass_DL.cls
@isTest 
private class ASI_FOC_HK_TestClass_DL {

    static testMethod void testTriggers_MKT_Normal() {
        ASI_HK_CRM_ThresholdValues__c threshold = new ASI_HK_CRM_ThresholdValues__c(ASI_HK_CRM_SO_Urgent_Cutoff_Time_1__c = '10:00', ASI_HK_CRM_SO_Urgent_Cutoff_Time_2__c = '16:00');
        insert threshold;
        
        user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        ASI_FOC_Route_Type__c rt = new ASI_FOC_Route_Type__c(ASI_FOC_Role_Name__c = u.userRole.developerName, ASI_FOC_Department__c = 'Marketing', ASI_FOC_Line_Manager__c = u.id, ASI_FOC_Director__c = u.id, ASI_FOC_Sales_POS_Approver__c = u.id, ASI_FOC_LUX_Approver__c = u.id, ASI_FOC_Finance_Director__c = u.id, recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Route_Type__cASI_FOC_HK_Route_Type'));
        insert rt;

        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id
            , ASI_MFM_Sys_Approver_2__c = u.id);
        insert po;
        
        ASI_MFM_SKU_Code__c sku = new ASI_MFM_SKU_Code__c(recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), Name = 'Testing SKU', ASI_FOC_Stock_Price__c  = 10, ASI_MFM_SKU_Code__c = 'Testing SKU', ASI_FOC_Inventory__c = 100, ASI_HK_CRM_Active__c = TRUE);
        insert sku;
        
        test.startTest();
        
        ASI_FOC_Free_Goods_Request__c fr = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales_Admin'),
            ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true, ASI_FOC_Delivery_Window_Instruction__c = 'Between', ASI_FOC_Delivery_Time_1__c = '11:00');
        insert fr;      
        
        fr.ASI_FOC_Request_Type__c = 'POS';
        fr.ASI_FOC_Delivery_Remarks__c = 'test';
        fr.ASI_FOC_Urgent_Order__c = false;
        fr.ASI_FOC_Date_of_Delivery__c = Date.today()+1;
        
        update fr;
        
        ASI_FOC_Request_Item__c ri3 = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c=fr.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku.id, ASI_FOC_Request_Quantity_Bottle__c = 10);
        insert ri3;
        
        PageReference pageRef = Page.ASI_FOC_HK_Request_NotifySalesAdminPage;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(fr);
        ASI_FOC_HK_Request_NotifySalesAdminCON con = new ASI_FOC_HK_Request_NotifySalesAdminCON(sc);
                
        con.notifySalesAdmin();
        
        test.stopTest();
    }
    
    static testMethod void testTriggers_MKT_Normal_2() {
        ASI_HK_CRM_ThresholdValues__c threshold = new ASI_HK_CRM_ThresholdValues__c(ASI_HK_CRM_SO_Urgent_Cutoff_Time_1__c = '10:00', ASI_HK_CRM_SO_Urgent_Cutoff_Time_2__c = '16:00');
        insert threshold;
        
        user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        ASI_FOC_Route_Type__c rt = new ASI_FOC_Route_Type__c(ASI_FOC_Role_Name__c = u.userRole.developerName, ASI_FOC_Department__c = 'Marketing', ASI_FOC_Line_Manager__c = u.id, ASI_FOC_Director__c = u.id, ASI_FOC_Sales_POS_Approver__c = u.id, ASI_FOC_LUX_Approver__c = u.id, ASI_FOC_Finance_Director__c = u.id, recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Route_Type__cASI_FOC_HK_Route_Type'));
        insert rt;

        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id
            , ASI_MFM_Sys_Approver_2__c = u.id);
        insert po;
        
        
        ASI_MFM_SKU_Code__c sku = new ASI_MFM_SKU_Code__c(recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), Name = 'Testing SKU', ASI_FOC_Stock_Price__c  = 10, ASI_MFM_SKU_Code__c = 'Testing SKU', ASI_FOC_Inventory__c = 100, ASI_HK_CRM_Active__c = TRUE);
        insert sku;
        
        sku.ASI_FOC_Inventory__c = 99;
        update sku;
        
        test.startTest();
        ASI_FOC_Free_Goods_Request__c fr = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales_Admin'),
            ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true, ASI_FOC_Delivery_Window_Instruction__c = 'Between', ASI_FOC_Delivery_Time_1__c = '11:00');
        insert fr;      
                
        ASI_FOC_Request_Item__c ri2 = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c=fr.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku.id, ASI_FOC_Request_Quantity_Bottle__c = 10);
        insert ri2;
        
        ri2.ASI_FOC_Request_Quantity_Bottle__c = 20;
        update ri2;
        
        delete ri2;
        
        test.stopTest();
    }
    
    static testMethod void testTriggers2_Sales_Normal() {
        user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        ASI_FOC_Route_Type__c rt = new ASI_FOC_Route_Type__c(ASI_FOC_Role_Name__c = u.userRole.developerName, ASI_FOC_Department__c = 'Sales', ASI_FOC_Line_Manager__c = u.id, ASI_FOC_Director__c = u.id, ASI_FOC_Sales_POS_Approver__c = u.id, ASI_FOC_LUX_Approver__c = u.id, ASI_FOC_Finance_Director__c = u.id, recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Route_Type__cASI_FOC_HK_Route_Type'));
        insert rt;

        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id);
        insert po;
        
        ASI_MFM_SKU_Code__c sku = new ASI_MFM_SKU_Code__c(recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), Name = 'Testing SKU', ASI_FOC_Stock_Price__c  = 10, ASI_MFM_SKU_Code__c = 'SKU1', ASI_HK_CRM_Active__c = TRUE);
        insert sku;
        
        ASI_FOC_Free_Goods_Request__c fr = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales'),
            ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true, ASI_FOC_Delivery_Window_Instruction__c = 'Between', ASI_FOC_Delivery_Time_1__c = '11:00'
                , ASI_FOC_STK_4_Count_Sales_Volume__c = false);
        insert fr;
        
        test.startTest();
        
        ASI_FOC_Request_Item__c ri = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c=fr.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku.id, ASI_FOC_Request_Quantity_Bottle__c = 1);
        insert ri;

        delete ri;
        
        test.stopTest();
    }
    
    static testMethod void testTriggers2_Sales_WineSpirit() {
        user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        ASI_FOC_Route_Type__c rt = new ASI_FOC_Route_Type__c(ASI_FOC_Role_Name__c = u.userRole.developerName, ASI_FOC_Department__c = 'Sales', ASI_FOC_Line_Manager__c = u.id, ASI_FOC_Director__c = u.id, ASI_FOC_Sales_POS_Approver__c = u.id, ASI_FOC_LUX_Approver__c = u.id, ASI_FOC_Finance_Director__c = u.id, recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Route_Type__cASI_FOC_HK_Route_Type'));
        insert rt;

        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id);
        insert po;
        
        ASI_MFM_SKU_Code__c sku = new ASI_MFM_SKU_Code__c(recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), Name = 'Testing SKU', ASI_FOC_Stock_Price__c  = 10, ASI_MFM_SKU_Code__c = 'SKU1', ASI_HK_CRM_Active__c = TRUE);
        insert sku;
        
        ASI_FOC_Free_Goods_Request__c fr = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales'),
            ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true, ASI_FOC_Delivery_Window_Instruction__c = 'Between', ASI_FOC_Delivery_Time_1__c = '11:00'
                , ASI_FOC_STK_4_Count_Sales_Volume__c = false);
        insert fr;
        
        test.startTest();
        
        fr.ASI_FOC_Delivery_Remarks__c = 'test';
        fr.ASI_FOC_Urgent_Order__c = false;
        fr.ASI_FOC_Date_of_Delivery__c = Date.today()+1;
        update fr;
        
        PageReference pageRef = Page.ASI_FOC_HK_Request_NotifySalesAdminPage;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(fr);
        ASI_FOC_HK_Request_NotifySalesAdminCON con = new ASI_FOC_HK_Request_NotifySalesAdminCON(sc);
        
        //Test no request detail line
        con.notifySalesAdmin();
        con.goBack();
        
        ASI_FOC_Request_Item__c ri2 = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c=fr.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku.id, ASI_FOC_Request_Quantity_Bottle__c = 10);
        insert ri2; 
        
        delete fr;
        
        test.stopTest();
    }
    
    static testMethod void test_ASI_FOC_HK_FreeGoodRequestCloneChildCON() {
        final Integer numOfSKU = 5;
        final Integer numOfFGReqDetail = 3;
        
        ASI_FOC_SKUGenerator skuGen = new ASI_FOC_SKUGenerator();
        ASI_FOC_FreeGoodRequestGenerator fgReqGen = new ASI_FOC_FreeGoodRequestGenerator();
        ASI_FOC_FreeGoodRequestDetailGenerator fgReqDetailGen = new ASI_FOC_FreeGoodRequestDetailGenerator();
        
        List<ASI_MFM_SKU_Code__c> skuList = new List<ASI_MFM_SKU_Code__c>();
        ASI_FOC_Free_Goods_Request__c cloneFromFGReq;
        ASI_FOC_Free_Goods_Request__c cloneToFGReq;
        List<ASI_FOC_Request_Item__c> fgReqDetailList = new List<ASI_FOC_Request_Item__c>();
        
        for (Integer i = 0; i < numOfSKU; i++) {
            skuList.add(skuGen.generateSKU(null));
        }
        insert skuList;
        
        cloneFromFGReq = fgReqGen.generateTradeFreeGoodRequest();
        insert cloneFromFGReq;
        
        for (Integer i = 0; i < numOfFGReqDetail; i++) {
            fgReqDetailList.add(fgReqDetailGen.generateFreeGoodRequestDetail(cloneFromFGReq, skuList[i]));
        }
        insert fgReqDetailList;
        
        cloneToFGReq = fgReqGen.generateTradeFreeGoodRequest();
        insert cloneToFGReq;
        
        Test.startTest();
        
        PageReference testPage = Page.ASI_FOC_FreeGoodRequestCloneChildPage;
        Map<String, String> pageParams = testPage.getParameters();
        pageParams.put(ASI_FOC_HK_FreeGoodRequestCloneChildCON.URL_PARAM_NEW_ID, cloneToFGReq.Id);
        Test.setCurrentPageReference(testPage);
        ASI_FOC_HK_FreeGoodRequestCloneChildCON testController = new ASI_FOC_HK_FreeGoodRequestCloneChildCON();
        PageReference initRedirectPage = testController.initPage();
        PageReference linkRedirectPage = testController.redirectToAnotherPage();
        String linkDisplayStr = testController.anotherPageLabel;
        
        
        pageParams.put(ASI_FOC_HK_FreeGoodRequestCloneChildCON.URL_PARAM_FROM_ID, cloneFromFGReq.Id);
        testController = new ASI_FOC_HK_FreeGoodRequestCloneChildCON();
        initRedirectPage = testController.initPage();
        
        testController.newReqId = null;
        testController.redirectToAnotherPage();
        
        List<ASI_FOC_Request_Item__c> testReqItemList = [SELECT Id FROM ASI_FOC_Request_Item__c WHERE ASI_FOC_Request_Order__c = :cloneToFGReq.Id];
        
        Test.stopTest();
    }
    
   static testMethod void test_ASI_FOC_HK_RequestDetailEditCON() {
        /*user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        final Integer numOfFGReqDetail = 2;
        
        ASI_FOC_SKUGenerator skuGen = new ASI_FOC_SKUGenerator();
        ASI_FOC_FreeGoodRequestGenerator fgReqGen = new ASI_FOC_FreeGoodRequestGenerator();
        ASI_FOC_FreeGoodRequestDetailGenerator fgReqDetailGen = new ASI_FOC_FreeGoodRequestDetailGenerator();
        
        List<ASI_MFM_SKU_Code__c> skuList = new List<ASI_MFM_SKU_Code__c>();
        ASI_MFM_SKU_Code__c sku1 = new ASI_MFM_SKU_Code__c(Name = 'SKU 1', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU1', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c  = 5, ASI_FOC_Active__c = true);
        
        ASI_MFM_SKU_Code__c sku2 = new ASI_MFM_SKU_Code__c(Name = 'SKU 2', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU2', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c    = 5, ASI_FOC_Is_Premium__c = true, ASI_FOC_Active__c = true);
        
        ASI_MFM_SKU_Code__c sku3 = new ASI_MFM_SKU_Code__c(Name = 'SKU 1', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU1', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c  = 5, ASI_FOC_Active__c = true, ASI_HK_CRM_IsPOSProduct__c  = true);
        
        ASI_MFM_SKU_Code__c sku4 = new ASI_MFM_SKU_Code__c(Name = 'SKU 2', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU2', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c    = 5, ASI_FOC_Is_Premium__c = true, ASI_FOC_Active__c = true, ASI_HK_CRM_IsPOSProduct__c = false);
            
        skuList.add(sku1);
        skuList.add(sku2);
        skuList.add(sku3);
        skuList.add(sku4);
        insert skuList;
        
        List<ASI_FOC_Request_Item__c> fgReqDetailList = new List<ASI_FOC_Request_Item__c>();        
        
        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id);
        insert po;
        
        Test.startTest();
        
        ASI_FOC_Free_Goods_Request__c fgReq = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales'),
                ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true);      
        insert fgReq;
        
        ASI_FOC_Request_Item__c ri = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c = fgReq.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku1.id, ASI_FOC_Request_Quantity_Bottle__c = 1);
        fgReqDetailList.add(ri);

        insert fgReqDetailList;
        
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(fgReqDetailList);
        
        // Initialize the page
        PageReference testPage = Page.ASI_FOC_HK_RequestDetailEditPage;
        Map<String, String> pageParams = testPage.getParameters();
        pageParams.put('id', fgReq.Id);
        pageParams.put('PARAM_PB_BTN_ID', fgReq.Id);
        pageParams.put('clone', '1');

        Test.setCurrentPageReference(testPage);
        ASI_FOC_HK_RequestDetailEditCON testCon = new ASI_FOC_HK_RequestDetailEditCON(stdSetController);
        ASI_FOC_MassCreateAndUpdateController mcauCon = new ASI_FOC_MassCreateAndUpdateController();
        ASI_FOC_SFObjSelectTableController sobjstCon = new ASI_FOC_SFObjSelectTableController();
        
        // Assign component attributes
        mcauCon.isFastModeBool = true;
        mcauCon.sObjTypeStr = 'ASI_FOC_Request_Item__c';
        mcauCon.displayFieldsStr = 'ASI_FOC_SKU__c&read=A, ASI_FOC_Request_Quantity_Bottle__c&req=T';
        mcauCon.fieldToURLParamStr = 'ASI_FOC_Request_Order__c=>id';
        mcauCon.whereStatm = 'ASI_FOC_Request_Order__c = \'' + fgReq.Id + '\'';
        mcauCon.orderByStr = 'Name';
        mcauCon.pageBlockTitleStr = 'Free Goods Request Items';
        mcauCon.successLinkStr = '/' + fgReq.Id;
        mcauCon.cancelLinkStr = '/' + fgReq.Id;
        mcauCon.modeStr = 'BOTH';
        mcauCon.isDefaultEditVal = true;
        mcauCon.isShowAllRT = true;
        mcauCon.isUseFirstRowForNew = false;
        mcauCon.myComponentKey = 'massCreateAndUpdate';
        mcauCon.myPageController = testCon.thisController;
        mcauCon.includeRecordTypesStr  = 'ASI_FOC_HK_Request_Item';
        
        sobjstCon.sObjTypeStr = 'ASI_MFM_SKU_Code__c';
        sobjstCon.displayFieldsStr = 'Name, ASI_MFM_SKU_Description__c, ASI_MFM_Sub_brand__c';
        sobjstCon.defWhereStatmStr = testCon.baseWhereStatm;
        sobjstCon.orderByStr = 'ASI_MFM_SKU_Description__c';
        sobjstCon.numOfRowInTable = 8;
        sobjstCon.myComponentKey = 'selectTable';
        sobjstCon.myPageController = testCon.thisController;
        
        Boolean initPageBool = mcauCon.dummyVar;
        initPageBool = sobjstCon.initDummyVar;
        
        // Start testing user actions
        
        // Change page number
        sobjstCon.nextPage();
        sobjstCon.lastPage();
        sobjstCon.prevPage();
        sobjstCon.firstPage();
        
        // Clone product
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        pageParams.put(mcauCon.PARAM_TRID, mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).id);
        //mcauCon.cloneRow();
        
        // Dummy test of enableForEdit
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        List<ASI_FOC_MassCreateAndUpdateController.TableRow> recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
        pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
        mcauCon.enableForEdit();
        
        // Remove cloned product
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
        pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
        mcauCon.removeNew();
        
        // Filter products
        testCon.filterName = skuList[0].Name;
        testCon.filterSKU();

        
        // Add product
        pageParams.put('PARAM_BTN_ID', 'add');
        pageParams.put('PARAM_SOBJ_ID', sobjstCon.tableEleList.get(0).sObj.Id);
        sobjstCon.triggerRowAction();
        
        // Remove old product
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        pageParams.put(mcauCon.PARAM_TRID, mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).id);
        mcauCon.deleteOld();
        
        // Remove new product
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
        pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
        mcauCon.removeNew();
        
        // Dummy test of addMoreBlankRows
        mcauCon.addMoreBlankRows();
        
        // Add product
        pageParams.put('PARAM_BTN_ID', 'add');
        pageParams.put('PARAM_SOBJ_ID', sobjstCon.tableEleList.get(0).sObj.Id);
        sobjstCon.triggerRowAction();
        
        // Set values
        mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).mySObj.put('ASI_FOC_Request_Quantity_Bottle__c', 5);
        
        // Save
        mcauCon.commitAll();
        mcauCon.cancelPage();
        
               mcauCon.clearAll();
        mcauCon.triggerPageBlockAction();
        mcauCon.addNewRow(); 
        mcauCon.refresh();
        ASI_FOC_MassCreateAndUpdateController.PageBlockActionBtn  btn = new ASI_FOC_MassCreateAndUpdateController.PageBlockActionBtn('222222','Free Goods Request');    
        
        mcauCon.cancelLinkStr = null;
        mcauCon.cancelPage();

        Test.stopTest();
*/
       user u = [select userRole.developerName from user where id = :userInfo.getUserId()];
        
        final Integer numOfFGReqDetail = 2;
        
        ASI_FOC_SKUGenerator skuGen = new ASI_FOC_SKUGenerator();
        ASI_FOC_FreeGoodRequestGenerator fgReqGen = new ASI_FOC_FreeGoodRequestGenerator();
        ASI_FOC_FreeGoodRequestDetailGenerator fgReqDetailGen = new ASI_FOC_FreeGoodRequestDetailGenerator();
        
        List<ASI_MFM_SKU_Code__c> skuList = new List<ASI_MFM_SKU_Code__c>();
        ASI_MFM_SKU_Code__c sku1 = new ASI_MFM_SKU_Code__c(Name = 'SKU 1', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU1', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c  = 5, ASI_FOC_Active__c = true, ASI_HK_CRM_Active__c = TRUE);
        
        ASI_MFM_SKU_Code__c sku2 = new ASI_MFM_SKU_Code__c(Name = 'SKU 2', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU2', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c    = 5, ASI_FOC_Is_Premium__c = true, ASI_FOC_Active__c = true, ASI_HK_CRM_Active__c = TRUE);
        
        ASI_MFM_SKU_Code__c sku3 = new ASI_MFM_SKU_Code__c(Name = 'SKU 1', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU1', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c  = 5, ASI_FOC_Active__c = true, ASI_HK_CRM_IsPOSProduct__c  = true, ASI_HK_CRM_Active__c = TRUE);
        
        ASI_MFM_SKU_Code__c sku4 = new ASI_MFM_SKU_Code__c(Name = 'SKU 2', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_HK_CRM_SKU'), ASI_FOC_Stock_Price__c = 100, ASI_MFM_SKU_Code__c = 'SKU2', 
            ASI_MFM_SKU_Description__c = 'SKU1', ASI_FOC_Inventory__c    = 5, ASI_FOC_Is_Premium__c = true, ASI_FOC_Active__c = true, ASI_HK_CRM_IsPOSProduct__c = false, ASI_HK_CRM_Active__c = TRUE);
            
        skuList.add(sku1);
        skuList.add(sku2);
        skuList.add(sku3);
        skuList.add(sku4);
        insert skuList;
        
        List<ASI_FOC_Request_Item__c> fgReqDetailList = new List<ASI_FOC_Request_Item__c>();        
        
        Account acc = new Account(recordtypeid = Global_RecordTypeCache.getRtId('AccountASI_HK_CRM_Outlet'), Name = 'Outlet HK Test Data');
        insert acc;
        
        ASI_MFM_Prefix__c pxo = new ASI_MFM_Prefix__c(name='test', ASI_MFM_Module__c ='PO', recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Prefix__cASI_MFM_HK_Prefix'));
        insert pxo; 
        
        ASI_MFM_Role_Prefix_Relationship__c pro = new ASI_MFM_Role_Prefix_Relationship__c(ASI_MFM_Prefix__c=pxo.id, ASI_MFM_Role_Name__c=u.userRole.developerName);
        insert pro;  
        
        ASI_MFM_PO__c po = new ASI_MFM_PO__c(Name = 'Test PO', recordTypeID = Global_RecordTypeCache.getRtId('ASI_MFM_PO__cASI_MFM_HK_PO_Read_Only'), ASI_MFM_Status__c = 'Final', ASI_MFM_Is_FOC_PO__c = true, ASI_MFM_Net_off_FOC_PO__c = false, ASI_MFM_JDE_FOC_Return_Amount__c = -1000, ASI_MFM_Prefix__c = pxo.id);
        insert po;
        
        Test.startTest();
        
        ASI_FOC_Free_Goods_Request__c fgReq = new ASI_FOC_Free_Goods_Request__c(ASI_FOC_Request_Type__c='Wine/Spirits', recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Free_Goods_Request__cASI_FOC_HK_Free_Goods_Request_Sales'),
                ASI_FOC_Account_DA__c = acc.id, ASI_FOC_MFM_Consumer_AP_PO_Number__c = po.id, ASI_FOC_Date_of_Delivery__c = Date.today(), ASI_FOC_Urgent_Order__c = true);      
        insert fgReq;
        
        ASI_FOC_Request_Item__c ri = new ASI_FOC_Request_Item__c(recordtypeid = Global_RecordTypeCache.getRtId('ASI_FOC_Request_Item__cASI_FOC_HK_Request_Item'), ASI_FOC_Request_Order__c = fgReq.id, ASI_FOC_Free_Good_Cost__c=100, ASI_FOC_SKU__c = sku1.id, ASI_FOC_Request_Quantity_Bottle__c = 1);
        fgReqDetailList.add(ri);

        insert fgReqDetailList;
        
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(fgReqDetailList);
        
        // Initialize the page
        PageReference testPage = Page.ASI_FOC_HK_RequestDetailEditPage;
        Map<String, String> pageParams = testPage.getParameters();
        pageParams.put('id', fgReq.Id);
        pageParams.put('PARAM_PB_BTN_ID', fgReq.Id);
        pageParams.put('clone', '1');

        Test.setCurrentPageReference(testPage);
        ASI_FOC_HK_RequestDetailEditCON testCon = new ASI_FOC_HK_RequestDetailEditCON(stdSetController);
        ASI_FOC_MassCreateAndUpdateController mcauCon = new ASI_FOC_MassCreateAndUpdateController();
        ASI_FOC_SFObjSelectTableController sobjstCon = new ASI_FOC_SFObjSelectTableController();
        
        // Assign component attributes
        mcauCon.isFastModeBool = true;
        mcauCon.sObjTypeStr = 'ASI_FOC_Request_Item__c';
        mcauCon.displayFieldsStr = 'ASI_FOC_SKU__c&read=A, ASI_FOC_Request_Quantity_Bottle__c&req=T';
        mcauCon.fieldToURLParamStr = 'ASI_FOC_Request_Order__c=>id';
        mcauCon.whereStatm = 'ASI_FOC_Request_Order__c = \'' + fgReq.Id + '\'';
        mcauCon.orderByStr = 'Name';
        mcauCon.pageBlockTitleStr = 'Free Goods Request Items';
        mcauCon.successLinkStr = '/' + fgReq.Id;
        mcauCon.cancelLinkStr = '/' + fgReq.Id;
        mcauCon.modeStr = 'BOTH';
        mcauCon.isDefaultEditVal = true;
        mcauCon.isShowAllRT = true;
        mcauCon.isUseFirstRowForNew = false;
        mcauCon.myComponentKey = 'massCreateAndUpdate';
        mcauCon.myPageController = testCon.thisController;
        mcauCon.includeRecordTypesStr  = 'ASI_FOC_HK_Request_Item';
        
        sobjstCon.sObjTypeStr = 'ASI_MFM_SKU_Code__c';
        sobjstCon.displayFieldsStr = 'Name, ASI_MFM_SKU_Description__c, ASI_MFM_Sub_brand__c';
        sobjstCon.defWhereStatmStr = testCon.baseWhereStatm;
        sobjstCon.orderByStr = 'ASI_MFM_SKU_Description__c';
        sobjstCon.numOfRowInTable = 8;
        sobjstCon.myComponentKey = 'selectTable';
        sobjstCon.myPageController = testCon.thisController;
        
        Boolean initPageBool = mcauCon.dummyVar;
        initPageBool = sobjstCon.initDummyVar;
        
        // Start testing user actions
        
        // Change page number
        sobjstCon.nextPage();
        sobjstCon.lastPage();
        sobjstCon.prevPage();
        sobjstCon.firstPage();
        
        // Clone product
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        pageParams.put(mcauCon.PARAM_TRID, mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).id);
        //mcauCon.cloneRow();
        
        // Dummy test of enableForEdit
        pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
        List<ASI_FOC_MassCreateAndUpdateController.TableRow> recordList = new List<ASI_FOC_MassCreateAndUpdateController.TableRow>();
        if (mcauCon.theRecordTypeElementList.size() > 0) {
          recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
           pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
            if (recordList.size() > 0) {
        //mcauCon.enableForEdit();
            }
        }
        
        // Remove cloned product
      pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
    if (mcauCon.theRecordTypeElementList.size() > 0) {
          recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
          pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
            if (recordList.size() > 0) {
            //mcauCon.removeNew();
            }
      }
        
        // Filter products
        testCon.filterName = skuList[0].Name;
        testCon.filterSKU();

        
        // Add product
      if (sobjstCon.tableEleList.size() > 0) {
          pageParams.put('PARAM_BTN_ID', 'add');
          pageParams.put('PARAM_SOBJ_ID', sobjstCon.tableEleList.get(0).sObj.Id);
          sobjstCon.triggerRowAction();
        }
        
        // Remove old product
      if (mcauCon.theRecordTypeElementList.size() > 0 && mcauCon.theRecordTypeElementList.get(0).myRecordList.size() > 0) {
          pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
          pageParams.put(mcauCon.PARAM_TRID, mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).id);
          //mcauCon.deleteOld();
        }
        
        // Remove new product
      if (mcauCon.theRecordTypeElementList.size() > 0) {
          pageParams.put(mcauCon.PARAM_RTID, ASI_FOC_FreeGoodRequestDetailGenerator.RT_Default);
          recordList = mcauCon.theRecordTypeElementList.get(0).myRecordList;
          pageParams.put(mcauCon.PARAM_TRID, recordList.get(recordList.size() - 1).id);
            //mcauCon.removeNew();
        }
        
        // Dummy test of addMoreBlankRows
        //mcauCon.addMoreBlankRows();
        
        // Add product
      if (sobjstCon.tableEleList.size() > 0) {
          pageParams.put('PARAM_BTN_ID', 'add');
          pageParams.put('PARAM_SOBJ_ID', sobjstCon.tableEleList.get(0).sObj.Id);
          sobjstCon.triggerRowAction();
        }
            
        // Set values
      if (mcauCon.theRecordTypeElementList.size() > 0 && mcauCon.theRecordTypeElementList.get(0).myRecordList.size() > 0) {
          mcauCon.theRecordTypeElementList.get(0).myRecordList.get(0).mySObj.put('ASI_FOC_Request_Quantity_Bottle__c', 5);
        }
        
        // Save
        //mcauCon.commitAll();
        //mcauCon.cancelPage();
        
        //       mcauCon.clearAll();
        //mcauCon.triggerPageBlockAction();
        //mcauCon.addNewRow(); 
        //mcauCon.refresh();
        ASI_FOC_MassCreateAndUpdateController.PageBlockActionBtn  btn = new ASI_FOC_MassCreateAndUpdateController.PageBlockActionBtn('222222','Free Goods Request');    
        
        mcauCon.cancelLinkStr = null;
        //mcauCon.cancelPage();

        Test.stopTest();
    }
}