objects/ASI_CRM_Region__c.object
<CustomObject>
    <description>ASI_CRM_Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_RSP__c.object
<CustomObject>
    <description>ASI_TH_CRM_RSP</description>
    <fields>
        <fullName>ASI_CRM_CN_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (CN)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN RSP</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>VN RSP</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (VN)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>RSPs</relationshipLabel>
        <relationshipName>RSP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RSP</label>
    <nameField>
        <displayFormat>RSP-{0000}-TH</displayFormat>
        <label>RSP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_VN_AccountsAdditional_TriggerCls.cls
/*********************************************************************************
 * Name:ASI_CRM_VN_AfterUpdateRegion
 * Description: Update RSP Region field when customers' Region field change
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 16/12/2014       Laputa: Patrick          Created
*********************************************************************************/

public with sharing class ASI_CRM_VN_AccountsAdditional_TriggerCls extends ASI_HK_CRM_TriggerAbstract {

    public ASI_CRM_VN_AccountsAdditional_TriggerCls() {
        super('ASI_CRM_VN_AccountsAdditional_TriggerCls');
    }
    
     public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
     
       
        List<ASI_CRM_AccountsAdditionalField__c> detailList = (List<ASI_CRM_AccountsAdditionalField__c>)sObjList; //get AccountsAdditionalField object details
        Map<Id, ASI_CRM_AccountsAdditionalField__c> customerMap = new Map<Id, ASI_CRM_AccountsAdditionalField__c>();    
        List<ASI_TH_CRM_RSP__c> rsps = new List<ASI_TH_CRM_RSP__c>();
        
        // change AccountsAdditionalField  object data list to map
        for (ASI_CRM_AccountsAdditionalField__c customer: detailList ) {
            customerMap.put(customer.Id,customer);
        }
       
        //get all rsp details related to customers      
        rsps = [select id, ASI_CRM_CN_Customer__c,ASI_CRM_Region__c from ASI_TH_CRM_RSP__c where ASI_CRM_CN_Customer__c In :customerMap.keySet()];      
         
        for(ASI_TH_CRM_RSP__c rsp : rsps){
           rsp.ASI_CRM_Region__c = customerMap.get(rsp.ASI_CRM_CN_Customer__c).ASI_CRM_VN_Region__c;
        }

        update rsps;
     
     
     }
}