objects/ASI_eForm_IT_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_IT_Action__c</fullName>
        <label>IT Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IT Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Invalid Submission</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                    <default>true</default>
                    <label>Work In Progress</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IT Change Request</label>
    <nameField>
        <displayFormat>ITCRF-{0000000}</displayFormat>
        <label>Form No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Change Requests</pluralLabel>
    <recordTypes>
        <fullName>ASI_eForm_CN_IT_Change_Request_Final</fullName>
        <active>true</active>
        <label>IT Change Request Final (CN)</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_eForm_HK_IT_Change_Request_Final</fullName>
        <active>true</active>
        <label>IT Change Request Final (HK)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_eForm_IT_Change_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_IT_Action__c</fullName>
        <label>IT Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IT Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Invalid Submission</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_IT_Change_Request__c</fullName>
        <label>IT Change Request</label>
        <referenceTo>ASI_eForm_IT_Change_Request__c</referenceTo>
        <relationshipLabel>Context Details</relationshipLabel>
        <relationshipName>IT_Change_Request_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IT Change Request Item</label>
    <nameField>
        <displayFormat>ITCRI-{0000000}</displayFormat>
        <label>Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Change Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_eForm_ITChangeRequestAfterUpdateTest.cls
@isTest
private class ASI_eForm_ITChangeRequestAfterUpdateTest
{

    @isTest
    public static void testITChangeRequestAfterUpdateError()
    {
      User currentUser = ASI_eForm_TestClassHelper.createUser();
      Map<String,User> mapUser = new Map<String,User>();
      mapUser.put('owner',currentUser);
      
      //ASI_eForm_TestClassHelper.createRunningNumbers();
      try {
      ASI_eForm_IT_Change_Request__c  itChangeRequest = ASI_eForm_TestClassHelper.createITChangeRequest(mapUser);  
      
      /*
      List<ASI_eForm_IT_Change_Request_Item__c>  itChangeReqItems = ASI_eForm_TestClassHelper.createITChangeRequestItems(itChangeRequest,mapUser);    
      itChangeRequest.ASI_eForm_Status__c = 'Final';
      RecordType hkFinalRecordType = [SELECT Id from RecordType where DeveloperName = 'ASI_eForm_HK_IT_Change_Request_Final'];
      itChangeRequest.RecordTypeId = hkFinalRecordType.Id;
      update itChangeRequest;
      */
      
      } catch (Exception e)
      {
      
      
      }
      /*
      itChangeReqItems.get(0).ASI_eForm_IT_Action__c = 'Invalid Submission';
      
      update itChangeReqItems;  
      */
    }
    
    @isTest
    public static void testITChangeRequestAfterUpdateHK()
    {
      User currentUser = ASI_eForm_TestClassHelper.createUser();
      Map<String,User> mapUser = new Map<String,User>();
      mapUser.put('owner',currentUser);
      
      ASI_eForm_TestClassHelper.createRunningNumbers();
      
      ASI_eForm_IT_Change_Request__c  itChangeRequest = ASI_eForm_TestClassHelper.createITChangeRequest(mapUser);  
      List<ASI_eForm_IT_Change_Request_Item__c>  itChangeReqItems = ASI_eForm_TestClassHelper.createITChangeRequestItems(itChangeRequest,mapUser);    
      itChangeRequest.ASI_eForm_Status__c = 'Final';
      RecordType hkFinalRecordType = [SELECT Id from RecordType where DeveloperName = 'ASI_eForm_HK_IT_Change_Request_Final'];
      itChangeRequest.RecordTypeId = hkFinalRecordType.Id;
      update itChangeRequest;
      
      itChangeReqItems.get(0).ASI_eForm_IT_Action__c = 'Invalid Submission';
      
      update itChangeReqItems;  
    
    }
    
    @isTest
    public static void testITChangeRequestAfterUpdateCN()
    {
      User currentUser = ASI_eForm_TestClassHelper.createUser();
      Map<String,User> mapUser = new Map<String,User>();
      mapUser.put('owner',currentUser);
      
      ASI_eForm_TestClassHelper.createRunningNumbers();
      
      ASI_eForm_IT_Change_Request__c  itChangeRequest = ASI_eForm_TestClassHelper.createITChangeRequestCN(mapUser);  
      List<ASI_eForm_IT_Change_Request_Item__c>  itChangeReqItems = ASI_eForm_TestClassHelper.createITChangeRequestItems(itChangeRequest,mapUser);    
      itChangeRequest.ASI_eForm_Status__c = 'Final';
      RecordType hkFinalRecordType = [SELECT Id from RecordType where DeveloperName = 'ASI_eForm_CN_IT_Change_Request_Final'];
      itChangeRequest.RecordTypeId = hkFinalRecordType.Id;
      update itChangeRequest;
      
      itChangeReqItems.get(0).ASI_eForm_IT_Action__c = 'Invalid Submission';
      
      update itChangeReqItems;  
    
    }

}