objects/ASI_HK_CRM_Channel_Local_Channel_Map__c.object
<CustomObject>
    <description>ASI HK CRM - Channel to Local Channel Mapping Object</description>
    <fields>
        <fullName>ASI_HK_CRM_Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0DM - Domestic Customer</fullName>
                </value>
                <value>
                    <fullName>1CS - Cash Sales</fullName>
                </value>
                <value>
                    <fullName>1DL - Dealer</fullName>
                </value>
                <value>
                    <fullName>1JS - Wine Shop</fullName>
                </value>
                <value>
                    <fullName>1TD - Trading/Direct Sales</fullName>
                </value>
                <value>
                    <fullName>1WH - Wholesaler</fullName>
                </value>
                <value>
                    <fullName>2BR - Bar/Lounge/Night Club/Karaoke</fullName>
                </value>
                <value>
                    <fullName>2BW - Night Club</fullName>
                </value>
                <value>
                    <fullName>2CS - Cash Sales</fullName>
                </value>
                <value>
                    <fullName>2HT - Hotel</fullName>
                </value>
                <value>
                    <fullName>2MC - Bar &amp; Restaurant</fullName>
                </value>
                <value>
                    <fullName>2MR - Bar &amp; Restaurant - High</fullName>
                </value>
                <value>
                    <fullName>2TD - Prestige Off (Wine Shop)</fullName>
                </value>
                <value>
                    <fullName>2WR - Wholesaler On (HBR)</fullName>
                </value>
                <value>
                    <fullName>3CS - Cash Sales</fullName>
                </value>
                <value>
                    <fullName>3PC - Private Customers</fullName>
                </value>
                <value>
                    <fullName>3ST - Staff Purchase</fullName>
                </value>
                <value>
                    <fullName>3TD - Trading/Direct Sales</fullName>
                </value>
                <value>
                    <fullName>3ZZ - Luxury</fullName>
                </value>
                <value>
                    <fullName>4CR - Chinese Restaurant</fullName>
                </value>
                <value>
                    <fullName>4CS - Cash Sales</fullName>
                </value>
                <value>
                    <fullName>4TD - Trading/Direct Sales</fullName>
                </value>
                <value>
                    <fullName>4WR - Western Restaurant</fullName>
                </value>
                <value>
                    <fullName>4ZZ - Chinese Restaurant - Group</fullName>
                </value>
                <value>
                    <fullName>5AL - Airlines</fullName>
                </value>
                <value>
                    <fullName>5DM - Diplomats</fullName>
                </value>
                <value>
                    <fullName>5IC - Intecom Office Sales</fullName>
                </value>
                <value>
                    <fullName>5ZZ - Others</fullName>
                </value>
                <value>
                    <fullName>6BL - Bar - Local</fullName>
                </value>
                <value>
                    <fullName>6BW - Bar - Western</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F10 - Wholesalers - Off</fullName>
                </value>
                <value>
                    <fullName>F11 - Dealers / Cash Sales</fullName>
                </value>
                <value>
                    <fullName>F12 - Japanese Store</fullName>
                </value>
                <value>
                    <fullName>F14 - Other General Trade</fullName>
                </value>
                <value>
                    <fullName>F3 - Supermarket Chain</fullName>
                </value>
                <value>
                    <fullName>F5 - Modern Wine Shop</fullName>
                </value>
                <value>
                    <fullName>N1 - Chinese Restaurants</fullName>
                </value>
                <value>
                    <fullName>N11 - Chinese Restaurants-Group</fullName>
                </value>
                <value>
                    <fullName>N3 - Prestige HBR/MOT/MC</fullName>
                </value>
                <value>
                    <fullName>N5 - MOT / HBR</fullName>
                </value>
                <value>
                    <fullName>N6 - Wholesalers - On</fullName>
                </value>
                <value>
                    <fullName>N7 - Traditional On Trade</fullName>
                </value>
                <value>
                    <fullName>P1 - P2/3 Customers (indirect)</fullName>
                </value>
                <value>
                    <fullName>ST - Staff Purchase</fullName>
                </value>
                <value>
                    <fullName>T10 - DF Sales - HK</fullName>
                </value>
                <value>
                    <fullName>T11 - DP Sales - Others</fullName>
                </value>
                <value>
                    <fullName>F1 - General Trade</fullName>
                </value>
                <value>
                    <fullName>N4 - Other HBR</fullName>
                </value>
                <value>
                    <fullName>T9 - Luxury &amp; Corporate</fullName>
                </value>
                <value>
                    <fullName>T1 - Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Pricing_Channel__c</fullName>
        <description>Pricing Channel</description>
        <label>Pricing Channel</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Channel to Local Channel Map</label>
    <nameField>
        <displayFormat>CLC-Map-{0000}</displayFormat>
        <label>Channel to Local Channel Map</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel to Local Channel Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form__c.object
<CustomObject>
    <label>Pre-Approval Form</label>
    <nameField>
        <label>Pre-Approval Form Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Approval Forms</pluralLabel>
    <recordTypes>
        <fullName>ASI_HK_Pre_Approval_Form</fullName>
        <active>true</active>
        <label>ASI HK Pre-Approval Form</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_HK_All_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Fixed_Amount__c</fullName>
        <label>Fixed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Mechanic__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mechanic</label>
        <referenceTo>ASI_HK_CRM_Pre_Approval_Form_Mechanic__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Rebate_Disc_Percent__c</fullName>
        <label>Rebate/Disc %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_SKU_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items_Link_To_PAF_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Target_Volume_Qty__c</fullName>
        <label>Target Volume Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pre-Approval Form Item</label>
    <nameField>
        <displayFormat>PAF Item -{00000000}</displayFormat>
        <label>Pre-Approval Form Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Approval Form Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form_Mechanic__c.object
<CustomObject>
    <fields>
        <fullName>ASI_HK_CRM_Mechanic_Type__c</fullName>
        <label>Mechanic Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PAF Item - FOC</fullName>
                </value>
                <value>
                    <fullName>PAF Item - FOC Bulk</fullName>
                </value>
                <value>
                    <fullName>PAF Item - Variable</fullName>
                </value>
                <value>
                    <fullName>PAF Item - Fixed Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Approval Form Mechanic</label>
    <nameField>
        <label>PAF Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Approval Form Mechanics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Brand__c.object
<CustomObject>
    <description>ASI MFM</description>
    <label>Brand</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_HK_CRM_IsPOSProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPOSProduct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>SKU_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>ASI_MFM_Brand__c</referenceTo>
        <relationshipLabel>Sub-brands</relationshipLabel>
        <relationshipName>Sub_brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_HK_CRM_PreApprovalFormDetailEditTest.cls
@isTest
public with sharing class ASI_HK_CRM_PreApprovalFormDetailEditTest {
    
    static testMethod void test_pafEditPage(){
        Test.startTest();
        ASI_HK_CRM_AccountGenerator acctGenerator = new ASI_HK_CRM_AccountGenerator();
        ASI_HK_CRM_PreApprovalFormGenerator pafGenerator = new ASI_HK_CRM_PreApprovalFormGenerator();
        ASI_HK_CRM_PreApprovalFormItemGenerator paflineGenerator = new ASI_HK_CRM_PreApprovalFormItemGenerator();
        ASI_HK_CRM_SKUGenerator skuGenerator = new ASI_HK_CRM_SKUGenerator();
        ASI_HK_CRM_RunningNumberGenerator.initPAFRunningNumber();
        ASI_HK_CRM_BrandGenerator BrandGenerator = new ASI_HK_CRM_BrandGenerator(); 
        ASI_HK_CRM_SubBrandGenerator subBrandGenerator = new ASI_HK_CRM_SubBrandGenerator();
        
        //20160410, added by Leo
        ASI_CRM_HK_PAF_All_Product__c allPrdtSetting
            = new ASI_CRM_HK_PAF_All_Product__c(Name = 'All Product - Testing', ASI_CRM_HK_isActive__c = TRUE);
        insert allPrdtSetting;
        
        ASI_HK_CRM_Channel_Local_Channel_Map__c channel 
            = new ASI_HK_CRM_Channel_Local_Channel_Map__c(ASI_HK_CRM_Channel__c = '1JS - Japanese Store'
                                                          , ASI_HK_CRM_Local_Channel__c = 'F12 - Japanese Store'
                                                          , ASI_HK_CRM_Pricing_Channel__c = '1DL');
        insert channel;
        //20160410, added by Leo
        
        Account acctCredit = acctGenerator.generateAccount('ASI_HK_CRM_Outlet');    //Credit Account
        insert acctCredit;
        //System.debug('abc1'+acctCredit.id);
        
        /*Account acctPotential = acctGenerator.generateAccount('ASI_HK_CRM_Potential_Account');    //Credit Account
        insert acctPotential;*/
        
        ASI_HK_CRM_Pre_Approval_Form__c paf = pafGenerator.generatePreApprovalForm(acctCredit, 'ASI_HK_Pre_Approval_Form');        
        Insert paf;
        
        ASI_MFM_Brand__c Brand = brandGenerator.generateBrand(); 
        Insert Brand;
        
        ASI_MFM_Sub_brand__c subBrand = subBrandGenerator.generateSubBrand(Brand);
        Insert subBrand;
        
        ASI_MFM_SKU_Code__c sku = skuGenerator.generateBasicSKU(true);
        Insert sku;        
        
        /*ASI_MFM_SKU_Code__c sku2 = skuGenerator.generateBasicSKU(true);
        sku2.ASI_MFM_Sub_brand__c = subBrand.id;
        Insert sku2;*/

        ASI_MFM_SKU_Code__c sku3 = skuGenerator.generateBasicSKU(true);
        sku3.ASI_MFM_Sub_brand__c = subBrand.id;
        sku3.ASI_HK_CRM_IsPOSProduct__c = false;
        sku3.Name = allPrdtSetting.Name;
        Insert sku3;
        
        //List<ASI_MFM_SKU_Code__c> skuList = [select id, name from ASI_MFM_SKU_Code__c where ASI_MFM_Sub_brand__c <> null];
        
        ASI_HK_CRM_Pre_Approval_Form_Mechanic__c mech1 = new ASI_HK_CRM_Pre_Approval_Form_Mechanic__c();
        mech1.ASI_HK_CRM_Mechanic_Type__c = 'PAF Item - Fixed Amount';
        Insert mech1;
        
        ASI_HK_CRM_Pre_Approval_Form_Mechanic__c mech2 = new ASI_HK_CRM_Pre_Approval_Form_Mechanic__c();
        mech2.ASI_HK_CRM_Mechanic_Type__c = 'PAF Item - Variable';
        mech2.Name = 'V-On-Invoice Discount';
        Insert mech2;
        
        ASI_HK_CRM_Pre_Approval_Form_Item__c pafline = paflineGenerator.generateBasicPreApprovalFormItem(paf,sku);
        pafline.ASI_HK_CRM_Target_Volume_Qty__c = 50;
        pafline.ASI_HK_CRM_Price__c = 200;
        pafline.ASI_HK_CRM_Mechanic__c = mech1.Id;
        pafline.ASI_HK_CRM_Fixed_Amount__c = 5;
        insert pafline;
        
        ASI_HK_CRM_Pre_Approval_Form_Item__c pafline2 = paflineGenerator.generateBasicPreApprovalFormItem(paf,sku3);
        pafline2.ASI_HK_CRM_Mechanic__c = mech2.Id;
        pafline2.ASI_HK_CRM_Rebate_Disc_Percent__c = 5;
        pafline2.ASI_CRM_HK_All_Product__c = TRUE;
		pafline2.recordTypeId = Global_RecordTypeCache.getRtId('ASI_HK_CRM_Pre_Approval_Form_Item__cASI_HK_CRM_PAF_Item_Variable');
        //insert pafline2;
        
        List<ASI_HK_CRM_Pre_Approval_Form_Item__c> paflineList = new List<ASI_HK_CRM_Pre_Approval_Form_Item__c>();
        paflineList.add(pafline);
        //paflineList.add(pafline2);
   
        
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(paflineList);
        
        PageReference testPage = Page.ASI_HK_CRM_PreApprovalFormDetailEditPage;
        Map<String, String> pageParams = testPage.getParameters();
        pageParams.put('id', paf.id);
        Test.setCurrentPageReference(testPage);
        
        ASI_HK_CRM_PreApprovalFormDetailEditCON testController = new ASI_HK_CRM_PreApprovalFormDetailEditCON(stdSetController);
       
        //ASI_HK_CRM_PreApprovalFormDetailEditCON.lineItemList(testController.headerId);
        ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem pafChange;
        ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem pafChange2;
        List<ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem> pafChangeList = new List<ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem>();
        /*
        for(Integer i = 0; i <3; i++){
            pafChange = new ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem();
            pafChange.id= String.valueOf(i);
            pafChangeList.add(pafChange);
        }
        */
        
        pafChange = new ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem();
        pafChange.id = pafline.id;
        pafChange.skuId = pafline.ASI_HK_CRM_SKU_Lookup__c;
        pafChange.mechanicId = pafline.ASI_HK_CRM_Mechanic__c;
        pafChange.qty = pafline.ASI_HK_CRM_Target_Volume_Qty__c;
        pafChange.price = pafline.ASI_HK_CRM_Price__c;
        pafChange.allPrdt = pafline.ASI_CRM_HK_All_Product__c;
        pafChange2 = new ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem();
        pafChange2.id = pafline2.id;
        pafChange2.skuId = pafline2.ASI_HK_CRM_SKU_Lookup__c;
        pafChange2.mechanicId = pafline2.ASI_HK_CRM_Mechanic__c;
        pafChange2.qty = pafline2.ASI_HK_CRM_Target_Volume_Qty__c;
        pafChange2.price = pafline2.ASI_HK_CRM_Price__c;
        pafChange2.allPrdt = pafline2.ASI_CRM_HK_All_Product__c;
        pafChangeList.add(pafChange);
        pafChangeList.add(pafChange2);
        /*
        pafChange = new ASI_HK_CRM_PreApprovalFormDetailEditCON.ASI_HK_CRM_PAFLineItem();
        pafChange.id = paf.id;
        pafChangeList.add(pafChange);
        */
        ASI_HK_CRM_PreApprovalFormDetailEditCON.lineItemList(paf.id);
        ASI_HK_CRM_PreApprovalFormDetailEditCON.normalProductList(acctCredit.id);
        ASI_HK_CRM_PreApprovalFormDetailEditCON.saveChanges(paf.id, pafChangeList);
        testController.refreshPage();
        //ASI_HK_CRM_PreApprovalFormDetailEditCON.updateLineItemFromRemote(pafline, pafChange);
        
        Test.stopTest();
    }
}