objects/ASI_CRM_Division__c.object
<CustomObject>
    <description>ASI_CRM_Division</description>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>ASI_CRM_Region__c</referenceTo>
        <relationshipLabel>Divisions</relationshipLabel>
        <relationshipName>Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Region</fullName>
        <active>true</active>
        <label>CN Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_CRM_Fix_Approval_Route__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Region_Area_Channel__c</fullName>
        <label>Division/Region/Area/Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract 1st Part</fullName>
                </value>
                <value>
                    <fullName>Contract 2nd Part</fullName>
                </value>
                <value>
                    <fullName>Payment 1st Part</fullName>
                </value>
                <value>
                    <fullName>Payment 2nd Part</fullName>
                </value>
                <value>
                    <fullName>IOM</fullName>
                </value>
                <value>
                    <fullName>WS T1</fullName>
                </value>
                <value>
                    <fullName>WS T2</fullName>
                </value>
                <value>
                    <fullName>Channel Strategy</fullName>
                </value>
                <value>
                    <fullName>WS Evaluation</fullName>
                </value>
                <value>
                    <fullName>Visual Application</fullName>
                </value>
                <value>
                    <fullName>Last Payment 1st Part</fullName>
                </value>
                <value>
                    <fullName>Last Payment 2nd Part</fullName>
                </value>
                <value>
                    <fullName>National Group Contract 1st Part</fullName>
                </value>
                <value>
                    <fullName>National Group Contract 2nd Part</fullName>
                </value>
                <value>
                    <fullName>Contract (IHBR) 1st</fullName>
                </value>
                <value>
                    <fullName>Contract (IHBR) 2nd</fullName>
                </value>
                <value>
                    <fullName>Last Payment (IHBR) 1st Part</fullName>
                </value>
                <value>
                    <fullName>Last Payment (IHBR) 2nd Part</fullName>
                </value>
                <value>
                    <fullName>Payment (IHBR) 1st Part</fullName>
                </value>
                <value>
                    <fullName>Payment (IHBR) 2nd Part</fullName>
                </value>
                <value>
                    <fullName>PR Direct</fullName>
                </value>
                <value>
                    <fullName>Receiving G(non cash)&amp;H-Trip</fullName>
                </value>
                <value>
                    <fullName>Receiving G(non cash)&amp;H-Non-Trip</fullName>
                </value>
                <value>
                    <fullName>Receiving Cash-Notification</fullName>
                </value>
                <value>
                    <fullName>Offering PO(Non-Facilitation Fees)</fullName>
                </value>
                <value>
                    <fullName>Offering H- Contract Outlet(Non-PO)</fullName>
                </value>
                <value>
                    <fullName>Offering Non-PO</fullName>
                </value>
                <value>
                    <fullName>Sales Order</fullName>
                </value>
                <value>
                    <fullName>Sales Order - HQ</fullName>
                </value>
                <value>
                    <fullName>Sales Order - IHBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sales_Team__c</fullName>
        <label>Sales Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI CRM Fix Approval Route</label>
    <nameField>
        <displayFormat>FAR{000000}</displayFormat>
        <label>ASI CRM Fix Approval Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI CRM Fix Approval Route</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Region__c.object
<CustomObject>
    <description>ASI_CRM_Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Region</fullName>
        <active>true</active>
        <label>CN Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_CRM_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division</label>
        <referenceTo>ASI_CRM_Division__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <formula>ASI_CRM_Division__r.ASI_CRM_Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Importation_Document__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>ASI_CRM_Region__c</referenceTo>
        <relationshipLabel>Importation Documents</relationshipLabel>
        <relationshipName>Importation_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Request_Purpose__c</fullName>
        <inlineHelpText>请详细填写申请目的，如不详细，审批者会拒绝文件请求</inlineHelpText>
        <label>Request Purpose</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Importation Document</label>
    <nameField>
        <displayFormat>IDN-{YY}{000000}</displayFormat>
        <label>Importation Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Importation Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <label>CRM Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CN-Admin</fullName>
                </value>
                <value>
                    <fullName>CN-GC</fullName>
                </value>
                <value>
                    <fullName>CN-GE</fullName>
                </value>
                <value>
                    <fullName>CN-GN</fullName>
                </value>
                <value>
                    <fullName>CN-GNW</fullName>
                </value>
                <value>
                    <fullName>CN-GS</fullName>
                </value>
                <value>
                    <fullName>CN-HQ</fullName>
                </value>
                <value>
                    <fullName>CN-IHBR</fullName>
                </value>
                <value>
                    <fullName>CN-Premium</fullName>
                </value>
                <value>
                    <fullName>TH-Admin</fullName>
                </value>
                <value>
                    <fullName>TH-ALL</fullName>
                </value>
                <value>
                    <fullName>TH-CorpAff</fullName>
                </value>
                <value>
                    <fullName>TH-Finance</fullName>
                </value>
                <value>
                    <fullName>TH-HR</fullName>
                </value>
                <value>
                    <fullName>TH-Marketing</fullName>
                </value>
                <value>
                    <fullName>TH-Sales-OFF</fullName>
                </value>
                <value>
                    <fullName>TH-Sales-ON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sales_Team__c</fullName>
        <label>ASI CRM Sales Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BJ IHBR-Bar &amp; Restaurant</fullName>
                </value>
                <value>
                    <fullName>BJ IHBR-Hotel</fullName>
                </value>
                <value>
                    <fullName>Central-Others</fullName>
                </value>
                <value>
                    <fullName>Central-PG</fullName>
                </value>
                <value>
                    <fullName>Central-TMK</fullName>
                </value>
                <value>
                    <fullName>Central-VIP</fullName>
                </value>
                <value>
                    <fullName>Central-WS</fullName>
                </value>
                <value>
                    <fullName>East-Others</fullName>
                </value>
                <value>
                    <fullName>East-PG</fullName>
                </value>
                <value>
                    <fullName>East-TMK</fullName>
                </value>
                <value>
                    <fullName>East-VIP</fullName>
                </value>
                <value>
                    <fullName>East-WS</fullName>
                </value>
                <value>
                    <fullName>HQ-National Contract</fullName>
                </value>
                <value>
                    <fullName>HQ-Others</fullName>
                </value>
                <value>
                    <fullName>HQ-VIP Sales</fullName>
                </value>
                <value>
                    <fullName>North-Others</fullName>
                </value>
                <value>
                    <fullName>North-PG</fullName>
                </value>
                <value>
                    <fullName>North-TMK</fullName>
                </value>
                <value>
                    <fullName>North-VIP</fullName>
                </value>
                <value>
                    <fullName>North-WS</fullName>
                </value>
                <value>
                    <fullName>NW-Others</fullName>
                </value>
                <value>
                    <fullName>NW-PG</fullName>
                </value>
                <value>
                    <fullName>NW-TMK</fullName>
                </value>
                <value>
                    <fullName>NW-VIP</fullName>
                </value>
                <value>
                    <fullName>NW-WS</fullName>
                </value>
                <value>
                    <fullName>Premium-AH MOT</fullName>
                </value>
                <value>
                    <fullName>Premium-BJ MAC</fullName>
                </value>
                <value>
                    <fullName>Premium-BJ MOT</fullName>
                </value>
                <value>
                    <fullName>Premium-CC MAC</fullName>
                </value>
                <value>
                    <fullName>Premium-CC MOT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_MFM_CN_ImportationDoc_TriggerCls.cls
public without Sharing class ASI_MFM_CN_ImportationDoc_TriggerCls {

    Private Final Static Map<String, Schema.SObjectField> importationDoc_FIELD_MAP = Schema.SObjectType.ASI_MFM_Importation_Document__c.fields.getMap();
    Private Final Static Map<String, Schema.SObjectField> FixApproval_FIELD_MAP = Schema.SObjectType.ASI_CRM_Fix_Approval_Route__c.fields.getMap();
    
    Private Static Map<Id, ASI_CRM_Region__c> regionMap = new Map<Id, ASI_CRM_Region__c>([Select id, Name From ASI_CRM_Region__c Where recordType.developerName Like 'ASI_CRM_CN_Region']);
    
    Public Static void beforeInsertFunction(List<ASI_MFM_Importation_Document__c> triggerNew){
        
        Set<Id> ownerSet = new Set<Id>();
        Map<id, ASI_CRM_Sales_Team__c> ownerRegionMap = new Map<id, ASI_CRM_Sales_Team__c>();
        Map<String, ASI_CRM_Fix_Approval_Route__c> fixApprovalMap = new Map<String, ASI_CRM_Fix_Approval_Route__c>();
        
        String whereClause = ' WHERE ASI_CRM_CN_Type__c Like \'Importation Document\' AND RecordType.developerName Like \'ASI_CRM_CN_%\'';
        
        for(ASI_CRM_Fix_Approval_Route__c obj : RetrieveFixApprovalInfo(FixApproval_FIELD_MAP, whereClause)){
            
            fixApprovalMap.put(obj.ASI_CRM_CN_Region_Area_Channel__c, obj);
        }
        
        for(ASI_MFM_Importation_Document__c obj : triggerNew){
            
            ownerSet.add(obj.ownerId);
        }
        
        ownerRegionMap = getUserRegion(ownerSet);
        
        for(ASI_MFM_Importation_Document__c obj : triggerNew){
            
            if(ownerRegionMap.containsKey(obj.ownerId)){
                
                obj.ASI_MFM_Region__c = ownerRegionMap.get(obj.OwnerId).ASI_CRM_Division__r.ASI_CRM_Region__c;
            }
            
            if(obj.ASI_MFM_Status__c == 'Draft' && obj.ASI_MFM_Region__c != Null && regionMap.containsKey(obj.ASI_MFM_Region__c) && fixApprovalMap.containsKey(regionMap.get(obj.ASI_MFM_Region__c).Name)){
                setApproverToNull(obj);
                setApprover(obj, fixApprovalMap.get(regionMap.get(obj.ASI_MFM_Region__c).Name));
            }
        }
    }
    
    Public Static void beforeUpdateFunction(List<ASI_MFM_Importation_Document__c> triggerNew, Map<Id, ASI_MFM_Importation_Document__c> triggerOldMap){
        
        Set<Id> ownerSet = new Set<Id>();
        Map<id, ASI_CRM_Sales_Team__c> ownerRegionMap = new Map<id, ASI_CRM_Sales_Team__c>();
        Map<String, ASI_CRM_Fix_Approval_Route__c> fixApprovalMap = new Map<String, ASI_CRM_Fix_Approval_Route__c>();
        
        String whereClause = ' WHERE ASI_CRM_CN_Type__c Like \'Importation Document\' AND RecordType.developerName Like \'ASI_CRM_CN_%\'';
        
        for(ASI_CRM_Fix_Approval_Route__c obj : RetrieveFixApprovalInfo(FixApproval_FIELD_MAP, whereClause)){
            
            fixApprovalMap.put(obj.ASI_CRM_CN_Region_Area_Channel__c, obj);
        }
        
        for(ASI_MFM_Importation_Document__c obj : triggerNew){
            
            if(triggerOldMap.get(obj.id).ownerId != obj.ownerId)
                ownerSet.add(obj.ownerId);
        }
        
        ownerRegionMap = getUserRegion(ownerSet);
        
        for(ASI_MFM_Importation_Document__c obj : triggerNew){
            
            if(ownerRegionMap.containsKey(obj.ownerId)){
                
                if(ownerSet.contains(obj.ownerId)){
                    obj.ASI_MFM_Region__c = ownerRegionMap.get(obj.OwnerId).ASI_CRM_Division__r.ASI_CRM_Region__c;
                }
            }
            
            if(obj.ASI_MFM_Status__c == 'Draft' && obj.ASI_MFM_Region__c != Null && regionMap.containsKey(obj.ASI_MFM_Region__c) && fixApprovalMap.containsKey(regionMap.get(obj.ASI_MFM_Region__c).Name)){
                setApproverToNull(obj);
                setApprover(obj, fixApprovalMap.get(regionMap.get(obj.ASI_MFM_Region__c).Name));
            }
            
            if(obj.ASI_MFM_Status__c == 'Submitted' && triggerOldMap.get(obj.id).ASI_MFM_Status__c == 'Draft' && (obj.ASI_MFM_Request_Purpose__c == Null || obj.ASI_MFM_Request_Purpose__c == '')){
                
                obj.ASI_MFM_Request_Purpose__c.addError('Please input Request Purpose before submission');
            }
        }
    }
    
    Public Static void setApprover(ASI_MFM_Importation_Document__c ImpDoc, ASI_CRM_Fix_Approval_Route__c fixApproval){
        
        Integer i = 1;
        Integer j = 1;
        String sysApprover = 'asi_mfm_sys_approver_' + i + '__c';
        String fixApprover = 'asi_crm_cn_approver_' + j + '__c';
        
        if(importationDoc_FIELD_MAP.containsKey(sysApprover)){
            
            user recordOwner = ASI_CRM_CN_RoleAndSubordinateHelperCLS.getUser(ImpDoc.OwnerId);
            
            if(recordOwner != Null){
                ImpDoc.put(sysApprover, recordOwner.ManagerId);
                
                i++;
                sysApprover = 'ASI_MFM_Sys_Approver_' + i + '__c';
            }
        }

        While(importationDoc_FIELD_MAP.containsKey(sysApprover) && FixApproval_FIELD_MAP.containsKey(fixApprover)){
            
            if(ImpDoc.get(sysApprover) != Null){
                
                i++;
                sysApprover = 'ASI_MFM_Sys_Approver_' + i + '__c';
                continue;
            }
            
            if(fixApproval.get(fixApprover) == Null){
                
                j++;
                fixApprover = 'ASI_CRM_CN_Approver_' + j + '__c';
                continue;
            }
            
            ImpDoc.put(sysApprover, fixApproval.get(fixApprover));
            
            i++;
            sysApprover = 'ASI_MFM_Sys_Approver_' + i + '__c';
            
            j++;
            fixApprover = 'ASI_CRM_CN_Approver_' + j + '__c';
        }
    }
    
    Public Static void setApproverToNull(ASI_MFM_Importation_Document__c ImpDoc){
        
        Integer i = 1;
        String sysApprover = 'ASI_MFM_Sys_Approver_' + i + '__c';
        
        While(importationDoc_FIELD_MAP.containsKey(sysApprover)){
            
            ImpDoc.put(sysApprover, null);
            
            i++;
            sysApprover = 'ASI_MFM_Sys_Approver_' + i + '__c';
        }
    }
    
    Public Static Map<id, ASI_CRM_Sales_Team__c> getUserRegion(Set<id> OwnerSet){
        
        Map<Id, ASI_CRM_Sales_Team__c> userRegionMap = new Map<Id, ASI_CRM_Sales_Team__c>();
        Map<String, String> userSalesTeam = new Map<String, String>();
        
        for(Id ownerid : OwnerSet){
            
            user obj = ASI_CRM_CN_RoleAndSubordinateHelperCLS.getUser(ownerid);
            
            if(obj != Null)
                userSalesTeam.put(obj.ASI_CRM_Sales_Team__c, obj.id);
        }
        
        for(ASI_CRM_Sales_Team__c obj : [SELECT id, Name, ASI_CRM_Division__r.ASI_CRM_Region__c, ASI_CRM_Division__r.ASI_CRM_Region__r.Name FROM ASI_CRM_Sales_Team__c WHERE Name IN : userSalesTeam.keySet()]){
            
            if(userSalesTeam.containsKey(obj.Name)){
                
                userRegionMap.put(userSalesTeam.get(obj.Name), obj);
            }
        }
        
        return userRegionMap;
    }
    
    Private Static List<ASI_CRM_Fix_Approval_Route__c> RetrieveFixApprovalInfo(Map<String, Schema.SObjectField> fieldMap, String whereClause) {
        
        String query = 'SELECT ' + genQueryField(fieldMap) + ' FROM ASI_CRM_Fix_Approval_Route__c ' + whereClause;
        
        List<ASI_CRM_Fix_Approval_Route__c> fixApprovalList = (List<ASI_CRM_Fix_Approval_Route__c>) Database.query(query);
        return fixApprovalList.size() > 0 ? fixApprovalList : new List<ASI_CRM_Fix_Approval_Route__c>();
    }
    
    Private Static String genQueryField(Map<String, Schema.SObjectField> fieldMap) {
        String queryField = '';
        for(String fields : fieldMap.keySet()) {
            queryField += fields + ',';
        }
        return queryField.subString(0, queryField.length() - 1);
    }
}