objects/ASI_CRM_Promotion_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Enrollment_Cut_off_Date__c</fullName>
        <inlineHelpText>Sales must enroll outlets / wholesalers before this date.</inlineHelpText>
        <label>Enrollment Cut-off Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Promotion Plan</label>
    <nameField>
        <label>Promotion Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion</description>
    <fields>
        <fullName>ASI_CRM_Promotion_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Plan</label>
        <referenceTo>ASI_CRM_Promotion_Plan__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Promotion_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Promotion Detail</description>
    <fields>
        <fullName>ASI_HK_CRM_Promotion__c</fullName>
        <label>Promotion Code</label>
        <referenceTo>ASI_HK_CRM_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Details</relationshipLabel>
        <relationshipName>ASI_HK_CRM_Promotion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Promotion Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>SKU_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_EnrollPromotionPlanTest.cls
/***************************************************************************************************************************
 * Name:        ASI_CRM_SG_EnrollPromotionPlanTest
 * Description: Test class for ASI_CRM_SG_EnrollPromotionPlan
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 2018-05-15       Jeffrey Cheung          Created
 ****************************************************************************************************************************/

@IsTest
private class ASI_CRM_SG_EnrollPromotionPlanTest {
    @IsTest static void testBehavior() {
        ASI_CRM_SG_TestClassHelper.createDataSettings();
        List<ASI_MFM_SKU_Code__c> skuList = ASI_CRM_SG_TestClassHelper.createSKUandPRiceData();

        ASI_CRM_SG_TestClassHelper.customerData customerC1 = new ASI_CRM_SG_TestClassHelper.customerData(false, 'Customer1');
        customerC1.customer.RecordtypeId = Global_RecordTypeCache.getRtId('ASI_CRM_AccountsAdditionalField__cASI_CRM_SG_Outlet');
        ASI_CRM_SG_TestClassHelper.customerData customerC2 = new ASI_CRM_SG_TestClassHelper.customerData(false, 'Customer2');
        customerC1.customer.RecordtypeId = Global_RecordTypeCache.getRtId('ASI_CRM_AccountsAdditionalField__cASI_CRM_SG_Wholesaler');

        List<ASI_CRM_AccountsAdditionalField__c> customerList = new List<ASI_CRM_AccountsAdditionalField__c>();
        customerList.add(customerC1.customer);
        customerList.add(customerC2.customer);
        insert customerList;

        ASI_CRM_Promotion_Plan__c promotionPlan = new ASI_CRM_Promotion_Plan__c(
            Name = 'testPromotionPlan',
            ASI_CRM_Start_Date__c = Date.today().toStartOfMonth(),
            ASI_CRM_End_Date__c = Date.today().addMonths(1).toStartOfMonth().addDays(-1),
            ASI_CRM_Enrollment_Cut_off_Date__c = Date.today().addDays(15),
            RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Promotion_Plan__cASI_CRM_SG_Wholesaler_Promotion_Plan')
        );
        insert promotionPlan;


        ASI_HK_CRM_Promotion__c promotion = new ASI_HK_CRM_Promotion__c(
            Name = 'testPromotionPlan',
            ASI_CRM_Promotion_Plan__c = promotionPlan.Id,
            RecordTypeId = Global_RecordTypeCache.getRtId('ASI_HK_CRM_Promotion__cASI_CRM_SG_Ad_hoc_Trade_Promotion')
        );
        insert promotion;

        ASI_HK_CRM_Promotion_Detail__c promotionDetail = new ASI_HK_CRM_Promotion_Detail__c(
            ASI_HK_CRM_Promotion__c = promotion.Id,
            RecordTypeId = Global_RecordTypeCache.getRtId('ASI_HK_CRM_Promotion_Detail__cASI_CRM_SG_Customer')
        );
        insert promotionDetail;

        ApexPages.currentPage().getParameters().put('id', promotion.Id);
        ApexPages.currentPage().getParameters().put('customerName', 'Customer1');
        Set<Id> skuIds = new Map<Id, ASI_MFM_SKU_Code__c>([SELECT Id FROM ASI_MFM_SKU_Code__c]).keySet();
        ApexPages.currentPage().getParameters().put('skuIds', JSON.serialize(skuIds));
        Set<Id> subBrandIds = new Map<Id, ASI_MFM_Sub_brand__c>([SELECT Id FROM ASI_MFM_Sub_brand__c]).keySet();
        ApexPages.currentPage().getParameters().put('subBrandIds', JSON.serialize(subBrandIds));
        ApexPages.currentPage().getParameters().put('upsertPromotionDetailListJson', JSON.serialize(new List<ASI_HK_CRM_Promotion_Detail__c>{promotionDetail}));


        ApexPages.StandardController sc = new ApexPages.StandardController(promotion);
        ASI_CRM_SG_EnrollPromotionPlanCtrl controller = new ASI_CRM_SG_EnrollPromotionPlanCtrl(sc);

        controller.getAllRelatedOfftakes();
        controller.getAllRelatedSalesOrderHistories();
        controller.savePromotionDetail();
    }
}