objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM TW FOC Request, ASI CRM TW POSM Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Free Goods Request &amp; POSM</relationshipLabel>
        <relationshipName>Free_Goods_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected by Logistic</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved by Logistic</fullName>
                </value>
                <value>
                    <fullName>Rejected by Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TW_FOC_Request</fullName>
        <active>true</active>
        <label>ASI CRM TW FOC Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_FOC_Request_Item__c.object
<CustomObject>
    <description>used for PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>Request Items</relationshipLabel>
        <relationshipName>Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_TW_Amount__c</fullName>
        <formula>ASI_FOC_Request_Quantity_Bottle__c * ASI_FOC_Unit_Cost_PC_BT__c</formula>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Cancel_Qty__c</fullName>
        <label>Cancel Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Reason__c</fullName>
        <label>Reason</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Request_Order__c</fullName>
        <label>Request Order</label>
        <referenceTo>ASI_FOC_Free_Goods_Request__c</referenceTo>
        <relationshipLabel>Request Order Details</relationshipLabel>
        <relationshipName>ASI_FOC_Request_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_FOC_Request_Quantity_Bottle__c</fullName>
        <label>Request Quantity (Bottle)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Request Item</label>
    <nameField>
        <displayFormat>LN-{000000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Plan_Amount__c</fullName>
        <label>Plan Amount</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Total_Cost__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Balance__c</fullName>
        <formula>IF (CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_GF&quot;), ASI_MFM_Plan_Amount__c - ASI_MFM_GF_Total_PO_Amount_PR_Gulf__c, 
IF(CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_TW&quot;), ASI_MFM_Plan_Amount__c - ASI_MFM_Total_PO_Amount__c + ASI_MFM_Total_Draft_PO_Amount__c - ASI_MFM_Total_without_PO_Actual_Amount__c, 
IF(CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_KR&quot;), ASI_MFM_Plan_Amount__c - ASI_MFM_Total_Actual_Spending_Amount__c - ASI_MFM_KR_AnP_RollupAmount__c, 
IF (CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_CAP_Plan&quot;), ASI_MFM_Plan_Amount__c - ASI_MFM_Total_PO_Amount__c, 
IF(CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_MY_Plan&quot;),ASI_MFM_Plan_Amount__c - ASI_MFM_Total_PO_Amount__c-ASI_MFM_Total_FI_Amount__c,
IF(CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_SC_Plan&quot;),ASI_MFM_Plan_Amount__c * ASI_MFM_Exchange_Rate__c  - ASI_MFM_Total_PO_Amount__c ,ASI_MFM_Plan_Amount__c - ASI_MFM_Total_PO_Amount__c) 
)
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prefix</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Prefix__c.ASI_MFM_Module__c</field>
                <operation>equals</operation>
                <value>Plan</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_TnE_Non_A_D_Amount__c</fullName>
        <label>T&amp;E Amount (A&amp;P)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Total_without_PO_Actual_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>FOR TW MFM</description>
        <label>Total without PO Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Plan Line Item</label>
    <nameField>
        <displayFormat>PLI{000000}</displayFormat>
        <label>Plan Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Plan_Balance__c</fullName>
        <formula>ASI_MFM_Plan__r.ASI_MFM_Plan_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>3 OR (1 AND 2) OR (4 AND 5) OR (6 AND 7)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP PO, PH DP PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP Plan, PH DP Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>PH DF PO, PH DF PO Read-Only, PH DP PO, PH DP PO Read-Only, KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF PO, PH DF PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF Plan, PH DF Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prefix</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Prefix__c.ASI_MFM_Module__c</field>
                <operation>equals</operation>
                <value>PO, Direct PO, Dummy PO</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Prefix__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Over_Spending_Checking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over Spending Checking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Tolerance__c</fullName>
        <label>Tolerance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>ASI MFM Prefix</label>
    <nameField>
        <label>Prefix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI MFM Prefixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_FOC_TW_SubmitFOCController.cls
/*Filename:       ASI_FOC_TW_SubmitFOCController.cls
* Author:         Elufa
* Purpose:        Submit for approval - TW FOC
* Created Date:   2016-12-12
* Testing Record: https://pernod-ricard--asisb6conf--c.cs8.visual.force.com/apex/ASI_FOC_TW_SubmitFOCPage?scontrolCaching=1&id=a87L00000004Ei0
				  One FOC will have one Plan
* -----------------------------------------------------------------------------
*/

public class ASI_FOC_TW_SubmitFOCController {
    public ASI_FOC_Free_Goods_Request__c foc = new ASI_FOC_Free_Goods_Request__c();
    public String Msg {set;get;} {Msg='';}
    public Boolean IsProcess {set;get;} {IsProcess=true;}
    
    
    public ASI_FOC_TW_SubmitFOCController(apexpages.standardController sc) 
    {
        foc = (ASI_FOC_Free_Goods_Request__c)sc.getRecord();
        foc=[select Id,Name,recordTypeId,RecordType.DeveloperName,ASI_CRM_Plan__r.Name,ASI_CRM_Plan__r.ASI_MFM_Plan_Amount__c,ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Over_Spending_Checking__c,ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Tolerance__c,ASI_CRM_Plan__c,ASI_CRM_Plan__r.ASI_MFM_Plan_Balance__c,ASI_CRM_Plan__r.ASI_MFM_TnE_Non_A_D_Amount__c ,ASI_CRM_Plan__r.ASI_MFM_Total_without_PO_Actual_Amount__c from ASI_FOC_Free_Goods_Request__c where id = :sc.getId()];
    }
    
    public pageReference submitRequest2() {
        if(foc.RecordType.DeveloperName.contains('ASI_CRM_TW_FOC_Request')) {
            IsProcess=true;
            //SQL
            List<ASI_FOC_Request_Item__c> FOCLines = [select Id, Name,ASI_FOC_Cancel_Qty__c,ASI_FOC_Reason__c,ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__r.name,ASI_FOC_Request_Order__c,
                                                      ASI_FOC_Request_Quantity_Bottle__c,ASI_CRM_Plan_Line_Item__r.ASI_MFM_Unit_Cost__c,ASI_CRM_TW_Amount__c,ASI_FOC_Request_Order__r.ASI_FOC_Request_Status__c,
                                                      ASI_CRM_Plan_Line_Item__r.ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c,ASI_CRM_Plan_Line_Item__r.ASI_MFM_A_C_Code__c,
                                                      ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__c,ASI_CRM_Plan_Line_Item__c,ASI_CRM_Plan_Line_Item__r.ASI_MFM_Total_Cost__c 
                                                      from ASI_FOC_Request_Item__c where ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__c=:foc.ASI_CRM_Plan__c ];

            IsProcess=ValdationChecking(FOCLines);
            if(IsProcess){
                // Running Update Plan FOC Amount  *** Added by 2018-07-06 Linus@introv
                if(!Test.isRunningTest())
                    update FOCLines;
                submitforapproval();
                return new pageReference('/' + foc.Id);
            }else{
                Msg='☹ We cannot submit for approval.<br/>'+Msg;
                return null;
            }
        }else{
            submitforapproval();
            return new pageReference('/' + foc.Id);
        }
        
    }
    
    
    public Boolean ValdationChecking(List<ASI_FOC_Request_Item__c> FOCLines){
        Boolean isProcess = true;
        
        Decimal FOCAmount=0; //  (w/o A&D) 
        Decimal TotalAPFOCAmt=0;
        Decimal TotalAPPlanAmount=0;
        Decimal TotalAPPOAmount=0; //  (Approved/Completed)  
        Decimal TotalwoPOActual=foc.ASI_CRM_Plan__r.ASI_MFM_Total_without_PO_Actual_Amount__c ;  // Amount used and synced from JDE   *** Added by 2018-07-05 Linus@introv
        
        
        set<Id> PlanIdSet = new set<Id>();
        Boolean HasLines= false; //for current FOC
        Map<String,ASI_MFM_Plan_Line_Item__c> PlanLineMap = new Map<String,ASI_MFM_Plan_Line_Item__c>();
        Map<String,ASI_MFM_PO_Line_Item__c> POLineMap = new Map<String,ASI_MFM_PO_Line_Item__c>();
        
        Map<String,ASI_FOC_Request_Item__c> CurrentLineMap = new Map<String,ASI_FOC_Request_Item__c>();
        
        for(ASI_FOC_Request_Item__c focl:FOCLines){
            //Checking 1: check FOC Amount 
            if(focl.ASI_CRM_TW_Amount__c ==null && focl.ASI_FOC_Request_Order__c == foc.id){
                Msg+='Free Goods Request Line (<a href="/'+focl.Id+'">'+focl.Name+ '</a>) Error:  Amount in FOC Line is Blank. <br/>';
                IsProcess=false;
            }
            
            //Checking 2: check Plan Number
            if(focl.ASI_CRM_Plan_Line_Item__c !=null){
                PlanIdSet.add(focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__c);
            }else if(focl.ASI_FOC_Request_Order__c == foc.id && focl.ASI_CRM_Plan_Line_Item__c ==null){
                Msg+='Free Goods Request Line (<a href="/'+focl.Id+'">'+focl.Name+ '</a>) Error:  Please input Plan line number. <br/>';
                IsProcess=false;
            }
            
            
            
            
            //checking 3: check if there have  foc line 
            if(focl.ASI_FOC_Request_Order__c == foc.id){
                HasLines=true;
            }
            
            //Start calculation    
          
            if(IsProcess && focl.ASI_FOC_Request_Order__c == foc.id && focl.ASI_CRM_TW_Amount__c!=null){
                FOCAmount+=focl.ASI_CRM_TW_Amount__c;
            }
            
            if(IsProcess && focl.ASI_CRM_TW_Amount__c!=NULL && ((focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c =='TOTAL A&P'))){ // &&  (focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__r.Name.substring(0,1)=='F' || focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__r.name.substring(0,1)=='M'))){
                if((focl.ASI_FOC_Request_Order__r.ASI_FOC_Request_Status__c!='Draft' && focl.ASI_FOC_Request_Order__c != foc.id ) ||focl.ASI_FOC_Request_Order__c == foc.id   ){ 
                     TotalAPFOCAmt+=focl.ASI_CRM_TW_Amount__c;
                     string mapkey=string.valueOf(focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_Plan__c)+focl.ASI_CRM_Plan_Line_Item__r.ASI_MFM_A_C_Code__c;
                     if(!CurrentLineMap.containsKey(mapkey)){
                         focl.ASI_FOC_Cancel_Qty__c=focl.ASI_CRM_TW_Amount__c;
                         focl.ASI_FOC_Reason__c='The related FOC Line is : <a href="/'+focl.Id+'">'+focl.Name+ '</a>';
                         CurrentLineMap.put(mapkey,focl);
                     }else{
                         ASI_FOC_Request_Item__c FOCline= new ASI_FOC_Request_Item__c();FOCline=focl.clone(false, true);FOCline.ASI_FOC_Cancel_Qty__c=CurrentLineMap.get(mapkey).ASI_FOC_Cancel_Qty__c+focl.ASI_CRM_TW_Amount__c;FOCline.ASI_FOC_Reason__c=focl.ASI_FOC_Reason__c+';<a href="/'+focl.Id+'">'+focl.Name+ '</a>';CurrentLineMap.remove(mapkey);CurrentLineMap.put(mapkey,FOCline);
                     }// AC Code level Map
                        
                }
                
                
            }
            
        }//end of FOC Line for loop
        
        //Get Plan line
        List<ASI_MFM_Plan_Line_Item__c> PlanLines= [select id, Name,ASI_MFM_A_C_Code__c,ASI_MFM_Plan__c,ASI_MFM_Total_Cost__c,ASI_MFM_A_C_Code__r.ASI_MFM_A_C_Code__c,ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c   from ASI_MFM_Plan_Line_Item__c 
                                                        where ASI_MFM_Plan__c =: foc.ASI_CRM_Plan__c and ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c ='TOTAL A&P' ];
                                                        
        
          for(ASI_MFM_Plan_Line_Item__c pl:PlanLines){
              if(pl.ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c=='TOTAL A&P'){
                  TotalAPPlanAmount+=pl.ASI_MFM_Total_Cost__c;
              }
              
                string mapkey=string.valueOf(pl.ASI_MFM_Plan__c)+pl.ASI_MFM_A_C_Code__c;
                if(!PlanLineMap.containsKey(mapkey)){
                    PlanLineMap.put(mapkey, pl);
                }else{// Contain in Map
                    ASI_MFM_Plan_Line_Item__c planline= new ASI_MFM_Plan_Line_Item__c();
                    planline=pl.clone(false, true);
                    
                    if(pl.ASI_MFM_Total_Cost__c!=null){
                        planline.ASI_MFM_Total_Cost__c=PlanLineMap.get(mapkey).ASI_MFM_Total_Cost__c+pl.ASI_MFM_Total_Cost__c;
                    }
                    PlanLineMap.remove(mapkey);
                    PlanLineMap.put(mapkey,planline);
                    
                }
            }// end of for loop Plan line 
            
            
            //Get PO line 
            List<ASI_MFM_PO_Line_Item__c> poList = [select id ,name,ASI_MFM_PO__c,ASI_MFM_PO__r.ASI_MFM_Plan__c, ASI_MFM_Amount__c,ASI_MFM_Base_Currency_Amount__c,
                                                    ASI_MFM_A_C_Code__c,ASI_MFM_A_C_Code__r.Name,ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c
                                                    from ASI_MFM_PO_Line_Item__c  
                                                    where ASI_MFM_PO__r.ASI_MFM_Plan__c in : PlanIdSet  and ASI_MFM_PO__r.ASI_MFM_Status__c !='Draft' and ASI_MFM_Base_Currency_Amount__c !=null and
                                                    ASI_MFM_PO__r.ASI_MFM_Accrual_PO__c = false ]; /* Added by 2018-05-02 Linus@introv*/
            //and ASI_MFM_PO__r.ASI_MFM_Status__c !='Submitted'
            for(ASI_MFM_PO_Line_Item__c pol : poList){
                
                if(pol.ASI_MFM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c=='TOTAL A&P'){
                    TotalAPPOAmount+=pol.ASI_MFM_Base_Currency_Amount__c;
                }
                string mapkey=string.valueOf(pol.ASI_MFM_PO__r.ASI_MFM_Plan__c)+pol.ASI_MFM_A_C_Code__c;
                //POLineMap
                if(!POLineMap.containsKey(mapkey)){
                    POLineMap.put(mapkey, pol);
                }else{// Contain in Map
                    ASI_MFM_PO_Line_Item__c POline= new ASI_MFM_PO_Line_Item__c();
                    POline=pol.clone(false, true);
                    if(pol.ASI_MFM_Amount__c!=null){
                        POline.ASI_MFM_Amount__c=POLineMap.get(mapkey).ASI_MFM_Amount__c+pol.ASI_MFM_Base_Currency_Amount__c;
                    }
                    POLineMap.remove(mapkey);
                    POLineMap.put(mapkey,POline);
                }
                
            }// end of for loop PO line
            
        	/* check A&P instead of checking each A/C Code           *******Hided by 2018-07-06 Linus@introv 
            integer num=1;
            //AC Code level checking 
            for (string k : CurrentLineMap.keySet()){
                if(PlanLineMap.containsKey(k)){
                    decimal CostAmount=0;
                    if(POLineMap.containsKey(k)){
                        CostAmount=CurrentLineMap.get(k).ASI_FOC_Cancel_Qty__c+POLineMap.get(k).ASI_MFM_Amount__c;
                    }else{
                        CostAmount=CurrentLineMap.get(k).ASI_FOC_Cancel_Qty__c;
                    }
                    //*(1/100)
                    if(PlanLineMap.get(k).ASI_MFM_Total_Cost__c<CostAmount){
                        IsProcess=false;if(num==1){Msg+='<b>A/C Code level Checking</b>: <br/>';}num++;Msg+=' A/C Code: '+ PlanLineMap.get(k).ASI_MFM_A_C_Code__r.ASI_MFM_A_C_Code__c+': Total spending amount ( $'+CostAmount.intValue().format()+ ') greater than plan amount :( $' +(PlanLineMap.get(k).ASI_MFM_Total_Cost__c).intValue().format()+'). <br/>'+CurrentLineMap.get(k).ASI_FOC_Reason__c+'<br/>';
                    }
                }
                
            }//end of for loop
        	*/
        
        //Total AP Balance checking : Total AP Balance = total A&P Plan Amount - total w/o PO Actual amount - total A&P PO Amount (Approved/Completed/Non-Accural)-Total FOC Amount (w/o A&D) – Total T&E Amount (w/o A&D). 
        system.debug('Plan Amount: ' + TotalAPPlanAmount);
        system.debug('Without PO Actual: ' + TotalwoPOActual);
        system.debug('AP PO Amount: ' + TotalAPPOAmount);
        system.debug('AP FOC Amount: ' + TotalAPFOCAmt);
        decimal TotalAPBalanceChecking= TotalAPPlanAmount-TotalwoPOActual-TotalAPPOAmount-TotalAPFOCAmt;
        Decimal TnENon_AD_Amount=0;
        if(foc.ASI_CRM_Plan__r.ASI_MFM_TnE_Non_A_D_Amount__c!=null){
            TnENon_AD_Amount=foc.ASI_CRM_Plan__r.ASI_MFM_TnE_Non_A_D_Amount__c;
        }
        TotalAPBalanceChecking=TotalAPBalanceChecking-TnENon_AD_Amount; system.debug('AP Balance: ' + TotalAPBalanceChecking);
        if((TotalAPBalanceChecking)<0){  // && (foc.ASI_CRM_Plan__r.Name.substring(0,1)=='F' || foc.ASI_CRM_Plan__r.name.substring(0,1)=='M')){
            IsProcess=false;
            Msg+='<br/> <b>A&P Checking</b>: Total AP Amount Balance('+TotalAPBalanceChecking.format()+')=Total A&P Plan Amount('+TotalAPPlanAmount.format()+')  -Total A&P PO Amount (Non-Accural/Non-Draft)('+TotalAPPOAmount.format()+')  -Total FOC Amount (w/o A&D) ('+TotalAPFOCAmt.format()+') -Total TnE Amount (w/o A&D) ('+TnENon_AD_Amount.format()+')  <0. <br/>';
        }

        
        //Plan Balance level checking 
        Decimal Tolerance = 0;
        if(foc.ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Over_Spending_Checking__c){
            Tolerance = foc.ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Tolerance__c == null ? 0: foc.ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Tolerance__c;
            double balance =(foc.ASI_CRM_Plan__r.ASI_MFM_Plan_Balance__c-FOCAmount)/foc.ASI_CRM_Plan__r.ASI_MFM_Plan_Amount__c;
            if(balance<0 && (math.abs(balance)>(foc.ASI_CRM_Plan__r.ASI_MFM_Prefix__r.ASI_MFM_Tolerance__c/100))){
                IsProcess=false;
                Decimal OverAmount=(foc.ASI_CRM_Plan__r.ASI_MFM_Plan_Balance__c-FOCAmount);
                Msg+='<br/> <b>Plan Balance Checking</b>: Plan Balance('+OverAmount.format()+')<0. <br/>';
            }
        }
        
        
        
        if(!HasLines){
            IsProcess=false;
            Msg+='Please input FOC Line. <br/>';
        }
        return isProcess;
    }//**********************end of checking ***********************************************
        
    public void submitforapproval(){ 
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setObjectId(foc.id);
        if(!Test.isRunningTest()){ Approval.ProcessResult result = Approval.process(req1);}
        
    }
    
    public pageReference goBack() {
        return new pageReference('/' + foc.id);
    }
    
    
}