objects/ASI_eForm_Donation_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_Sys_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sys Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Donation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Sys_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sys Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Donation_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Donation Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Donation Request No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Fix_Approval_Route__c.object
<CustomObject>
    <description>MFM CN Use Only
2nd Table for the fixed approval route of CN MFM approval
Finance, BA, Corporate Approver 1, 2</description>
    <fields>
        <fullName>ASI_MFM_Corporate_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_MFM_Fix_Approval_Routes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_KR_Grand_Category__c</fullName>
        <label>Grand Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Direct Payment</fullName>
                </value>
                <value>
                    <fullName>Normal Payment-Non Service</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Non Service</fullName>
                </value>
                <value>
                    <fullName>Pre-payment Service</fullName>
                </value>
                <value>
                    <fullName>Pre-payment Non Service</fullName>
                </value>
                <value>
                    <fullName>Pre-payment</fullName>
                </value>
                <value>
                    <fullName>Offset Payment</fullName>
                </value>
                <value>
                    <fullName>Corporate Card - New</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
                <value>
                    <fullName>Return Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Prepayment Proposal Change Log</fullName>
                </value>
                <value>
                    <fullName>eForm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NTMK</fullName>
                </value>
                <value>
                    <fullName>MMPJ</fullName>
                </value>
                <value>
                    <fullName>Whiskies</fullName>
                </value>
                <value>
                    <fullName>Wine</fullName>
                </value>
                <value>
                    <fullName>Innovation and White Spirits</fullName>
                </value>
                <value>
                    <fullName>Luxe</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Cognac and White spirits</fullName>
                </value>
                <value>
                    <fullName>Merchandising</fullName>
                </value>
                <value>
                    <fullName>Bar&amp;Restaurant</fullName>
                </value>
                <value>
                    <fullName>KTV</fullName>
                </value>
                <value>
                    <fullName>IHBR</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>North West</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>South West</fullName>
                </value>
                <value>
                    <fullName>Brand Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Trade Marketing</fullName>
                </value>
                <value>
                    <fullName>North Premium</fullName>
                </value>
                <value>
                    <fullName>Central Premium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ASI MFM Fix Approval Route</label>
    <nameField>
        <displayFormat>FAR{000000}</displayFormat>
        <label>ASI_MFM_Fix_Approval_Route Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI MFM Fix Approval Routes</pluralLabel>
    <recordTypes>
        <fullName>ASI_MFM_KR_Fix_Approval_Route</fullName>
        <active>true</active>
        <label>KR Fix Approval Route</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ASI_eForm_KR_Donation_Handler__c</fullName>
        <label>KR Donation Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI MFM Setting</label>
</CustomObject>

objects/ASI_MFM_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Team__c</fullName>
        <label>ASI MFM Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NTMK</fullName>
                </value>
                <value>
                    <fullName>MMPJ</fullName>
                </value>
                <value>
                    <fullName>Whiskies</fullName>
                </value>
                <value>
                    <fullName>Wine</fullName>
                </value>
                <value>
                    <fullName>Innovation and White Spirits</fullName>
                </value>
                <value>
                    <fullName>Luxe</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Cognac and White spirits</fullName>
                </value>
                <value>
                    <fullName>Merchandising</fullName>
                </value>
                <value>
                    <fullName>Bar&amp;Restaurant</fullName>
                </value>
                <value>
                    <fullName>KTV</fullName>
                </value>
                <value>
                    <fullName>IHBR</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>North West</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>South West</fullName>
                </value>
                <value>
                    <fullName>IT-PC</fullName>
                </value>
                <value>
                    <fullName>IT-HQ</fullName>
                </value>
                <value>
                    <fullName>Brand Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Trade Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_eForm_KR_DonationRequestTriggerClass.cls
public class ASI_eForm_KR_DonationRequestTriggerClass {
    public static void routineBeforeUpsert(List<ASI_eForm_Donation_Request__c> triggerNew, Map<Id, ASI_eForm_Donation_Request__c> triggerOldMap) {
        Set<Id> OwnerIdSet = New Set<Id>();
        Map<String,ASI_MFM_Fix_Approval_Route__c>  FixApprovalRouteMap = new Map<String,ASI_MFM_Fix_Approval_Route__c>();  
        Map<Id,User> UserMap = new Map<Id,User>();
        
        for(ASI_eForm_Donation_Request__c obj : triggerNew){
            OwnerIdSet.add(obj.OwnerId);
        }
        if(OwnerIdSet.size()>0 ){
            Set<String> UserSalesTeamSet = new Set<String>();
            List<User> UserList= [select Id,Email,ASI_MFM_Team__c from User where Id in : OwnerIdSet and ASI_MFM_Team__c!=null ];
            for(User u : UserList){
                UserMap.put(u.Id,u);
                UserSalesTeamSet.add(u.ASI_MFM_Team__c); 
            }

            List<ASI_MFM_Fix_Approval_Route__c> FARList = new List<ASI_MFM_Fix_Approval_Route__c>([SELECT Id,ASI_MFM_Team__c, ASI_MFM_Corporate_Approver_1__c
                                                                                                   FROM ASI_MFM_Fix_Approval_Route__c 
                                                                                                   WHERE ASI_MFM_Team__c in :UserSalesTeamSet  and RecordType.DeveloperName LIKE 'ASI_MFM_KR_Fix_Approval_Route' 
                                                                                                   AND ASI_MFM_Module__c LIKE 'eForm' and ASI_MFM_KR_Grand_Category__c ='Donation' AND ASI_MFM_Inactive__c = false ]);
            
            for(ASI_MFM_Fix_Approval_Route__c FixApprovalRoute : FARList){
                FixApprovalRouteMap.put(FixApprovalRoute.ASI_MFM_Team__c,FixApprovalRoute);
            }
        }
        
        String handlerUserName = [select id,ASI_eForm_KR_Donation_Handler__c from  ASI_MFM_Setting__c ][0].ASI_eForm_KR_Donation_Handler__c;
        String delegatorId = [select id, delegatedApproverId from user where username = :handlerUserName limit 1][0].delegatedApproverId;
        
        for(ASI_eForm_Donation_Request__c obj : triggerNew){
            if(FixApprovalRouteMap.containsKey(UserMap.get(obj.OwnerId).ASI_MFM_Team__c) ){
                obj.ASI_eForm_Sys_Approver_1__c = FixApprovalRouteMap.get(UserMap.get(obj.OwnerId).ASI_MFM_Team__c).ASI_MFM_Corporate_Approver_1__c; 
            }
            if(delegatorId != null){
                obj.ASI_eForm_Sys_Approver_2__c = delegatorId;
            }
        }
        
        
    }
}