objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_T_E_Amount__c</fullName>
        <label>T&amp;E Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimDetail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_ClaimHeader__c</fullName>
        <label>Travel &amp; Entertainment Claim</label>
        <referenceTo>ASI_TnE_ClaimHeader__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>ASI_TnE_ClaimDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MFM PO</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5) OR (6 AND 7) OR (1 AND 8)</booleanFilter>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>TH PO, TH PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_T_E__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Complete</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final, Complete, Partial Paid</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HK PO, HK PO Read-Only, TR PO, TR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>SG PO, SG PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>Travel_Entertainment_Claims_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Receipt_Amount__c</fullName>
        <label>Receipt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Travel &amp; Entertainment Claim Detail</label>
    <nameField>
        <displayFormat>TED-{YY}-{00000}</displayFormat>
        <label>Claim Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimHeader__c.object
<CustomObject>
    <label>Travel &amp; Entertainment Claim</label>
    <nameField>
        <displayFormat>TE-{YY}-{00000}</displayFormat>
        <label>Travel &amp; Entertainment Claim Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_TnE_TW_ClaimHeaderTriggerClass.cls
public with sharing class ASI_TnE_TW_ClaimHeaderTriggerClass {


    public static void beforeDeleteMethod(Map<Id, ASI_TnE_ClaimHeader__c> pMapOldClaimHeaders) {
        system.debug('**beforeDeleteMethod**' + pMapOldClaimHeaders);
        //Initiallizing collections
        List<ASI_MFM_PO__c> lstPO_ToUpdate = new List<ASI_MFM_PO__c>();
        Map<Id, Double> mapPOWithAmt = new Map<Id, Double>();
        Map<Id, Double> mapPOWithAmtToReduce = new Map<Id, Double>();
        
        Double amt;
        
        //Iterating to calculate amount to deduct for a PO
        for(ASI_TnE_ClaimDetail__c claimDtl : [SELECT Id, ASI_TnE_Receipt_Amount__c, 
                                                      ASI_TnE_MFM_PO__c,
                                                      ASI_TnE_MFM_PO__r.ASI_MFM_T_E_Amount__c
                                               FROM ASI_TnE_ClaimDetail__c
                                               WHERE ASI_TnE_Receipt_Amount__c != null 
                                               AND ASI_TnE_MFM_PO__c != null 
                                               AND  ASI_TnE_ClaimHeader__c IN : pMapOldClaimHeaders.keySet()]){
            
            amt = mapPOWithAmtToReduce.get(claimDtl.ASI_TnE_MFM_PO__c);
            
            if(amt == null) 
                amt  = 0.0;
               
            amt = amt + claimDtl.ASI_TnE_Receipt_Amount__c;
            
            mapPOWithAmtToReduce.put(claimDtl.ASI_TnE_MFM_PO__c, amt);
            mapPOWithAmt.put(claimDtl.ASI_TnE_MFM_PO__c, claimDtl.ASI_TnE_MFM_PO__r.ASI_MFM_T_E_Amount__c);
        }//End for
        
        system.debug('**mapPOWithAmt**' + mapPOWithAmt); 
        system.debug('**mapPOWithAmtToReduce**' + mapPOWithAmtToReduce);  
                                                  
        //Calculating remaining amount for PO
        for(Id poId : mapPOWithAmtToReduce.keySet()){
            amt = mapPOWithAmt.get(poId ) == null ? 0.0 : mapPOWithAmt.get(poId );
            
            lstPO_ToUpdate.add(new ASI_MFM_PO__c(Id = poId, 
                                                 ASI_MFM_T_E_Amount__c = (amt - mapPOWithAmtToReduce.get(poId))));
        }//End for
        
        system.debug('**lstPO_ToUpdate**' + lstPO_ToUpdate);
               
        if(!lstPO_ToUpdate.isEmpty()) {
            try {
                update lstPO_ToUpdate;
            } catch(DmlException exceptionInstance) {
                System.debug('Error occurred : ' + exceptionInstance.getMessage());
            }//End Catch
        }//End if !lstPosToUpdate.isEmpty()
    }//End beforeDeleteMethod method

}//End ASI_TnE_TW_ClaimHeaderTriggerClass  Class