objects/ASI_DFPM_Project_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Complete_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Complete Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Overdue_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Overdue Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Total_Task__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Task</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_DFPM_Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>ASI_DFPM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Overdue__c</fullName>
        <formula>IF( NOT( ASI_DFPM_Complete__c ) &amp;&amp; ASI_DFPM_End_Date__c - TODAY() &lt; 0, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Overdue?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_DFPM_Project_Milestone__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>ASI_DFPM_Project_Milestone__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ASI_DFPM_Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_DFPM_PromotionalMstStatisticManager.cls
public without sharing class ASI_DFPM_PromotionalMstStatisticManager {
	
	private ASI_DFPM_ChildRecordSummaryHelper summaryHelper;
	
	public ASI_DFPM_PromotionalMstStatisticManager() {
		this.summaryHelper = new ASI_DFPM_ChildRecordSummaryHelper('ASI_DFPM_Project_Milestone__c');
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Task__c', 'ASI_DFPM_Project_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Complete_Task__c', 'ASI_DFPM_Project_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT, null
			, 'ASI_DFPM_Complete__c', true
		));
		this.summaryHelper.addSummarySetting(new ASI_DFPM_ChildRecordSummaryHelper.ChildRecordSummarySetting(
			'ASI_DFPM_Total_Overdue_Task__c', 'ASI_DFPM_Project_Tasks__r'
			, ASI_DFPM_ChildRecordSummaryHelper.SummaryType.COUNT, null
			, 'ASI_DFPM_Overdue__c', 'Yes'
		));
	}
	
	public List<ASI_DFPM_Project_Milestone__c> getRefreshedMilestones(Set<ID> mstIdSet) {
		Map<ID, ASI_DFPM_Project_Milestone__c> mstMap = new Map<ID, ASI_DFPM_Project_Milestone__c>([SELECT Id
			, ASI_DFPM_Total_Task__c
			, ASI_DFPM_Total_Complete_Task__c
			, ASI_DFPM_Total_Overdue_Task__c
			FROM ASI_DFPM_Project_Milestone__c WHERE Id IN :mstIdSet
		]);
		List<ASI_DFPM_Project_Milestone__c> mstList = mstMap.values();
		Set<ID> updatedIdSet = this.summaryHelper.refreshSummaryValues(mstList);
		List<ASI_DFPM_Project_Milestone__c> updatedMstList = new List<ASI_DFPM_Project_Milestone__c>();
		for (ID updatedId : updatedIdSet) {
			ASI_DFPM_Project_Milestone__c tempMst = mstMap.get(updatedId);
			if (tempMst != null)
				updatedMstList.add(tempMst);
		}
		return updatedMstList;
	}
}