objects/ASI_CRM_Item_Group_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Item Group Allocations</relationshipLabel>
        <relationshipName>Item_Group_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>ASI_CRM_Region__c</referenceTo>
        <relationshipLabel>Item Group Allocations</relationshipLabel>
        <relationshipName>Item_Group_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Group Allocation</label>
    <nameField>
        <displayFormat>IGA-{MM}{YY}{0000}</displayFormat>
        <label>Item Group Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Group Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Item_Group_Customer_Price__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Item Group Customer Prices</relationshipLabel>
        <relationshipName>Item_Group_Customer_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Effective_Date_To__c</fullName>
        <label>Effective Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Item Group Customer Prices</relationshipLabel>
        <relationshipName>Item_Group_Customer_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Price_Type__c</fullName>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>T1</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Customer Group Code</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotion_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Code</label>
        <referenceTo>ASI_CRM_Promotion_Master__c</referenceTo>
        <relationshipLabel>Item Group Customer Prices</relationshipLabel>
        <relationshipName>Item_Group_Customer_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotion_Expiration_Date__c</fullName>
        <label>Promotion Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Unit_Price_BT__c</fullName>
        <label>Unit Price (BT)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Item Group Customer Price</label>
    <nameField>
        <displayFormat>ICP-{000000}</displayFormat>
        <label>Item Group Customer Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Group Customer Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Order_Form__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Order_Form_Type__c</fullName>
        <label>Order Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal Item</fullName>
                </value>
                <value>
                    <fullName>RTD</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Form</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Order Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Order_Form_Customer_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Order_From_Customer_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Order_Form_Type__c</fullName>
        <formula>IF(ISPICKVAL(ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c, &quot;Normal Item&quot;), &quot;Normal Item&quot;, IF(ISPICKVAL(ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c, &quot;RTD&quot;), &quot;RTD&quot;, &quot;Premium&quot;))</formula>
        <label>Order Form Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Order_Form__c</fullName>
        <label>Order Form</label>
        <referenceTo>ASI_CRM_Order_Form__c</referenceTo>
        <relationshipLabel>Order Form Customer Relationships</relationshipLabel>
        <relationshipName>Order_From_Customer_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Form Customer Relationship</label>
    <nameField>
        <displayFormat>OFCR-{0000000}</displayFormat>
        <label>Order From Customer Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Form Customer Relationships</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Order_Form_Customer_Relationship</fullName>
        <active>true</active>
        <label>CN Order Form Customer Relationship</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Order_Form_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Order_Form__c</fullName>
        <label>Order Form</label>
        <referenceTo>ASI_CRM_Order_Form__c</referenceTo>
        <relationshipLabel>Order Form Details</relationshipLabel>
        <relationshipName>Order_Form_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Order Form Details</relationshipLabel>
        <relationshipName>Order_Form_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Remark__c</fullName>
        <label>Remark</label>
        <type>TextArea</type>
    </fields>
    <label>Order Form Detail</label>
    <nameField>
        <displayFormat>OFD-{0000000}</displayFormat>
        <label>Order Form Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Form Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Promotion_Master__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Buy_X__c</fullName>
        <label>Buy X</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Get_Y__c</fullName>
        <label>Get Y</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Sales Order Requests (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Premium__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Premium</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_RTD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR-{00000000}</displayFormat>
        <label>Sales Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Allocation_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allocation Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Sales Order Request Items</relationshipLabel>
        <relationshipName>Sales_Order_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Promotion_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Code</label>
        <referenceTo>ASI_CRM_Promotion_Master__c</referenceTo>
        <relationshipLabel>Sales Order Request Items</relationshipLabel>
        <relationshipName>Sales_Order_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Promotion_Expiration_Date__c</fullName>
        <label>Promotion Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Remark__c</fullName>
        <label>Remark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Unit_Price_BT_with_VAT__c</fullName>
        <label>Unit Price - BT(with-VAT)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Unit_Price_Source__c</fullName>
        <label>Unit Price Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Effective_Date_To__c</fullName>
        <label>Effective Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Sales_Order_Request__c</fullName>
        <label>Sales Order Request</label>
        <referenceTo>ASI_KOR_Sales_Order_Request__c</referenceTo>
        <relationshipName>ASI_KOR_Sales_Order_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Request Item</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Sales Order Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Allocation_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allocation Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Remark__c</fullName>
        <label>Remark</label>
        <type>TextArea</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_SalesOrderItem_TriggerClass.cls
public without sharing class ASI_CRM_CN_SalesOrderItem_TriggerClass {
    
    Public Static Void beforeUpsertMethod(List<ASI_KOR_Sales_Order_Transaction__c> triggerNew){
        
        Set<ID> headerId = new Set<ID>();
        Set<ID> customerId = new Set<ID>();
        Set<ID> IHBRCusomterID = new Set<ID>();
        Set<ID> orderFormId = new Set<ID>();
        List<ASI_KOR_Sales_Order_Request__c> headerList = new List<ASI_KOR_Sales_Order_Request__c>();
        List<ASI_CRM_Order_Form_Customer_Relationship__c> ofcrList = new List<ASI_CRM_Order_Form_Customer_Relationship__c>();
        List<ASI_CRM_Order_Form_Detail__c> orderFormItem = new List<ASI_CRM_Order_Form_Detail__c>();
        Map<Id, Id> mapOrderForm = new Map<Id, Id>();
        Map<Id, Id> mapRTDOrderForm = new Map<Id, Id>();
        Map<Id, Id> mapPremiumOrderForm = new Map<Id, Id>();//20161019 Ben @ ELufa
        Map<Id, Id> mapCustomer = new Map<Id, Id>();
        Map<Id, Id> mapIHBRCustomer = new Map<Id, Id>();
        Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>> RTDItem = new Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>>();
        Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>> NormalItem = new Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>>();
        Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>> PremiumItem = new Map<Id, Map<id, ASI_CRM_Order_Form_Detail__c>>();//20161019 Ben @ Elufa
        Map<Id, Map<Id, ASI_CRM_Order_Form_Detail__c>> mapOrderFormItem = new Map<Id, Map<Id, ASI_CRM_Order_Form_Detail__c>>();
        List<ASI_CRM_Item_Group_Customer_Price__c> itemGroupCustomerPrice = new List<ASI_CRM_Item_Group_Customer_Price__c>();
        Map<Id, Map<Id, ASI_CRM_Item_Group_Customer_Price__c>> mapCustomerPrice = new Map<Id, Map<Id, ASI_CRM_Item_Group_Customer_Price__c>>();
        Map<Id, Map<Id, ASI_CRM_Item_Group_Customer_Price__c>> mapIHBRCustomerPrice = new Map<Id, Map<Id, ASI_CRM_Item_Group_Customer_Price__c>>();
        Date todayDate = Date.today();
        
        for(ASI_KOR_Sales_Order_Transaction__c obj : triggerNew){
            headerId.add(obj.ASI_KOR_Sales_Order_Request__c);
        }
        headerList = [SELECT id
                      , ASI_CRM_CN_RTD__c
                      , ASI_CRM_CN_Premium__c
                      , ASI_CRM_CN_Customer__c
                      , ASI_CRM_CN_Customer__r.ASI_CRM_CN_Is_IHBR_Outlet__c
                      , ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c
                      , ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c
                      , ASI_CRM_SG_Order_Date__c
                      FROM ASI_KOR_Sales_Order_Request__c
                      WHERE ID IN : headerId
                      AND ASI_KOR_Order_Status__c LIKE 'Open'
                     ];
        
        if(headerList.size() > 0){
            
            for(ASI_KOR_Sales_Order_Request__c obj : headerList){
                
                if(!obj.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Is_IHBR_Outlet__c){
                    mapCustomer.put(obj.id, obj.ASI_CRM_CN_Customer__c);
                    customerId.add(obj.ASI_CRM_CN_Customer__c);
                }else{
                    mapIHBRCustomer.put(obj.id, obj.ASI_CRM_CN_Customer__c);
                    IHBRCusomterID.add(obj.ASI_CRM_CN_Customer__c);
                }
            }
            
            itemGroupCustomerPrice = [SELECT ASI_CRM_Customer__c
                                      , ASI_CRM_Item_Group__c
                                      , ASI_CRM_Price_Type__c
                                      , ASI_CRM_Promotion_Code__c
                                      , ASI_CRM_Promotion_Expiration_Date__c
                                      , ASI_CRM_Unit_Price_BT__c
                                      , ASI_CRM_Promotion_Code__r.Name
                                      , ASI_CRM_Promotion_Code__r.ASI_CRM_Get_Y__c
                                      , ASI_CRM_Promotion_Code__r.ASI_CRM_Buy_X__c
                                      , ASI_CRM_Effective_Date_To__c //20161124 Elufa
                                      , ASI_CRM_Item_Group__r.ASI_CRM_Allocation_Information__c //20170206 Elufa
                                      FROM ASI_CRM_Item_Group_Customer_Price__c 
                                      WHERE (ASI_CRM_Customer__c IN : mapCustomer.values()
                                             OR ASI_CRM_Customer__c IN : mapIHBRCustomer.values()
                                            )
                                     ];
            
            if(itemGroupCustomerPrice.size() > 0){
                
                for(ASI_CRM_Item_Group_Customer_Price__c obj : itemGroupCustomerPrice){
                    
                    Map<Id, ASI_CRM_Item_Group_Customer_Price__c> tmpMap = new Map<Id, ASI_CRM_Item_Group_Customer_Price__c>();
                    
                    if(obj.ASI_CRM_Promotion_Expiration_Date__c < todayDate){
                        obj.ASI_CRM_Promotion_Code__c = NULL;
                    }
                    if(customerId.contains(obj.ASI_CRM_Customer__c)){
                        if(mapCustomerPrice.containsKey(obj.ASI_CRM_Customer__c))
                            tmpMap = mapCustomerPrice.get(obj.ASI_CRM_Customer__c);
                        
                        tmpMap.put(obj.ASI_CRM_Item_Group__c, obj);
                        
                        mapCustomerPrice.put(obj.ASI_CRM_Customer__c, tmpMap);
                    }else if(IHBRCusomterID.contains(obj.ASI_CRM_Customer__c)){
                        
                        if(mapIHBRCustomerPrice.containsKey(obj.ASI_CRM_Customer__c))
                            tmpMap = mapIHBRCustomerPrice.get(obj.ASI_CRM_Customer__c);
                        
                        tmpMap.put(obj.ASI_CRM_Item_Group__c, obj);
                        
                        mapIHBRCustomerPrice.put(obj.ASI_CRM_Customer__c, tmpMap);
                    }
                }
            }
            
            ofcrList = [SELECT id
                        , ASI_CRM_Customer__c
                        , ASI_CRM_Order_Form__c
                        , ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c
                        FROM ASI_CRM_Order_Form_Customer_Relationship__c
                        WHERE ( ASI_CRM_Customer__c IN : mapCustomer.values()
                               //OR ASI_CRM_Customer__c IN : mapIHBRCustomer.values()
                              )
                        AND RecordType.DeveloperName = 'ASI_CRM_CN_Order_Form_Customer_Relationship'
                       ];
            
            if(ofcrList.size() > 0){
                
                for(ASI_CRM_Order_Form_Customer_Relationship__c obj : ofcrList){
                    
                    if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'Normal Item'){
                        
                        mapOrderForm.put(obj.ASI_CRM_Customer__c, obj.ASI_CRM_Order_Form__c);
                    }else if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'RTD'){
                        
                        mapRTDOrderForm.put(obj.ASI_CRM_Customer__c, obj.ASI_CRM_Order_Form__c);
                    }else if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'Premium'){//20161019 Ben @ Elufa
                        
                        mapPremiumOrderForm.put(obj.ASI_CRM_Customer__c, obj.ASI_CRM_Order_Form__c);
                    }//20161019 End
                    orderFormId.add(obj.ASI_CRM_Order_Form__c);
                }
                
                orderFormItem = [SELECT id
                                 , ASI_CRM_Order_Form__c
                                 , ASI_CRM_Product_Name__c
                                 , ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c
                                 , ASI_CRM_Remark__c
                                 , ASI_CRM_Product_Name__r.ASI_CRM_Allocation_Information__c //20170206 Elufa
                                 FROM ASI_CRM_Order_Form_Detail__c
                                 WHERE ASI_CRM_Order_Form__c IN : orderFormId
                                ];
                
                if(orderFormItem.size() > 0){
                    for(ASI_CRM_Order_Form_Detail__c obj : orderFormItem){
                        if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'RTD'){
                            
                            Map<Id, ASI_CRM_Order_Form_Detail__c> itemGroupId = new Map<Id, ASI_CRM_Order_Form_Detail__c>();
                            
                            if(RTDItem.containsKey(obj.ASI_CRM_Order_Form__c))
                                itemGroupId = RTDItem.get(obj.ASI_CRM_Order_Form__c);
                            
                            itemGroupId.put(obj.ASI_CRM_Product_Name__c, obj);
                            
                            RTDItem.put(obj.ASI_CRM_Order_Form__c, itemGroupId);
                        }else if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'Normal Item'){
                            
                            Map<Id, ASI_CRM_Order_Form_Detail__c> itemGroupId = new Map<Id, ASI_CRM_Order_Form_Detail__c>();
                            
                            if(NormalItem.containsKey(obj.ASI_CRM_Order_Form__c))
                                itemGroupId = NormalItem.get(obj.ASI_CRM_Order_Form__c);
                            
                            itemGroupId.put(obj.ASI_CRM_Product_Name__c, obj);
                            
                            NormalItem.put(obj.ASI_CRM_Order_Form__c, itemGroupId);
                        }else if(obj.ASI_CRM_Order_Form__r.ASI_CRM_Order_Form_Type__c == 'Premium'){//20161019 Ben @ Elufa
                            
                            Map<Id, ASI_CRM_Order_Form_Detail__c> itemGroupId = new Map<Id, ASI_CRM_Order_Form_Detail__c>();
                            
                            if(PremiumItem.containsKey(obj.ASI_CRM_Order_Form__c))
                                itemGroupId = PremiumItem.get(obj.ASI_CRM_Order_Form__c);
                            
                            itemGroupId.put(obj.ASI_CRM_Product_Name__c, obj);
                            
                            PremiumItem.put(obj.ASI_CRM_Order_Form__c, itemGroupId);
                        }
                    }
                }
            }
            for(ASI_KOR_Sales_Order_Request__c obj : headerList){
                if(mapRTDOrderForm.containsKey(obj.ASI_CRM_CN_Customer__c) && RTDItem.containsKey(mapRTDOrderForm.get(obj.ASI_CRM_CN_Customer__c)) && obj.ASI_CRM_CN_RTD__c){
                    mapOrderFormItem.put(obj.id, RTDItem.get(mapRTDOrderForm.get(obj.ASI_CRM_CN_Customer__c)));
                }else if(mapPremiumOrderForm.containsKey(obj.ASI_CRM_CN_Customer__c) && PremiumItem.containsKey(mapPremiumOrderForm.get(obj.ASI_CRM_CN_Customer__c)) && obj.ASI_CRM_CN_Premium__c){//20161019 Ben @ Elufa
                    mapOrderFormItem.put(obj.id, PremiumItem.get(mapPremiumOrderForm.get(obj.ASI_CRM_CN_Customer__c)));
                }else if(mapOrderForm.containsKey(obj.ASI_CRM_CN_Customer__c) && NormalItem.containsKey(mapOrderForm.get(obj.ASI_CRM_CN_Customer__c)) && !obj.ASI_CRM_CN_RTD__c && !obj.ASI_CRM_CN_Premium__c){
                    mapOrderFormItem.put(obj.id, NormalItem.get(mapOrderForm.get(obj.ASI_CRM_CN_Customer__c)));
                }
            }
        }
        
        for(ASI_KOR_Sales_Order_Transaction__c obj : triggerNew){
            
            if(mapCustomer.containsKey(obj.ASI_KOR_Sales_Order_Request__c)){
                if(mapOrderFormItem.containsKey(obj.ASI_KOR_Sales_Order_Request__c) && !mapOrderFormItem.get(obj.ASI_KOR_Sales_Order_Request__c).containsKey(obj.ASI_CRM_CN_Product_Name__c)){
                    obj.addError('Invalid Item Group');
                    break;
                }else if(mapOrderFormItem.containsKey(obj.ASI_KOR_Sales_Order_Request__c) && mapOrderFormItem.get(obj.ASI_KOR_Sales_Order_Request__c).containsKey(obj.ASI_CRM_CN_Product_Name__c)){
                    
                    if(trigger.isInsert)//20170206 Elufa
                        obj.ASI_CRM_Allocation_Information__c = mapOrderFormItem.get(obj.ASI_KOR_Sales_Order_Request__c).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Product_Name__r.ASI_CRM_Allocation_Information__c;
                    
                    obj.ASI_CRM_CN_Remark__c = mapOrderFormItem.get(obj.ASI_KOR_Sales_Order_Request__c).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Remark__c;
                    if(mapCustomerPrice.containsKey(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c))){
                        obj.ASI_CRM_CN_Unit_Price_BT_with_VAT__c = mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Unit_Price_BT__c * 1.16 : NULL; //20180426 Introv Changed tax rate from 17% to 16%
                        obj.ASI_CRM_CN_Promotion_Code__c = mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Promotion_Code__c : NULL;
                        obj.ASI_CRM_CN_Unit_Price_Source__c = mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Price_Type__c : NULL;
                        obj.ASI_CRM_CN_Promotion_Expiration_Date__c = mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapCustomerPrice.get(mapCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Promotion_Expiration_Date__c : NULL;
                    }
                }
            }else if(mapIHBRCustomer.containsKey(obj.ASI_KOR_Sales_Order_Request__c) && mapIHBRCustomerPrice.containsKey(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c))){
                
                if(trigger.isInsert)//20170206 Elufa
                    obj.ASI_CRM_Allocation_Information__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Item_Group__r.ASI_CRM_Allocation_Information__c : False;
                
                obj.ASI_CRM_CN_Unit_Price_BT_with_VAT__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Unit_Price_BT__c * 1.16 : NULL; //20180426 Introv Changed tax rate from 17% to 16%
                obj.ASI_CRM_CN_Promotion_Code__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Promotion_Code__c : NULL;
                obj.ASI_CRM_CN_Unit_Price_Source__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Price_Type__c : NULL;
                obj.ASI_CRM_CN_Promotion_Expiration_Date__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Promotion_Expiration_Date__c : NULL;
                //20161124 Elufa
                obj.ASI_CRM_Effective_Date_To__c = mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).containsKey(obj.ASI_CRM_CN_Product_Name__c) ? mapIHBRCustomerPrice.get(mapIHBRCustomer.get(obj.ASI_KOR_Sales_Order_Request__c)).get(obj.ASI_CRM_CN_Product_Name__c).ASI_CRM_Effective_Date_To__c : NULL;
            }
        }
    }
    
    /*Public Static Map<String, ASI_CRM_Item_Group_Allocation__c> calculateRemainingQty(List<ASI_KOR_Sales_Order_Transaction__c> triggerNew, Set<id> regionSet, Set<Id> itemGroupSet, Set<String> commercialTeamSet, Date Startdate, Date endDate){
        
        Startdate = date.newInstance(Startdate.year(), Startdate.month(), 1);
        endDate = date.newInstance(endDate.year(), endDate.month(), date.daysInMonth(endDate.year(), endDate.month()));
        Set<Id> allocatedItemGroup = new Set<Id>();
        Map<String, ASI_CRM_Item_Group_Allocation__c> allocationMap = new Map<String, ASI_CRM_Item_Group_Allocation__c>();
        
        List<ASI_CRM_Item_Group_Allocation__c> allocationList = new List<ASI_CRM_Item_Group_Allocation__c>([SELECT id
                                                                                                            , ASI_CRM_Allocation_Quantity_Bottle__c
                                                                                                            , ASI_CRM_Commercial_Team__c
                                                                                                            , ASI_CRM_Effective_Date__c
                                                                                                            , ASI_CRM_Item_Group__c
                                                                                                            , ASI_CRM_Region__c
                                                                                                            , ASI_CRM_MTD_Order_Quantity__c
                                                                                                            FROM ASI_CRM_Item_Group_Allocation__c
                                                                                                            WHERE ASI_CRM_Effective_Date__c >= : startDate
                                                                                                            AND ASI_CRM_Effective_Date__c <= : endDate
                                                                                                            AND ASI_CRM_Item_Group__c IN : itemGroupSet
                                                                                                            AND ASI_CRM_Region__c IN : regionSet
                                                                                                            AND recordType.developerName Like '%_CN_%'
                                                                                                           ]);
        
        for(ASI_CRM_Item_Group_Allocation__c allocationItem : allocationList){
            
            String Key = '' + allocationItem.ASI_CRM_Item_Group__c + allocationItem.ASI_CRM_Region__c + allocationItem.ASI_CRM_Commercial_Team__c + String.valueOf(date.newInstance(allocationITem.ASI_CRM_Effective_Date__c.year(), allocationITem.ASI_CRM_Effective_Date__c.month(), 1));
            
            allocatedItemGroup.add(allocationItem.ASI_CRM_Item_Group__c);
            
            allocationItem.ASI_CRM_MTD_Order_Quantity__c = 0;
            allocationMap.put(Key, allocationItem);
        }
        
        List<ASI_KOR_Sales_Order_Transaction__c> allSOLines = new List<ASI_KOR_Sales_Order_Transaction__c>([SELECT id
                                                                                                            , ASI_CRM_CN_Product_Name__c
                                                                                                            , ASI_CRM_Order_Qty_Bottle__c
                                                                                                            , ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c
                                                                                                            , ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c
                                                                                                            , ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c
                                                                                                            , ASI_KOR_Sales_Order_Request__c
                                                                                                            FROM ASI_KOR_Sales_Order_Transaction__c
                                                                                                            WHERE ASI_CRM_CN_Product_Name__c IN : allocatedItemGroup
                                                                                                            AND id NOT IN : triggerNew
                                                                                                            AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c IN : regionSet
                                                                                                            AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c IN : commercialTeamSet
                                                                                                            AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c >= : startDate
                                                                                                            AND ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c <= : endDate
                                                                                                            AND (NOT ASI_KOR_Sales_Order_Request__r.ASI_KOR_Order_Status__c Like 'Open')
                                                                                                            AND RecordType.developerName Like '%_CN_%'
                                                                                                           ]);
        
        for(ASI_KOR_Sales_Order_Transaction__c obj : allSOLines){
            
            String key = '' + obj.ASI_CRM_CN_Product_Name__c + obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_CCity__r.ASI_CRM_CN_Area__r.ASI_CRM_Division__r.ASI_CRM_Region__c + obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_CN_Customer__r.ASI_CRM_CN_Commercial_Team__c + String.valueOf(date.newInstance(obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c.year(), obj.ASI_KOR_Sales_Order_Request__r.ASI_CRM_SG_Order_Date__c.month(), 1));
            
            if(allocationMap.containsKey(Key)){
                ASI_CRM_Item_Group_Allocation__c tmp = allocationMap.get(Key);
                tmp.ASI_CRM_MTD_Order_Quantity__c = tmp.ASI_CRM_MTD_Order_Quantity__c + obj.ASI_CRM_Order_Qty_Bottle__c;
                allocationMap.put(Key, tmp);
            }
        }
        
        Return allocationMap;
    }*/
}