objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Brand__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>EUR_CRM_Category__c</referenceTo>
        <relationshipName>Brand</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand (EU)</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Category__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Wine_Spirits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wine/Spirits</label>
        <referenceTo>EUR_CRM_Wine_Spirits__c</referenceTo>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category (EU)</label>
    <nameField>
        <label>Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Cocktail_Menu__c.object
<CustomObject>
    <description>Master data for cocktail names</description>
    <label>Cocktail Menu (EU)</label>
    <nameField>
        <label>Cocktail Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktail Menus (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_GB_Cocktail_Menu</fullName>
        <active>true</active>
        <label>GB Cocktail Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Chain contract cannot be created for an Outlet account.</errorMessage>
            <filterItems>
                <field>EUR_CRM_Account__c.EUR_CRM_Business_Type__c</field>
                <operation>equals</operation>
                <value>Head Office</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 3) OR 2 OR (4 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>GB Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>GB Contract, EUR FI Chain Contract, EUR FI Independent Contract</value>
            </filterItems>
            <filterItems>
                <field>Contact.EUR_CRM_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.EUR_CRM_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract, EUR FI Independent Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Type__c</fullName>
        <description>For the following affiliate/s:
1. DE</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flagship Contract</fullName>
                </value>
                <value>
                    <fullName>Standard Contract</fullName>
                </value>
                <value>
                    <fullName>Chain Contract</fullName>
                </value>
                <value>
                    <fullName>Independent Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Marketing_Package_Lump_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Lump Sum for Marketing Package, which can either have lump sum or per Brand- Quality contract item.

For the following affiliate/s:
1. GB</description>
        <label>Marketing Package Lump Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Cocktail__c.object
<CustomObject>
    <description>Junction object between contract line item and cocktail 

For the following affiliate/s:
1. GB</description>
    <fields>
        <fullName>EUR_CRM_Cocktail_Menu__c</fullName>
        <label>Cocktail Menu</label>
        <referenceTo>EUR_CRM_Cocktail_Menu__c</referenceTo>
        <relationshipLabel>Contract Cocktails</relationshipLabel>
        <relationshipName>Contract_Cocktails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Line_Item__c</fullName>
        <label>Contract Line Item</label>
        <referenceTo>EUR_CRM_Contract_Line_Item__c</referenceTo>
        <relationshipLabel>Contract Cocktails</relationshipLabel>
        <relationshipName>Contract_Cocktails</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <formula>EUR_CRM_Contract_Line_Item__r.EUR_CRM_Contract__r.Id</formula>
        <label>Contract</label>
        <type>Text</type>
    </fields>
    <label>Contract Cocktail (EU)</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>Contract Cocktail Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Cocktails (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Line_Item__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand_Quality__c</fullName>
        <description>Brand-Quality of Contract Mechanic
Uses by:
UK</description>
        <formula>EUR_CRM_Contract_Mechanic__r.EUR_CRM_Brand_Quality__r.Id</formula>
        <inlineHelpText>Contract Mechanic&apos;s Brand-Quality</inlineHelpText>
        <label>Brand-Quality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Mechanic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Mechanic</label>
        <referenceTo>EUR_CRM_Contract_Mechanic__c</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To identify which Mechanic Type Lump Sum is for.</description>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Process_Option_Lump_Sum__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Process Type: Lump Sum
For system use only</description>
        <label>Lump Sum</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract Line Item (EU)</label>
    <nameField>
        <displayFormat>CLI-{0000000000}</displayFormat>
        <label>Contract Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Mechanic__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>Contract_Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic__c</fullName>
        <label>Mechanic</label>
        <referenceTo>EUR_CRM_Mechanic__c</referenceTo>
        <relationshipName>Contract_Mechanics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Mechanic (EU)</label>
    <nameField>
        <displayFormat>CMN-{0000000000}</displayFormat>
        <label>Contract Mechanic No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Mechanic (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Grouping_Name__c</fullName>
        <formula>EUR_CRM_Mechanic_Type__r.EUR_CRM_Grouping_Name__c</formula>
        <label>Grouping Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mechanic (EU)</label>
    <nameField>
        <label>Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Grouping_Name__c</fullName>
        <label>Grouping Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Mechanic Type (EU)</label>
    <nameField>
        <label>Mechanic Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic Type (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated to Brand object for product heirarchy</description>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Qualities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Category__c</fullName>
        <formula>EUR_CRM_Brand__r.EUR_CRM_Category__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Wine_Spirits__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Wine/Spirits (EU)</label>
    <nameField>
        <label>Wine/Spirits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wine/Spirits (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_ContractClass_Test.cls
/*
  @Company:     IP-Converge Data Services, Inc.
  @Description: Test Class for EUR_CRM_ContractClass Class.
  @Author:      IPC
  @History:     JUN.03.2014 - Created
*/
@isTest (SeeAllData=true)
private with sharing class EUR_CRM_ContractClass_Test{
    private static EUR_CRM_Account__c accountEU;
    private static EUR_CRM_Contract__c contract;
    private static EUR_CRM_Contract__c contractNull;
    private static EUR_CRM_Contract_Line_Item__c contractItem;
    private static EUR_CRM_Contract_Mechanic__c contractMech;
    private static EUR_CRM_Mechanic_Type__c mechType;
    private static EUR_CRM_Mechanic__c mechanic;
    private static EUR_CRM_Wine_Spirits__c wineSpirits;
    private static EUR_CRM_Category__c category;
    private static EUR_CRM_Brand__c brand;
    private static EUR_CRM_Quality__c brandQuality;
    private static EUR_CRM_Cocktail_Menu__c cockMenu;
    private static EUR_CRM_Contract_Cocktail__c contractCock;
    
    public static void dataInsert1(){
        accountEU = EUR_CRM_TestClassUtilityHelper.createAccountsEU(1, 'GB FS Indirect')[0];
        accountEU.EUR_CRM_Sub_Channel__c = null;
        insert accountEU;

        Contact c = new Contact(firstname='Test fname', lastname='Test Lastname',EUR_CRM_Account__c=accountEU.Id);
        insert c;
        
        contractNull = EUR_CRM_TestClassUtilityHelper.createContracts(1, 'GB Contract', accountEU.Id, date.today(), date.today().addDays(20))[0];
        contractNull.EUR_CRM_Contract_Type__c = 'Standard Contract';
        contractNull.EUR_CRM_Contact__c = c.Id;
        
        mechType = EUR_CRM_TestClassUtilityHelper.createMechType(1, 'GB Mechanic Type', 'Cocktail')[0];
        mechType.EUR_CRM_Grouping_Name__c = 'Cocktail';
        insert mechType;
        system.assertNotEquals(mechType, null);
        
        mechanic = EUR_CRM_TestClassUtilityHelper.createMechanic(1, 'GB Mechanic', 'Cocktail', mechType.Id)[0];
        insert mechanic;
        system.assertNotEquals(mechanic, null);
        
        wineSpirits = EUR_CRM_TestClassUtilityHelper.createWineSpirits(1, 'GB Wine/Spirits', 'TEST-0001', 'SPIRITS')[0];
        insert wineSpirits;
        system.assertNotEquals(wineSpirits, null);
        
        category = EUR_CRM_TestClassUtilityHelper.createCategory(1, 'GB Category', 'TEST-0001', wineSpirits.Id)[0];
        insert category;
        system.assertNotEquals(category, null);
        
        brand = EUR_CRM_TestClassUtilityHelper.createBrand(1, 'GB Brand', 'VODKA', 'TEST-0001', category.Id)[0];
        insert brand;
        system.assertNotEquals(brand, null);
        
        brandQuality = EUR_CRM_TestClassUtilityHelper.createBrandQuality(1, 'GB Quality', 'Cocktail', 'TEST-0001', brand.Id)[0];
        insert brandQuality;
        system.assertNotEquals(brandQuality, null);
        
        contractMech = EUR_CRM_TestClassUtilityHelper.createContractMechanic(1, 'GB Contract Mechanic', mechanic.Id)[0];
        contractMech.EUR_CRM_Brand_Quality__c = brandQuality.Id;
        contractMech.EUR_CRM_Brand__c = brand.Id;
        insert contractMech;
        system.assertNotEquals(contractMech, null);
        
        contract = EUR_CRM_TestClassUtilityHelper.createContracts(1, 'GB Contract', accountEU.Id, date.today(), date.today().addDays(20))[0];
        contract.EUR_CRM_Contract_Type__c = 'Standard Contract';
        contract.EUR_CRM_Marketing_Package_Lump_Sum__c = null;
        contract.EUR_CRM_Contact__c = c.Id;
        insert contract;
        system.assertNotEquals(contract, null);
        
        contractItem = EUR_CRM_TestClassUtilityHelper.createContactLineItem(1, 'GB Contract Line Item', contract.Id)[0];
        contractItem.EUR_CRM_Process_Option_Lump_Sum__c = false;
        contractItem.EUR_CRM_Mechanic_Type__c = mechType.Id;
        contractItem.EUR_CRM_Contract_Mechanic__c = contractMech.Id;
        insert contractItem;

        cockMenu = new EUR_CRM_Cocktail_Menu__c(name='test Menu');
        insert cockMenu;

        contractCock = new  EUR_CRM_Contract_Cocktail__c(EUR_CRM_Cocktail_Menu__c=cockMenu.Id,EUR_CRM_Contract_Line_Item__c=contractItem.Id);
        insert contractCock;

        system.assertNotEquals(contractItem, null);
        
        //Create Contract Cocktail
        createContractCocktail(contractItem.Id);
    }
    
    static testMethod void testContractClass1(){
        dataInsert1();
        
        test.startTest();
            List<EUR_CRM_Contract_Line_Item__c> contractLineItemList = new List<EUR_CRM_Contract_Line_Item__c>();
            contractLineItemList.add(contractItem);

            Map<Id, List<EUR_CRM_Contract_Line_Item__c>> contractLineItemMap = new Map<Id, List<EUR_CRM_Contract_Line_Item__c>>();
            contractLineItemMap.put(mechType.Id, contractLineItemList);
 
            EUR_CRM_ContractClass ctrl = new EUR_CRM_ContractClass(contract.Id);
            
            ctrl.retrieveAllContractMechanicItems();
            ctrl.getMechanicTypeId('Cocktail');
            ctrl.retrieveTrimmedContractMechanicItems(contractLineItemMap);
            ctrl.retrieveContractMechanic(contractMech.Id);
            ctrl.retrieveContractMechanicItems(mechType.Id);
            ctrl.getTrimmedContractMechanicItems(mechType.Id, contractLineItemMap);
            ctrl.retrieveContractMechanic(brandQuality.Id, 'Cocktail');
            EUR_CRM_ContractClass.ContractCocktailWrapper cockWrap = new EUR_CRM_ContractClass.ContractCocktailWrapper(contractMech.Id,brandQuality.Id,cockMenu.Id,contractCock.name);
            EUR_CRM_ContractClass.ContractLineItemWrapper lineWrapper = new EUR_CRM_ContractClass.ContractLineItemWrapper(contract.Id,contractMech.Id,brandQuality.Id);
            EUR_CRM_ContractClass.ContractLineItemWrapper lineWrapper2 = new EUR_CRM_ContractClass.ContractLineItemWrapper(contractItem);
            
        test.stopTest();
    }
    
    private static EUR_CRM_Contract_Cocktail__c createContractCocktail(Id contractLineItemId){
        //Create Cocktail Menu
        Id cocktailMenuRecordTypeGB = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Cocktail_Menu__c', 'EUR_GB_Cocktail_Menu');
        
        EUR_CRM_Cocktail_Menu__c cocktailMenu = new EUR_CRM_Cocktail_Menu__c(Name='Test_Cocktail', RecordTypeId=cocktailMenuRecordTypeGB);
        insert cocktailMenu;
        system.assertNotEquals(cocktailMenu, null);
        
        //Create Contract Cocktail
        EUR_CRM_Contract_Cocktail__c contractCocktail = new EUR_CRM_Contract_Cocktail__c(EUR_CRM_Contract_Line_Item__c=contractLineItemId, EUR_CRM_Cocktail_Menu__c=cocktailMenu.Id);
        insert contractCocktail;
        system.assertNotEquals(contractCocktail, null);
        
        return contractCocktail;
    }
}