objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Contact_FI</fullName>
        <active>true</active>
        <label>EUR Contact FI</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Apex_Configuration__c.object
<CustomObject>
    <description>Configuration (Master Data) container for EMEA Solution
- Running Number (AO, KE, Sys Admins)</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <description>Country Code (ALL, GB, DE, SK, FI, LT, RU)</description>
        <inlineHelpText>ALL, AO, AT, DE, FI, GB,  JB, LT, LV, KE, SK, RU</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Apex Configuration (EU)</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Apex Configuration (EU) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Configurations (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_CRM_General_Configuration</fullName>
        <active>true</active>
        <label>General Configuration</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EUR_CRM_Brand__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Brand (EU)</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Brand</fullName>
        <active>true</active>
        <label>EUR FI Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Chain contract cannot be created for an Outlet account.</errorMessage>
            <filterItems>
                <field>EUR_CRM_Account__c.EUR_CRM_Business_Type__c</field>
                <operation>equals</operation>
                <value>Head Office</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 3) OR 2 OR (4 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>GB Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>GB Contract, EUR FI Chain Contract, EUR FI Independent Contract</value>
            </filterItems>
            <filterItems>
                <field>Contact.EUR_CRM_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.EUR_CRM_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract, EUR FI Independent Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Include_VAT__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to select the FI PDF Template</description>
        <label>Include VAT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_this_contract_material__c</fullName>
        <label>Is this contract material?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_this_contract_profitable__c</fullName>
        <label>Is this contract profitable enough?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Approved-Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Prolongated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Independent_Contract</fullName>
        <active>true</active>
        <label>EUR FI Independent Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Event_To_Prod_Mapping__c.object
<CustomObject>
    <description>Join object for many to many relationship between the Contract Mechanic and Contract Event</description>
    <fields>
        <fullName>EUR_CRM_Contract_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Event</label>
        <referenceTo>EUR_CRM_Contract_Event__c</referenceTo>
        <relationshipName>Contract_Event_Product_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Event - Product Mapping (EU)</label>
    <nameField>
        <displayFormat>CEPM-{0000000000}</displayFormat>
        <label>Contract Event - Product Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Event - Product Mapping (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_CRM_FI_Contract_Event_Product_Mapping_Education</fullName>
        <active>true</active>
        <label>EUR FI Contract Event - Product Mapping - Education</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_CRM_FI_Contract_Event_Product_Mapping_Trip</fullName>
        <active>true</active>
        <label>EUR FI Contract Event - Product Mapping - Trip</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Mechanic__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Contract Mechanic (EU)</label>
    <nameField>
        <displayFormat>CMN-{0000000000}</displayFormat>
        <label>Contract Mechanic No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Mechanic (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Contract_Mechanic</fullName>
        <active>true</active>
        <label>EUR FI Contract Mechanic</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Amount__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Event</label>
        <referenceTo>EUR_CRM_Contract_Event__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <description>Country code of the contract</description>
        <formula>EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Contract__r.EUR_CRM_Country_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Marketing_Amount__c</fullName>
        <label>Marketing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_No_of_People__c</fullName>
        <label>No. of People</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Product Item (EU)</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Contract Product Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mechanic (EU)</label>
    <nameField>
        <label>Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Mechanic</fullName>
        <active>true</active>
        <label>EUR FI Mechanic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Mechanic Type (EU)</label>
    <nameField>
        <label>Mechanic Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic Type (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Mechanic_Type</fullName>
        <active>true</active>
        <label>EUR FI Mechanic Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Quality</fullName>
        <active>true</active>
        <label>EUR FI Quality</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(
BEGINS(UserRole.DeveloperName, &apos;EUR_&apos;),
 RIGHT(LEFT(UserRole.DeveloperName, 6), 2) , TEXT(EUR_CRM_Affiliate_Code_Picklist__c) )</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_FI_TestContractBuilderController.cls
@isTest
public class EUR_CRM_FI_TestContractBuilderController{

    static User eurSysUser; 
    static void setUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser = new User(Alias = 'standt', Email='userEmail1234aoke@test.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke@test.com');
        insert eurSysUser;
    }
    
    /**
       EUR_CRM_FI_ContractBuilderController
    */
    static testMethod  void testContractBuilder(){
        setUser();
        System.runAs(eurSysUser){
            setMasterData();
            
            //create eu account, contact, contract
            Id fiOnAccountRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Account__c' ,'EUR_FI_Direct_On_Trade');
          //  Id fiOnContactRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('Contact' ,'EUR_Contact_FI');         
            Id fiOnContractRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract__c' ,'EUR_FI_Independent_Contract');
         
            EUR_CRM_Account__c account = new EUR_CRM_Account__c(recordtypeid = fiOnAccountRecordTypeId,
            name = 'test', eur_crm_business_type__c = 'Outlet');
            insert account;
         //   Contact contact = new Contact (EUR_CRM_Account__c = account.id, recordtypeid = fiOnContactRecordTypeId, lastname='test');
        //    insert contact;
            EUR_CRM_Contract__c contract = new EUR_CRM_Contract__c(
                 recordtypeid = fiOnContractRecordTypeId,
                 EUR_CRM_Account__c = account.id, 
                 EUR_CRM_Start_Date__c = System.today(),
                 EUR_CRM_End_Date__c = System.today(),
                 EUR_CRM_Status__c = 'Draft',
                 EUR_CRM_Is_this_contract_material__c = 60000,
                 EUR_CRM_Is_this_contract_profitable__c = 60
            );
            insert contract;
            contract = [select id, EUR_CRM_Include_VAT__c,EUR_CRM_Contact__c,EUR_CRM_Account__c,EUR_CRM_Account__r.ownerid ,EUR_CRM_Is_this_contract_material__c,EUR_CRM_Is_this_contract_profitable__c,RecordType.developername,EUR_CRM_Country_Code__c
                             from  EUR_CRM_Contract__c where id=:contract.id];
            Test.startTest();           
            // START TEST ---
            PageReference aPage = Page.EUR_CRM_FI_ContractBuilderPage;
            test.setCurrentPage(aPage);
            ApexPages.StandardController sc = new ApexPages.StandardController(contract);
            
            EUR_CRM_FI_ContractBuilderController con = new EUR_CRM_FI_ContractBuilderController(sc);
            
            EUR_CRM_FI_ContractBuilderController.MechanicTypeWrapper pouringRefundSpiritsMechType = con.mechanicTypeWrapperMap.get('Pouring Refund Spirits');
            
            system.assert(pouringRefundSpiritsMechType.getSelectableProducts() != null && pouringRefundSpiritsMechType.getSelectableProducts().size() == 1);
            
            //add contract product item
            aPage.getParameters().put('PARAM_MECHANIC_TYPE_NAME', 'Pouring Refund Spirits');
            aPage.getParameters().put('PARAM_PRODUCT_ID', bqs.id);
            aPage.getParameters().put('PARAM_ROW_NUMBER', '0');
            con.addContractLineItem();
            system.assert(pouringRefundSpiritsMechType.getSelectableProducts().size() == 0);
            //remove contract product item
            con.removeContractLineItem();
            //add contract product item
            con.addContractLineItem(); 
            pouringRefundSpiritsMechType.getProductName();
            
            //PORUING REFUNDS
            List<EUR_CRM_Contract_Product_Item__c> productItems = pouringRefundSpiritsMechType.getContractProductItems();
            EUR_CRM_Contract_Product_Item__c prod= productItems.get(0);
            prod.EUR_CRM_Quantity__c = 10000; 
            prod.EUR_CRM_Amount__c = 0.1;
            //retrive product items.
            //system.assert(pouringRefundSpiritsMechType.getProductName() == 'test bqs');
            
            //- TRIPS
            aPage.getParameters().put('PARAM_MECHANIC_TYPE_NAME', 'Trips');
            aPage.getParameters().put('PARAM_PRODUCT_ID', brand.id);
            aPage.getParameters().put('PARAM_ROW_NUMBER', '0');
            con.addContractLineItem();
               
            EUR_CRM_FI_ContractBuilderController.MechanicTypeWrapper tripsMechType = con.mechanicTypeWrapperMap.get('Trips');
            EUR_CRM_Contract_Product_Item__c tripProd= tripsMechType .getContractProductItems().get(0);
            tripProd.EUR_CRM_Contract_Event__c= contractEventTrip.id; 
            tripProd.EUR_CRM_Marketing_Amount__c= 1000;
            tripProd.EUR_CRM_No_of_People__c= 1000;
            tripsMechType.productContractEventMap.get(brand.id).getContractEventOptions(); 
            con.getContractMaterialColor();
            con.getProfitColor();
            con.save();
            system.assert(pouringRefundSpiritsMechType.getHasValue());
            system.assert(!pouringRefundSpiritsMechType.getHasLumpSumValue());
            system.assert(pouringRefundSpiritsMechType.getHasVolumeValue());
            tripsMechType.productContractEventMap.get(brand.id).getContractEventOptions(); 
            con.getContractAccount();
            tripsMechType.productContractEventMap.get(brand.id).getContractEventOptions(); 
            
            //reload
            con = new EUR_CRM_FI_ContractBuilderController(sc);
            tripsMechType = con.mechanicTypeWrapperMap.get('Trips');
            pouringRefundSpiritsMechType = con.mechanicTypeWrapperMap.get('Pouring Refund Spirits');
            con.removeContractLineItem();
            
            Test.stopTest();           
            // STOP TEST --- 
        }
    }
    
    static Map<String, EUR_CRM_Mechanic_Type__c> mechanicTypeMap;
    static EUR_CRM_Brand__c brand;
    static EUR_CRM_Quality__c bq;
    static EUR_CRM_Size__c bqs;
    static EUR_CRM_SKU__c sku;
    static EUR_CRM_Contract_Event__c contractEventEducation;
    static EUR_CRM_Contract_Event__c contractEventTrip;
    static void setMasterData(){
        //set products
        Id fiBrandRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Brand__c' ,'EUR_FI_Brand');
        Id fiBQRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Quality__c' ,'EUR_FI_Quality');
        Id fiBQSRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Size__c' ,'EUR_FI_Size');
        Id fiSKURecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_SKU__c' ,'EUR_FI_SKU');
        
        brand = new EUR_CRM_Brand__c(name = 'test brand', recordtypeid = fiBrandRecordTypeId, EUR_CRM_Active__c = true);
        insert brand;
        bq= new EUR_CRM_Quality__c(name = 'test bq', recordtypeid = fiBQRecordTypeId,EUR_CRM_Active__c = true );
        insert bq;
        bqs= new EUR_CRM_Size__c(name = 'test bqs', recordtypeid = fiBQSRecordTypeId, EUR_CRM_Active__c = true );
        insert bqs;
        sku= new EUR_CRM_SKU__c(name = 'test sku', recordtypeid = fiSKURecordTypeId,EUR_CRM_Active__c = true );
        insert sku;
        
        //mechanic type
        Id fiMechanicTypeRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Mechanic_Type__c' ,'EUR_FI_Mechanic_Type');
         
        mechanicTypeMap = new Map<String, EUR_CRM_Mechanic_Type__c>();
        //List<EUR_CRM_Mechanic_Type__c> mechTypes = new List<EUR_CRM_Mechanic_Type__c>();
        List<String> mechTypeNames = new List<String>{'Education','Free Stock','Marketing Activity Spirits','Marketing Activity Wines'
        ,'Pouring Refund Spirits','Pouring Refund Wines','Selection Brands Spirits','Selection Brands Wines','Trips'};
        
        for(String mechTypeName : mechTypeNames){
            EUR_CRM_Mechanic_Type__c mechType = new EUR_CRM_Mechanic_Type__c(
                recordtypeid = fiMechanicTypeRecordTypeId,
                Name = mechTypeName,
                EUR_CRM_Mechanic_Type_Name_English__c = mechTypeName
            ); 
            mechanicTypeMap.put(mechTypeName, mechType);
        }
        insert mechanicTypeMap.values();
        Id fiMechanicRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Mechanic__c' ,'EUR_FI_Mechanic');
       
        Map<String, EUR_CRM_Mechanic__c> mechanicMap = new Map<String, EUR_CRM_Mechanic__c>(); 
        //mechanic
        for(String mechTypeName : mechTypeNames) {
            EUR_CRM_Mechanic__c mechType = new EUR_CRM_Mechanic__c(
                recordtypeid = fiMechanicRecordTypeId,
                Name = mechTypeName,
                EUR_CRM_Mechanic_Type__c = mechanicTypeMap.get(mechTypeName).id
            ); 
            mechanicMap.put(mechTypeName, mechType);
        }
        insert mechanicMap.values();
        
        //contract mechanic
        Id fiContractMechanicRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract_Mechanic__c' ,'EUR_FI_Contract_Mechanic');
        
        Map<String,EUR_CRM_Contract_Mechanic__c> contractMechanicMap = new   Map<String,EUR_CRM_Contract_Mechanic__c>();
        
        EUR_CRM_Contract_Mechanic__c pouringRefundSpiritsCM = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_Brand_Quality_Size__c = bqs.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Pouring Refund Spirits').id
        );
        contractMechanicMap.put('Pouring Refund Spirits', pouringRefundSpiritsCM );

        EUR_CRM_Contract_Mechanic__c pouringRefundWinesCM = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_SKU__c = sku.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Pouring Refund Wines').id
        );
        contractMechanicMap.put('Pouring Refund Wines', pouringRefundWinesCM );

        EUR_CRM_Contract_Mechanic__c selectionBransSpiritsCM = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_Brand_Quality_Size__c = bqs.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Selection Brands Spirits').id
        );
        contractMechanicMap.put('Selection Brands Spirits', selectionBransSpiritsCM );
        
        EUR_CRM_Contract_Mechanic__c selectionBransWinesCM = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_Brand__c = brand.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Selection Brands Wines').id
        );
        contractMechanicMap.put('Selection Brands Wines', selectionBransWinesCM );
        
        EUR_CRM_Contract_Mechanic__c education = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_Brand__c = brand.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Education').id
        );
        contractMechanicMap.put('Education', education);
        
        EUR_CRM_Contract_Mechanic__c trips = new EUR_CRM_Contract_Mechanic__c(
            recordTypeId = fiContractMechanicRecordTypeId,
            EUR_CRM_Brand__c = brand.id,
            EUR_CRM_Mechanic__c = mechanicMap.get('Trips').id
        );
        contractMechanicMap.put('Trips', trips );
        
        insert contractMechanicMap.values();
        Id fiContractEventEducationRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract_Event__c' ,'EUR_CRM_FI_Contract_Event_Education');
        Id fiContractEventTripRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract_Event__c' ,'EUR_CRM_FI_Contract_Event_Trip');
        Id fiContractEventEducationMapRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract_Event_To_Prod_Mapping__c' ,'EUR_CRM_FI_Contract_Event_Product_Mapping_Education');
        Id fiContractEventTripMapRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract_Event_To_Prod_Mapping__c' ,'EUR_CRM_FI_Contract_Event_Product_Mapping_Trip');
        
          contractEventEducation = new EUR_CRM_Contract_Event__c(
             recordtypeid = fiContractEventEducationRecordTypeId ,
             name = 'edu'
         );
         insert contractEventEducation;
          contractEventTrip = new EUR_CRM_Contract_Event__c(
             recordtypeid = fiContractEventTripRecordTypeId ,
             name = 'trip'
         );
         insert contractEventTrip ;
         
         EUR_CRM_Contract_Event_To_Prod_Mapping__c cemEdu = new EUR_CRM_Contract_Event_To_Prod_Mapping__c(
             recordtypeid = fiContractEventEducationMapRecordTypeId ,
             EUR_CRM_Contract_Event__c = contractEventEducation.id,
             EUR_CRM_Contract_Mechanic__c =contractMechanicMap.get('Education').id
         );
         
         insert cemEdu;
         
         EUR_CRM_Contract_Event_To_Prod_Mapping__c cemTrip = new EUR_CRM_Contract_Event_To_Prod_Mapping__c(
             recordtypeid = fiContractEventTripMapRecordTypeId ,
             EUR_CRM_Contract_Event__c = contractEventTrip.id,
             EUR_CRM_Contract_Mechanic__c = contractMechanicMap.get('Trips').id
         );
         
         insert cemTrip ;
          
        
        Id fiConfigRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Apex_Configuration__c' ,'EUR_CRM_General_Configuration');
        List<EUR_CRM_Apex_Configuration__c > configs = new List<EUR_CRM_Apex_Configuration__c >();
        EUR_CRM_Apex_Configuration__c config1 = new EUR_CRM_Apex_Configuration__c(
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 20,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_Profitability',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 1
        );
        EUR_CRM_Apex_Configuration__c config2 = new EUR_CRM_Apex_Configuration__c (
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 20,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_Profitability',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 2
        );
        EUR_CRM_Apex_Configuration__c config3 = new EUR_CRM_Apex_Configuration__c (
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 40,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_Profitability',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 3
        );
        EUR_CRM_Apex_Configuration__c  config4 = new EUR_CRM_Apex_Configuration__c (
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 1000,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_ContractMaterial',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 1
        );
        EUR_CRM_Apex_Configuration__c  config5 = new EUR_CRM_Apex_Configuration__c (
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 1000,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_ContractMaterial',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 1
        );
        EUR_CRM_Apex_Configuration__c  config6 = new EUR_CRM_Apex_Configuration__c (
            recordtypeid = fiConfigRecordTypeId,
            EUR_CRM_Country_Code__c = 'fi',
            EUR_CRM_Decimal_Value__c = 2000,
            EUR_CRM_Module__c = 'EUR_CRM_FI_ContractBuilder',
            EUR_CRM_Sub_Module__c = 'EUR_CRM_ContractMaterial',
            EUR_CRM_Text_Value__c = 'red',
            EUR_CRM_Sequence__c = 1
        );
        configs.add(config1); configs.add(config2); configs.add(config3); configs.add(config4); configs.add(config5); configs.add(config6); 
        insert configs;
    }

}