objects/DBT_Debit_ARG__c.object
<CustomObject>
    <fields>
        <fullName>ReceiptNo_AR__c</fullName>
        <description>Receipt Number</description>
        <label>Receipt No</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipName>Debits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Debit</label>
    <nameField>
        <label>Nombre de debit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Debits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RCP_Receipt_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Status_AR__c</fullName>
        <description>Receipt Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt Issued Deposit pending</fullName>
                </value>
                <value>
                    <fullName>Receipt Issued Deposit done</fullName>
                </value>
                <value>
                    <fullName>Receipt printed Deposit pending</fullName>
                </value>
                <value>
                    <fullName>Receipt printed Deposit done</fullName>
                </value>
                <value>
                    <fullName>Receipt Sent to Treasury</fullName>
                </value>
                <value>
                    <fullName>Receipt Verified</fullName>
                </value>
                <value>
                    <fullName>Receipt with TXT</fullName>
                </value>
                <value>
                    <fullName>Receipt Value with Guarantee</fullName>
                </value>
                <value>
                    <fullName>Receipt printed with Value in Custody</fullName>
                </value>
                <value>
                    <fullName>Receipt cancelled</fullName>
                </value>
                <value>
                    <fullName>Receipt of Applying Documents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Receipt</label>
    <nameField>
        <label>Receipt No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_AR_Debit.cls
/*******************************************************************************
*   Company: Zimmic   Developer : Nicolás Marán    Fecha: 23/3/2016
*-------------------------------------------------------------------------------
*   Clase utilizada en los triggers del objeto LAT_AR_Debit
*******************************************************************************/
public with sharing class LAT_AR_Debit {
	

/*******************************************************************************
*   Company: Zimmic   Developer : Nicolás Marán    Fecha: 23/3/2016
*-------------------------------------------------------------------------------
*   //Metodo verifica el estado del padre del débito para ver si el débito puede ser modificado
*******************************************************************************/  

	public static void DebitCheckPrintStatus(Map<id,DBT_Debit_ARG__c> triggerNewMap){
			
		 Map<id,DBT_Debit_ARG__c> mapTemp = new Map<id,DBT_Debit_ARG__c>([Select id , ReceiptNo_AR__r.Status_AR__c from DBT_Debit_ARG__c where id IN : triggerNewMap.keyset()]);
        
        for (DBT_Debit_ARG__c deb : triggerNewMap.values()) { 

        	String statusReceipt = mapTemp.get(deb.id).ReceiptNo_AR__r.Status_AR__c;

        	 if(statusReceipt == null || Lat_RecieptValidationsUtil.checkBothStatus(statusReceipt)) 
                    deb.addError(Label.LAT_AR_TRIGGER_DebitForPrintReciept);
        
        }		
	}

}