objects/DCM_Documents_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Amounttoapply_AR__c</fullName>
        <description>Amount to apply over &apos;NetOpenBalance_AR__c&apos;</description>
        <label>Amount to apply</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DocAppliedinJDE_AR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the document has been applied in JDE (by TXT file batch process)</description>
        <label>Doc applied in JDE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_id_pk_AR__c</fullName>
        <description>Key value to integrate back with &apos;Analítico de Cuenta Corriente&apos;. The value is the concatenation of several JDE fields in the customer ledger: (AN8, Company, Document Type, Document Number, Parcela). The matching field in &apos;Analítico de Cuenta Corriente&apos; is: Internal_id_pk__c</description>
        <externalId>true</externalId>
        <label>Internal ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>LAT Document</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Titulos__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Títulos em aberto</relationshipLabel>
        <relationshipName>Titulos_de_cobranca</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_id_pk__c</fullName>
        <externalId>true</externalId>
        <label>Internal_id_pk</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NetSRReceipts_AR__c</fullName>
        <description>Amount of receipts not recorded yet in JDE</description>
        <label>Receipts pending in SF</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inadimplente</label>
        <type>Checkbox</type>
    </fields>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_UY</fullName>
        <active>true</active>
        <label>Standard UY</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PCS01_UpdateOfAnalyticsofCC_AR.cls
/*********************************************************************
 Dev: Denis Aranda-Elena Schwarzböck  Version: 1  Consulting: Valuenet
**********************************************************************/

public with sharing class PCS01_UpdateOfAnalyticsofCC_AR {
    /*
    public static String UpdateOfDocuments(){
        system.debug(LoggingLevel.ERROR, 'entroupdate:');
        
        RecordType rtAR = [select id, DeveloperName FROM RecordType WHERE SobjectType = 'Titulos__c'and DeveloperName = 'Standard_AR'];
        RecordType rtUY = [select id, DeveloperName FROM RecordType WHERE SobjectType = 'Titulos__c'and DeveloperName = 'Standard_UY'];
        set<Id> setRts = new set<Id>{rtAR.Id, rtUY.Id};
        
        List<Titulos__c> titulos = [SELECT Id, Name, Internal_id_pk__c, NetSRReceipts_AR__c, Status__c, Cliente__c, RecordTypeId FROM Titulos__c WHERE RecordTypeId IN: setRts];
        
        map<Id, Account> mapIdAccountAccounts = new map<Id, Account>(); 
        
        set<string> internalId = new set<string>();
        
        for(Titulos__c tit: titulos){
            internalId.add(tit.Internal_id_pk__c);
            if(tit.Cliente__c != null){
                if( !mapIdAccountAccounts.containsKey(tit.Cliente__c) ) {
                    if( tit.Status__c == true){
                        Account acc = new Account (id = tit.Cliente__c, Overdue__c = true);
                        mapIdAccountAccounts.put(tit.Cliente__c, acc);
                    }else{
                        Account acc = new Account (id = tit.Cliente__c, Overdue__c = false);
                        mapIdAccountAccounts.put(tit.Cliente__c, acc);
                    }
                }else if( tit.Status__c == true && mapIdAccountAccounts.get(tit.Cliente__c).Overdue__c == false ){
                    mapIdAccountAccounts.get(tit.Cliente__c).Overdue__c = true;
                }
            }
        }
        
        List<DCM_Documents_ARG__c>  documentos = [SELECT Id, Name, Internal_id_pk_AR__c, Amounttoapply_AR__c FROM DCM_Documents_ARG__c WHERE Internal_id_pk_AR__c IN: internalId AND DocAppliedinJDE_AR__c = false AND Amounttoapply_AR__c != null];
        if(documentos.isEmpty()){
            return 'OK';
        }
        
        map<String, Decimal> mapIdPk = new map<String, Decimal>();
        Map<String, List<DCM_Documents_ARG__c>> mapTituloListDocumentos = new Map<String, List<DCM_Documents_ARG__c>>();
        for(DCM_Documents_ARG__c doc: documentos){
            
            if(mapTituloListDocumentos.containskey(doc.Internal_id_pk_AR__c)){
                mapTituloListDocumentos.get(doc.Internal_id_pk_AR__c).add(doc);
            }else{
                mapTituloListDocumentos.put(doc.Internal_id_pk_AR__c, new List<DCM_Documents_ARG__c>{doc});
            }
            
        }
        List<Titulos__c> titulosToUpdate = new List<Titulos__c>();
        for(Titulos__c tit: titulos){
            
            if(mapTituloListDocumentos.containskey(tit.Internal_id_pk__c)){
                Decimal amountToApply = 0;
                for(DCM_Documents_ARG__c d: mapTituloListDocumentos.get(tit.Internal_id_pk__c)){
                     amountToApply += d.Amounttoapply_AR__c;
                }
                tit.NetSRReceipts_AR__c = amountToApply;
                titulosToUpdate.add(tit);
            }
        }
        
        string error = '';
        
        if(titulosToUpdate.size() > 0){
            system.debug(LoggingLevel.ERROR,'entroTitulos:');
            try{
                update titulosToUpdate;
            }catch(exception e){
                error = 'Se ha producido un error en analitico de cuentas: '+e.getMessage();
            }
        }
        
        if(mapIdAccountAccounts.values().size() > 0){
            system.debug(LoggingLevel.ERROR,'entrocuentas:');
            try {
                update mapIdAccountAccounts.values();
            } catch(exception e){
                if(error == ''){
                    error = 'Se ha producido un error en Clientes: '+e.getMessage();
                }else{
                    error += ' y en Clientes' + e.getMessage();
                }
                
            }
            
        }
        
        if(error == ''){
            return 'OK';
        }else{
            return error;
        }
        
        
    }
    */
}

/*TEST CODE IN PCS01_UpdateOfAnalyticsofCC_Arg_Test CLASS*/