objects/DCM_Documents_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Amounttoapply_AR__c</fullName>
        <description>Amount to apply over &apos;NetOpenBalance_AR__c&apos;</description>
        <label>Amount to apply</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_AR__c</fullName>
        <description>Bank of collections (for RU documents)</description>
        <label>Bank</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_id_pk_AR__c</fullName>
        <description>Key value to integrate back with &apos;Analítico de Cuenta Corriente&apos;. The value is the concatenation of several JDE fields in the customer ledger: (AN8, Company, Document Type, Document Number, Parcela). The matching field in &apos;Analítico de Cuenta Corriente&apos; is: Internal_id_pk__c</description>
        <externalId>true</externalId>
        <label>Internal ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptNo_AR__c</fullName>
        <description>Recipt Number</description>
        <label>Receipt No.</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Document</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Documents</pluralLabel>
    <recordTypes>
        <fullName>DCM_Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DPT_Deposit_ARG__c.object
<CustomObject>
    <fields>
        <fullName>AccType_AR__c</fullName>
        <description>Type of bank account</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collection Bank Account</fullName>
                </value>
                <value>
                    <fullName>Bank Account</fullName>
                </value>
                <value>
                    <fullName>Rapipago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount_AR__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_AR__c</fullName>
        <description>Bank account</description>
        <label>Bank</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AccType_AR__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>007</fullName>
                </value>
                <value>
                    <fullName>017R</fullName>
                </value>
                <value>
                    <fullName>072</fullName>
                </value>
                <value>
                    <fullName>011</fullName>
                </value>
                <value>
                    <fullName>015</fullName>
                </value>
                <value>
                    <fullName>017</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReceiptNo_AR__c</fullName>
        <description>Receipt number</description>
        <label>Receipt No.</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipName>Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Deposit</label>
    <nameField>
        <label>Bank Slip No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Deposits</pluralLabel>
    <recordTypes>
        <fullName>DPT_Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Parcela__c.object
<CustomObject>
    <label>Parcela</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Número da parcela</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcelas</pluralLabel>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <label>Standard_AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RCP_Receipt_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Account_AR__c</fullName>
        <description>Fantasy Name in JDE</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_AR_DepositAccountType__c</fullName>
        <label>AR Deposit Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_AR__c</fullName>
        <description>Receipt Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt Issued Deposit pending</fullName>
                </value>
                <value>
                    <fullName>Receipt Issued Deposit done</fullName>
                </value>
                <value>
                    <fullName>Receipt printed Deposit pending</fullName>
                </value>
                <value>
                    <fullName>Receipt printed Deposit done</fullName>
                </value>
                <value>
                    <fullName>Receipt Sent to Treasury</fullName>
                </value>
                <value>
                    <fullName>Receipt Verified</fullName>
                </value>
                <value>
                    <fullName>Receipt with TXT</fullName>
                </value>
                <value>
                    <fullName>Receipt Value with Guarantee</fullName>
                </value>
                <value>
                    <fullName>Receipt printed with Value in Custody</fullName>
                </value>
                <value>
                    <fullName>Receipt cancelled</fullName>
                </value>
                <value>
                    <fullName>Receipt of Applying Documents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Receipt</label>
    <nameField>
        <label>Receipt No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Receipts</pluralLabel>
    <recordTypes>
        <fullName>RCP_ReceiptGeneratedDepositDone_AR</fullName>
        <active>true</active>
        <label>Receipt generated deposit done AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Titulos__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Títulos em aberto</relationshipLabel>
        <relationshipName>Titulos_de_cobranca</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_id_pk__c</fullName>
        <externalId>true</externalId>
        <label>Internal_id_pk</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NetSRReceipts_AR__c</fullName>
        <description>Amount of receipts not recorded yet in JDE</description>
        <label>Receipts pending in SF</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ruinusebypendingreceipt_AR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up with Receipts to validate an RU is not used in more than one Receipt.</description>
        <label>RU in use by pending receipt</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipLabel>Títulos em aberto</relationshipLabel>
        <relationshipName>T_tulos_em_aberto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>codigoCia__c</fullName>
        <label>Código companhia</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dataEmissao__c</fullName>
        <label>Data emissão</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dataVencimentoAtual__c</fullName>
        <label>Data vencimento</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dataVencimentoOriginal__c</fullName>
        <label>Data venc. original</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>numeroDocumento__c</fullName>
        <label>No. documento</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>parcela__c</fullName>
        <label>Parcela</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>valorOriginalTitulo__c</fullName>
        <label>Valor original título</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>valorSaldo__c</fullName>
        <label>Valor Saldo</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TXC_TaxCertificates_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Amount_AR__c</fullName>
        <description>Withholding tax Amount</description>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ReceiptNo_AR__c</fullName>
        <description>Receipt Number</description>
        <label>Receipt No.</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipName>Tax_Certificates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Tax Certificate</label>
    <nameField>
        <label>Certificate No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Tax Certificates</pluralLabel>
    <recordTypes>
        <fullName>TXC_Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VLS_Values_ARG__c.object
<CustomObject>
    <fields>
        <fullName>AccType_AR__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collection Bank Account</fullName>
                </value>
                <value>
                    <fullName>Bank Account</fullName>
                </value>
                <value>
                    <fullName>Rapipago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount_AR__c</fullName>
        <description>Value Amount</description>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_AR__c</fullName>
        <description>Bank number</description>
        <label>Bank</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BranBranch_AR__c</fullName>
        <label>Branch</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptNo_AR__c</fullName>
        <description>Receipt Number</description>
        <label>Receipt No.</label>
        <referenceTo>RCP_Receipt_ARG__c</referenceTo>
        <relationshipName>Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Value</label>
    <nameField>
        <label>Cheque No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Values</pluralLabel>
    <recordTypes>
        <fullName>VLS_tandard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AP01_Receipt_AR_TEST.cls
/********************************************************************************
*  Company:Valuenet     Developer:Elena Schwarzböck      Date:09/04/2013        *
********************************************************************************/

@istest
public with sharing class AP01_Receipt_AR_TEST{

    static testMethod void unitTest1(){
                    
        Account acc = new Account(
            RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'ACC_1_OffTrade_ARG'),
            CNPJ__c = '20354266645',
            Name = 'testAccount',
            Type = 'Prospect_ARG',
            Corporate_Name__c = 'test',
            Channel_Type__c = 'Direto',
            Sub_Channel__c = 'Delicatessen',
            AddressLine1_AR__c= 'test',
            Shipping_Neighbourhood__c = 'test',
            Revenue_Neighbourhood__c = 'test',
            Billing_Neighbourhood__c ='test',
            Shipping_Country__c ='test',
            Revenue_Country__c ='test',
            Billing_Country__c ='test'
        );
        insert acc;
        
        system.Test.startTest();
        
        RCP_Receipt_ARG__c receipt = new RCP_Receipt_ARG__c(
            Account_AR__c = acc.id,
            LAT_AR_DepositAccountType__c = 'C',
            RecordTypeId = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c' + 'RCP_ReceiptGeneratedDepositDone_AR')
        );
        insert receipt;
        
        DCM_Documents_ARG__c doc = new DCM_Documents_ARG__c(
            Amounttoapply_AR__c = 200,
            Internal_id_pk_AR__c = 'TEST',
            ReceiptNo_AR__c = receipt.id,
            RecordTypeId = Global_RecordTypeCache.getRtId('DCM_Documents_ARG__c' + 'DCM_Standard_AR')
        );
        insert doc;
        
        Titulos__c titulo = new Titulos__c(
            NetSRReceipts_AR__c = 200,
            Internal_id_pk__c = 'TEST',
            Cliente__c = acc.id,
            codigoCia__c = 'TEST',
            dataEmissao__c = date.today(),
            dataVencimentoAtual__c = date.today(),
            dataVencimentoOriginal__c = date.today(),
            numeroDocumento__c = 1,
            parcela__c = 'T',
            valorOriginalTitulo__c = 10,
            Ruinusebypendingreceipt_AR__c = receipt.id,
            valorSaldo__c = 10,
            RecordTypeId = Global_RecordTypeCache.getRtId('Titulos__c' + 'Standard_AR')
        );
        insert titulo;
        
        delete receipt;
        
        system.Test.stopTest();
        
    }
    
    static testMethod void unitTest2(){
        
        Account acc = new Account(
            RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'ACC_1_OffTrade_ARG'),
            CNPJ__c = '20354266645',
            Name = 'testAccount',
            Type = 'Prospect_ARG',
            Corporate_Name__c = 'test',
            Channel_Type__c = 'Direto',
            Sub_Channel__c = 'Delicatessen',
            AddressLine1_AR__c= 'test',
            Shipping_Neighbourhood__c = 'test',
            Revenue_Neighbourhood__c = 'test',
            Billing_Neighbourhood__c ='test',
            Shipping_Country__c ='test',
            Revenue_Country__c ='test',
            Billing_Country__c ='test'
        );
        insert acc;
        
        system.Test.startTest();
        
        RCP_Receipt_ARG__c rece = new RCP_Receipt_ARG__c(
            Account_AR__c = acc.id,
            LAT_AR_DepositAccountType__c = 'C',
            RecordTypeId = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c' + 'RCP_ReceiptGeneratedDepositDone_AR')
        );
        
        insert rece;

        DPT_Deposit_ARG__c dep = new DPT_Deposit_ARG__c(
            ReceiptNo_AR__c = rece.id,
            Amount_AR__c = 123,
            AccType_AR__c = 'Bank Account',
            Name = '2',
            RecordTypeId = Global_RecordTypeCache.getRtId('DPT_Deposit_ARG__c' + 'DPT_Standard_AR')
        );
        
        insert dep;
        
        rece.LAT_AR_DepositAccountType__c = 'R';
        update rece;
        
        rece.LAT_AR_DepositAccountType__c = 'c';
        update rece;
        
        system.Test.stopTest();
        
    }
    
    static testMethod void unitTest3(){
                
        Account acc = new Account(
            RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'ACC_1_OffTrade_ARG'),
            CNPJ__c = '20354266645',
            Name = 'testAccount',
            Type = 'Prospect_ARG',
            Corporate_Name__c = 'test',
            Channel_Type__c = 'Direto',
            Sub_Channel__c = 'Delicatessen',
            AddressLine1_AR__c= 'test',
            Shipping_Neighbourhood__c = 'test',
            Revenue_Neighbourhood__c = 'test',
            Billing_Neighbourhood__c ='test',
            Shipping_Country__c ='test',
            Revenue_Country__c ='test',
            Billing_Country__c ='test'
        );
        insert acc;
        
        system.Test.startTest();
        
        RCP_Receipt_ARG__c rece = new RCP_Receipt_ARG__c(
            Account_AR__c = acc.id,
            Status_AR__c = 'Receipt Deposited',
            LAT_AR_DepositAccountType__c = 'C',
            RecordTypeId = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c' + 'RCP_ReceiptGeneratedDepositDone_AR')
        );
        
        insert rece;
        
        DPT_Deposit_ARG__c dep = new DPT_Deposit_ARG__c(
            ReceiptNo_AR__c = rece.id,
            Amount_AR__c = 123,
            AccType_AR__c = 'Bank Account',
            Name = '2',
            RecordTypeId = Global_RecordTypeCache.getRtId('DPT_Deposit_ARG__c' + 'DPT_Standard_AR')
        );
        
        insert dep;
        
        VLS_Values_ARG__c val = new VLS_Values_ARG__c(
            ReceiptNo_AR__c = rece.id,
            Bank_AR__c = '123',
            BranBranch_AR__c = '123',
            Name = '333458',
            RecordTypeId = Global_RecordTypeCache.getRtId('VLS_Values_ARG__c' + 'VLS_tandard_AR')
        );
        insert val;
        
        TXC_TaxCertificates_ARG__c tax = new TXC_TaxCertificates_ARG__c(
            ReceiptNo_AR__c = rece.id,
            RecordTypeId = Global_RecordTypeCache.getRtId('TXC_TaxCertificates_ARG__c' + 'TXC_Standard_AR')
        );
        insert tax;
        
        
        rece.Status_AR__c = 'Receipt Verified';
        update rece;
        
        system.Test.stopTest();
        
    }
}