objects/ESN_Video__c.object
<CustomObject>
    <fields>
        <fullName>ESN_Categories__c</fullName>
        <label>Categories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chatter Best Practices</fullName>
                </value>
                <value>
                    <fullName>Chatter Tutorials</fullName>
                </value>
                <value>
                    <fullName>Connect Tutorials</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_Description__c</fullName>
        <description>Description of the video.</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ESN_VideoTags__c</fullName>
        <description>Enters a list of keywords about this video, separated by semi-colon.</description>
        <inlineHelpText>Enters a list of keywords about this video, separated by semi-colon.</inlineHelpText>
        <label>Video Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ESN_ViewsCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Video</label>
    <nameField>
        <label>Video Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter TV Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESN_VFC29_ChatterTV_TEST.cls
/*
+-----------------------+------------------------------------------------------------------------------------+
| Author                | Cécile Lartaud                                                                     |
+-----------------------+------------------------------------------------------------------------------------+
| Description           |                                                                                    |
|                       |                                                                                    |
|     - Object(s)       | ESN_Video__c                                                                       |
|     - Description     | Test class of ESN_VFC29_ChatterTV                                                  |
+-----------------------+------------------------------------------------------------------------------------+
| Creation Date         | 09/10/2013                                                                         |
+-----------------------+------------------------------------------------------------------------------------+
| Modifications         |                                                                                    |
+-----------------------+------------------------------------------------------------------------------------+
| Governor informations |                                                                                    |
+-----------------------+------------------------------------------------------------------------------------+
*/
@isTest
private class ESN_VFC29_ChatterTV_TEST{

    static testMethod void myUnitTest() {
        User contextUsr;
        /* Query the permission set "Project Management" */
        List<PermissionSet> searchList = [SELECT Id FROM PermissionSet WHERE Name = 'ESN_ChatterTV_Viewer'];
        
        if(searchList.size() != 0) {
            String permId = searchList[0].Id;
            
            /* Create a context user */
            contextUsr = TestFactory.createUserWithProfile('ctxUsr', 'ESN SSO User');
            insert contextUsr;
            
            /* Assign the permission set to the user */
            PermissionSetAssignment permAssign = new PermissionSetAssignment( AssigneeId = contextUsr.Id, PermissionSetId = permId );
            insert permAssign;
        } else {
            /* Create a context user */
            contextUsr = TestFactory.createUserWithProfile('ctxUsr', 'System Administrator');
            insert contextUsr;
        }
        
        System.runas(contextUsr){               
            // Create Chatter Videos with contextUsr as owner //
            ESN_Video__c vid1 = new ESN_Video__c(Name = 'vid1', ESN_Description__c = 'vid1 descr', ESN_VideoTags__c = 'tag', ESN_Categories__c = 'cat');
            insert vid1;
            ESN_Video__c vid2 = new ESN_Video__c(Name = 'vid2', ESN_Description__c = 'vid2 descr', ESN_VideoTags__c = 'tag', ESN_Categories__c = 'cat', ESN_ViewsCount__c = 2);
            insert vid2;
            ESN_Video__c vid3 = new ESN_Video__c(Name = 'vid3', ESN_Description__c = 'vid3 descr', ESN_VideoTags__c = 'tag', ESN_Categories__c = '');
            insert vid3;
            ESN_Video__c vid4 = new ESN_Video__c(Name = 'vid4', ESN_Description__c = 'vid4 descr', ESN_VideoTags__c = 'tag', ESN_Categories__c = 'cat');
            insert vid4;
            
            
            /* Create new instance of Visualforce Page */
            Pagereference vf = Page.ESN_VFP29_ChatterTV;
            Test.setCurrentPageReference(vf);
            ESN_VFC29_ChatterTV con1 = new ESN_VFC29_ChatterTV();    
        }
    }
}