objects/ESN_MB_Article__c.object
<CustomObject>
    <description>ESN_MB MyBrands Article: Object to store MyBrands app Web Article</description>
    <fields>
        <fullName>ESN_MB_Stage__c</fullName>
        <description>Define stage of Articles, Draft, published, archived</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MyBrands Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Entry__c.object
<CustomObject>
    <description>ESN_MB Entry : Allows to link My Brands objects thanks to a &quot;Many-to-many&quot; relation</description>
    <fields>
        <fullName>ESN_MB_Article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Web Article of MyBrands</description>
        <label>MyBrands Article</label>
        <referenceTo>ESN_MB_Article__c</referenceTo>
        <relationshipLabel>MyBrands Entries</relationshipLabel>
        <relationshipName>Rubric</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MyBrands Entry</label>
    <nameField>
        <displayFormat>EN-{00000}</displayFormat>
        <label>Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyBrands Entries</pluralLabel>
    <recordTypes>
        <fullName>Articles_To_Products</fullName>
        <active>true</active>
        <description>Used to store relation between Articles and Products (which products an article is attached to)</description>
        <label>Articles To Products</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESN_MB_DraftArticleCleaner.cls
/**
    About
    -----
    Description: Schedulable class responsible for deleting Draft articles older than yesterday
    Created for salesforce PS SOW : Pernod Ricard
    Create date: Jun 2015

    Details
    -------
    This class execution should be scheduled once a day.
    
    Update History
    --------------
    Jun 2015 / Created by Sébastien Chateau

    Issues / TODOs
    --------------
    
*/
global class ESN_MB_DraftArticleCleaner implements Schedulable {
    global void execute(SchedulableContext ctx) {
        //Retrieving and deleting the Articles with status Draft and last modified date before yesterday
        List<Database.DeleteResult> listResult = 
            Database.delete([SELECT id
                             FROM ESN_MB_Article__c
                             WHERE ESN_MB_Stage__c = 'Draft'
                             AND LastModifiedDate < YESTERDAY]);
        
        System.debug('listResult delete ESN_MB_Article__c = ' + listResult);
        
        //Retrieving and deleting entries with Record Type=Articles_To_Products linked to no article
        //These entries are "orphans", their related article has been deleted so they must be deleted
        listResult = Database.delete([Select id from ESN_MB_Entry__c
                             Where RecordType.DeveloperName = 'Articles_To_Products'
                             And ESN_MB_Article__c = NULL]);
        
        System.debug('listResult delete ESN_MB_Entry__c = ' + listResult);
    }
}