objects/ESN_MB_Activation__c.object
<CustomObject>
    <description>ESN_MB MyBrands : Object to store Brand and Market Activations for MyBrands app</description>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_LeCercle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ESN_MB_LeCercle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Market__c</fullName>
        <description>Market concerned by the Activation</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Balkans</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>Caribbean Cesam</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Coa Rica</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cuba</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_MB_Stage__c</fullName>
        <description>Define stage of Articles, Draft, published, archived</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MyBrands Activation</label>
    <nameField>
        <label>Activation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Activations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Article__c.object
<CustomObject>
    <description>ESN_MB MyBrands Article: Object to store MyBrands app Web Article</description>
    <fields>
        <fullName>ESN_MB_Abstract__c</fullName>
        <description>Contains the article small description.</description>
        <label>Abstract</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Bottom_Text__c</fullName>
        <description>Bottom description text of a web Article for MyBrand Application</description>
        <label>Bottom Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Stage__c</fullName>
        <description>Define stage of Articles, Draft, published, archived</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_MB_Top_Text__c</fullName>
        <description>Top description text of a web Article for MyBrand Application</description>
        <label>Top Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>MyBrands Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Asset__c.object
<CustomObject>
    <description>ESN_MB Asset : Object to handle DAM asset description and local Asset for MyBrands app</description>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_DAMId__c</fullName>
        <description>Hold External Id from DAM</description>
        <externalId>true</externalId>
        <label>DAMId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ESN_MB_description__c</fullName>
        <description>DAM Field : description</description>
        <label>description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESN_MB_fileName__c</fullName>
        <description>DAM Field : fileName</description>
        <label>fileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_isWebinar__c</fullName>
        <description>Define weither is a webinar video or not</description>
        <label>isWebinar</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_originalFile_extension__c</fullName>
        <description>DAM Field : originalFile_extension</description>
        <label>originalFile extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MyBrands Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_NodePage__c.object
<CustomObject>
    <description>ESN_MB MyBrands : Object to store MyBrands app landing pages and skeleton navigation</description>
    <fields>
        <fullName>ESN_MB_Abstract__c</fullName>
        <defaultValue>&quot;-&quot;</defaultValue>
        <description>Abstract description for a rubric</description>
        <label>Abstract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_BrandParentId__c</fullName>
        <label>ESN_MB_BrandParentId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Brand_Category__c</fullName>
        <description>Brand Category for MyBrands</description>
        <label>Brand Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TOP14</fullName>
                </value>
                <value>
                    <fullName>Wines</fullName>
                </value>
                <value>
                    <fullName>Key Local Brands</fullName>
                </value>
                <value>
                    <fullName>Pernod Ricard Brand</fullName>
                </value>
                <value>
                    <fullName>Other Brands</fullName>
                </value>
                <value>
                    <fullName>LeCercle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_MB_ChatterGroup_Id__c</fullName>
        <description>Salesforce Id of the chatter public group supporting the brand</description>
        <inlineHelpText>Salesforce Id of the chatter public group supporting the brand</inlineHelpText>
        <label>Chatter Group Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Default_Brand_Variant_Value__c</fullName>
        <label>Default Brand Variant Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MyBrands Node Page</label>
    <nameField>
        <label>PageNode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Node Pages</pluralLabel>
    <recordTypes>
        <fullName>ESN_MB_Brand</fullName>
        <active>true</active>
        <description>Define Homepage for a Brand</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESN_MB_NOP_Search_Cx.cls
global class ESN_MB_NOP_Search_Cx {
    /**
    * Method searchMyBrands()
    * @param searchText: String param corresponding to the text typed by user
    * @return searchList: returns a list containing lists of results for each object
    */
    @RemoteAction
    global static List<List<SObject>> searchMyBrands(String searchText, String brandId) {
//        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        ESN_MB_NodePage__c brandPage = [Select Name, ESN_MB_ChatterGroup_Id__c, ESN_MB_Brand_Category__c from ESN_MB_NodePage__c Where id = :brandId];

        //String rawBrandName = brandPage.Name;
        //String brandName = '%' + rawBrandName + '%';
        String brandName = brandPage.Name;
        String brandCategory = brandPage.ESN_MB_Brand_Category__c;
        
        String brandVariantValue = [Select ESN_MB_Default_Brand_Variant_Value__c 
                            From ESN_MB_NodePage__c 
                            Where Id = : brandId 
                            limit 1].ESN_MB_Default_Brand_Variant_Value__c;
        brandVariantValue = '%' + brandVariantValue + '%';
        

        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        
        String chatterGroupId = brandPage.ESN_MB_ChatterGroup_Id__c;
        
        system.debug('--------------------------- ' + searchValue + ' -------------------------------');
        List<List<SObject>> searchList;
        if (brandCategory == Label.ESN_MB_LeCercle) {
            searchList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                          ESN_MB_Article__c (Id, Name, ESN_MB_Abstract__c, ESN_MB_Bottom_Text__c, ESN_MB_Top_Text__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC), 
                                          ESN_MB_Asset__c (Id, Name, ESN_MB_Description__c, ESN_MB_fileName__c, ESN_MB_isWebinar__c, ESN_MB_originalFile_extension__c, ESN_MB_DAMId__c WHERE ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC),
                                          ESN_MB_Activation__c (Id, Name, CreatedDate, ESN_MB_Market__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC),
                                          FeedItem (Id, Body, Type, linkUrl, title, CreatedById, CreatedBy.Name, CreatedBy.Profile.CreatedBy.SmallPhotoUrl where parentId = :chatterGroupId ORDER BY CreatedDate DESC),
                                          FeedComment(Id, CommentBody, CommentType, CreatedBy.Name, FeedItemId, InsertedById, ParentId where parentId = :chatterGroupId ORDER BY CreatedDate DESC)];
        } else {
            searchList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                          ESN_MB_Article__c (Id, Name, ESN_MB_Abstract__c, ESN_MB_Bottom_Text__c, ESN_MB_Top_Text__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC), 
                                          ESN_MB_Asset__c (Id, Name, ESN_MB_Description__c, ESN_MB_fileName__c, ESN_MB_isWebinar__c, ESN_MB_originalFile_extension__c, ESN_MB_DAMId__c WHERE ESN_MB_Brand_Scope_Text__c LIKE :brandVariantValue ORDER BY CreatedDate DESC),
                                          ESN_MB_Activation__c (Id, Name, CreatedDate, ESN_MB_Market__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC),
                                          FeedItem (Id, Body, Type, linkUrl, title, CreatedById, CreatedBy.Name, CreatedBy.Profile.CreatedBy.SmallPhotoUrl where parentId = :chatterGroupId ORDER BY CreatedDate DESC),
                                          FeedComment(Id, CommentBody, CommentType, CreatedBy.Name, FeedItemId, InsertedById, ParentId where parentId = :chatterGroupId ORDER BY CreatedDate DESC)];            
        }
        return searchList;
    }

/**
    * Method searchMyBrandsLeCercle()
    * @param searchText: String param corresponding to the text typed by user
    * @return searchList: returns a list containing lists of results for each object
    */
    @RemoteAction
    global static List<List<SObject>> searchMyBrandsLeCercle(String searchText, String brandId) {
//        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        ESN_MB_NodePage__c brandPage = [Select Name, ESN_MB_ChatterGroup_Id__c from ESN_MB_NodePage__c Where id = :brandId];

        String rawBrandName = brandPage.Name;
        String brandName = '%' + rawBrandName + '%';

        String brandVariantValue = [Select ESN_MB_Default_Brand_Variant_Value__c 
                            From ESN_MB_NodePage__c 
                            Where Id = : brandId 
                            limit 1].ESN_MB_Default_Brand_Variant_Value__c;
        brandVariantValue = '%' + brandVariantValue + '%';
        

        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        
        String chatterGroupId = brandPage.ESN_MB_ChatterGroup_Id__c;
        
        system.debug('--------------------------- ' + searchValue + ' -------------------------------');
        List<List<SObject>> searchList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                          ESN_MB_Article__c (Id, Name, ESN_MB_Abstract__c, ESN_MB_Bottom_Text__c, ESN_MB_Top_Text__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC), 
                                          ESN_MB_Asset__c (Id, Name, ESN_MB_Description__c, ESN_MB_fileName__c, ESN_MB_isWebinar__c, ESN_MB_originalFile_extension__c, ESN_MB_DAMId__c WHERE ESN_MB_Brand_Scope_Text__c LIKE :brandVariantValue ORDER BY CreatedDate DESC),
                                          ESN_MB_Activation__c (Id, Name, CreatedDate, ESN_MB_Market__c WHERE ESN_MB_Stage__c = 'Published' AND ESN_MB_LeCercle__c = true AND ESN_MB_Brand_Scope_Text__c LIKE :brandName ORDER BY CreatedDate DESC),
                                          FeedItem (Id, Body, Type, linkUrl, title, CreatedById, CreatedBy.Name, CreatedBy.Profile.CreatedBy.SmallPhotoUrl where parentId = :chatterGroupId ORDER BY CreatedDate DESC),
                                          FeedComment(Id, CommentBody, CommentType, CreatedBy.Name, FeedItemId, InsertedById, ParentId where parentId = :chatterGroupId ORDER BY CreatedDate DESC)];            
        return searchList;
    }

    @RemoteAction
    global static List<List<ESN_MB_NOP_Search_DTO>> search(String searchText, String currentBrandId) {
        String brandId = '';
        List<ESN_MB_NodePage__c> brandInfo = [SELECT Id, Name, ESN_MB_Brand_Category__c, ESN_MB_BrandParentId__c FROM ESN_MB_NodePage__c WHERE RecordType.DeveloperName = 'ESN_MB_Brand' AND Id=:currentBrandId LIMIT 1];
        for(ESN_MB_NodePage__c brand : brandInfo) {
            if(brand.ESN_MB_Brand_Category__c == Label.ESN_MB_LeCercle && brand.Name != Label.ESN_MB_LeCercle && brand.ESN_MB_BrandParentId__c != null) {
                brandId = brand.ESN_MB_BrandParentId__c;
            } else {
                brandId = '';
            }
        }
        
        List<List<ESN_MB_NOP_Search_DTO>> resultList = new List<List<ESN_MB_NOP_Search_DTO>>();

        List<List<sObject>> searchList = searchMyBrands(searchText, currentBrandId);

        List<ESN_MB_NOP_Search_DTO> articleDtoList = new List<ESN_MB_NOP_Search_DTO>();

        List<ESN_MB_Article__c> articleList = searchList.get(0);
        for (ESN_MB_Article__c article : articleList) {
            ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
            searchDto.searchType = 'Article';
            searchDto.article = article;
            articleDtoList.add(searchDto);
        }
        resultList.add(articleDtoList);

        List<ESN_MB_NOP_Search_DTO> assetDtoList = new List<ESN_MB_NOP_Search_DTO>();
        List<ESN_MB_NOP_Search_DTO> feedItemAndWebinarsDtoList = new List<ESN_MB_NOP_Search_DTO>();

        List<ESN_MB_Asset__c> assetList = searchList.get(1);
        for (ESN_MB_Asset__c asset : assetList) {
            ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
            searchDto.searchType = 'Asset';
            searchDto.asset = asset;
            if ('Webinar'.equals(asset.ESN_MB_isWebinar__c)) {
                feedItemAndWebinarsDtoList.add(searchDto);
            } else {
                assetDtoList.add(searchDto);
            }
        }
        resultList.add(assetDtoList);

        List<ESN_MB_NOP_Search_DTO> activationDtoList = new List<ESN_MB_NOP_Search_DTO>();
        if (brandId != '') {
            List<List<sObject>> searchListLeCercle = searchMyBrandsLeCercle(searchText, brandId);
            List<ESN_MB_Activation__c> activationList = searchListLeCercle.get(2);
            for (ESN_MB_Activation__c activation : activationList) {
                ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
                searchDto.searchType = 'Activation';
                searchDto.activation = activation;
                activationDtoList.add(searchDto);
            }
            resultList.add(activationDtoList);
        } else {
            List<ESN_MB_Activation__c> activationList = searchList.get(2);
            for (ESN_MB_Activation__c activation : activationList) {
                ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
                searchDto.searchType = 'Activation';
                searchDto.activation = activation;
                activationDtoList.add(searchDto);
            }
            resultList.add(activationDtoList);  
        }

        Map<Id, User> userList = new Map<Id, User>([select Id, SmallPhotoUrl from User where SmallPhotoUrl != null]);

        List<FeedItem> feedItemList = searchList.get(3);
        for (FeedItem feedItem : feedItemList) {
            ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
            searchDto.searchType = 'FeedItem';
            searchDto.feedItem = feedItem;

            String createdBySmallPhoto = userList.get(feedItem.CreatedById).SmallPhotoUrl;
            System.debug('createdBySmallPhoto :' + createdBySmallPhoto);
            searchDto.createdBySmallPhotoUrl = createdBySmallPhoto;
            feedItemAndWebinarsDtoList.add(searchDto);
        }
        resultList.add(feedItemAndWebinarsDtoList);

        List<ESN_MB_NOP_Search_DTO> feedCommentDtoList = new List<ESN_MB_NOP_Search_DTO>();
        List<FeedComment> feedCommentList = searchList.get(4);
        for (FeedComment feedComment : feedCommentList) {
            ESN_MB_NOP_Search_DTO searchDto = new ESN_MB_NOP_Search_DTO();
            searchDto.searchType = 'FeedComment';
            searchDto.feedComment = feedComment;

            String createdBySmallPhoto = userList.get(feedComment.CreatedById).SmallPhotoUrl;
            System.debug('createdBySmallPhoto :' + createdBySmallPhoto);
            searchDto.createdBySmallPhotoUrl = createdBySmallPhoto;
            feedCommentDtoList.add(searchDto);
        }
        resultList.add(feedCommentDtoList);

        return resultList;
    }
    
}