objects/ESN_MB_Activation__c.object
<CustomObject>
    <description>ESN_MB MyBrands : Object to store Brand and Market Activations for MyBrands app</description>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Parent_Activation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Global Activation that has been used as a model to make this Market Activation</description>
        <inlineHelpText>The Global Activation that has been used as a model to make this Market Activation</inlineHelpText>
        <label>Parent Activation</label>
        <referenceTo>ESN_MB_Activation__c</referenceTo>
        <relationshipLabel>Associated Activations</relationshipLabel>
        <relationshipName>Adapted_Market_Activations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Product in NodePage records</description>
        <inlineHelpText>Select a product in Node pages record</inlineHelpText>
        <label>Product</label>
        <referenceTo>ESN_MB_NodePage__c</referenceTo>
        <relationshipName>Activations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Stage__c</fullName>
        <description>Define stage of Articles, Draft, published, archived</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MyBrands Activation</label>
    <nameField>
        <label>Activation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Activations</pluralLabel>
    <recordTypes>
        <fullName>ESN_MB_Brand_Activation</fullName>
        <active>true</active>
        <description>Brand Activation</description>
        <label>Brand Activation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Article__c.object
<CustomObject>
    <description>ESN_MB MyBrands Article: Object to store MyBrands app Web Article</description>
    <fields>
        <fullName>ESN_MB_Abstract__c</fullName>
        <description>Contains the article small description.</description>
        <label>Abstract</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Bottom_Text__c</fullName>
        <description>Bottom description text of a web Article for MyBrand Application</description>
        <label>Bottom Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Stage__c</fullName>
        <description>Define stage of Articles, Draft, published, archived</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_MB_Top_Text__c</fullName>
        <description>Top description text of a web Article for MyBrand Application</description>
        <label>Top Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>MyBrands Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Asset__c.object
<CustomObject>
    <description>ESN_MB Asset : Object to handle DAM asset description and local Asset for MyBrands app</description>
    <fields>
        <fullName>ESN_MB_Brand_Scope_Text__c</fullName>
        <description>Stores the Name of the Brand</description>
        <inlineHelpText>Stores the Name of the Brand</inlineHelpText>
        <label>Brand Scope Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_DocumentId__c</fullName>
        <label>DocumentId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_URL_thumbnail__c</fullName>
        <description>DAM Field : thumbnail</description>
        <label>URL thumbnail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MyBrands Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_Entry__c.object
<CustomObject>
    <description>ESN_MB Entry : Allows to link My Brands objects thanks to a &quot;Many-to-many&quot; relation</description>
    <fields>
        <fullName>ESN_MB_Activation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to MyBrands activation record</description>
        <label>MyBrands Activation</label>
        <referenceTo>ESN_MB_Activation__c</referenceTo>
        <relationshipLabel>MyBrands Entries</relationshipLabel>
        <relationshipName>MyBrand_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Article_See_Also__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related article</description>
        <label>MyBrands Article See Also</label>
        <referenceTo>ESN_MB_Article__c</referenceTo>
        <relationshipLabel>MyBrands Related Articles</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Web Article of MyBrands</description>
        <label>MyBrands Article</label>
        <referenceTo>ESN_MB_Article__c</referenceTo>
        <relationshipLabel>MyBrands Entries</relationshipLabel>
        <relationshipName>Rubric</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Asset (asset is stored indifferently in the DAM or SFDC)</description>
        <label>MyBrands Asset</label>
        <referenceTo>ESN_MB_Asset__c</referenceTo>
        <relationshipLabel>MyBrands Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_KeyContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link key contact to activation</description>
        <label>MyBrands Key Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MyBrands_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESN_MB_RoleAsset__c</fullName>
        <description>Explicits what role the asset plays for the article. Only used in a Article to Asset relation.
Concretely, this field&apos;s value determines where the asset will be displayed (on the left, in the Video part or in the Image Carousel.</description>
        <label>ESN_MB_RoleAsset</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MainAsset</fullName>
                </value>
                <value>
                    <fullName>BrandContent</fullName>
                </value>
                <value>
                    <fullName>VideoAsset</fullName>
                </value>
                <value>
                    <fullName>ImageAsset</fullName>
                </value>
                <value>
                    <fullName>InPracticeBasic</fullName>
                </value>
                <value>
                    <fullName>InPracticeAverage</fullName>
                </value>
                <value>
                    <fullName>InPracticeSophisticated</fullName>
                </value>
                <value>
                    <fullName>PresentationAsset</fullName>
                </value>
                <value>
                    <fullName>ActivationContent</fullName>
                </value>
                <value>
                    <fullName>ArtworkAsset</fullName>
                </value>
                <value>
                    <fullName>LinkAsset</fullName>
                </value>
                <value>
                    <fullName>DownloadAsset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN_MB_Rubric__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a rubric in NodePage Object
Kevin Gerard 22/07/2014 - Probablemet à supprimer car doublon avec Node Page qui peut être une Rubric (record type)</description>
        <label>Rubric</label>
        <referenceTo>ESN_MB_NodePage__c</referenceTo>
        <relationshipLabel>Rubric</relationshipLabel>
        <relationshipName>Assigned_Rubric</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MyBrands Entry</label>
    <nameField>
        <displayFormat>EN-{00000}</displayFormat>
        <label>Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyBrands Entries</pluralLabel>
    <recordTypes>
        <fullName>ESN_MB_Activations_To_KeyContacts</fullName>
        <active>true</active>
        <description>Link between activations and key contacts</description>
        <label>Activations To Key Contacts</label>
    </recordTypes>
    <recordTypes>
        <fullName>ESN_MB_Articles_To_Articles</fullName>
        <active>true</active>
        <description>Record type used to handle related articles</description>
        <label>Articles To Articles</label>
    </recordTypes>
    <recordTypes>
        <fullName>ESN_MB_Articles_To_Rubrics</fullName>
        <active>true</active>
        <description>Record Type to link many Article to many Rubrics</description>
        <label>Articles To Rubrics</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESN_MB_NodePage__c.object
<CustomObject>
    <description>ESN_MB MyBrands : Object to store MyBrands app landing pages and skeleton navigation</description>
    <fields>
        <fullName>ESN_MB_Abstract__c</fullName>
        <defaultValue>&quot;-&quot;</defaultValue>
        <description>Abstract description for a rubric</description>
        <label>Abstract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN_MB_Section__c</fullName>
        <description>Define an type for Asset record</description>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strategy</fullName>
                </value>
                <value>
                    <fullName>Brand Activations Library</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Guidelines</fullName>
                </value>
                <value>
                    <fullName>History &amp; Education</fullName>
                </value>
                <value>
                    <fullName>Strategy_LeCercle</fullName>
                </value>
                <value>
                    <fullName>Global Commercial Agreements</fullName>
                </value>
                <value>
                    <fullName>Assets &amp; Activations</fullName>
                </value>
                <value>
                    <fullName>Performance &amp; Monitoring</fullName>
                </value>
                <value>
                    <fullName>Who&apos;s Who &amp; Organization</fullName>
                </value>
                <value>
                    <fullName>Trainings</fullName>
                </value>
                <value>
                    <fullName>Belief</fullName>
                </value>
                <value>
                    <fullName>Mythtelling</fullName>
                </value>
                <value>
                    <fullName>Parish</fullName>
                </value>
                <value>
                    <fullName>Set Of Visual Icons</fullName>
                </value>
                <value>
                    <fullName>Services, Rituals &amp; Experiences</fullName>
                </value>
                <value>
                    <fullName>Temple</fullName>
                </value>
                <value>
                    <fullName>Way Of Life</fullName>
                </value>
                <value>
                    <fullName>News</fullName>
                </value>
                <value>
                    <fullName>Full Beyond Model</fullName>
                </value>
                <value>
                    <fullName>Business Activation Library</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MyBrands Node Page</label>
    <nameField>
        <label>PageNode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyBrands Node Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESN_MB_NOP_RelatedArticles_Cx.cls
global class ESN_MB_NOP_RelatedArticles_Cx {
    /**
    * Method searchRelatedArticles(String searchText)
    * @param searchText: String param corresponding to the text typed by user
    * @param brandId: param of type String containing the id of the current brand
    * @return articlesList: returns a list of articles
    */
    @RemoteAction
    global static List<List<Object>> searchRelatedArticles(String searchText, String brandId) {
        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        String brandName = '%' + rawBrandName + '%';
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        List<List<Object>> articlesList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                           ESN_MB_Article__c (Id, Name, ESN_MB_Abstract__c, ESN_MB_Bottom_Text__c, ESN_MB_Top_Text__c
                                                              WHERE ESN_MB_Stage__c = 'Published'
                                                              AND ESN_MB_Brand_Scope_Text__c LIKE :brandName
                                                              ORDER BY CreatedDate DESC)];
                                          
        return articlesList;
    }
    
     /**
    * Method searchMoreRelatedArticles(String searchText, List<String> lastArticleIdList)
    * @param searchText: String param corresponding to the text typed by user
    * @param lastArticleIdList: param of type List<String> corresponding to the list of ids of the last articles selected by user
    * @param brandId: param of type String containing the id of the current brand
    * @return articlesList: returns a list of articles
    */
    @RemoteAction
    global static List<List<Object>> searchMoreRelatedArticles(String searchText, List<String> lastArticleIdList, String brandId) {
        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        String brandName = '%' + rawBrandName + '%';
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        List<List<Object>> articlesList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                           ESN_MB_Article__c (Id, Name, ESN_MB_Abstract__c, ESN_MB_Bottom_Text__c, ESN_MB_Top_Text__c 
                                                              WHERE Id NOT IN :lastArticleIdList 
                                                              AND ESN_MB_Stage__c = 'Published'
                                                              AND ESN_MB_Brand_Scope_Text__c LIKE :brandName
                                                              ORDER BY CreatedDate DESC)];
                                          
        return articlesList;
    }
    
    /**
    * Method retrieveSelectedArticles(List<String> articleIdList)
    * @param articleId: List of string param corresponding to the list of ids of articles selected by user
    * @return articlesList: returns the list of the articles
    */
    @RemoteAction
    global static List<ESN_MB_NOP_Related_Article_DTO> retrieveSelectedArticles(List<String> articleIdList) {
        List<ESN_MB_Entry__c> articlesList = [Select ESN_MB_Article__c, 
                                              ESN_MB_Article__r.Name, ESN_MB_Asset__r.ESN_MB_Url_Thumbnail__c, ESN_MB_Article__r.ESN_MB_Abstract__c,
                                              ESN_MB_Article__r.LastModifiedDate, ESN_MB_Article__r.LastModifiedById, ESN_MB_Asset__r.ESN_MB_DocumentId__c
                                              From ESN_MB_Entry__c 
                                              Where ESN_MB_RoleAsset__c = 'MainAsset' 
                                              And ESN_MB_Article__c in :articleIdList
                                              Order by CreatedDate Desc];
        
        List <ESN_MB_Entry__c> articleToRubricList = [Select ESN_MB_Article__c, ESN_MB_Rubric__r.Name, ESN_MB_Rubric__r.ESN_MB_Section__c 
                                                      From ESN_MB_Entry__c 
                                                      Where ESN_MB_Article__c in :articleIdList
                                                      And recordType.DeveloperName = 'ESN_MB_Articles_To_Rubrics'];
        
        List<ESN_MB_NOP_Related_Article_DTO> linkedArticlesList = new List<ESN_MB_NOP_Related_Article_DTO>();
        
        for(ESN_MB_Entry__c article : articlesList) {
            for(ESN_MB_Entry__c articleToRubric : articleToRubricList) {
                if(article.ESN_MB_Article__c == articleToRubric.ESN_MB_Article__c) {
                    ESN_MB_NOP_Related_Article_DTO relatedArticle = new ESN_MB_NOP_Related_Article_DTO();
                    String lastModifiedById = article.ESN_MB_Article__r.LastModifiedById;
                    String lastModifiedByName = [Select Name
                                                 From User
                                                 Where id = :lastModifiedById].Name;
                    relatedArticle.articleId = article.ESN_MB_Article__c;
                    relatedArticle.articleName = article.ESN_MB_Article__r.Name;
                    relatedArticle.articleAbstract = article.ESN_MB_Article__r.ESN_MB_Abstract__c;
                    relatedArticle.articleLastModifiedBy = lastModifiedByName;
                    relatedArticle.articleLastModifiedDate = article.ESN_MB_Article__r.LastModifiedDate;
                    relatedArticle.mainAssetThumbnail = article.ESN_MB_Asset__r.ESN_MB_Url_Thumbnail__c;
                    relatedArticle.section = articleToRubric.ESN_MB_Rubric__r.ESN_MB_Section__c;
                    relatedArticle.rubric = articleToRubric.ESN_MB_Rubric__r.Name;
                    relatedArticle.mainAssetDocumentId = article.ESN_MB_Asset__r.ESN_MB_DocumentId__c;
                    linkedArticlesList.add(relatedArticle);
                }
            }
        }
        return linkedArticlesList;
    }
    
    //Creates an entry to link two Articles that are related
    @RemoteAction
    global static String createEntryRelatedArticle(String sourceArticleId, String targetArticleId) {
        ESN_MB_Entry__c entry = new ESN_MB_Entry__c();
        entry.ESN_MB_Article__c = sourceArticleId;
        entry.ESN_MB_Article_See_Also__c = targetArticleId;
        entry.RecordTypeId = ESN_MB_Utils.getRecordTypeId('ESN_MB_Articles_To_Articles');
        insert(entry);
        return entry.Id;
    }

    
   /**
    * Method searchBrandActivations(String searchText)
    * @param searchText: String param corresponding to the text typed by user
    * @param brandId: param of type String containing the id of the current brand
    * @return activationsList: returns a list of activations
    */
    @RemoteAction
    global static List<List<Object>> searchBrandActivations(String searchText, String brandId) {
        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        String brandName = '%' + rawBrandName + '%';
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        String brandActivationRtId = ESN_MB_Utils.getRecordTypeId('ESN_MB_Brand_Activation');
        List<List<Object>> activationsList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                              ESN_MB_Activation__c (Id, Name, ESN_MB_Product__r.Name
                                                                    WHERE recordTypeId = :brandActivationRtId 
                                                                    AND ESN_MB_Stage__c = 'Published'
                                                                    AND ESN_MB_Brand_Scope_Text__c LIKE :brandName
                                                                    ORDER BY CreatedDate DESC)];
                                          
        return activationsList;
    }
    
     /**
    * Method searchMoreBrandActivations(String searchText, List<String> lastActivationIdList)
    * @param searchText: String param corresponding to the text typed by user
    * @param lastActivationIdList: param of type List<String> corresponding to the list of ids of the last activations selected by user
    * @param brandId: param of type String containing the id of the current brand
    * @return activationsList: returns a list of activations
    */
    @RemoteAction
    global static List<List<Object>> searchMoreBrandActivations(String searchText, List<String> lastActivationIdList, String brandId) {
        String rawBrandName = [Select Name from ESN_MB_NodePage__c Where id = :brandId].Name;
        String brandName = '%' + rawBrandName + '%';
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        String brandActivationRtId = ESN_MB_Utils.getRecordTypeId('ESN_MB_Brand_Activation');
        List<List<Object>> activationsList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                               ESN_MB_Activation__c (Id, Name, ESN_MB_Product__r.Name
                                                                     WHERE Id NOT IN :lastActivationIdList 
                                                                     AND recordTypeId = :brandActivationRtId
                                                                     AND ESN_MB_Stage__c = 'Published'
                                                                     AND ESN_MB_Brand_Scope_Text__c LIKE :brandName
                                                                     ORDER BY CreatedDate DESC)];
                                              
        return activationsList;
    }
    
    /**
    * Method retrieveSelectedActivations(List<String> activationIdsList)
    * @param activationIdsList: List of string param corresponding to the list of ids of activations selected by user
    * @return linkedActivationList: returns the list of the activations
    */
    @RemoteAction
    global static List<ESN_MB_Entry__c> retrieveSelectedActivations(List<String> activationIdsList) {
        List<ESN_MB_Entry__c> linkedActivationList = [Select ESN_MB_Activation__c, 
                                                      ESN_MB_Activation__r.Name, ESN_MB_Activation__r.ESN_MB_Product__r.Name, 
                                                      ESN_MB_Asset__r.ESN_MB_Url_Thumbnail__c, ESN_MB_Asset__r.ESN_MB_DocumentId__c
                                                      From ESN_MB_Entry__c 
                                                      Where ESN_MB_RoleAsset__c = 'MainAsset' 
                                                      And ESN_MB_Activation__c in :activationIdsList
                                                      Order by CreatedDate Desc];
        return linkedActivationList;
    }
    
    /**
    * Method setParentActivation(String marketActivationId, String brandActivationId)
    * @param marketActivationId: id of the market activation to edit
    * @param brandActivationId: id of the brand activation to set as the toolkit
    */
    @RemoteAction
    global static void setParentActivation(String marketActivationId, String brandActivationId) {
        ESN_MB_Activation__c currentActivation = [Select Id, ESN_MB_Parent_Activation__c 
                                                  From ESN_MB_Activation__c 
                                                  Where Id = :marketActivationId];
        currentActivation.ESN_MB_Parent_Activation__c = brandActivationId;
        update currentActivation;
    }
    
    /**
    * Method searchKeyContact(String searchText)
    * @param searchText: String param corresponding to the text typed by user
    * @return keyContactList: returns a list of activations
    */
    @RemoteAction
    global static List<List<Object>> searchKeyContact(String searchText) {
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        List<List<Object>> keyContactList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                             User (Id, Name)];
                                          
        return keyContactList;
    }
    
     /**
    * Method searchMoreKeyContact(String searchText, List<String> lastKeyContactIdsList)
    * @param searchText: String param corresponding to the text typed by user
    * @param lastKeyContactIdsList: param of type List<String> corresponding to the list of ids of the last key contacts selected by user
    * @return keyContactList: returns a list of activations
    */
    @RemoteAction
    global static List<List<Object>> searchMoreKeyContact(String searchText, List<String> lastKeyContactIdsList) {
        String[] searchTextArray = searchText.split(' ');
        String searchValue = searchTextArray[0] + '*';
        integer arrayLength = searchTextArray.size();
        if(arrayLength  > 1) {
            for(integer i = 1; i < arrayLength; i++) {
                searchValue += ' and ' + searchTextArray[i] + '*';
            }
        }
        List<List<Object>> keyContactList = [FIND :searchValue IN ALL FIELDS RETURNING 
                                             User (Id, Name
                                                   WHERE Id NOT IN :lastKeyContactIdsList)];
                                              
        return keyContactList;
    }
    
    /**
    * Method retrieveSelectedKeyContact(List<String> keyContactIdsList)
    * @param keyContactIdsList: List of string param corresponding to the list of ids of key Contacts selected by user
    * @return keyContactList: returns the list of the key contacts (users)
    */
    @RemoteAction
    global static List<User> retrieveSelectedKeyContact(List<String> keyContactIdsList) {
        List<User> keyContactList = [Select Id, 
                                     Name, Title, SmallPhotoUrl
                                     From User
                                     Where Id in :keyContactIdsList];
        return keyContactList;
    }
    
    /**
    * Method updateOwner(String OwnerId, String activationId)
    * @param OwnerId: It's the new Owner ID
    * @param activationId: It's the activation ID
    */
    @RemoteAction
    global static void updateOwner(String OwnerId, String activationId, Boolean isActivation) {
        if(isActivation) {
            ESN_MB_Activation__c retrieveOwner = [Select Id, Name, OwnerId From ESN_MB_Activation__c Where Id = :activationId];
            retrieveOwner.OwnerId  = OwnerId;
            update retrieveOwner; 
        } else {
            ESN_MB_Article__c retrieveOwner= [Select Id, Name, OwnerId From ESN_MB_Article__c Where Id = :activationId];
            retrieveOwner.OwnerId  = OwnerId;
            update retrieveOwner; 
        }

    }
    
    /**
    * Method createEntryActivationKeyContact(String activationId, String keyContactId)
    * @param activationId: String param containing the activation id
    * @param keyContactId: String param containing the key contact id
    * @return entry.Id: returns the id of the created entry
    */
    @RemoteAction
    global static String createEntryActivationKeyContact(String activationId, String keyContactId) {
        ESN_MB_Entry__c entry = new ESN_MB_Entry__c();entry.ESN_MB_Activation__c = activationId;
        entry.ESN_MB_KeyContact__c = keyContactId;entry.RecordTypeId = ESN_MB_Utils.getRecordTypeId('ESN_MB_Activations_To_KeyContacts');insert(entry);return entry.Id;
    }
}