objects/EUR_CRM_Postal_Code_Territory_Mapping__c.object
<CustomObject>
    <description>PR EUR Data Model - Used to map EUR_CRM_Accounts to Territories by Postal Code values on the Account card.</description>
    <fields>
        <fullName>EUR_CRM_Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>EUR_CRM_Territory__c</referenceTo>
        <relationshipLabel>Included Postal Codes</relationshipLabel>
        <relationshipName>Postal_Code_Territory_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Postal Code - Territory Mapping (EU)</label>
    <nameField>
        <label>Postal Code - Territory Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Code - Territory Mappings (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Region__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Region (EU)</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Territory__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <referenceTo>EUR_CRM_Region__c</referenceTo>
        <relationshipName>Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory (EU)</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Territory__c</fullName>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_TestMassUpdateAccountOwner.cls
/*------------------------------------------------------------
Author/Company:   IP Converge Data Services,Inc.
Description:      test class for EUR_CRM_MassUpdateAccountOwner 
History
05/05/2014        IPC     Created
------------------------------------------------------------*/
@isTest
public with sharing class EUR_CRM_TestMassUpdateAccountOwner {
    private static User accUser;
    private static List<EUR_CRM_Account__c> account;
    
    static testmethod void dataInsert(){
    
        Id userId = UserInfo.getUserId();
    
        EUR_CRM_Region__c region = EUR_CRM_TestClassUtilityHelper.createRegion(1, '', userId)[0];
        insert region;
        system.assert(region.Id<>null);
        EUR_CRM_Territory__c territory = EUR_CRM_TestClassUtilityHelper.createTerritory(1, '', userId, region.Id)[0];
        insert territory;
        system.assert(territory.Id<>null);
        EUR_CRM_Postal_Code_Territory_Mapping__c territoryMap = EUR_CRM_TestClassUtilityHelper.createTerritoryMapping(1, '', territory.Id)[0];
    
        account = EUR_CRM_TestClassUtilityHelper.createAccountsEU(5, 'AT On Trade');
        for(EUR_CRM_Account__c accEU :account){
             accEU.EUR_CRM_Territory__c = territory.Id;
        }
        insert account;
        system.assert(account<>null);
        
        
    }
    static testmethod void testManager(){
        accUser = EUR_CRM_DE_TestClassUtilityHelper.createUser('System Administrator','EUR_DE_National_Sales_Manager_Off_Trade', 'testuser123902@sales.com', 'testuser123902@sales.com', 'accTest1990');
        
        System.runAs(accUser) {
            Test.startTest();
            
            dataInsert();
            EUR_CRM_MassUpdateAccountOwner massUpdateAccOwn = new EUR_CRM_MassUpdateAccountOwner('SELECT Id, Name, OwnerId, EUR_CRM_Territory__r.EUR_CRM_Territory_Owner__c, EUR_CRM_Territory__r.EUR_CRM_Territory_Owner__r.Id ' + 'FROM EUR_CRM_Account__c ' + 'WHERE OwnerId=\'' + UserInfo.getUserId() + '\'' + ' LIMIT 10');
            database.executeBatch(massUpdateAccOwn, 200);
        
            Test.stopTest();
        }
    }
}