objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Activity_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Contract_Activity_Total__c</fullName>
        <formula>IF(OR(ISNULL(EUR_CRM_Amount__c), EUR_CRM_Amount__c==0), 
		(IF(ISNULL(EUR_CRM_Lumpsum_Value__c ),0,EUR_CRM_Lumpsum_Value__c) + IF(ISNULL(EUR_CRM_Product_Items_Total__c),0,EUR_CRM_Product_Items_Total__c))
			,EUR_CRM_Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract Activity Item (EU)</label>
    <nameField>
        <displayFormat>CA - {0000000000}</displayFormat>
        <label>Contract Activity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Activity Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_ISP_ContractActivityTriggerHandler.cls
/**
 * Contract Activity Item Trigger class for iSPend APP
 *
 * @author afi
 * @copyright PARX
 */
public without sharing class EUR_ISP_ContractActivityTriggerHandler extends EUR_CRM_TriggerAbstract
{
	public EUR_ISP_ContractActivityTriggerHandler()
	{
		super('EUR_ISP_ContractActivityTriggerHandler');
	}

	public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<Id, sObject> newMap, Map<Id, sObject> oldMap)
	{
		if (TriggerAction.AFTER_UPDATE == tAction)
		{
			this.chechIfDatesChanged(sObjList, (Map<Id, EUR_CRM_Contract_Activity_Item__c>)oldMap);
		}
	}

	private void chechIfDatesChanged(List<EUR_CRM_Contract_Activity_Item__c> activities, Map<Id, EUR_CRM_Contract_Activity_Item__c> oldMap)
	{
		List<Id> contractIdsToUpdate = new List<Id>();
		for (EUR_CRM_Contract_Activity_Item__c activity : activities)
		{
			EUR_CRM_Contract_Activity_Item__c oldActivity = oldMap.get(activity.Id);
			if (activity.EUR_CRM_Contract_Activity_Total__c == oldActivity.EUR_CRM_Contract_Activity_Total__c &&
			        (activity.EUR_CRM_Start_Date__c != oldActivity.EUR_CRM_Start_Date__c || activity.EUR_CRM_End_Date__c != oldActivity.EUR_CRM_End_Date__c))
			{
				contractIdsToUpdate.add(activity.EUR_CRM_Contract__c);
			}
		}

		if (!contractIdsToUpdate.isEmpty())
		{
			EUR_ISP_ContractTransactionsServiceDE.createDraftTransactions(contractIdsToUpdate);
			EUR_ISP_ContractTransactionsServiceDE.commitTransactions();
		}
	}
}