objects/EUR_CRM_Customer_Taxonomy__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Taxonomy (EU)</label>
    <nameField>
        <label>Outlet Taxonomy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Taxonomy (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Active_End_Date__c</fullName>
        <label>Active End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Active_Start_Date__c</fullName>
        <label>Active Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Regions</fullName>
                </value>
                <value>
                    <fullName>On Trade Region 1</fullName>
                </value>
                <value>
                    <fullName>On Trade Region 2</fullName>
                </value>
                <value>
                    <fullName>On Trade Region 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EUR_CRM_Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>All Territories</fullName>
                </value>
                <value>
                    <fullName>On Trade Territory 1</fullName>
                </value>
                <value>
                    <fullName>On Trade Territory 9</fullName>
                </value>
                <value>
                    <fullName>On Trade Territory 7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>O_P_Account_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Account Mapping (EU)</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>O/P - Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Account Mapping (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Action_List_Template__c.object
<CustomObject>
    <description>EUR CRM - This object will contain the actions that the SR needs to do on the Mobile App for the Object or Promotional Campaign</description>
    <label>O/P Action List Template (EU)</label>
    <nameField>
        <label>O/P Action List Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action List Template (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Customer_Taxonomy_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Customer_Taxonomy__c</fullName>
        <label>Customer Taxonomy</label>
        <referenceTo>EUR_CRM_Customer_Taxonomy__c</referenceTo>
        <relationshipName>O_P_Customer_Taxonomy_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Customer_Taxonomy_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Customer Taxonomy Mapping (EU)</label>
    <nameField>
        <displayFormat>OPCT-{0000000000}</displayFormat>
        <label>O/P - Customer Taxonomy Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Customer Taxonomy Mapping (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Postal_Code_Territory_Mapping__c.object
<CustomObject>
    <description>PR EUR Data Model - Used to map EUR_CRM_Accounts to Territories by Postal Code values on the Account card.</description>
    <fields>
        <fullName>EUR_CRM_Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>EUR_CRM_Territory__c</referenceTo>
        <relationshipLabel>Included Postal Codes</relationshipLabel>
        <relationshipName>Postal_Code_Territory_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Postal Code - Territory Mapping (EU)</label>
    <nameField>
        <label>Postal Code - Territory Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Code - Territory Mappings (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Region__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Region (EU)</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Territory__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <referenceTo>EUR_CRM_Region__c</referenceTo>
        <relationshipName>Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Territory (EU)</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Territory__c</fullName>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_DE_TestAccountHandler.cls
/*
  @Company:     IP-Converge Data Services, Inc.
  @Description: Test Class for EUR_CRM_DE_AccountHandler Class.
  @Author:      IPC
  @History:     AUG.1.2014 - Created
*/
@isTest (SeeAllData=true)
private with sharing class EUR_CRM_DE_TestAccountHandler{
    private static EUR_CRM_Account__c accountEU;
    private static EUR_CRM_Customer_Taxonomy__c custTaxonomy;
    private static EUR_CRM_Customer_Taxonomy__c custTaxonomy2;
    private static EUR_CRM_ObjPromo__c objPromo;
    private static EUR_CRM_ObjPromo_Account_Mapping__c aMapping;
    private static User onTradeUser ;
    private static EUR_CRM_Region__c testRegion;
    private static EUR_CRM_Territory__c offTradeTerritory;
    private static EUR_CRM_Postal_Code_Territory_Mapping__c offTradeTerritoryMapping;
    private static EUR_CRM_Postal_Code_Territory_Mapping__c onTradeTerritoryMapping;
    private static EUR_CRM_Territory__c onTradeTerritory;
    private static EUR_CRM_OP_Action_List_Template__c actionListTemplate;
    
    static void setUpUsers(){
        onTradeUser = EUR_CRM_DE_TestClassUtilityHelper.createUser('System Administrator','EUR_DE_National_Sales_Manager_Off_Trade', 'testuser123902@test.com', 'testuser123902@test.com', 'test898441');
       
    }
    
    static void dataInsert1(){
    	
        testRegion = EUR_CRM_DE_TestClassUtilityHelper.createRegion('region 1', UserInfo.getUserId(),'DE Region');
        
        onTradeTerritory = EUR_CRM_DE_TestClassUtilityHelper.createTerritory('onTradeTerritory' , UserInfo.getUserId(), testRegion.id, 'DE Territory');
        
        offTradeTerritory = EUR_CRM_DE_TestClassUtilityHelper.createTerritory('offTradeTerritory' , UserInfo.getUserId(), testRegion.id, 'DE Territory');
        offTradeTerritoryMapping = EUR_CRM_DE_TestClassUtilityHelper.createPostalCodeMapping('offTradeTerritoryMapping', '12345' , onTradeTerritory.id, 'DE Off Trade Postal Code - Territory Mapping');
        
        onTradeTerritoryMapping = EUR_CRM_DE_TestClassUtilityHelper.createPostalCodeMapping('offTradeTerritoryMapping', '12345' , onTradeTerritory.id, 'DE On Trade Postal Code - Territory Mapping');
        
        custTaxonomy = EUR_CRM_DE_TestClassUtilityHelper.createCustomerTaxonomy('test taxonomy', UserInfo.getUserId(), 'DE Customer Taxonomy');
        system.assertNotEquals(custTaxonomy, null);
        
        custTaxonomy2 = EUR_CRM_DE_TestClassUtilityHelper.createCustomerTaxonomy('test taxonomy2', UserInfo.getUserId(), 'DE Customer Taxonomy');
     //   system.assertNotEquals(custTaxonomy2, null);
     
       
        /*actionListTemplate = EUR_CRM_DE_TestClassUtilityHelper.createActionTemplate(1,'DE_OFF_ALT_Tasting','DE O/P Action List Template')[0];
        insert actionListTemplate;*/
        
        //objPromo = EUR_CRM_DE_TestClassUtilityHelper.createObjPromo(1,'DE Off Trade Tasting Campaign','objPromoTest')[0];
        objPromo = EUR_CRM_DE_TestClassUtilityHelper.createObjPromo(1,'DE Off Trade Trade Fair','objPromoTest')[0];
        objPromo.EUR_CRM_Status__c = 'Active';
        //objPromo.EUR_CRM_Customer_Taxonomy__c = custTaxonomy.Id;
        Datetime GDTmyDTStart = Datetime.now().addDays(1);
        String GDTmyDateStart = GDTmyDTStart.format('MM/dd/yyyy');
        objPromo.EUR_CRM_Active_Start_Date__c = date.parse(GDTmyDateStart);
        
        //******MODIFIED BY GDT********
        //objPromo.EUR_CRM_Active_End_Date__c = date.parse('6/25/2015');
        Datetime GDTmyDT = Datetime.now().addDays(7);
        String GDTmyDate = GDTmyDT.format('MM/dd/yyyy');
        objPromo.EUR_CRM_Active_End_Date__c = date.parse(GDTmyDate);
        //******END********
        
        insert objPromo;
        objPromo.EUR_CRM_Status__c = 'Active';
        update objPromo;

     EUR_CRM_OP_Customer_Taxonomy_Mapping__c mapping = new EUR_CRM_OP_Customer_Taxonomy_Mapping__c(EUR_CRM_Customer_Taxonomy__c = custTaxonomy2.Id, EUR_CRM_ObjPromo__c = objPromo.id);
                  insert mapping;
       system.assertNotEquals(objPromo, null);
    }
    
    static testMethod void testMapping(){
        setUpUsers();
        System.runAs(onTradeUser){
            Test.startTest();
                
                dataInsert1();
        //        accountEU = EUR_CRM_DE_TestClassUtilityHelper.creaEUAccount('euAccount1 ', '12345' , 'DE OFF STD', custTaxonomy.Id);
                
         //       aMapping = new EUR_CRM_ObjPromo_Account_Mapping__c();
         //       aMapping.EUR_CRM_Account__c = accountEU.Id;
         //       aMapping.EUR_CRM_ObjPromo__c = objPromo.Id;
                //insert aMapping;
            Test.stopTest();
        }
    }
    
    static testMethod void testOffTrade(){
        setUpUsers();
        System.runAs(onTradeUser){
            Test.startTest();
                dataInsert1();
                
                //objPromo.EUR_CRM_Customer_Taxonomy__c = custTaxonomy2.Id;
                //update objPromo; 
                 accountEU = EUR_CRM_DE_TestClassUtilityHelper.creaEUAccount('euAccount1 ', '12345' , 'DE OFF STD', custTaxonomy.Id);

          		accountEU.EUR_CRM_Status_of_Customer__c = 'Active';
                accountEU.EUR_JB_Customer_Taxonomy__c = custTaxonomy2.Id;
                update accountEU;
            Test.stopTest();
        }
    }
    
    static testMethod void testOnTrade(){
        setUpUsers();
        System.runAs(onTradeUser){
            Test.startTest();
                dataInsert1();
                
                accountEU = EUR_CRM_DE_TestClassUtilityHelper.creaEUAccount('euAccount1 ', '12345' , 'DE ON Consumers', custTaxonomy.Id);
                accountEU.EUR_JB_Customer_Taxonomy__c = custTaxonomy2.Id;
                accountEU.EUR_CRM_Territory__c = offTradeTerritory.Id;
            	accountEU.EUR_CRM_Status_of_Customer__c = 'Active';
                update accountEU;
            Test.stopTest();
        }
    }
}