objects/EUR_CRM_Brand__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Brand (EU)</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_ZA_Brand</fullName>
        <active>true</active>
        <label>EUR ZA Brand</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Chain contract cannot be created for an Outlet account.</errorMessage>
            <filterItems>
                <field>EUR_CRM_Account__c.EUR_CRM_Business_Type__c</field>
                <operation>equals</operation>
                <value>Head Office</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Approved-Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Prolongated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_ZA_Outlet_Contract</fullName>
        <active>true</active>
        <label>EUR ZA Outlet Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Activity_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic</label>
        <referenceTo>EUR_CRM_Mechanic__c</referenceTo>
        <relationshipLabel>Contract Activity Item (EU)</relationshipLabel>
        <relationshipName>Contract_Activity_Item_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract Activity Item (EU)</label>
    <nameField>
        <displayFormat>CA - {0000000000}</displayFormat>
        <label>Contract Activity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Activity Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Brand_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Quality</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>Contract_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Activity_Item__c</fullName>
        <label>Contract Activity Item</label>
        <referenceTo>EUR_CRM_Contract_Activity_Item__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <description>Country code of the contract</description>
        <formula>EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Contract__r.EUR_CRM_Country_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Contract Product Item (EU)</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Contract Product Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mechanic (EU)</label>
    <nameField>
        <label>Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_ZA_Mechanic</fullName>
        <active>true</active>
        <label>EUR ZA Mechanic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type_Name_English__c</fullName>
        <label>Mechanic Type Name - English</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Mechanic Type (EU)</label>
    <nameField>
        <label>Mechanic Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic Type (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_ZA_Mechanic_Type</fullName>
        <active>true</active>
        <label>EUR ZA Mechanic Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated to Brand object for product heirarchy</description>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Qualities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_ZA_Quality</fullName>
        <active>true</active>
        <label>EUR ZA Quality</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(
BEGINS(UserRole.DeveloperName, &apos;EUR_&apos;),
 RIGHT(LEFT(UserRole.DeveloperName, 6), 2) , TEXT(EUR_CRM_Affiliate_Code_Picklist__c) )</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_ZA_TestContractBuilderController.cls
@isTest
private class EUR_CRM_ZA_TestContractBuilderController {
    
    static User eurSysUser; 
    static void setUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser = new User(Alias = 'standt', Email='userEmail1234aoke@test.com', userroleid=r.id,
                              EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke@test.com');
        insert eurSysUser;
    }
    
    static testMethod void testContractBuilder() {
        setUser();
        System.runAs(eurSysUser) {
            setMasterData();
            
            Id ZAOnTradeAccountRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Account__c', 'EUR_ZA_On_Trade_Direct');
            Id ZAOnContractRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract__c', 'EUR_ZA_Outlet_Contract');
            
            EUR_CRM_Account__c account = new EUR_CRM_Account__C(
                recordTypeId = ZAOnTradeAccountRecordTypeId,
                Name = 'Test Account',
                EUR_CRM_Business_Type__c = 'Outlet'
            );
            insert account;
            
            EUR_CRM_Contract__c contract = new EUR_CRM_Contract__c(
                recordTypeId = ZAOnContractRecordTypeId,
                EUR_CRM_Account__c = account.Id,
                EUR_CRM_Start_Date__c = System.today(),
                EUR_CRM_End_Date__c = System.today(),
                EUR_CRM_Status__c = 'Draft'
            );
            insert contract;
            
            Test.startTest();
            setPageData(contract);
            
            PageReference pageRef = Page.EUR_CRM_ZA_ContractSummaryPage;
            pageRef.getParameters().put('id', contract.id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(contract);
            
            EUR_CRM_ZA_ContractBuilderController con = new EUR_CRM_ZA_ContractBuilderController(sc);
            con.getContractAccount();
            con.getProfitColor();
            con.getIsCurrentUserApprover();
            con.getHasDeactivatePermissionSet();
            con.getEventsActivitiesTotal();  
            
            EUR_CRM_Mechanic_Type__c mechType = mechanicTypeMap.get('Listing');
            EUR_CRM_Mechanic_Type__c mechType2 = mechanicTypeMap.get('EVENTS');
                
            EUR_CRM_ZA_ContractBuilderController.MechanicTypeWrapper testWrapper = new EUR_CRM_ZA_ContractBuilderController.MechanicTypeWrapper(con, mechType, contractActivityItems[0], contractProductItems, null);
                        
            //testWrapper.setEventsMap();
            testWrapper.getProductName();
            testWrapper.getProductActiveFlag();
            testWrapper.getSelectableProducts();
            testWrapper.getContractProductItems();
            testWrapper.hasValue();
            testWrapper.getHasValue();
            testWrapper.getHasLumpSumValue();
            testWrapper.getHasVolumeValue();
            
            //EUR_CRM_ZA_ContractBuilderController.MechanicTypeWrapper testWrapper2 = new EUR_CRM_ZA_ContractBuilderController.MechanicTypeWrapper(con, mechType2, contractActivityItems[0], contractProductItems, null);
            
            Test.stopTest();
        }        
    }
    
    static Map<String, EUR_CRM_Mechanic_Type__c> mechanicTypeMap;
    static EUR_CRM_Brand__c brand;
    static EUR_CRM_Quality__c brandQuality;
    static testMethod void setMasterData() {
        // set products
        Id ZABrandRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Brand__c', 'EUR_ZA_Brand');
        Id ZABrandQualityRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Brand_Quality__c', 'EUR_ZA_Quality');
        
        brand = new EUR_CRM_Brand__c(
            name='test brand',
            recordTypeId = ZABrandRecordTypeId,
            EUR_CRM_Active__c = true
        );
        brandQuality = new EUR_CRM_Quality__c(
            name='test brand quality',
            recordTypeId = ZABrandQualityRecordTypeId,
            EUR_CRM_Active__c = true
        );
        
        // Mechanic type
        Id ZAMechanicTypeRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Mechanic_Type__c', 'EUR_ZA_Mechanic_Type');
        
        mechanicTypeMap = new Map<String, EUR_CRM_Mechanic_Type__c>();
        List<String> mechTypeNames = new List<String>{'Listing', 'Exclusivity', 'House pour', 'Stock deals', 'Events', 'POS material',
            'Uniforms', 'Drinks Menu', 'Bar Styling', 'Trainings', 'Displays', 'Promotions'
            };
                
                for(String mechTypeName: mechTypeNames) {
                    EUR_CRM_Mechanic_Type__c mechType = new EUR_CRM_Mechanic_Type__c(
                        recordTypeId = ZAMechanicTypeRecordTypeId,
                        Name = mechTypeName,
                        EUR_CRM_Mechanic_Type_Name_English__c = mechTypeName
                    );
                    mechanicTypeMap.put(mechTypeName, mechType);
                }
        insert mechanicTypeMap.values();
        
        // Mechanic
        Id ZAMechanicRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Mechanic__c', 'EUR_ZA_Mechanic');
        
        Map<String, EUR_CRM_Mechanic__c> mechanicMap = new Map<String, EUR_CRM_Mechanic__c>();
        
        for(String mechTypeName: mechTypeNames) {
            EUR_CRM_Mechanic__c mechType = new EUR_CRM_Mechanic__c(
                recordTypeId = ZAMechanicRecordTypeId,
                Name = mechTypeName,
                EUR_CRM_Mechanic_Type__c = mechanicTypeMap.get(mechTypeName).Id
            );
            mechanicMap.put(mechTypeName, mechType);
        }
        insert mechanicMap.values();
        
        // TODO: Remove Contract Mechanic from the controller
    }
    
    static Map<String, String> mechanicProductMap = new Map<String, String>{
        'Listing' => 'EUR_CRM_Brand_Quality__c',
            'Exclusivity' => 'EUR_CRM_Brand_Quality__c',
            'House pour' => 'EUR_CRM_Brand_Quality__c',
            'Stock deals' => 'EUR_CRM_Brand_Quality__c',
            'Events' => 'EUR_CRM_Brand__c',
            'POS material' => 'EUR_CRM_Brand__c',
            'Uniforms' => 'EUR_CRM_Brand__c',
            'Drinks Menu' => 'EUR_CRM_Brand__c',
            'Bar Styling' => 'EUR_CRM_Brand__c',
            'Trainings' => 'EUR_CRM_Brand__c',
            'Displays' => 'EUR_CRM_Brand__c',
            'Promotions' => 'EUR_CRM_Brand__c'
            };
                static List<EUR_CRM_Contract_Activity_Item__c> contractActivityItems;
    static List<EUR_CRM_Contract_Product_Item__c> contractProductItems; 
    
    static void setPageData(EUR_CRM_Contract__c contract) {
        Map<Id, EUR_CRM_Mechanic_Type__c> mechanicTypes = new Map<Id, EUR_CRM_Mechanic_Type__c>([SELECT Id, Name FROM EUR_CRM_Mechanic_Type__c WHERE EUR_CRM_Country_Code__c = 'ZA']);
        
        contractActivityItems = new List<EUR_CRM_Contract_Activity_Item__c>();
        contractProductItems = new List<EUR_CRM_Contract_Product_Item__c>();
        
        for(integer i = 0 ; i < 5; i++) {
            for(Id mechanicType: mechanicTypes.keySet()) {
                contractActivityItems.add(new EUR_CRM_Contract_Activity_Item__c(
                    EUR_CRM_Name__c = 'Test ContractActivityItems ' + mechanicTypes.get(mechanicType).Name,
                    EUR_CRM_Contract__c = contract.Id,
                    EUR_CRM_Mechanic_Type__c = mechanicType
                ));
            }
        }
        
        insert contractActivityItems;
        
        for(EUR_CRM_Contract_Activity_Item__c contractActivityItem : contractActivityItems) {
            EUR_CRM_Contract_Product_Item__c contractProductItem = new EUR_CRM_Contract_Product_Item__c(
                EUR_CRM_Contract_Activity_Item__c = contractActivityItem.Id
            );
            
            if(mechanicProductMap.get(mechanicTypes.get(contractActivityItem.EUR_CRM_Mechanic_Type__c).Name) == 'EUR_CRM_Brand__c') {
                contractProductItem.EUR_CRM_Brand__c = brand.Id;
            } else {
                contractProductItem.EUR_CRM_Brand_Quality__c = brandQuality.Id;
            }
            
            contractProductItems.add(contractProductItem);
        }
        
        insert contractProductItems;
    }
}