objects/EUR_CRM_JB_Template__c.object
<CustomObject>
    <description>PREU JB Data Model</description>
    <label>Template (EU)</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_On_Trade_Template</fullName>
        <active>true</active>
        <label>EUR BE On Trade Template</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_JB_Template_Criteria__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_PRS_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PRS Group Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Group_Outlet_Type__c</referenceTo>
        <relationshipLabel>Template Criteria (EU)</relationshipLabel>
        <relationshipName>Template_Criteria_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Outlet_Type_Name__c</fullName>
        <formula>EUR_CRM_PRS_Outlet_Type__r.EUR_CRM_PRS_Outlet_Type_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRS Outlet Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PRS Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Outlet_Type__c</referenceTo>
        <relationshipLabel>Template Criteria (EU)</relationshipLabel>
        <relationshipName>Template_Criteria_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Seg_Aspect_IL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PRS Segmentation Aspect (Image Level)</label>
        <referenceTo>EUR_CRM_PRS_Seg_Aspect__c</referenceTo>
        <relationshipLabel>Template Criteria (EU) (PRS Segmentation Aspect (Image Level))</relationshipLabel>
        <relationshipName>Template_Criteria_EU1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Seg_Aspect_VP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PRS Segmentation Aspect (Vol. Potential)</label>
        <referenceTo>EUR_CRM_PRS_Seg_Aspect__c</referenceTo>
        <relationshipLabel>Template Criteria (EU) (PRS Segmentation Aspect (Vol. Potential))</relationshipLabel>
        <relationshipName>Template_Criteria_EU2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_JB_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_JB_Template__c</fullName>
        <label>Template</label>
        <referenceTo>EUR_CRM_JB_Template__c</referenceTo>
        <relationshipName>Template_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Template Criteria (EU)</label>
    <nameField>
        <displayFormat>TPC-{00000000}</displayFormat>
        <label>Template Criteria No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Criteria (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_On_Trade_Template_Criteria</fullName>
        <active>true</active>
        <label>EUR BE On Trade Template Criteria</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Group_Outlet_Type__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PRS Group Outlet Type (EU)</label>
    <nameField>
        <displayFormat>PRS-GO-{00000}</displayFormat>
        <label>PRS Group Outlet Type No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Group Outlet Types (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Outlet_Type__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_PRS_Group_Outlet_Type__c</fullName>
        <label>PRS Group Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Group_Outlet_Type__c</referenceTo>
        <relationshipLabel>PRS Outlet Types (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_PRS_Outlet_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Outlet_Type_Name__c</fullName>
        <label>PRS Outlet Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PRS Outlet Type (EU)</label>
    <nameField>
        <displayFormat>PRS-O-{00000}</displayFormat>
        <label>PRS Outlet Type No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Outlet Types (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Seg_Aspect__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_Segmentation_IL_Aspect_Name__c</fullName>
        <label>PRS Segmentation IL Aspect Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iconic</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Leading</fullName>
                </value>
                <value>
                    <fullName>Mainstream</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Segmentation_VP_Aspect_Name__c</fullName>
        <label>PRS Segmentation VP Aspect Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PRS Segmentation Aspect (EU)</label>
    <nameField>
        <displayFormat>PRS-SA-{00000000}</displayFormat>
        <label>PRS Segmentation Aspect No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Segmentation Aspect (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_PRS_Segmentation_Aspect_Image_Level</fullName>
        <active>true</active>
        <label>EUR BE PRS Segmentation Aspect - Image Level</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_BE_PRS_Segmentation_Aspect_Volume_Potential</fullName>
        <active>true</active>
        <label>EUR BE PRS Segmentation Aspect - Volume Potential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Territory__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Territory (EU)</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Frequency__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ON TRADE</fullName>
                </value>
                <value>
                    <fullName>OFF TRADE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Frequency_Span_Days__c</fullName>
        <label>Interval (Every N Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_No_of_Visits_Within_Interval__c</fullName>
        <label>No. of Visits Within Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visit Frequency (EU)</label>
    <nameField>
        <label>Visit Frequency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Frequency (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_Visit_Frequency</fullName>
        <active>true</active>
        <label>EUR BE Visit Frequency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_PRS_ListingTplAssignmentHdlrTest.cls
/***********************************************************************************
 * Name: EUR_CRM_PRS_ListingTplAssignmentHdlrTest
 * Description: Test Class for EUR_CRM_PRS_ListingTplAssignmentHandler 
 *
 * Version History
 * Date         Developer   			Comments
 * ----------   -------------------  	--------------------------------------------    
 *  5-7-2017  	[Laputa] Kevin Choi  	Created. 
***********************************************************************************/

@isTest
public class EUR_CRM_PRS_ListingTplAssignmentHdlrTest {
    private static EUR_CRM_PRS_Group_Outlet_Type__c goutletType;
    private static EUR_CRM_PRS_Outlet_Type__c outletType;
    private static EUR_CRM_PRS_Seg_Aspect__c imgLevel;
    private static EUR_CRM_PRS_Seg_Aspect__c volPotential;
    
    
    static void createData(){
        
        //create Template
        Id seTemplateRt = Global_RecordTypeCache.getRtId('EUR_CRM_JB_Template__c' + 'EUR_BE_On_Trade_Template');
        EUR_CRM_JB_Template__c seTemplate = new EUR_CRM_JB_Template__c(Name = 'Test BE Template', recordTypeId = seTemplateRt);
        Insert seTemplate;
        
        //Create Template Criteria
        Id setempCriteriaRt = Global_RecordTypeCache.getRtId('EUR_CRM_JB_Template_Criteria__c' + 'EUR_BE_On_Trade_Template_Criteria');
        
        goutletType = new EUR_CRM_PRS_Group_Outlet_Type__c(EUR_CRM_Name__c='Restaurant');
        insert goutletType;
        
        outletType = new EUR_CRM_PRS_Outlet_Type__c(EUR_CRM_PRS_Outlet_Type_Name__c='Restaurant', EUR_CRM_PRS_Group_Outlet_Type__c=goutletType.Id);
        insert outletType;
        
        Id imageLevelRt = Global_RecordTypeCache.getRtId('EUR_CRM_PRS_Seg_Aspect__c' + 'EUR_BE_PRS_Segmentation_Aspect_Image_Level');
        imgLevel = new EUR_CRM_PRS_Seg_Aspect__c(recordTypeId = imageLevelRt,
                                                 EUR_CRM_Segmentation_IL_Aspect_Name__c='Iconic');
        insert imgLevel;
        
        Id volPotentialRt = Global_RecordTypeCache.getRtId('EUR_CRM_PRS_Seg_Aspect__c' + 'EUR_BE_PRS_Segmentation_Aspect_Volume_Potential');
        volPotential = new EUR_CRM_PRS_Seg_Aspect__c(recordTypeId = volPotentialRt,
                                                     EUR_CRM_Segmentation_VP_Aspect_Name__c='High');
        insert volPotential;        
        
        EUR_CRM_JB_Template_Criteria__c tempCriteria = new EUR_CRM_JB_Template_Criteria__c(EUR_JB_Active__c = true,
                                                                                           EUR_CRM_PRS_Group_Outlet_Type__c = goutletType.id,
                                                                                           EUR_CRM_PRS_Outlet_Type__c = outletType.id,
                                                                                           EUR_CRM_PRS_Seg_Aspect_IL__c = imgLevel.id,
                                                                                           EUR_CRM_PRS_Seg_Aspect_VP__c = volPotential.id,
                                                                                           EUR_JB_Template__c = seTemplate.Id,
                                                                                           recordTypeId = setempCriteriaRt);
        insert tempCriteria;
        
    }
    
    static testMethod void testBEOnTrade(){
        //Create Account
        createData();
        Test.startTest();
        
        Id seVisitRt = Global_RecordTypeCache.getRtId('EUR_CRM_Visit_Frequency__c' + 'EUR_BE_Visit_Frequency');
        EUR_CRM_Visit_Frequency__c seVisit = new EUR_CRM_Visit_Frequency__c(Name = 'Test Visit',
                                                                            EUR_CRM_No_of_Visits_Within_Interval__c = 2,
                                                                            EUR_CRM_Frequency_Span_Days__c = 2,
                                                                           recordTypeId = seVisitRt);
        
        insert seVisit;
        
        Id seAccountRt = Global_RecordTypeCache.getRtId('EUR_CRM_Account__c' + 'EUR_BE_On_Trade');
        EUR_CRM_Account__c seOnTrade = new EUR_CRM_Account__c(recordTypeId = seAccountRt,
                                                              Name = 'Test SE Account',
                                                              EUR_CRM_Company_Name__c = 'ABC',
                                                              EUR_CRM_Channel__c = 'Chain',
                                                              EUR_CRM_Business_Type__c = 'Outlet',
                                                              EUR_CRM_Status__c = 'Active',
                                                              EUR_CRM_Street__c = 'Street',
                                                              EUR_CRM_City__c = 'Ciry',
                                                              EUR_CRM_Postal_Code__c = 'Z1',
                                                              EUR_CRM_Delivery_Type__c = 'Direct', 
                                                              EUR_CRM_Visit_Frequency__c = seVisit.Id,
                                                              EUR_CRM_PRS_Group_Outlet_Type__c = goutletType.id,
                                                              EUR_CRM_PRS_Outlet_Type__c = outletType.id,
                                                              EUR_CRM_PRS_Image_Level__c = imgLevel.id,
                                                              EUR_CRM_PRS_Volume_Potential__c = volPotential.id
                                                              //EUR_CRM_Territory__c = 
                                                             );
        insert seOnTrade;
        
        Test.stopTest();
        
        
    }
}