objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Active_Start_Date__c</fullName>
        <label>Active Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>O_P_Account_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypass flag for Mobile app, so it doesn&apos;t need to create Visit Actions against that Promotion for that Account</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Account Mapping (EU)</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>O/P - Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Account Mapping (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_CRM_DE_O_P_Account_Mapping</fullName>
        <active>true</active>
        <label>DE O/P - Account Mapping</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_OP_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Action_RecordType_DevName__c</fullName>
        <description>Specifies the Record Type Developer Name of the matching Visit Action so the Mobile App can create the correct Visit Action for the SR to fill out</description>
        <label>Visit Action RecordType DevName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>O/P Action (EU)</label>
    <nameField>
        <label>O/P Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DE_OFF_Confirm_Agreement_To_Buy</fullName>
        <active>true</active>
        <label>DE OFF Confirm Agreement to Buy</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Enter_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Enter Sell In Qty</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Target__c.object
<CustomObject>
    <description>Child object of the O/P header</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PR PT is the 1st country using this field.</description>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>O/P Target (EU)</relationshipLabel>
        <relationshipName>O_P_Target_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_BQS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BQS</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Initially for PR DK - Effects Manager Interface - to reflect changes in Product changes in Effects Manager</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P Target (EU)</label>
    <nameField>
        <displayFormat>OPT-{0000000000}</displayFormat>
        <label>O/P Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P Target (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Customer_Taxonomy_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Customer_Taxonomy__c</fullName>
        <label>Customer Taxonomy</label>
        <referenceTo>EUR_CRM_Customer_Taxonomy__c</referenceTo>
        <relationshipName>O_P_Customer_Taxonomy_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Customer_Taxonomy_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Customer Taxonomy Mapping (EU)</label>
    <nameField>
        <displayFormat>OPCT-{0000000000}</displayFormat>
        <label>O/P - Customer Taxonomy Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Customer Taxonomy Mapping (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Datetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Datetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Data_Capture_EndDateTime__c</fullName>
        <label>Visit Data Capture End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Data_Capture_StartDateTime__c</fullName>
        <label>Visit Data Capture Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>Visit (EU)</label>
    <nameField>
        <displayFormat>VST-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DE_Off_Trade_Visit</fullName>
        <active>true</active>
        <label>DE Off Trade Visit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Datetime__c</fullName>
        <formula>EUR_CRM_Visit_ID__r.EUR_CRM_End_Datetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>O/P Target</label>
        <referenceTo>EUR_CRM_ObjPromo_Target__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective / Promotion</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Datetime__c</fullName>
        <formula>EUR_CRM_Visit_ID__r.EUR_CRM_Start_Datetime__c</formula>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Action Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Qty Confirmed</fullName>
                </value>
                <value>
                    <fullName>Qty Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Did Not Present</fullName>
                </value>
                <value>
                    <fullName>Participating</fullName>
                </value>
                <value>
                    <fullName>Not Participating</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Unsuccessful</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Successful</fullName>
                </value>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Not Installed</fullName>
                </value>
                <value>
                    <fullName>Tag Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Tag Not Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Actualized</fullName>
                </value>
                <value>
                    <fullName>Not Actualized</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Placed Products</fullName>
                </value>
                <value>
                    <fullName>Did Not Place Products</fullName>
                </value>
                <value>
                    <fullName>Staff Informed</fullName>
                </value>
                <value>
                    <fullName>Staff Not Informed</fullName>
                </value>
                <value>
                    <fullName>Suitable</fullName>
                </value>
                <value>
                    <fullName>Not Suitable</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Not Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit Action (EU)</label>
    <nameField>
        <displayFormat>VACT-{0000000000}</displayFormat>
        <label>Visit Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Action (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DE_OFF_Leaflet_Campaign_Agree_To_Buy</fullName>
        <active>true</active>
        <description>Not In Use as of Phase 2 Wave 1 (Jan 26 2016)</description>
        <label>DE OFF Leaflet Campaign Agreement To Buy</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Leaflet Campaign Sell In Qty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_DE_TestVisitActionHandler.cls
@isTest
public class EUR_CRM_DE_TestVisitActionHandler{ 
    @isTest
    public static void testOffTrade(){
        EUR_CRM_DE_TestClassUtilityHelper.initOffTradeUsers();
        system.runAs(EUR_CRM_DE_TestClassUtilityHelper.offTradeNationalManager){
            
            EUR_CRM_DE_TestClassUtilityHelper.initOffTradeDataSet();  
            EUR_CRM_OP_Action_List_Template__c actionListTemplate = EUR_CRM_DE_TestClassUtilityHelper.creaActionListTemplate('testDE_OFF_ALT_Leaflet_Campaign','DE_OFF_ALT_Leaflet_Campaign' ,EUR_CRM_DE_TestClassUtilityHelper.DE_ACTION_LIST_TEMPLATE_RECORD_TYPE  );
            Id rt1 = [select id from RecordType where developername = 'EUR_DE_OFF_Confirm_Agreement_To_Buy' and sobjecttype ='EUR_CRM_ObjPromo_Action__c'][0].id;
            Id rt2 = [select id from RecordType where developername = 'EUR_DE_OFF_Enter_Sell_In_Qty' and sobjecttype ='EUR_CRM_ObjPromo_Action__c'][0].id;
            EUR_CRM_ObjPromo_Action__c opaction1 = new EUR_CRM_ObjPromo_Action__c(recordtypeid = rt1,name='test', EUR_CRM_OP_Action_List_Template__c = actionListTemplate.id
                ,EUR_CRM_Visit_Action_RecordType_DevName__c = 'EUR_DE_OFF_Leaflet_Campaign_Agree_To_Buy');
            insert opaction1;
            EUR_CRM_ObjPromo_Action__c opaction2 = new EUR_CRM_ObjPromo_Action__c(recordtypeid = rt1,name='test', EUR_CRM_OP_Action_List_Template__c = actionListTemplate.id
                ,EUR_CRM_Visit_Action_RecordType_DevName__c = 'EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty');
            insert opaction2;

            EUR_CRM_ObjPromo__c objPromo = EUR_CRM_DE_TestClassUtilityHelper.createObjPromo(
            1,EUR_CRM_DE_TestClassUtilityHelper.OP_DE_LEAFLET_CAMPAIGN,'test')[0];
            objPromo.EUR_CRM_Active_Start_Date__c = Date.newInstance(2014, 07,02); 
            insert objPromo;
            EUR_CRM_OP_Customer_Taxonomy_Mapping__c accountCustTax= new EUR_CRM_OP_Customer_Taxonomy_Mapping__c();
            accountCustTax.EUR_CRM_Customer_Taxonomy__c = EUR_CRM_DE_TestClassUtilityHelper.customerTaxonomy1.id;
            accountCustTax.EUR_CRM_ObjPromo__c = objPromo.id;
            insert accountCustTax;


            List<EUR_CRM_ObjPromo_Target__c> targets = new List<EUR_CRM_ObjPromo_Target__c>();
            EUR_CRM_ObjPromo_Target__c leafletTarget = EUR_CRM_DE_TestClassUtilityHelper.createOPTarget(1, 'Objective Volume Target', objPromo.Id, null)[0];
            leafletTarget.EUR_CRM_BQS__c = EUR_CRM_DE_TestClassUtilityHelper.bqs.id;
            leafletTarget.EUR_CRM_BQS__r  = EUR_CRM_DE_TestClassUtilityHelper.bqs; 
            insert leafletTarget;

            EUR_CRM_Account__c testAccount = EUR_CRM_DE_TestClassUtilityHelper.offTradeAccount1;
            EUR_CRM_Visit__c accountVisit = new EUR_CRM_Visit__c();
            accountVisit.EUR_CRM_Account__c = testAccount.id;
            accountVisit.RecordTypeId = [select id from RecordType where sobjecttype='EUR_CRM_Visit__c' and developername = 'EUR_DE_Off_Trade_Visit'].id;
            accountVisit.EUR_CRM_Visit_Data_Capture_EndDateTime__c =  date.today();
            accountVisit.EUR_CRM_Visit_Data_Capture_StartDateTime__c=   date.today();
            accountVisit.EUR_CRM_End_Datetime__c=  date.today();
            accountVisit.EUR_CRM_Start_Datetime__c=  date.today();
            insert accountVisit;
            EUR_CRM_ObjPromo_Account_Mapping__c opAccountMap = new EUR_CRM_ObjPromo_Account_Mapping__c();
            opAccountMap.EUR_CRM_Account__c = testAccount.id;
            opAccountMap.EUR_CRM_Is_Active__c = true;
            opAccountMap.EUR_CRM_ObjPromo__c = objPromo.id;
            opAccountMap.RecordTypeId = [select id from RecordType where sobjecttype='EUR_CRM_ObjPromo_Account_Mapping__c' and developername = 'EUR_CRM_DE_O_P_Account_Mapping'].id;
            insert opAccountMap;
            Test.startTest();
            //-- test leaflet
            EUR_CRM_Visit_Action__c visitAction = new EUR_CRM_Visit_Action__c();
            visitAction.EUR_CRM_Account__c = testAccount.id;  
            visitAction.EUR_CRM_Status__c = 'Yes';  
            visitAction.EUR_CRM_Brand_Quality_Size__c = EUR_CRM_DE_TestClassUtilityHelper.bqs.id;  
            visitAction.EUR_CRM_OP_Action__c = opaction1.id;  
            visitAction.EUR_CRM_ObjPromo__c= objPromo.id;  
            visitAction.EUR_CRM_Visit_ID__c = accountVisit.id;  
            visitAction.EUR_CRM_ObjPromo_Target__c = leafletTarget.id;
             visitAction.RecordTypeId = [select id from RecordType where sobjecttype='EUR_CRM_Visit_Action__c' and developername = 'EUR_DE_OFF_Leaflet_Campaign_Agree_To_Buy'].id;
           
            insert visitAction;
            
            EUR_CRM_Visit_Action__c visitAction2 = new EUR_CRM_Visit_Action__c();
            visitAction2.EUR_CRM_Account__c = testAccount.id;  
            visitAction2.EUR_CRM_Status__c = 'Yes';  
            visitAction2.EUR_CRM_Brand_Quality_Size__c = EUR_CRM_DE_TestClassUtilityHelper.bqs.id;  
            visitAction2.EUR_CRM_OP_Action__c = opaction1.id;  
            visitAction2.EUR_CRM_ObjPromo__c= objPromo.id;  
            visitAction2.EUR_CRM_Visit_ID__c = accountVisit.id;  
            visitAction2.EUR_CRM_ObjPromo_Target__c = leafletTarget.id;
            visitAction2.RecordTypeId = [select id from RecordType where sobjecttype='EUR_CRM_Visit_Action__c' and developername = 'EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty'].id;
           
            insert visitAction2;
            
            Test.stopTest();
        }
    }
}