objects/EUR_CRM_Apex_Configuration__c.object
<CustomObject>
    <description>Configuration (Master Data) container for EMEA Solution
- Running Number (AO, KE, Sys Admins)</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <description>Country Code (ALL, GB, DE, SK, FI, LT, RU)</description>
        <inlineHelpText>ALL, AO, AT, DE, FI, GB,  JB, LT, LV, KE, SK, RU</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Module__c</fullName>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Prefix__c</fullName>
        <description>For Running - Auto Number Creation.</description>
        <label>Prefix</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Running_Number_Length__c</fullName>
        <label>Running Number Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Running_Number__c</fullName>
        <label>Running Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Configuration (EU)</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Apex Configuration (EU) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Configurations (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_CRM_Running_Number</fullName>
        <active>true</active>
        <description>For Running Number Records that can be used my multiple affiliates</description>
        <label>Running Number</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EUR_CRM_Sales_Order__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Sales Orders (EU) (Account)</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>RIGHT(LEFT( RecordType.DeveloperName , 6) , 2)</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_TeleSales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TeleSales Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order (EU)</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(
BEGINS(UserRole.DeveloperName, &apos;EUR_&apos;),
 RIGHT(LEFT(UserRole.DeveloperName, 6), 2) , TEXT(EUR_CRM_Affiliate_Code_Picklist__c) )</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Telesales_Agent__c</fullName>
        <label>Telesales Agent</label>
        <relationshipName>Telesales_Agent</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_ZA_AssignTeleSalesAgentTest.cls
@isTest
public with sharing class EUR_CRM_ZA_AssignTeleSalesAgentTest {
	
	public static EUR_CRM_Account__c euaccount = new EUR_CRM_Account__c();
	public static EUR_CRM_Sales_Order__c salesOrder = new EUR_CRM_Sales_Order__c();

	public static User eurSysUser;
	public static User eurSysUser2;
	public static User eurSysUser3;
    public static void setUser(){
        //Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR ZA Standard On Trade User']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser = new User(Alias = 'standt', Email='userEmail1234aoke@test.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke@test.com');
        insert eurSysUser;

    }
    public static void setUser2(){
        //Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR ZA Standard On Trade User']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser2 = new User(Alias = 'standt2', Email='userEmail1234aoke2@test.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke2@test.com');
        insert eurSysUser2;

    }
    
    public static void setUser3(){
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        //Profile p = [SELECT Id FROM Profile WHERE Name ='EUR ZA Standard On Trade User']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser3 = new User(Alias = 'standt3', Email='userEmail1234aoke3@test.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke3@test.com');
        insert eurSysUser3;

    }
    
    public static void dataInsert1(){
    	
    	euaccount = EUR_CRM_ZA_TestClassHelper.createEUAccount(1,'Test EU ACCOUNT', 'EUR_ZA_On_Trade_Indirect').get(0);
        insert euaccount;
        system.assertNotEquals(euaccount, null);
               
    }
    
    public static void dataInsert2(){
    	
    	euaccount = EUR_CRM_ZA_TestClassHelper.createEUAccount(1,'Test EU ACCOUNT', 'EUR_ZA_On_Trade_Indirect').get(0);
        insert euaccount;
        system.assertNotEquals(euaccount, null);
               
        salesOrder = EUR_CRM_ZA_TestClassHelper.createSalesOrder(1,euaccount).get(0);
    	insert salesOrder;
    	system.assertNotEquals(salesOrder, null);
    }
    
    static testMethod void test1(){
        setUser();
        setUser2();
        eurSysUser2.EUR_CRM_Telesales_Agent__c = eurSysUser.Id;
        update eurSysUser2;
        setUser3();
        System.runAs(eurSysUser3){
        	EUR_CRM_Apex_Configuration__c configApex = new EUR_CRM_Apex_Configuration__c();
	        configApex.EUR_CRM_Module__c = 'EUR_CRM_Running_Number';
	        configApex.EUR_CRM_Prefix__c = 'ZA-SO-';
	        configApex.EUR_CRM_Running_Number_Length__c = 10;
	        configApex.EUR_CRM_Running_Number__c = 0;
	        configApex.EUR_CRM_Country_Code__c = 'ZA';
	        insert configApex;	
        	
        }
        System.runAs(eurSysUser2){
            Test.startTest();
            dataInsert1();
            
			salesOrder = EUR_CRM_ZA_TestClassHelper.createSalesOrder(1,euaccount).get(0);
        	insert salesOrder;
        	system.assertNotEquals(salesOrder, null);
           	
            Test.stopTest();

        }
    }
    
    static testMethod void test2(){
        setUser();
        setUser2();
        eurSysUser2.EUR_CRM_Telesales_Agent__c = eurSysUser.Id;
        update eurSysUser2;
        setUser3();
        System.runAs(eurSysUser3){
        	EUR_CRM_Apex_Configuration__c configApex = new EUR_CRM_Apex_Configuration__c();
	        configApex.EUR_CRM_Module__c = 'EUR_CRM_Running_Number';
	        configApex.EUR_CRM_Prefix__c = 'ZA-SO-';
	        configApex.EUR_CRM_Running_Number_Length__c = 10;
	        configApex.EUR_CRM_Running_Number__c = 0;
	        configApex.EUR_CRM_Country_Code__c = 'ZA';
	        insert configApex;	
        	
        }
        System.runAs(eurSysUser2){
        	Test.startTest();           
            dataInsert2();	
            Test.stopTest();	
        }
        
        System.runAs(eurSysUser3){
        	eurSysUser2.EUR_CRM_Telesales_Agent__c = null;
        	update eurSysUser2;
        }
    }
}