objects/EUR_CRM_Brand__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Contributive_Margin_Brand__c</fullName>
        <label>Contributive Margin / Brand</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <label>Brand (EU)</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mktg_Package_Mechanic_Handling__c</fullName>
        <description>Picklist to determine how Marketing Package is handled as contract line item (deviates from typical per Brand-Quality contract line item association).

For the following affiliate/s:
1. GB</description>
        <label>Marketing Package Mechanic Handling</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                    <default>true</default>
                    <label>Lump Sum</label>
                </value>
                <value>
                    <fullName>Per Brand-Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Activity_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Lumpsum_Value__c</fullName>
        <label>Lumpsum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mktg_Package_Mechanic_Handling__c</fullName>
        <label>Marketing Package Mechanic Handling</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Per Brand-Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Activity Item (EU)</label>
    <nameField>
        <displayFormat>CA - {0000000000}</displayFormat>
        <label>Contract Activity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Activity Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Amount__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand_Quality_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality-Size (EU)</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Quality</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>Contract_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Activity_Item__c</fullName>
        <label>Contract Activity Item</label>
        <referenceTo>EUR_CRM_Contract_Activity_Item__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <description>Country code of the contract</description>
        <formula>EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Contract__r.EUR_CRM_Country_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Marketing_Amount__c</fullName>
        <label>Marketing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU (EU)</label>
        <referenceTo>EUR_CRM_SKU__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Product Item (EU)</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Contract Product Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Grouping_Name__c</fullName>
        <label>Grouping Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Has_Lump_Sum__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Lump Sum</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Has_Per_BQ__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Per BQ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Process_Type__c</fullName>
        <formula>IF( AND(EUR_CRM_Has_Lump_Sum__c = TRUE, EUR_CRM_Has_Per_BQ__c = FALSE, EUR_CRM_Lump_Sum_Or_Per_BQ__c =FALSE), 
 &apos;LUMP_SUM_ONLY&apos;,  
 IF( AND(EUR_CRM_Has_Per_BQ__c = TRUE, EUR_CRM_Has_Lump_Sum__c = FALSE, EUR_CRM_Lump_Sum_Or_Per_BQ__c = FALSE), 
  &apos;PER_BQ_ONLY&apos;, 
   IF( EUR_CRM_Lump_Sum_Or_Per_BQ__c = TRUE, 
     &apos;LUMP_SUM_OR_PER_BQ&apos;, 
      IF(AND(EUR_CRM_Has_Lump_Sum__c = TRUE, EUR_CRM_Has_Per_BQ__c = TRUE), 
        &apos;BOTH&apos;, 
        null) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mechanic Process Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type_Name_English__c</fullName>
        <label>Mechanic Type Name - English</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Mechanic Type (EU)</label>
    <nameField>
        <label>Mechanic Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic Type (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated to Brand object for product heirarchy</description>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Qualities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contributive_Margin_BQ__c</fullName>
        <label>Contributive Margin / BQ</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;PRT&quot;), &quot;PRT&quot;, RIGHT(LEFT(RecordType.DeveloperName,6),2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU (EU)</label>
        <referenceTo>EUR_CRM_SKU__c</referenceTo>
        <relationshipLabel>Brand-Quality (EU)</relationshipLabel>
        <relationshipName>Brand_Quality_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Size__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>EUR_CRM_Brand_Quality_Size</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <formula>EUR_CRM_Brand_Quality__r.EUR_CRM_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contributive_Margin_BQS__c</fullName>
        <label>Contributive Margin / BQS</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Brand-Quality-Size (EU)</label>
    <nameField>
        <label>Brand Quality Size</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality-Size (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_SKU__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand_Quality_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality-Size</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipName>SKUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contributive_Margin_SKU__c</fullName>
        <label>Contributive Margin / SKU</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SKU (EU)</label>
    <nameField>
        <label>Product SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_FI_ProfitCalculatorExt.cls
public with sharing class EUR_CRM_FI_ProfitCalculatorExt {

    public final String LUMP_SUM = 'Lump Sum';
    public final String EDUCATION = 'Education';

    public EUR_CRM_Contract__c contractObj{get; set;}

    private ApexPages.StandardController standardController {get;set;}
    private Id contractId {
        get{if (this.standardController!=null){
                return this.standardController.getId();                                 
        }   
        return null;
    }}

    public EUR_CRM_ContractClass contractClassObject {get; private set;}

    public Map<Id,EUR_CRM_Mechanic_Type__c> mechanicTypeMap = new Map<Id,EUR_CRM_Mechanic_Type__c>();

    public Map<String,  List<EUR_CRM_Contract_Product_Item__c>> contractActivityItemsMap {get;set;}

    //public List<ProfitCalculatorWrapper> profCalculatorWrapList {get;set;}

    public List<ProfitCalculatorWrapper2> profCalculatorWrapList2 {get;set;}
    public String thousandSep {get;set;}
    public String decimalSep {get;set;}
    public EUR_CRM_FI_ProfitCalculatorExt(ApexPages.StandardController standardController){
        this.standardController = standardController;
        
        contractObj = (EUR_CRM_Contract__c )standardController.getRecord();

        //Init Contract
        contractClassObject = new EUR_CRM_ContractClass(contractId);

        //Init MechanicTypeMap
        retrieveMechanicTypes();

        //Init Wrapper
        buildProfitCalculatorWrapper(contractId);
        Decimal value = 1000.10;
        String formattedValue = value.format();
        thousandSep = formattedValue.substring(1,2);
        decimalSep = formattedValue.substring(5,6); 

        
    }

    public void buildProfitCalculatorWrapper(Id contractId){
        contractActivityItemsMap = new Map<String,  List<EUR_CRM_Contract_Product_Item__c>>();
        //profCalculatorWrapList = new List<ProfitCalculatorWrapper>();
        profCalculatorWrapList2 = new List<ProfitCalculatorWrapper2>();
        Map<Id,  List<EUR_CRM_Contract_Product_Item__c>> contractActivityItems = new Map<Id,  List<EUR_CRM_Contract_Product_Item__c>>();

        contractActivityItems = EUR_CRM_FI_UtilClass.retrieveContractProductLineItems(contractId);

        System.debug('FLAG - ITEMS: '+contractActivityItems);

        /*

        system.debug('FLAG - NEW MAP ITEMS: '+contractActivityItemsMap);*/


        /*for(String key : contractActivityItems.keyset()){
            System.debug('&&KEY: '+key);
            for(EUR_CRM_Contract_Product_Item__c productItem: contractActivityItems.get(key)){
                profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(productItem, mechanicTypeMap, false, null));
            }
        }

        for(EUR_CRM_Contract_Activity_Item__c contractActivity : [SELECT Id, EUR_CRM_Mechanic_Type__r.Name, EUR_CRM_Lumpsum_Value__c, EUR_CRM_Mktg_Package_Mechanic_Handling__c FROM EUR_CRM_Contract_Activity_Item__c WHERE EUR_CRM_Contract__c = :contractId]){
            if(contractActivity.EUR_CRM_Mktg_Package_Mechanic_Handling__c == LUMP_SUM){
                profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(null, null, true, contractActivity));
            }
        }*/
        
        //for(EUR_CRM_Contract_Activity_Item__c key : [SELECT Id, EUR_CRM_Mechanic_Type__c, EUR_CRM_Mechanic_Type__r.Name, EUR_CRM_Lumpsum_Value__c, EUR_CRM_Mktg_Package_Mechanic_Handling__c FROM EUR_CRM_Contract_Activity_Item__c WHERE EUR_CRM_Contract__c = :contractId ORDER BY EUR_CRM_Mechanic_Type__r.EUR_CRM_Display_Order__c]){
        for(EUR_CRM_Contract_Activity_Item__c key : [SELECT Id, EUR_CRM_Mechanic_Type__c, EUR_CRM_Mechanic_Type__r.Name, EUR_CRM_Lumpsum_Value__c, EUR_CRM_Mktg_Package_Mechanic_Handling__c FROM EUR_CRM_Contract_Activity_Item__c WHERE EUR_CRM_Contract__c = :contractId AND EUR_CRM_Mechanic_Type__r.Name <> :EDUCATION ORDER BY EUR_CRM_Mechanic_Type__r.EUR_CRM_Display_Order__c]){
            System.debug('&&KEY: '+key.Id);
            System.debug('&&KEY2: '+contractActivityItems.containskey(key.EUR_CRM_Mechanic_Type__c));
            if(contractActivityItems.containskey(key.EUR_CRM_Mechanic_Type__c)){
                for(EUR_CRM_Contract_Product_Item__c productItem: contractActivityItems.get(key.EUR_CRM_Mechanic_Type__c)){
                    profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(productItem, mechanicTypeMap, false, null, false));
                }
                if(key.EUR_CRM_Lumpsum_Value__c != null && key.EUR_CRM_Lumpsum_Value__c != 0){
                    profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(null, null, true, key, true));
                    //profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(productItem, mechanicTypeMap, true, key, true));
                }
            } else {
                //if(key.EUR_CRM_Mktg_Package_Mechanic_Handling__c == LUMP_SUM){
                    profCalculatorWrapList2.add(new ProfitCalculatorWrapper2(null, null, true, key, false));
                //}
            }
        }
        
    }

    private void retrieveMechanicTypes(){
        mechanicTypeMap = new  Map<Id, EUR_CRM_Mechanic_Type__c>();        
        for (EUR_CRM_Mechanic_Type__c mechanic: [SELECT Id, Name, EUR_CRM_Grouping_Name__c, 
                                                EUR_CRM_Mechanic_Process_Type__c, EUR_CRM_Country_Code__c, 
                                                EUR_CRM_Has_Lump_Sum__c, EUR_CRM_Has_Per_BQ__c,
                                                EUR_CRM_Mechanic_Type_Name_English__c
                                                FROM EUR_CRM_Mechanic_Type__c
                                                WHERE EUR_CRM_Country_Code__c =: contractClassObject.contractDetails.EUR_CRM_Country_Code__c
                                             
                                                LIMIT 49999]){
            mechanicTypeMap.put(mechanic.Id, mechanic);
        }
        
        System.debug('Flag - Retrieve mechanicTypeMap:' + mechanicTypeMap); 
    } 

    public class ProfitCalculatorWrapper2{

        public final String POURING_REFUND_SPIRITS = 'Pouring Refund Spirits';
        public final String POURING_REFUND_WINES = 'Pouring Refund Wines';
        public final String SELECTION_BRANDS_SPIRITS = 'Selection Brands Spirits';
        public final String SELECTION_BRANDS_WINES = 'Selection Brands Wines';
        public final String MARKETING_ACTIVITY_SPIRITS= 'Marketing Activity Spirits';
        public final String MARKETING_ACTIVITY_WINES = 'Marketing Activity Wines';
        public final String TRIPS = 'Trips';
        public final String EDUCATION = 'Education';
        public final String FREE_STOCK = 'Free stock';
        public final Set<String> MARKETING_GROUP_NAME = new Set<String>{MARKETING_ACTIVITY_SPIRITS,MARKETING_ACTIVITY_WINES,TRIPS,EDUCATION,FREE_STOCK};
        public final String LUMP_SUM = 'Lump Sum';
        public final String BOTH_LUMP_SUM = 'Amount inputted as Lump sum';


        public String sourceName {get;set;}
        public String itemName {get;set;}
        public Decimal volBottles {get;set;}
        public Decimal cMargin {get;set;}
        public Decimal totalVolperCMargin {get;set;}
        public Decimal retroBottles {get;set;}
        public Decimal totalRetroperCMargin {get;set;}
        public Decimal totalCM {get;set;}
        public Decimal lumpSum {get;set;}
        public Decimal totalCMByRow {get;set;}

        public ProfitCalculatorWrapper2(EUR_CRM_Contract_Product_Item__c productItem, Map<Id, EUR_CRM_Mechanic_Type__c> mechanicTypeMap, Boolean isLumpSum, EUR_CRM_Contract_Activity_Item__c contractActivity, Boolean isBothLumpSum){
                    

            if(isLumpSum != true){
                sourceName = productItem.EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Mechanic_Type__r.Name;
                if(sourceName == POURING_REFUND_SPIRITS){
                    itemName = productItem.EUR_CRM_Brand_Quality_Size__r.Name;
                    if(productItem.EUR_CRM_Brand_Quality_Size__r.EUR_CRM_Contributive_Margin_BQS__c != null){
                        cMargin = productItem.EUR_CRM_Brand_Quality_Size__r.EUR_CRM_Contributive_Margin_BQS__c;
                    }
                }
                if(sourceName == POURING_REFUND_WINES){
                    itemName = productItem.EUR_CRM_SKU__r.Name;
                    if(productItem.EUR_CRM_SKU__r.EUR_CRM_Contributive_Margin_SKU__c != null){
                        cMargin = productItem.EUR_CRM_SKU__r.EUR_CRM_Contributive_Margin_SKU__c;
                    }
                }
                if(sourceName == SELECTION_BRANDS_SPIRITS){
                    itemName = productItem.EUR_CRM_Brand_Quality_Size__r.Name;
                    if(productItem.EUR_CRM_Brand_Quality_Size__r.EUR_CRM_Contributive_Margin_BQS__c != null){
                        cMargin = productItem.EUR_CRM_Brand_Quality_Size__r.EUR_CRM_Contributive_Margin_BQS__c;
                    }
                }
                if(sourceName == SELECTION_BRANDS_WINES){
                    itemName = productItem.EUR_CRM_Brand__r.Name;
                    if(productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c != null){
                        cMargin = productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c;
                    }
                }
                if(sourceName == MARKETING_ACTIVITY_SPIRITS){
                    /*itemName = productItem.EUR_CRM_Brand_Quality__r.Name;
                    if(productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c != null){
                        cMargin = productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c;
                    }*/
                    itemName = productItem.EUR_CRM_Brand__r.Name;
                    if(productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c != null){
                        cMargin = productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c;
                    }
                }
                if(sourceName == MARKETING_ACTIVITY_WINES){
                    /*itemName = productItem.EUR_CRM_Brand_Quality__r.Name;
                    if(productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c != null){
                        cMargin = productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c;
                    }*/
                    itemName = productItem.EUR_CRM_Brand__r.Name;
                    if(productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c != null){
                        cMargin = productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c;
                    }
                }
                if(sourceName == TRIPS){
                    itemName = productItem.EUR_CRM_Brand__r.Name;
                    if(productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c != null){
                        cMargin = productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c;
                    }
                }
                if(sourceName == EDUCATION){
                    itemName = productItem.EUR_CRM_Brand__r.Name;
                    if(productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c != null){
                        cMargin = productItem.EUR_CRM_Brand__r.EUR_CRM_Contributive_Margin_Brand__c;
                    }
                }
                if(sourceName == FREE_STOCK){
                    itemName = productItem.EUR_CRM_Brand_Quality__r.Name;
                    if(productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c != null){
                        cMargin = productItem.EUR_CRM_Brand_Quality__r.EUR_CRM_Contributive_Margin_BQ__c;
                    }
                }

                if(cMargin != null){
                    //cMargin = cMargin.setScale(2);
                    if(!MARKETING_GROUP_NAME.contains(sourceName)){
                        cMargin = cMargin.setScale(2);
                    } else{cMargin = null;}
                }

                if(productItem.EUR_CRM_Quantity__c == 0){
                    volBottles = null;
                } else{volBottles = productItem.EUR_CRM_Quantity__c;}

                if(cMargin != null && volBottles != null){
                    totalVolperCMargin = volBottles * cMargin;
                    totalVolperCMargin = totalVolperCMargin.setScale(2);
                }
                //aug 07 2015 - 
                //if(productItem.EUR_CRM_Amount__c != 0){
                    retroBottles = productItem.EUR_CRM_Amount__c;
                    if(MARKETING_GROUP_NAME.contains(sourceName)){
                        retroBottles = null;
                    }
                //} else{retroBottles = null;}

                /*if(cMargin != null && retroBottles != null){
                    totalRetroperCMargin = cMargin - retroBottles;
                    totalRetroperCMargin = totalRetroperCMargin.setScale(2);
                }*/  
                
                /*if(retroBottles != null){
                    if(cMargin == null){
                        totalRetroperCMargin = 0 - retroBottles;
                    } else{
                        totalRetroperCMargin = cMargin - retroBottles;
                    }
                    totalRetroperCMargin = totalRetroperCMargin.setScale(2);
                }*/

                if(cMargin == null && retroBottles == null){
                    
                } else{
                    Decimal cMarginTemp = 0;
                    Decimal retroBottlesTemp = 0;

                    if(retroBottles != null){
                        retroBottlesTemp = retroBottles;
                    }
                    if(cMargin != null){
                        cMarginTemp = cMargin;
                    }
                    totalRetroperCMargin = cMarginTemp - retroBottlesTemp;
                    totalRetroperCMargin = totalRetroperCMargin.setScale(2);
                }

                

                if(totalRetroperCMargin != null && volBottles != null){
                    totalCM = totalRetroperCMargin * volBottles;
                    totalCM = totalCM.setScale(2);
                } 

                /*if(productItem.EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Lumpsum_Value__c != null){
                    lumpSum = productItem.EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Lumpsum_Value__c;
                } else{*/
                    if(MARKETING_GROUP_NAME.contains(sourceName)){
                        //if(productItem.EUR_CRM_Amount__c != 0){lumpSum = productItem.EUR_CRM_Amount__c;}
                        if(productItem.EUR_CRM_Marketing_Amount__c != 0){lumpSum = productItem.EUR_CRM_Marketing_Amount__c;}
                    }
                //}

                /*if(productItem.EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Lumpsum_Value__c != null){
                    lumpSum = productItem.EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Lumpsum_Value__c;
                } else{
                    if(MARKETING_GROUP_NAME.contains(sourceName)){
                        //if(productItem.EUR_CRM_Amount__c != 0){lumpSum = productItem.EUR_CRM_Amount__c;}
                        if(productItem.EUR_CRM_Marketing_Amount__c != 0){lumpSum = productItem.EUR_CRM_Marketing_Amount__c;}
                    }
                }*/
            } else{
                sourceName = contractActivity.EUR_CRM_Mechanic_Type__r.Name;
                lumpSum = contractActivity.EUR_CRM_Lumpsum_Value__c;
                //itemName = LUMP_SUM;
                if(isBothLumpSum == false){
                    itemName = LUMP_SUM;
                } else{
                    itemName = BOTH_LUMP_SUM;
                }
                
            }

            

            if(lumpsum == null && totalCM != null){
                totalCMByRow = totalCM;
            }
            if(lumpsum != null && totalCM == null){
                totalCMByRow = 0 - lumpsum;
            }
            if(lumpsum == null && totalCM == null){
                totalCMByRow = 0;
            }
        }
    }

    /*public class ProfitCalculatorWrapper{

        public String key {get;set;}
        public List<EUR_CRM_Contract_Product_Item__c> productItems {get;set;}

        public ProfitCalculatorWrapper(String key, List<EUR_CRM_Contract_Product_Item__c> productItems){
            this.key = key;
            this.productItems = productItems;

            
        }
    }*/

   
}