objects/EUR_CRM_Apex_Configuration__c.object
<CustomObject>
    <description>Configuration (Master Data) container for EMEA Solution
- Running Number (AO, KE, Sys Admins)</description>
    <label>Apex Configuration (EU)</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Apex Configuration (EU) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Configurations (EU)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Active_End_Date__c</fullName>
        <label>Active End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Evaluation_Period_End_Date__c</fullName>
        <label>Evaluation Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_RU_ON_Trade_Phase_1</fullName>
        <active>true</active>
        <label>RU ON Trade Phase 1</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>O_P_Account_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Evaluation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypass flag for Mobile app, so it doesn&apos;t need to create Visit Actions against that Promotion for that Account</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Account Mapping (EU)</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>O/P - Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Account Mapping (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DK_OP_Account_Mapping</fullName>
        <active>true</active>
        <label>DK O/P - Account Mapping</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_RU_O_P_Account_Mapping</fullName>
        <active>true</active>
        <label>RU O/P - Account Mapping</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_OP_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Sell</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>O/P Action (EU)</label>
    <nameField>
        <label>O/P Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Action_List_Template__c.object
<CustomObject>
    <description>EUR CRM - This object will contain the actions that the SR needs to do on the Mobile App for the Object or Promotional Campaign</description>
    <label>O/P Action List Template (EU)</label>
    <nameField>
        <label>O/P Action List Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action List Template (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective / Promotion</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-sell</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Action Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Qty Confirmed</fullName>
                </value>
                <value>
                    <fullName>Qty Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Did Not Present</fullName>
                </value>
                <value>
                    <fullName>Participating</fullName>
                </value>
                <value>
                    <fullName>Not Participating</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Unsuccessful</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Successful</fullName>
                </value>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Not Installed</fullName>
                </value>
                <value>
                    <fullName>Tag Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Tag Not Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Actualized</fullName>
                </value>
                <value>
                    <fullName>Not Actualized</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Placed Products</fullName>
                </value>
                <value>
                    <fullName>Did Not Place Products</fullName>
                </value>
                <value>
                    <fullName>Staff Informed</fullName>
                </value>
                <value>
                    <fullName>Staff Not Informed</fullName>
                </value>
                <value>
                    <fullName>Suitable</fullName>
                </value>
                <value>
                    <fullName>Not Suitable</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Not Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit Action (EU)</label>
    <nameField>
        <displayFormat>VACT-{0000000000}</displayFormat>
        <label>Visit Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Action (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_MassUpdateOPAcctMapEndTest.cls
@isTest
private class EUR_CRM_MassUpdateOPAcctMapEndTest {

    static testmethod void test() {
    	EUR_CRM_Account__c euaccount = new EUR_CRM_Account__c();
		EUR_CRM_Apex_Configuration__c apexConfig = new EUR_CRM_Apex_Configuration__c();
        // The query used by the batch job.
        String query = 'Select Id, EUR_CRM_Is_Active__c, EUR_CRM_Evaluation_Required__c, EUR_CRM_Account__c,' + 
                 ' EUR_CRM_ObjPromo__c FROM EUR_CRM_ObjPromo_Account_Mapping__c WHERE'+
                 ' Recordtype.DeveloperName = :validRecordTypes AND EUR_CRM_Is_Active__c = FALSE';
       	
       	apexConfig = EUR_CRM_RU_TestClassHelper.createApexConfig();
		insert apexConfig;
		
       	euaccount = EUR_CRM_RU_TestClassHelper.createEUAccount('Test EU ACCOUNT');
       	insert euaccount;
       	
       	EUR_CRM_OP_Action_List_Template__c template = EUR_CRM_RU_TestClassHelper.createActionListTemplate();
       	insert template;
       	// Create Promo
       	List<EUR_CRM_ObjPromo__c> promos = EUR_CRM_RU_TestClassHelper.createObjPromo(20,'EUR_RU_ON_Trade_Phase_1','Test Promo',template);
       	List<EUR_CRM_ObjPromo__c> promosToInsert = new List<EUR_CRM_ObjPromo__c>();
       	List<EUR_CRM_ObjPromo__c> promosToUpdate = new List<EUR_CRM_ObjPromo__c>();
       	for(EUR_CRM_ObjPromo__c p: promos){
       		p.EUR_CRM_Status__c='Draft';
       		promosToInsert.add(p);
       	}
       	insert promosToInsert;
       	for(EUR_CRM_ObjPromo__c p :promosToInsert){
   			p.EUR_CRM_Active_End_Date__c = Date.today()-1; 
       		p.EUR_CRM_Status__c='Active';
       		p.EUR_CRM_Evaluation_Period_End_Date__c = Date.today()-1;
       		promosToUpdate.add(p);
       	}
       	update promosToUpdate;
       
		List<EUR_CRM_ObjPromo_Account_Mapping__c>  opMapping = 	EUR_CRM_RU_TestClassHelper.createOPAccountMapping(10,'EUR_RU_O_P_Account_Mapping',euaccount,promos[0]);
		List<EUR_CRM_ObjPromo_Account_Mapping__c>  opMapping2 = EUR_CRM_RU_TestClassHelper.createOPAccountMapping(1,'EUR_DK_OP_Account_Mapping',euaccount,promos[0]);
       	List<EUR_CRM_ObjPromo_Account_Mapping__c> opMappingToInsert = new List<EUR_CRM_ObjPromo_Account_Mapping__c>();
       	for(EUR_CRM_ObjPromo_Account_Mapping__c m: opMapping){
       		m.EUR_CRM_Is_Active__c = true;
       		m.EUR_CRM_Evaluation_Required__c = false;
       		opMappingToInsert.add(m);
       	}
        opMappingToInsert.addAll(opMapping2);
       	insert opMappingToInsert;
       	
       	EUR_CRM_ObjPromo_Action__c objPromoAction = EUR_CRM_RU_TestClassHelper.createObjPromoAction();
       	objPromoAction.EUR_CRM_OP_Action_List_Template__c = template.Id;
       	insert objPromoAction;
       	
       	EUR_CRM_Visit_Action__c visitAction = EUR_CRM_RU_TestClassHelper.createVisitAction(euaccount,promos[0]);
       	visitAction.EUR_CRM_Stage__c = 'Execution';
       	visitAction.EUR_CRM_Status__c ='Participating';
       	insert visitAction;
       	
       	Test.startTest();
       	EUR_CRM_MassUpdateOPAcctMapEnd c = new EUR_CRM_MassUpdateOPAcctMapEnd();
       	Database.executeBatch(c);
       	Test.stopTest();

    }
}