objects/EUR_CRM_Visit_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Is_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Successful?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Action Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Qty Confirmed</fullName>
                </value>
                <value>
                    <fullName>Qty Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Did Not Present</fullName>
                </value>
                <value>
                    <fullName>Participating</fullName>
                </value>
                <value>
                    <fullName>Not Participating</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Unsuccessful</fullName>
                </value>
                <value>
                    <fullName>Evaluation: Successful</fullName>
                </value>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Not Installed</fullName>
                </value>
                <value>
                    <fullName>Tag Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Tag Not Placed Correctly</fullName>
                </value>
                <value>
                    <fullName>Actualized</fullName>
                </value>
                <value>
                    <fullName>Not Actualized</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Placed Products</fullName>
                </value>
                <value>
                    <fullName>Did Not Place Products</fullName>
                </value>
                <value>
                    <fullName>Staff Informed</fullName>
                </value>
                <value>
                    <fullName>Staff Not Informed</fullName>
                </value>
                <value>
                    <fullName>Suitable</fullName>
                </value>
                <value>
                    <fullName>Not Suitable</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Not Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit Action (EU)</label>
    <nameField>
        <displayFormat>VACT-{0000000000}</displayFormat>
        <label>Visit Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Action (EU)</pluralLabel>
    <recordTypes>
        <fullName>DE_OFF_Ad_hoc_Agree_To_Buy</fullName>
        <active>true</active>
        <label>DE OFF Ad hoc Agreement To Buy</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Do_TMKT_Doc</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Do TMKT Doc</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Present_Theme</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Present Theme</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Carton</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Carton</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Gondelkopf</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Gondelkopf</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Promo_Display</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Promo Display</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Razz_Fazz</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Razz Fazz</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Standard</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_2nd_PL_Sell_In_Qty_Theme</fullName>
        <active>true</active>
        <label>DE OFF 2nd Placement Sell In Qty - Theme</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Ad_Hoc_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Ad Hoc Sell In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Dist_Drive_Listing_Check</fullName>
        <active>true</active>
        <label>DE OFF Dist Drive Listing Check</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Leaflet_Campaign_Agree_To_Buy</fullName>
        <active>true</active>
        <description>Not In Use as of Phase 2 Wave 1 (Jan 26 2016)</description>
        <label>DE OFF Leaflet Campaign Agreement To Buy</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Leaflet Campaign Sell In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Sales_Drive_SKU_Bottles_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Sales Drive SKU Bottles Sell-In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Sales_Drive_SKU_Displays_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Sales Drive SKU Displays Sell-In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Sales_Drive_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Sales Drive Sell-In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Tasting_Discussion</fullName>
        <active>true</active>
        <label>DE OFF Tasting Discussion</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Tasting_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Tasting Sell In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_OFF_Trade_Fair_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE OFF Trade Fair Sell In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_ON_TMKT_Promo_Confirm_Participation</fullName>
        <active>true</active>
        <label>DE ON TMKT Promo Confirm Participation</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_ON_TMKT_Promo_Enter_Sell_In_Qty</fullName>
        <active>true</active>
        <label>DE ON TMKT Promo Enter Sell In Qty</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_DE_ON_TMKT_Promo_Presentation</fullName>
        <active>true</active>
        <label>DE ON TMKT Promo Presentation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_DE_IsSucccessfulHandler.cls
/**

Functions: 

(($RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Do_TMKT_Doc' || 
$RecordType.DeveloperName == 'DE_OFF_Ad_hoc_Agree_To_Buy' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_Tasting_Discussion'|| 
$RecordType.DeveloperName == 'EUR_DE_OFF_Leaflet_Campaign_Agree_To_Buy' ) 
&& ISPICKVAL(EUR_CRM_Status__c,'Yes')) || 
(($RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Carton' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Theme'|| 
$RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Promo_Display'|| 
$RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Gondelkopf'|| 
$RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Razz_Fazz' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Standard' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_Ad_Hoc_Sell_In_Qty' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty'|| 
$RecordType.DeveloperName == 'EUR_DE_OFF_Sales_Drive_Sell_In_Qty' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_Tasting_Sell_In_Qty' || 
$RecordType.DeveloperName == 'EUR_DE_OFF_Trade_Fair_Sell_In_Qty' || 
$RecordType.DeveloperName == 'EUR_DE_ON_TMKT_Promo_Enter_Sell_In_Qty') 
&& ISPICKVAL(EUR_CRM_Status__c,'Qty Confirmed')) || 
(($RecordType.DeveloperName == 'EUR_DE_OFF_Dist_Drive_Listing_Check' ) 
&& ISPICKVAL(EUR_CRM_Status__c,'Listed')) || 
(($RecordType.DeveloperName == 'EUR_DE_OFF_2nd_PL_Present_Theme' || 
$RecordType.DeveloperName == 'EUR_DE_ON_TMKT_Promo_Presentation' ) 
&& ISPICKVAL(EUR_CRM_Status__c,'Presented')) || 
(($RecordType.DeveloperName == 'EUR_DE_ON_TMKT_Promo_Confirm_Participation' ) 
&& ISPICKVAL(EUR_CRM_Status__c,'Participating'))

Is Successful?

EUR_CRM_Is_Successful__c

*/
public class EUR_CRM_DE_IsSucccessfulHandler  extends EUR_CRM_TriggerAbstract {

    public EUR_CRM_DE_IsSucccessfulHandler(){
        super('EUR_CRM_DE_VisitActionHandler');
    }
    private Set<String> YES_RecordTypes  = new Set<String>{
        'EUR_DE_OFF_2nd_PL_Do_TMKT_Doc',
        'DE_OFF_Ad_hoc_Agree_To_Buy',
        'EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty',
        'EUR_DE_OFF_Tasting_Discussion' 
    };
    private Set<String> LISTED_RecordTypes  = new Set<String>{
        'EUR_DE_OFF_Dist_Drive_Listing_Check'     
    };
    private Set<String> PARTICIPATING_RecordTypes  = new Set<String>{
        'EUR_DE_ON_TMKT_Promo_Confirm_Participation' 
    };
    private Set<String> PRESENTED_RecordTypes  = new Set<String>{
        'EUR_DE_ON_TMKT_Promo_Presentation'
    };
    private Set<String> QTY_CONFIRMED_RecordTypes  = new Set<String>{
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Carton',   
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Gondelkopf',
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Promo_Display',
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Razz_Fazz',
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Standard',
        'EUR_DE_OFF_2nd_PL_Sell_In_Qty_Theme',
        'EUR_DE_OFF_Ad_Hoc_Sell_In_Qty',
        'EUR_DE_OFF_Leaflet_Campaign_Sell_In_Qty',
        'EUR_DE_OFF_Sales_Drive_SKU_Bottles_Sell_In_Qty',  
        'EUR_DE_OFF_Sales_Drive_SKU_Displays_Sell_In_Qty',
        'EUR_DE_OFF_Sales_Drive_Sell_In_Qty', 
        'EUR_DE_OFF_Tasting_Sell_In_Qty',  
        'EUR_DE_OFF_Trade_Fair_Sell_In_Qty',
        'EUR_DE_ON_TMKT_Promo_Enter_Sell_In_Qty', 
        'EUR_DE_OFF_2nd_PL_Present_Theme' 
   };
    
    private final String LISTED = 'Listed';
    private final String PARTICIPATING = 'Participating';
    private final String PRESENTED = 'Presented';
    private final String YES = 'Yes';
    private final String QTY_CONFIRMED = 'Qty Confirmed'; 
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap){
        List<Recordtype> visitActionRecordTypes = Global_RecordTypeCache.getRtList('EUR_CRM_Visit_Action__c');
        Map<Id,Recordtype> visitActionRecordTypesMap = new Map<Id,Recordtype>();        
        
        for(Recordtype rt : visitActionRecordTypes ){
           visitActionRecordTypesMap.put(rt.id,rt);
        } 
        
        for(EUR_CRM_Visit_Action__c visitAction: (List<EUR_CRM_Visit_Action__c>) sObjList){
            String recordTypeName = visitActionRecordTypesMap.get(visitAction.recordtypeid).developername;
            
           // if(Trigger.isInsert || 
           //   (Trigger.IsUpdate && 
           //      visitAction.EUR_CRM_Status__c != ((EUR_CRM_Visit_Action__c) oldMap.get(visitAction.id)).EUR_CRM_Status__c)){          
           
                if(YES_RecordTypes.contains(recordTypeName) && visitAction.EUR_CRM_Status__c == YES){
                    visitAction.EUR_CRM_Is_Successful__c = true;
                }else  if(PRESENTED_RecordTypes.contains(recordTypeName) && visitAction.EUR_CRM_Status__c == PRESENTED ){
                    visitAction.EUR_CRM_Is_Successful__c = true;
                }else  if(LISTED_RecordTypes.contains(recordTypeName) && visitAction.EUR_CRM_Status__c == LISTED ){
                    visitAction.EUR_CRM_Is_Successful__c = true;
                }else  if(QTY_CONFIRMED_RecordTypes.contains(recordTypeName) && visitAction.EUR_CRM_Status__c == QTY_CONFIRMED ){
                    visitAction.EUR_CRM_Is_Successful__c = true;
                }else  if(PARTICIPATING_RecordTypes.contains(recordTypeName) && visitAction.EUR_CRM_Status__c == PARTICIPATING ){
                    visitAction.EUR_CRM_Is_Successful__c = true;
                }else{
                     visitAction.EUR_CRM_Is_Successful__c = false;
                }
          //  }
        }
    }

}