objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DK_Off_Trade_EM_Price_Promotion</fullName>
        <active>true</active>
        <label>DK Off Trade EM Price Promotion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Action_List_Template__c.object
<CustomObject>
    <description>EUR CRM - This object will contain the actions that the SR needs to do on the Mobile App for the Object or Promotional Campaign</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>O/P Action List Template (EU)</label>
    <nameField>
        <label>O/P Action List Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action List Template (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_ObjectivePromoHandler.cls
public with sharing class EUR_CRM_ObjectivePromoHandler extends EUR_CRM_TriggerAbstract {

    public EUR_CRM_ObjectivePromoHandler() {
        super('EUR_CRM_ObjectivePromoHandler');
    }
    
    private final static Map<String, String> opActionMap = EUR_CRM_RecordTypeHelper.ObjectivePromoHandler_opActionMap;
    private final static Set<String> emPricePromotionRecordTypes = new Set<String> {
        'EUR_DK_Off_Trade_EM_Price_Promotion'
    };
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap){
         Map<Id,RecordType> recordTypes = new Map<Id,RecordType>();
         Set<Id> recordTypesId = new Set<Id>();
         Set<String> externalIds = new Set<String>();

         for(EUR_CRM_ObjPromo__c promo : (List<EUR_CRM_ObjPromo__c>)sObjList){
             recordTypesId.add(promo.recordTypeId);
         }
         
         if(recordTypesId.size() > 0) {
             for(RecordType rt : [select id, developername from RecordType where id in:recordTypesId]){
                 recordTypes.put(rt.id,rt);
                 if(opActionMap.get(rt.developername) != null) {
                     externalIds.add(opActionMap.get(rt.developername));                     
                 }
             }
         }
         
         Map<String,id> actionListTemplateMap = new Map<String,id>();
         
         if(externalIds.size() > 0) {
             for(EUR_CRM_OP_Action_List_Template__c actionListTemplate: [select id,EUR_CRM_External_ID__c from EUR_CRM_OP_Action_List_Template__c where EUR_CRM_External_ID__c in: externalIds]){
                 actionListTemplateMap.put(actionListTemplate.EUR_CRM_External_ID__c , actionListTemplate.id);
             }             
         }
        
         for(EUR_CRM_ObjPromo__c promo : (List<EUR_CRM_ObjPromo__c>)sObjList){         
             String recordTypeDevName = recordTypes.get(promo.recordTypeId).developername;
                        
             if(opActionMap.keySet().contains(recordTypeDevName)){
                 String key = opActionMap.get(recordTypeDevName);
                 if(key != null && actionListTemplateMap.get(key) != null){
                     promo.EUR_CRM_OP_Action_List_Template__c = actionListTemplateMap.get(key);
                 }else{
                     promo.addError('No Action List Template found for this type of Objective / Promotion');
                 }
                 
                 if(tAction == EUR_CRM_TriggerAbstract.TriggerAction.BEFORE_INSERT && !emPricePromotionRecordTypes.contains(recordTypeDevName)){
                     promo.EUR_CRM_Status__c = 'Draft';
                 }
             }             
         }
    }

}