objects/EUR_CRM_Group_Outlet_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group Outlet Type (EU)</label>
    <nameField>
        <displayFormat>GO-{00000}</displayFormat>
        <label>Group Outlet Type No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Outlet Type (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Image_Level__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Image_Levels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Iconic</fullName>
                </value>
                <value>
                    <fullName>Leading</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Mainstream</fullName>
                    <default>true</default>
                    <label>Mainstream</label>
                </value>
                <value>
                    <fullName>Mainstream Quality</fullName>
                </value>
                <value>
                    <fullName>Mainstream Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Image Level (EU)</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Image Level No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Level (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Outlet_Type__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>EUR_PROS_Outlet_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Outlet Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outlet Type (EU)</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Outlet Type No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Type (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Frequency__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Visit Frequency (EU)</label>
    <nameField>
        <label>Visit Frequency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Frequency (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Frequency_Criteria__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>Visit_Frequency_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Image_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Image Level</label>
        <referenceTo>EUR_CRM_Image_Level__c</referenceTo>
        <relationshipName>Visit_Frequency_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet Type</label>
        <referenceTo>EUR_CRM_Outlet_Type__c</referenceTo>
        <relationshipName>Visit_Frequency_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Frequency__c</fullName>
        <label>Visit Frequency</label>
        <referenceTo>EUR_CRM_Visit_Frequency__c</referenceTo>
        <relationshipName>Visit_Frequency_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Volume_Potential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volume Potential</label>
        <referenceTo>EUR_CRM_Volume_Potential__c</referenceTo>
        <relationshipName>Visit_Frequency_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Frequency Criteria (EU)</label>
    <nameField>
        <displayFormat>VFC-{00000000}</displayFormat>
        <label>Visit Frequency Criteria No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Frequency Criteria (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Volume_Potential__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Volume_Potentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Name__c</fullName>
        <label>Volume Potential Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Volume Potential (EU)</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>Volume Potential No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Potential (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_AccountVisitFrequencyHandlerTest.cls
@isTest
private class EUR_CRM_AccountVisitFrequencyHandlerTest {

    static testMethod void myUnitTest() {
        Id rtId = [select id from recordtype where developername = 'EUR_GB_FS_Indirect' and sobjecttype = 'eur_crm_account__c' limit 1].id;
        EUR_CRM_Group_Outlet_Type__c goutletType = new EUR_CRM_Group_Outlet_Type__c(EUR_CRM_Name__c='Restaurant');
        insert goutletType;
        EUR_CRM_Outlet_Type__c outletType = new EUR_CRM_Outlet_Type__c(EUR_CRM_Name__c='Restaurant', EUR_CRM_Group_Outlet_Type__c=goutletType.Id);
        insert outletType;
        EUR_CRM_Image_Level__c imgLevel = new EUR_CRM_Image_Level__c(EUR_CRM_Name__c='Leading');
        insert imgLevel;
        EUR_CRM_Volume_Potential__c volPotential = new EUR_CRM_Volume_Potential__c(EUR_CRM_Name__c='High');
        insert volPotential;
        EUR_CRM_Visit_Frequency__c visitFreq = new EUR_CRM_Visit_Frequency__c(name='once a week');
        insert visitFreq;
        EUR_CRM_Visit_Frequency_Criteria__c visitCriteria = new EUR_CRM_Visit_Frequency_Criteria__c(EUR_CRM_Visit_Frequency__c=visitFreq.Id, 
            EUR_CRM_Group_Outlet_Type__c=goutletType.Id, EUR_CRM_Outlet_Type__c=outletType.Id, EUR_CRM_Image_Level__c=imgLevel.Id, EUR_CRM_Volume_Potential__c=volPotential.id);
        insert visitCriteria;
        
        EUR_CRM_Account__c acct = new EUR_CRM_Account__c(Name='GB test on trade account');
        acct.EUR_CRM_Group_Outlet_Type__c = goutletType.Id;
        acct.EUR_CRM_Outlet_Type__c = outletType.Id;
        acct.EUR_CRM_Image_Level__c = imgLevel.id;
        acct.EUR_CRM_Volume_Potential__c = volPotential.Id;
        acct.recordtypeid = rtId;
        insert acct;
        
        acct = [Select Id, EUR_CRM_Visit_Frequency__c From EUR_CRM_Account__c Where Id=: acct.Id];
        system.assertEquals(acct.EUR_CRM_Visit_Frequency__c, visitFreq.Id);
    }
}