objects/LAT_Contract2__c.object
<CustomObject>
    <description>This objects represents a contract in LATAM (&apos;16 version)</description>
    <label>Contrato</label>
    <nameField>
        <label>Número do contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_ContractDocs__c.object
<CustomObject>
    <description>Object to customize files to attach to the contract</description>
    <fields>
        <fullName>Body__c</fullName>
        <inlineHelpText>Available tags: [STARTDATE],  [ENDATE] and [CCNEGOCIATED]</inlineHelpText>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>LAT Contract Docs</label>
    <nameField>
        <label>LAT Contract Docs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Contracts Docs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LAT_ContractDocumentsPDFControllerTest.cls
@isTest
private class LAT_ContractDocumentsPDFControllerTest {

	@isTest static void test_method_one() {

		LAT_Contract2__c c = LAT_ContractsWS_Test.getContract();
		insert c;

		LAT_ContractDocs__c lcd = new LAT_ContractDocs__c();
		lcd.name = 'MinutaPadrao';
		lcd.body__c = '[STARTDATE] [ENDATE]';
		insert lcd;


		system.CurrentPageReference().getParameters().put('id',c.id);
		LAT_ContractDocumentsPDFController lpdfc = new LAT_ContractDocumentsPDFController();
	}



}