objects/LAT_ACCOUNT__c.object
<CustomObject>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_MasiveOwnerLine__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MasiveOwnerLines</relationshipLabel>
        <relationshipName>MasiveOwnerLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Header</label>
        <referenceTo>LAT_MasiveOwnerHeader__c</referenceTo>
        <relationshipLabel>MasiveOwnerLines</relationshipLabel>
        <relationshipName>MasiveOwnerLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_NewValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NewValue</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MasiveOwnerLineNewValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MasiveOwnerLine</label>
    <nameField>
        <displayFormat>MOL-{0000}</displayFormat>
        <label>MasiveOwnerLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MasiveOwnerLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Planejamento__c.object
<CustomObject>
    <fields>
        <fullName>Ano_de_Referencia__c</fullName>
        <label>Ano de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                    <label>2014</label>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>M_s_de_Ref_rencia__c</fullName>
        <label>Mês de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Nome do Planejamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamentos de Visitas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <fields>
        <fullName>Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Visitas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planejamento__c</fullName>
        <label>Planejamento</label>
        <referenceTo>Planejamento__c</referenceTo>
        <relationshipLabel>Visitas</relationshipLabel>
        <relationshipName>Visitas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planejada</fullName>
                    <default>true</default>
                    <label>Planejada</label>
                </value>
                <value>
                    <fullName>Encerrada</fullName>
                </value>
                <value>
                    <fullName>Visit not made</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_UpdateVisitasOwner_Batch.cls
global class LAT_UpdateVisitasOwner_Batch implements Database.Batchable<sObject>, Database.Stateful,Database.AllowsCallouts{
		
	String query;
	Map <Id, Id> accountNewOwner = new Map<Id, Id>();
	Set <Id> accounts = new Set <Id>();
	Id newOwner = null;
	
	global LAT_UpdateVisitasOwner_Batch(String headerId) {


		List <LAT_MasiveOwnerLine__c> lines = [Select LAT_Account__c, LAT_NewValue__c From LAT_MasiveOwnerLine__c Where LAT_Header__c = :headerId];
	

		for(LAT_MasiveOwnerLine__c line :lines){
			accounts.add(line.LAT_Account__c);
			accountNewOwner.put(line.LAT_Account__c, line.LAT_NewValue__c);
			newOwner = line.LAT_NewValue__c;
		}

		String status = 'Encerrada';

		query = 'Select Id, Conta__c, Planejamento__c, Planejamento__r.ownerid, Planejamento__r.Ano_de_Referencia__c, Planejamento__r.M_s_de_Ref_rencia__c From Visitas__c where status__c != \'Encerrada\' and Conta__c in :accounts';

	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		List <Visitas__c> visitas = (List<Visitas__c>)scope;
		   		
		Map <String, Planejamento__c> pvpsNewOwner = new Map<String, Planejamento__c>();

		List<Planejamento__c> listaPVP = [select id, ownerid, M_s_de_Ref_rencia__c, Ano_de_Referencia__c from Planejamento__c where ownerid = :newOwner and createddate = Last_N_Months:6];

		for(Planejamento__c plan :listaPVP){
			
			pvpsNewOwner.put(plan.M_s_de_Ref_rencia__c+plan.Ano_de_Referencia__c, plan);
		}

		for (Visitas__c visita : visitas) {
						
			if(!pvpsNewOwner.isEmpty() && pvpsNewOwner.get(visita.Planejamento__r.M_s_de_Ref_rencia__c+visita.Planejamento__r.Ano_de_Referencia__c) != null){
				
				visita.Planejamento__c = pvpsNewOwner.get(visita.Planejamento__r.M_s_de_Ref_rencia__c+visita.Planejamento__r.Ano_de_Referencia__c).id;
			}
		}

		update visitas;
	
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}