objects/LAT_ACCOUNT__c.object
<CustomObject>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_AR_ParentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LAT_AR_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Country__c</fullName>
        <label>País</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_OrderOrigin__c</fullName>
        <label>Origem do pedido</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM</fullName>
                    <default>true</default>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>JDE</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_StageName__c</fullName>
        <label>Stage Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Novo pedido</fullName>
                </value>
                <value>
                    <fullName>Pedido enviado para o JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido cancelado no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido com erro no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido processado no JDE</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento aprobado</fullName>
                </value>
                <value>
                    <fullName>Payment period approval</fullName>
                </value>
                <value>
                    <fullName>Approval rejected</fullName>
                </value>
                <value>
                    <fullName>Approval pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Mobile Order</fullName>
                </value>
                <value>
                    <fullName>Moblie Order Sent To JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido aprobado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <recordTypes>
        <fullName>LAT_MX_OPP_NewOrder</fullName>
        <active>true</active>
        <description>Record Type MX New Order for Mexico</description>
        <label>MX New Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nova_oportunidade</fullName>
        <active>true</active>
        <label>Nova oportunidade</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_2_NewOrder_URU</fullName>
        <active>true</active>
        <label>2 - New Order URU</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_3_HeaderBlocked_ARG</fullName>
        <active>true</active>
        <label>3 - Header Blocked ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_5_OrderBlocked_ARG</fullName>
        <active>true</active>
        <label>5 - Order Blocked ARG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_AR_LATOpportunityBeforeInsert.cls
//LAT_Opportunity__c TRIGGER
/********************************************************************************
* 
* MIGRACION LICENCIAS 
* AUTHOR: ZIMMIC                     DATE: 08/11/2016
*
********************************************************************************/

public with sharing class LAT_AR_LATOpportunityBeforeInsert   {
	
	public static void execute(){
		Set<Id> setOppRt = Global_RecordTypeCache.getRtIdSet('LAT_Opportunity__c',new set<String>{'Nova_oportunidade','OPP_1_NewOrder_ARG','OPP_2_NewOrder_URU','LAT_MX_OPP_NewOrder'});
    
	    list <Id> accIds = new list<Id>();
	    for (LAT_Opportunity__c opp : LAT_OpportunityTriggerHandler.triggerNew) {
	        if(setOppRt.contains(opp.RecordTypeId)){
	            accIds.add(opp.LAT_Account__c);
	        }
	    }
	    
	    if(!accIds.isEmpty()){
	        map <Id, Account> mapAccounts = new map <Id, Account>([SELECT Id, Name, ParentId FROM Account WHERE Id IN: accIds]);
	        for (LAT_Opportunity__c opp : LAT_OpportunityTriggerHandler.triggerNew) {
	            if(opp.LAT_Account__c != null && mapAccounts.containsKey(opp.LAT_Account__c) && opp.RecordTypeId != Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'LAT_MX_OPP_NewOrder')){
	                opp.LAT_AR_ParentAccount__c = mapAccounts.get(opp.LAT_Account__c).ParentId;
	            }
	            if(opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'Nova_oportunidade'))
	                opp.LAT_Country__c = 1;
	            else if(opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_2_NewOrder_URU'))
	                opp.LAT_Country__c = 5;
	            else if(opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_1_NewOrder_ARG'))
	                opp.LAT_Country__c = 6;
	            else if(opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'LAT_MX_OPP_NewOrder'))  
	                opp.LAT_Country__c = 12; 

	            if (opp.LAT_StageName__c == 'Mobile Order') {
	                opp.Name = mapAccounts.get(opp.LAT_Account__c).Name;
	                if (opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_1_NewOrder_ARG') 
	                    || opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_3_HeaderBlocked_ARG')
	                    || opp.RecordTypeId == Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_5_OrderBlocked_ARG')) {
	                    opp.LAT_OrderOrigin__c = 'APP';
	                }
	            }
	        }
	    }
	    
	}

}