objects/LAT_AccountInAction__c.object
<CustomObject>
    <fields>
        <fullName>ClientNotAdhering__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cliente não aderente a Ação</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_PromotionalAction__c</fullName>
        <label>Ação promocional</label>
        <referenceTo>LAT_PromotionalAction__c</referenceTo>
        <relationshipName>LAT_AccountInAction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clientes Ação Promocional</label>
    <nameField>
        <displayFormat>AIA-{0000}</displayFormat>
        <label>Cliente Foco</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes Ação Promocional</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_PromotionalAction__c.object
<CustomObject>
    <label>Ação Promocional</label>
    <nameField>
        <label>Ação Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações Promocionais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_PromotionalActionMessageCon_Test.cls
@isTest
private class LAT_PromotionalActionMessageCon_Test {

	@isTest static void LAT_PromotionalActionMessageController() {

		LAT_PromotionalAction__c ap = LAT_ClientByRegionHandlerTest.createAP();
		LAT_AccountInAction__c aiac = LAT_ClientByRegionHandlerTest.createAccountInAction(ap.id);
		aiac.ClientNotAdhering__c = true;
		update aiac;
		Test.startTest();
			ApexPages.CurrentPage().getparameters().put('id', ap.id);
			ApexPages.StandardController apStandard = new ApexPages.StandardController(ap);

        	LAT_PromotionalActionMessageController cl = new LAT_PromotionalActionMessageController(apStandard);
		Test.stopTest();
	}



}