objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_CloseDate__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_DSMessage1__c</fullName>
        <label>Mensagem 1 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_DSMessage2__c</fullName>
        <label>Mensagem 2 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_NRCustomerOrder__c</fullName>
        <label>Número do pedido do cliente</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_NROrderJDE__c</fullName>
        <externalId>true</externalId>
        <label>Número do pedido do JDE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_StageName__c</fullName>
        <label>Stage Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Novo pedido</fullName>
                </value>
                <value>
                    <fullName>Pedido enviado para o JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido cancelado no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido com erro no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido processado no JDE</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento aprobado</fullName>
                </value>
                <value>
                    <fullName>Payment period approval</fullName>
                </value>
                <value>
                    <fullName>Approval rejected</fullName>
                </value>
                <value>
                    <fullName>Approval pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Mobile Order</fullName>
                </value>
                <value>
                    <fullName>Moblie Order Sent To JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido aprobado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empresa existente</fullName>
                </value>
                <value>
                    <fullName>Nova empresa</fullName>
                </value>
                <value>
                    <fullName>Add-On Business</fullName>
                </value>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>SO - Standard Order</fullName>
                </value>
                <value>
                    <fullName>SV - Free Goods (Sales)</fullName>
                </value>
                <value>
                    <fullName>SF - Border Order</fullName>
                </value>
                <value>
                    <fullName>SD - Post Delivery Billing</fullName>
                </value>
                <value>
                    <fullName>SG - No Charge FC</fullName>
                </value>
                <value>
                    <fullName>SJ - Ofrecidos de Ventas por Acuerdos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Nova_oportunidade</fullName>
        <active>true</active>
        <label>Nova oportunidade</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <formula>LAT_Product__r.LAT_CDUnit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_MX_KAMPromisedDate__c</fullName>
        <label>KAM promised date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>LAT_Product__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <formula>LAT_Product__r.LAT_Sku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Product__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_IsRefactorProduct__c</fullName>
        <description>This field indentifies records that are used in the new product schema with the project Account-Product-Payment object.
Fields with the new schema should be loaded with the value &quot;Y&quot;</description>
        <externalId>true</externalId>
        <label>Is refactor product?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_QTLeadTime__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>LAT Product</label>
    <nameField>
        <label>LAT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Products</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <description>Argentina standard record type</description>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Composição do Preço</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DS_Message1__c</fullName>
        <label>Mensagem 1 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DS_Message2__c</fullName>
        <label>Mensagem 2 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NR_customer_order__c</fullName>
        <label>Número do pedido do cliente</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NR_order_JDE__c</fullName>
        <externalId>true</externalId>
        <label>Número do pedido do JDE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Nova_oportunidade</fullName>
        <active>true</active>
        <businessProcess>Padrão</businessProcess>
        <label>Nova oportunidade</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <businessProcess>Standard_ARG</businessProcess>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CD_unit__c</fullName>
        <formula>PricebookEntry.Product2.CD_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Campo de formatação</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Descricao_do_status__c</fullName>
        <label>Descrição Status</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_MX_KAMPromisedDate__c</fullName>
        <label>KAM promised date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sku__c</fullName>
        <formula>PricebookEntry.Product2.SKU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UOM_AR__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CD_Unit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_id__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_IsRefactorProduct__c</fullName>
        <description>This field indentifies records that are used in the new product schema with the project Account-Product-Payment object.
Fields with the new schema should be loaded with the value &quot;Y&quot;</description>
        <externalId>true</externalId>
        <label>Is refactor product?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QT_lead_time__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <description>Argentina standard record type</description>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UDC__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Id__c</fullName>
        <externalId>true</externalId>
        <label>Internal Id</label>
        <length>46</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>UDC_Tabela</label>
    <nameField>
        <label>Descricao1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC_Tabela</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LAT_BR_AP01_OpportunityLineItem_TEST.cls
/******************************************************************************************
 *   Company:Valuenet    Developers: Romero Nicolas Javier                Date:11/12/2013 *
 ******************************************************************************************/
 /********************************************************************************
* 
* MIGRACION LICENCIAS 
* AUTHOR: ZIMMIC                     DATE: 08/11/2016
*
********************************************************************************/

@isTest(seeAllData=False)
public class LAT_BR_AP01_OpportunityLineItem_TEST{
    
    static testMethod void UnitTest(){
        Utils.setMigrationDoneTest(false);
        Account acc = new Account(Client_code_AN8__c = '100', Name = 'TEST', AccountNumber = '1000', Status__c = 'Novo cadastro', Type = 'Payer', Phone = '11 1111-1111', Notes__c = 'TEST', AddressLine1_AR__c = 'TEST', CNPJ__c = '51987528000137', Corporate_Name__c = 'TEST', Channel__c = 'WS', RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'Off_Trade'));
        insert acc;
        acc.Client_code_AN8__c = '100';
        //update acc;

        Opportunity opp = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='143123', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'Nova_oportunidade'));
        Opportunity opp2 = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='173123', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'Nova_oportunidade'));
        Opportunity opp3 = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='123129', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'Nova_oportunidade'));       
        insert new List<Opportunity>{opp, opp2, opp3};
        
        Product2 prod1 = new Product2(Name = 'TestProd', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '444', QT_lead_time__c = 5, SKU__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'BRA_Standard'));
        Product2 prod2 = new Product2(Name = 'TestProd2', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '443', SKU__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'BRA_Standard'));
        insert new List<Product2>{prod1, prod2};

        Id standardPB =  Test.getStandardPricebookId();
        
        PricebookEntry pbe1 = new PricebookEntry(Product2Id = prod1.Id, UnitPrice = 12, Pricebook2Id = standardPB, IsActive =true, UseStandardPrice = false);
        insert pbe1;
        
        List<OpportunityLineItem> listOli = new List<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem(Remover__c = false,Quantity = 200, UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Faturado - test', Campo_de_formatacao__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
        listOli.add(oli);
        OpportunityLineItem oli2 = new OpportunityLineItem(Remover__c = false, Quantity = 200,UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp2.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Cancelado - test');
        listOli.add(oli2);
        
        insert listOli;
        
      //  LAT_BR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli, new List<OpportunityLineItem>(), new Map<Id,OpportunityLineItem>());
        LAT_BR_AP01_OpportunityLineItem.decodeCompositionPrice(listOli);
        //LAT_BR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli, null, null);

    }

    static testMethod void UnitTest2(){
        
        Utils.setMigrationDoneTest(true);
        Account acc = new Account(Client_code_AN8__c = '100', Name = 'TEST', AccountNumber = '1000', Status__c = 'Novo cadastro', Type = 'Payer', Phone = '11 1111-1111', Notes__c = 'TEST', AddressLine1_AR__c = 'TEST', CNPJ__c = '51987528000137', Corporate_Name__c = 'TEST', Channel__c = 'WS', RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'Off_Trade'));
        insert acc;
        acc.Client_code_AN8__c = '100';
        //update acc;

        LAT_Opportunity__c opp = new LAT_Opportunity__c(LAT_Account__c = acc.Id, LAT_NROrderJDE__c='143123', Name = 'test', LAT_NRCustomerOrder__c = '100', LAT_CloseDate__c = date.today(), LAT_Type__c = 'Replenish', LAT_DSMessage1__c = 'test', LAT_DSMessage2__c = 'test', LAT_StageName__c = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'Nova_oportunidade'));
        LAT_Opportunity__c opp2 = new LAT_Opportunity__c(LAT_Account__c = acc.Id, LAT_NROrderJDE__c='173123', Name = 'test', LAT_NRCustomerOrder__c = '100', LAT_CloseDate__c = date.today(), LAT_Type__c = 'Replenish', LAT_DSMessage1__c = 'test', LAT_DSMessage2__c = 'test', LAT_StageName__c = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'Nova_oportunidade'));
        LAT_Opportunity__c opp3 = new LAT_Opportunity__c(LAT_Account__c = acc.Id, LAT_NROrderJDE__c='123129', Name = 'test', LAT_NRCustomerOrder__c = '100', LAT_CloseDate__c = date.today(), LAT_Type__c = 'Replenish', LAT_DSMessage1__c = 'test', LAT_DSMessage2__c = 'test', LAT_StageName__c = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'Nova_oportunidade'));       
        insert new List<LAT_Opportunity__c>{opp, opp2, opp3};
        
        LAT_Product__c prod1 = new LAT_Product__c(Name = 'TestProd', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '1-444', LAT_IsRefactorProduct__c = 'Y', LAT_QTLeadTime__c = 5, LAT_Sku__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'BRA_Standard'));
        LAT_Product__c prod2 = new LAT_Product__c(Name = 'TestProd2', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '1-443', LAT_IsRefactorProduct__c = 'Y', LAT_Sku__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'BRA_Standard'));
        insert new List<LAT_Product__c>{prod1, prod2};

        
        
        List<LAT_OpportunityLineItem__c> listOli = new List<LAT_OpportunityLineItem__c>();
        LAT_OpportunityLineItem__c oli = new LAT_OpportunityLineItem__c(LAT_Remover__c = false, LAT_Quantity__c = 200, LAT_AR_UOM__c = 'CA', LAT_SkuText__c = '100', LAT_UnitPrice__c = 10, LAT_Opportunity__c = opp.Id, LAT_MX_KAMPromisedDate__c = date.today(), LAT_StatusDescription__c = 'Faturado - test', LAT_FormatField__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
        listOli.add(oli);
        LAT_OpportunityLineItem__c oli2 = new LAT_OpportunityLineItem__c(LAT_Remover__c = false, LAT_Quantity__c = 200,LAT_AR_UOM__c = 'CA', LAT_SkuText__c = '100', LAT_UnitPrice__c = 10, LAT_Opportunity__c = opp2.Id, LAT_MX_KAMPromisedDate__c = date.today(), LAT_StatusDescription__c = 'Cancelado - test');
        listOli.add(oli2);
        LAT_BR_AP01_OpportunityLineItem.decodeCompositionPrice(listOli);

        map<id, LAT_OpportunityLineItem__c> mapOlis = new map<id, LAT_OpportunityLineItem__c>();
        for(LAT_OpportunityLineItem__c oli5:listOli){
            mapOlis.put(oli5.Id,oli5);
        }

        insert listOli;

        LAT_OpportunityLineItem__c oli1 = listOli.get(0);
        oli1.LAT_StatusDescription__c = 'Aprovação Test';
        

        LAT_OpportunityLineItem__c oli3 = listOli.get(1);
        oli3.LAT_StatusDescription__c = 'Faturado Test';

        update new List<LAT_OpportunityLineItem__c> {oli1,oli3};
      //  LAT_BR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli, new List<OpportunityLineItem>(), new Map<Id,OpportunityLineItem>());
        LAT_BR_AP01_OpportunityLineItem.decodeCompositionPrice(listOli);
        //LAT_BR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli, null, null);
    }

    static testMethod void UnitTestB(){
    
       /* UDC__c udc = new UDC__c(
            RecordTypeId = Global_RecordTypeCache.getRtId('UDC__c' + 'Standard_AR'),
            Internal_Id__c = 'CRM-PT'
            /*CodUs__c = 'PT',
            CodProd__c = 'CRM'*/
        /*);
        try{insert udc;} catch(exception e){}*/
        Utils.setMigrationDoneTest(false);
        
        Account acc = new Account(Name = 'TEST',/* Payment_Condition__c = udc.id,*/AccountNumber = '1000', Status__c = 'Novo cadastro', Type = 'Payer', Phone = '11 1111-1111', Notes__c = 'TEST', AddressLine1_AR__c = 'TEST', CNPJ__c = '30641670223', Corporate_Name__c = 'TEST', Channel__c = 'WS', RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'ACC_1_OffTrade_ARG'));
        insert acc;
        acc.Client_code_AN8__c = '100';
        update acc;
        Test.startTest();
        Utils.setMigrationDoneTest(false);
        Opportunity opp = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='123923', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'OPP_1_NewOrder_ARG'));
        Opportunity opp2 = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='128123', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'OPP_1_NewOrder_ARG'));
        Opportunity opp3 = new Opportunity(AccountId = acc.Id, NR_order_JDE__c='123723', Name = 'test', NR_customer_order__c = '100', CloseDate = date.today(), Type = 'Replenish', DS_Message1__c = 'test', DS_Message2__c = 'test', StageName = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('Opportunity' + 'OPP_1_NewOrder_ARG'));       
        insert new List<Opportunity>{opp, opp2, opp3};
        
        Product2 prod1 = new Product2(Name = 'TestProd', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '444', QT_lead_time__c = 5, SKU__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'Standard_AR'));
        Product2 prod2 = new Product2(Name = 'TestProd2', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '443', SKU__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'Standard_AR'));
        insert new List<Product2>{prod1, prod2};

        Id standardPB =  Test.getStandardPricebookId();
        
        PricebookEntry pbe1 = new PricebookEntry(Product2Id = prod1.Id, UnitPrice = 12, Pricebook2Id = standardPB, IsActive =true, UseStandardPrice = false);
        insert pbe1;
        
        List<OpportunityLineItem> listOli = new List<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem(Remover__c = false,Quantity = 200, UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Faturado - test', Campo_de_formatacao__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
        insert oli;
        listOli.add(oli);
        
        OpportunityLineItem oli2 = new OpportunityLineItem(Remover__c = false, Quantity = 200,UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp2.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Cancelado - test'); 
        insert oli2;
        listOli.add(oli2);
        
        OpportunityLineItem oli3 = new OpportunityLineItem(Remover__c = false, Quantity = 200,UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp2.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Back Order');
        //insert oli3;
        //listOli.add(oli3);
        

        update listOli;
        //insert listOli;
        
        LAT_AR_AP01_OpportunityLineItem.validateStatus( listOli, new Map<Id,OpportunityLineItem>());
        LAT_AR_AP01_OpportunityLineItem.existeItemEmBackOrder(listOli);
       // LAT_AR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli,listOli,new Map<Id,OpportunityLineItem>());
       Test.stopTest();
    }

    static testMethod void UnitTest2B(){
        Utils.setMigrationDoneTest(true);
        Account acc = new Account(Name = 'TEST',/* Payment_Condition__c = udc.id,*/AccountNumber = '1000', Status__c = 'Novo cadastro', Type = 'Payer', Phone = '11 1111-1111', Notes__c = 'TEST', AddressLine1_AR__c = 'TEST', CNPJ__c = '30641670223', Corporate_Name__c = 'TEST', Channel__c = 'WS', RecordTypeId = Global_RecordTypeCache.getRtId('Account' + 'ACC_1_OffTrade_ARG'));
        insert acc;
        acc.Client_code_AN8__c = '100';
        update acc;

        Test.startTest();
        Utils.setMigrationDoneTest(true);
        LAT_Opportunity__c opp = new LAT_Opportunity__c(LAT_Account__c = acc.Id, 
            LAT_NROrderJDE__c='123923', 
            Name = 'test', 
            LAT_NRCustomerOrder__c = '100', 
            LAT_CloseDate__c = date.today(), 
            LAT_Type__c = 'Replenish', 
            LAT_DSMessage1__c = 'test', 
            LAT_DSMessage2__c = 'test', 
            LAT_StageName__c = 'Novo pedido', 
            RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_1_NewOrder_ARG'));
        LAT_Opportunity__c opp2 = new LAT_Opportunity__c(LAT_Account__c = acc.Id, LAT_NROrderJDE__c='128123', Name = 'test', LAT_NRCustomerOrder__c = '100', LAT_CloseDate__c = date.today(), LAT_Type__c = 'Replenish', LAT_DSMessage1__c = 'test', LAT_DSMessage2__c = 'test', LAT_StageName__c = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_1_NewOrder_ARG'));
        LAT_Opportunity__c opp3 = new LAT_Opportunity__c(LAT_Account__c = acc.Id, LAT_NROrderJDE__c='123723', Name = 'test', LAT_NRCustomerOrder__c = '100', LAT_CloseDate__c = date.today(), LAT_Type__c = 'Replenish', LAT_DSMessage1__c = 'test', LAT_DSMessage2__c = 'test', LAT_StageName__c = 'Novo pedido', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Opportunity__c' + 'OPP_1_NewOrder_ARG'));       
        insert new List<LAT_Opportunity__c>{opp, opp2, opp3};
        
        LAT_Product__c prod1 = new LAT_Product__c(Name = 'TestProd', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '444', LAT_QTLeadTime__c = 5, LAT_Sku__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'Standard_AR'));
        LAT_Product__c prod2 = new LAT_Product__c(Name = 'TestProd2', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '443', LAT_Sku__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'Standard_AR'));
        insert new List<LAT_Product__c>{prod1, prod2};

        
        List<LAT_OpportunityLineItem__c> listOli = new List<LAT_OpportunityLineItem__c>();
        LAT_OpportunityLineItem__c oli = new LAT_OpportunityLineItem__c(
            LAT_Remover__c = false,LAT_Quantity__c = 200, 
            LAT_AR_UOM__c = 'CA', 
            LAT_SkuText__c = '100',  
            LAT_UnitPrice__c = 10, 
            LAT_Opportunity__c = opp.Id, 
            LAT_MX_KAMPromisedDate__c = date.today(), 
            LAT_StatusDescription__c = 'Faturado - test', 
            LAT_FormatField__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
        insert oli;
        listOli.add(oli);
        LAT_OpportunityLineItem__c oli2 = new LAT_OpportunityLineItem__c(
            LAT_Remover__c = false, 
            LAT_Quantity__c = 200,
            LAT_AR_UOM__c = 'CA', 
            LAT_SkuText__c = '100', 
            LAT_UnitPrice__c = 10, 
            LAT_Opportunity__c = opp2.Id, 
            LAT_MX_KAMPromisedDate__c = date.today(), 
            LAT_StatusDescription__c = 'Cancelado - test');
        insert oli2;
        listOli.add(oli2);
        LAT_OpportunityLineItem__c oli3 = new LAT_OpportunityLineItem__c(
            LAT_Remover__c = false, 
            LAT_Quantity__c = 200,
            LAT_AR_UOM__c = 'CA', 
            LAT_SkuText__c = '100', 
            LAT_UnitPrice__c = 10, 
            LAT_Opportunity__c = opp2.Id, 
            LAT_MX_KAMPromisedDate__c = date.today(), 
            LAT_StatusDescription__c = 'Back Order');
        //insert oli3;
        //listOli.add(oli3);

        update listOli;
        //insert listOli;
        
        LAT_AR_AP01_OpportunityLineItem.validateStatus( listOli, new Map<Id,LAT_OpportunityLineItem__c>());
        LAT_AR_AP01_OpportunityLineItem.existeItemEmBackOrder(listOli);
       // LAT_AR_AP01_OpportunityLineItem.updateStatusOpportunity(listOli,listOli,new Map<Id,OpportunityLineItem>());
       Test.stopTest();
    }
}