objects/LAT_Contract2__c.object
<CustomObject>
    <description>This objects represents a contract in LATAM (&apos;16 version)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nome do cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LAT_Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>Data de término do contrato</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aprovado</fullName>
                </value>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Em Aprovação</fullName>
                </value>
                <value>
                    <fullName>Novo Contrato</fullName>
                    <default>true</default>
                    <label>Novo Contrato</label>
                </value>
                <value>
                    <fullName>Reprovado</fullName>
                </value>
                <value>
                    <fullName>Encerrado</fullName>
                </value>
                <value>
                    <fullName>Distrato Aprovado</fullName>
                </value>
                <value>
                    <fullName>Em Distrato</fullName>
                </value>
                <value>
                    <fullName>Finalizado</fullName>
                    <isActive>false</isActive>
                    <label>Finalizado</label>
                </value>
                <value>
                    <fullName>Prorrogado</fullName>
                    <isActive>false</isActive>
                    <label>Prorrogado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contrato</label>
    <nameField>
        <label>Número do contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_Contract__c.object
<CustomObject>
    <description>New LAT Object for Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT_Contracts</relationshipLabel>
        <relationshipName>LAT_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <formula>StartDate__c +  (ContractTerm__c * 30.4166)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Em elaboração</fullName>
                </value>
                <value>
                    <fullName>Em aprovação</fullName>
                </value>
                <value>
                    <fullName>Aprovado</fullName>
                </value>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Aditado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Em cancelamento</fullName>
                </value>
                <value>
                    <fullName>Finalizado</fullName>
                </value>
                <value>
                    <fullName>Não aprovado</fullName>
                </value>
                <value>
                    <fullName>Contrato Prorrogado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>LAT_Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Ammount__c</fullName>
        <label>Valor</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finality__c</fullName>
        <label>Finalidade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato</fullName>
                </value>
                <value>
                    <fullName>Festas/Eventos</fullName>
                </value>
                <value>
                    <fullName>Tailor Made</fullName>
                </value>
                <value>
                    <fullName>Festa/Eventos</fullName>
                    <isActive>false</isActive>
                    <label>Festa/Eventos</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Contract__c</fullName>
        <label>Número do contrato</label>
        <referenceTo>LAT_Contract2__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>LAT_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentPayment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentPayment</label>
        <referenceTo>LAT_Payment__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>Investimentos_Bonifica_es_e_Pagamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentDateDone__c</fullName>
        <label>Data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <label>Data prevista de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agrupamento de produto</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Pagamento Produto</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LAT_ReferenceProductGrouping__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>LAT_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>C</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Efetivo</label>
                </value>
                <value>
                    <fullName>Em Aprovação</fullName>
                </value>
                <value>
                    <fullName>Erro Integração</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Integrado</label>
                </value>
                <value>
                    <fullName>Pago</fullName>
                    <isActive>false</isActive>
                    <label>Pago</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <default>true</default>
                    <label>Pendente</label>
                </value>
                <value>
                    <fullName>Previsto</fullName>
                    <isActive>false</isActive>
                    <label>Previsto</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Reprovado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Investimentos, Bonificações e Pagamentos</label>
    <nameField>
        <displayFormat>IBP-{0000}</displayFormat>
        <label>ID Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investimentos, Bonificações e Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>LAT_Contract</fullName>
        <active>true</active>
        <label>LAT_Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_Contract_Batch.cls
/*
* LAT_Contract_Batch.
* Author: Martin Prado (martin@zimmic.com)
* Date: 07/28/2017
*/
global class LAT_Contract_Batch implements Database.Batchable<sObject> {

	String query;

	// Constructor
	global LAT_Contract_Batch() {
		String days_out_30 = getSoqlDate(30);
		query = 'SELECT Name, owner.Email, Account__r.Name, (Select Ammount__c,Finality__c,Id,LAT_Contract__c,Name,PaymentDateDone__c,PaymentDate__c,ProductGroup__c,RecordTypeId,Status__c,Type__c, ParentPayment__c FROM LAT_Payments__r), EndDate__c,OwnerId,Status__c FROM LAT_Contract2__c where Status__c = \'ativo\' and  (EndDate__c = TODAY	or EndDate__c = '+days_out_30+')';
	}

	// Start
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('START CONTRACT BATCH');
		return Database.getQueryLocator(query);
	}

	// Execute
	global void execute(Database.BatchableContext BC, List<sObject> scope) {

		List<LAT_Contract2__c> contracts = (List<LAT_Contract2__c>)scope;
		for(LAT_Contract2__c contract : contracts) {
			if(contract.EndDate__c == Date.Today()){
				System.debug(contract.id + 'ENDs TODAY');
				processExpireTodayContract(contract);
			} else {
				System.debug(contract.id + 'ENDs next month');
				processExpireNextMonthContract(contract);
			}

		}
	}

	// Finish process
	global void finish(Database.BatchableContext BC) {
		System.debug('END CONTRACT BATCH');
	}


	/*
	* getSoqlDate
	* Add days to Today and transform to string with valid format
	*/
	private static String getSoqlDate(Integer daysFromNow) {
	    return Datetime.now().addDays(daysFromNow).formatGmt('yyyy-MM-dd');
	}

	/*
	* processExpireTodayContract
	* If the Contract expire today and all the payments are done, we must close the contract, if we have payements unpaid we
	* have to create a task to the contract's owner
	*/
	private static void processExpireTodayContract(LAT_Contract2__c contract) {

		Boolean allPaymentsDone = true;
		for(LAT_Payment__c pay : contract.LAT_Payments__r) {
			if((pay.Status__c != 'E' && pay.Status__c !='C') && pay.ParentPayment__c == null) {
				allPaymentsDone = false;
			}
		}
		System.debug('allPaymentsDone:' +allPaymentsDone);

		// If allPaymentsDone we must close the contract and post on chatter
		if(allPaymentsDone) {
			List<CollaborationGroup> groupC = [SELECT Id,Name From CollaborationGroup WHERE name='Contratos OnTrade'];
			if(groupC.size()>0){
				FeedItem post = new FeedItem();
				post.Body = 'Contrato Número '+contract.Name+' com o cliente '+contract.Account__r.Name+' Encerrado.';
				post.ParentId = groupC[0].Id;
				post.Title = 'Contrato: ' + contract.Name + ' Encerrado';
				insert post;
			}
			contract.status__c = 'Encerrado';
			update contract;
		}
		// If we have unpaid payments, we must generate a task to the owner
		else {
			Integer daysToFinish = 15;
			String[] tdays = LAT_GeneralConfigDao.getValueAsStringArray('CONTRACT_TASK_DAYS', ' ');
			if(tdays != null && tdays.size()>0)daysToFinish = Integer.valueOf(tdays[0]);
			Task notif = LAT_ProcessesTaks.createTask(contract.id, contract.OwnerId, 'Distrato ou Prorrogação',
							'', Global_RecordTypeCache.getRtId('Task'+'LAT_Contract'),
							daysToFinish, 'CT-ExtendOrCancel');
			insert notif;
		}
	}

	/*
	* processExpireNextMonthContract
	* If the contract Expire next month we must to notify the owner if we have some payments != "efeito" we must
	* send an email to the owner to notify
	*/
	private static void processExpireNextMonthContract(LAT_Contract2__c contract) {

		Boolean mustNotify = false;
		for(LAT_Payment__c pay : contract.LAT_Payments__r) {
			if((pay.Status__c != 'E' && pay.Status__c !='C') && pay.ParentPayment__c == null) {
				mustNotify = true;
			}
		}
		System.debug('mustNotify:' +mustNotify);

		String[] mails = new String[]{contract.owner.Email};
		if(mustNotify){
			sendEmailNotification(mails, contract.Name, contract.Account__r.Name , contract.EndDate__c.format() );
		}
	}

	/**
	* sendEmailNotification
	*/
	public static void sendEmailNotification(String[] mailAddress, String contractName, String accountName, String endDate){

  		String html = 'O Contrato '+contractName+' do Cliente '+accountName+' vencerá em '+endDate+'. <br/> Avaliar a necessidade de Prorrogação ou Cancelamento do Contrato. <br/> Obrigado.<br/> Trade';
		String subject = 'Vencimento Contrato '+contractName;
		Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
		email.setToAddresses( mailAddress );
		email.setSaveAsActivity(false);
		email.setHtmlBody(html);
		email.setBccSender(false);
		email.setSubject(subject);
		email.setUseSignature(false);
		Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
	}

}