objects/LAT_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>C</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Efetivo</label>
                </value>
                <value>
                    <fullName>Em Aprovação</fullName>
                </value>
                <value>
                    <fullName>Erro Integração</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Integrado</label>
                </value>
                <value>
                    <fullName>Pago</fullName>
                    <isActive>false</isActive>
                    <label>Pago</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <default>true</default>
                    <label>Pendente</label>
                </value>
                <value>
                    <fullName>Previsto</fullName>
                    <isActive>false</isActive>
                    <label>Previsto</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Reprovado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Investimentos, Bonificações e Pagamentos</label>
    <nameField>
        <displayFormat>IBP-{0000}</displayFormat>
        <label>ID Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investimentos, Bonificações e Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_PaymentBefore.cls
public with sharing class LAT_PaymentBefore {

	public static void validateContractPayments (List <LAT_Payment__c> payments) {
		// Mobile must has this control 
		// for (LAT_Payment__c payment : payments) {
		// 	if ('Pendente' != payment.Status__c && 'Reprovado' != payment.Status__c) {
		// 		payment.addError('Somente pagamentos com Status igual a Pendente ou Reprovado poderão ser excluídos ou alterados');
		// 	}
		// }
	}

}