objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CancelOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_FormatField__c</fullName>
        <label>Composição do Preço</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LAT_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integração</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_StageName__c</fullName>
        <label>Stage Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Novo pedido</fullName>
                </value>
                <value>
                    <fullName>Pedido enviado para o JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido cancelado no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido com erro no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido processado no JDE</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento aprobado</fullName>
                </value>
                <value>
                    <fullName>Payment period approval</fullName>
                </value>
                <value>
                    <fullName>Approval rejected</fullName>
                </value>
                <value>
                    <fullName>Approval pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Mobile Order</fullName>
                </value>
                <value>
                    <fullName>Moblie Order Sent To JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido aprobado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_AR_UOM__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <formula>LAT_Product__r.LAT_CDUnit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_FormatField__c</fullName>
        <label>Campo de formatação</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LAT_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integração</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_MX_KAMPromisedDate__c</fullName>
        <label>KAM promised date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>LAT_Product__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <formula>LAT_Product__r.LAT_Sku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_StatusDescription__c</fullName>
        <label>Descrição Status</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_UnitPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Product__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_QTLeadTime__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>LAT Product</label>
    <nameField>
        <label>LAT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Products</pluralLabel>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <description>Argentina standard record type</description>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Composição do Preço</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Integracao__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integração</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CD_unit__c</fullName>
        <formula>PricebookEntry.Product2.CD_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Campo de formatação</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Descricao_do_status__c</fullName>
        <label>Descrição Status</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integracao__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integração</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_MX_KAMPromisedDate__c</fullName>
        <label>KAM promised date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sku__c</fullName>
        <formula>PricebookEntry.Product2.SKU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UOM_AR__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CD_Unit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_id__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QT_lead_time__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard_AR</fullName>
        <active>true</active>
        <description>Argentina standard record type</description>
        <label>Standard AR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SKU__c.object
<CustomObject>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKU</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_BR_TR_OpportunityTest.cls
/********************************************************************************
*                       
* MIGRACION LICENCIAS 
* AUTHOR: ZIMMIC                     DATE: 08/11/2016
*
********************************************************************************/
@isTest
public class LAT_BR_TR_OpportunityTest {
	
	static testMethod void testOpportunityMention() {
        Utils.setMigrationDoneTest(false);
		// Determins if the notification is sent or not
		LAT_CS007_PushNotifications__c PushNotificationSetting = new LAT_CS007_PushNotifications__c();
		PushNotificationSetting.LAT_isEnabled__c = true;
		insert PushNotificationSetting;

		// This are the status that will send notificatins
        LAT_GeneralConfig__c cfg1 = new LAT_GeneralConfig__c(
        	Name = 'OPP_STAGES_TO_PUSH',
        	LAT_Value__c = 'Totally billed,Partially billed');
        insert cfg1;


        // This are the status that will send a list of items in the push
        LAT_GeneralConfig__c cfg2 = new LAT_GeneralConfig__c(
        	Name = 'OPP_PUSH_STAGE_TO_SHOW_ITEMS',
        	LAT_Value__c = 'Partially billed');
        insert cfg2;

		Account acc = LAT_Account_TestFactory.getAccountOffTradeBraComplete();
		insert acc;

		Opportunity opp = LAT_Opportunity_TestFactory.getCRMOppty(acc.id);
		insert opp;

		Product2 prod1 = new Product2(Name = 'TestProd', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '444', QT_lead_time__c = 5, SKU__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'Standard_AR'));
        Product2 prod2 = new Product2(Name = 'TestProd2', IsActive = true, CD_Unit__c = 'CA', Internal_id__c = '443', SKU__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('Product2' + 'Standard_AR'));
        insert new List<Product2>{prod1, prod2};
        
        PricebookEntry pbe1 = new PricebookEntry(Product2Id = prod1.Id, UnitPrice = 12, Pricebook2Id = Test.getStandardPricebookId(), IsActive =true, UseStandardPrice = false);
        insert pbe1;

        Test.startTest();
	        List<OpportunityLineItem> listOli = new List<OpportunityLineItem>();
	        OpportunityLineItem oli = new OpportunityLineItem(Remover__c = false,Quantity = 200, UOM_AR__c = 'CA', LAT_SkuText__c = '100', PriceBookEntryId = pbe1.Id, UnitPrice = 10, OpportunityId = opp.Id, LAT_MX_KAMPromisedDate__c = date.today(), Descricao_do_status__c = 'Faturado - test', Campo_de_formatacao__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
	        listOli.add(oli);
	       
	        insert listOli;

			opp.StageName = 'Totally billed';
			opp.Integracao__c = true;
			update opp;

			opp.StageName = 'Partially billed';
			opp.Integracao__c = true;
			update opp;
		Test.stopTest();
	}

	static testMethod void testOpportunityMention2() {
		Utils.setMigrationDoneTest(true);
		// Determins if the notification is sent or not
		LAT_CS007_PushNotifications__c PushNotificationSetting = new LAT_CS007_PushNotifications__c();
		PushNotificationSetting.LAT_isEnabled__c = true;
		insert PushNotificationSetting;

		// This are the status that will send notificatins
        LAT_GeneralConfig__c cfg1 = new LAT_GeneralConfig__c(
        	Name = 'OPP_STAGES_TO_PUSH',
        	LAT_Value__c = 'Totally billed,Partially billed');
        insert cfg1;


        // This are the status that will send a list of items in the push
        LAT_GeneralConfig__c cfg2 = new LAT_GeneralConfig__c(
        	Name = 'OPP_PUSH_STAGE_TO_SHOW_ITEMS',
        	LAT_Value__c = 'Partially billed');
        insert cfg2;

		Account acc = LAT_Account_TestFactory.getAccountOffTradeBraComplete();
		insert acc;

		LAT_Opportunity__c opp = LAT_Opportunity_TestFactory.LAT_getCRMOppty(acc.id);
		insert opp;

		LAT_Product__c prod1 = new LAT_Product__c(Name = 'TestProd', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '444', LAT_QTLeadTime__c = 5, LAT_Sku__c = '5666', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'Standard_AR'));
        LAT_Product__c prod2 = new LAT_Product__c(Name = 'TestProd2', LAT_IsActive__c = true, LAT_CDUnit__c = 'CA', LAT_ExternalID__c = '443', LAT_Sku__c = '5667', RecordTypeId = Global_RecordTypeCache.getRtId('LAT_Product__c' + 'Standard_AR'));
        insert new List<LAT_Product__c>{prod1, prod2};
        

        Test.startTest();
	        List<LAT_OpportunityLineItem__c> listOli = new List<LAT_OpportunityLineItem__c>();
	        LAT_OpportunityLineItem__c oli = new LAT_OpportunityLineItem__c(LAT_Product__c = prod1.Id, LAT_Remover__c = false, LAT_Quantity__c = 200, LAT_AR_UOM__c = 'CA', LAT_SkuText__c = '100', LAT_UnitPrice__c = 10, LAT_Opportunity__c = opp.Id, LAT_MX_KAMPromisedDate__c = date.today(), LAT_StatusDescription__c = 'Faturado - test', LAT_FormatField__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74');
	        listOli.add(oli);
	       
	        insert listOli;

			opp.LAT_StageName__c = 'Totally billed';
			opp.LAT_Integration__c = true;
			update opp;
			oli.LAT_Remover__c = true;
			update oli;
			update opp;


			opp.LAT_StageName__c = 'Partially billed';
			opp.LAT_Integration__c = true;
			update opp;
			opp.LAT_CancelOrder__c = true;
			update opp;
		Test.stopTest();
	}
}