objects/LAT_AccountInAction__c.object
<CustomObject>
    <fields>
        <fullName>LAT_ClientByRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Id Cliente por Regional</label>
        <referenceTo>LAT_ClientByRegion__c</referenceTo>
        <relationshipLabel>Clientes Ação Promocional</relationshipLabel>
        <relationshipName>Clientes_Foco</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_PromotionalAction__c</fullName>
        <label>Ação promocional</label>
        <referenceTo>LAT_PromotionalAction__c</referenceTo>
        <relationshipName>LAT_AccountInAction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clientes Ação Promocional</label>
    <nameField>
        <displayFormat>AIA-{0000}</displayFormat>
        <label>Cliente Foco</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes Ação Promocional</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_ClientByRegion__c.object
<CustomObject>
    <fields>
        <fullName>LAT_RegionalSupervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable Regional</label>
        <referenceTo>LAT_RegionalSupervisor__c</referenceTo>
        <relationshipLabel>Clientes por Regional</relationshipLabel>
        <relationshipName>Clientes_por_Regional</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cliente por Regional</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Id Cliente por Regional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes por Regional</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_PromotionalAction__c.object
<CustomObject>
    <label>Ação Promocional</label>
    <nameField>
        <label>Ação Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações Promocionais</pluralLabel>
    <recordTypes>
        <fullName>Iniciada</fullName>
        <active>true</active>
        <label>Iniciada</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_RegionalSupervisor__c.object
<CustomObject>
    <label>Regional-Supervisor</label>
    <nameField>
        <label>Regional POP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supervisores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LAT_PromotionalActionHandlerTest.cls
@isTest
private class LAT_PromotionalActionHandlerTest {

    @isTest static void testBasicMethods() {
        LAT_RegionalSupervisor__c rs = LAT_ClientByRegionHandlerTest.createSupervisor(userInfo.getUserId());
        LAT_PromotionalAction__c ap = LAT_ClientByRegionHandlerTest.createAP();
        LAT_ClientByRegion__c cbrOn = LAT_ClientByRegionHandlerTest.createOnCBR(ap.id);
        LAT_ClientByRegion__c cbrOff = LAT_ClientByRegionHandlerTest.createOffCBR(ap.id);
        LAT_AccountInAction__c aiac = LAT_ClientByRegionHandlerTest.createAccountInAction(ap.id);

        Test.startTest();
        LAT_PromotionalActionHandler pah = new LAT_PromotionalActionHandler();
        LAT_PromotionalActionHandler.initAction(new List<String>{ap.id});
        LAT_PromotionalActionHandler.generateTaskForNewClients(ap.Id);

        LAT_PromotionalActionHandler.sendEmail(new List<String>{'test@test.com'}, ap);




        Test.stopTest();

    }

    @isTest static void testBasicMethodsPower() {
        LAT_RegionalSupervisor__c rs = LAT_ClientByRegionHandlerTest.createSupervisor(userInfo.getUserId());
        LAT_PromotionalAction__c ap = LAT_ClientByRegionHandlerTest.createAP();
        LAT_ClientByRegion__c cbrOn = LAT_ClientByRegionHandlerTest.createOnCBR(ap.id);
        LAT_ClientByRegion__c cbrOff = LAT_ClientByRegionHandlerTest.createOffCBR(ap.id);
        LAT_AccountInAction__c aiac = LAT_ClientByRegionHandlerTest.createAccountInAction(ap.id);

        Test.startTest();
        LAT_PromotionalActionHandler pah = new LAT_PromotionalActionHandler();
        LAT_PromotionalActionHandler.closePromotionalActionTasks(new List<String>{ap.id});
        LAT_PromotionalActionHandler.createPromotionalActionTasks(new List<String>{ap.id});
        //closePromotionalActionTasks(ids);
        //createPromotionalActionTasks(ids);
        Test.stopTest();

    }

    @isTest static void testBasicMethods2() {
        LAT_RegionalSupervisor__c rs = LAT_ClientByRegionHandlerTest.createSupervisor(userInfo.getUserId());
        LAT_PromotionalAction__c ap = LAT_ClientByRegionHandlerTest.createAP();
        LAT_ClientByRegion__c cbrOn = LAT_ClientByRegionHandlerTest.createOnCBR(ap.id);
        LAT_ClientByRegion__c cbrOff = LAT_ClientByRegionHandlerTest.createOffCBR(ap.id);
        LAT_AccountInAction__c aiac = LAT_ClientByRegionHandlerTest.createAccountInAction(ap.id);

        LAT_PromotionalActionHandler.getAmmountOfDays();
        LAT_PromotionalActionHandler.pagarPromotionalActionTasks(ap.id);
        LAT_PromotionalActionHandler.pagarClienteActionTasks(aiac.id);

        List<Task> tList = new List<Task>();
        tList.add(LAT_PromotionalActionHandler.createTask(aiac.id, UserInfo.getUserId(), 'test', 'descript', 'Coletar'));
        tList.add(LAT_PromotionalActionHandler.createTask(aiac.id, UserInfo.getUserId(), 'test', 'descript', 'Iniciada'));
        tList.add(LAT_PromotionalActionHandler.createTask(aiac.id, UserInfo.getUserId(), 'test', 'descript', 'Pagamento'));
        tList.add(LAT_PromotionalActionHandler.createTask(aiac.id, UserInfo.getUserId(), 'test', 'descript', 'Cancelada'));
        LAT_PromotionalActionHandler.closeTasks(tList);

        Test.startTest();
            //LAT_PromotionalActionHandler.sendEmail(new List<String>{'testing@testing.com'}, ap);
            LAT_PromotionalActionHandler.initPromotionalAction(ap.id);
            //LAT_PromotionalActionHandler.finaliceAction(ap.id);
            LAT_PromotionalActionHandler.cancelAction(ap.id);
            LAT_PromotionalActionHandler.sendToApproval(ap.id);
            LAT_PromotionalActionHandler.manageClosingTasks(tList.get(0).id);
        Test.stopTest();

    }

}