objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <description>U: Update
C: Cancel
I: Insert</description>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CloseDate__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_StageName__c</fullName>
        <label>Stage Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Novo pedido</fullName>
                </value>
                <value>
                    <fullName>Pedido enviado para o JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido cancelado no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido com erro no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido processado no JDE</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento aprobado</fullName>
                </value>
                <value>
                    <fullName>Payment period approval</fullName>
                </value>
                <value>
                    <fullName>Approval rejected</fullName>
                </value>
                <value>
                    <fullName>Approval pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Mobile Order</fullName>
                </value>
                <value>
                    <fullName>Moblie Order Sent To JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido aprobado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_AR_SentToApproveDiscount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to Approve Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <formula>LAT_Product__r.LAT_CDUnit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_NROrderLine__c</fullName>
        <label>Número da linha de pedido JDE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>LAT_Product__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <formula>LAT_Product__r.LAT_Sku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_UnitPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Product__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDUnit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_QTLeadTime__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Sku__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>LAT Product</label>
    <nameField>
        <label>LAT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Products</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CD_Action__c</fullName>
        <description>U: Update
C: Cancel
I: Insert</description>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Composição do Preço</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Origem_do_pedido__c</fullName>
        <label>Origem do pedido</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM</fullName>
                    <default>true</default>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>JDE</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <businessProcess>Standard_ARG</businessProcess>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CD_Action__c</fullName>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CD_unit__c</fullName>
        <formula>PricebookEntry.Product2.CD_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código da unidade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_de_formatacao__c</fullName>
        <label>Campo de formatação</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NR_order_line__c</fullName>
        <label>Número da linha de pedido JDE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SenttoApproveDiscount_AR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to Approve Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sku__c</fullName>
        <formula>PricebookEntry.Product2.SKU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cd_line_status__c</fullName>
        <label>Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CD_Unit__c</fullName>
        <label>Código da unidade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_id__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno(Chave)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QT_lead_time__c</fullName>
        <label>Prazo de entrega</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UDC__c.object
<CustomObject>
    <fields>
        <fullName>CodDefUsuario__c</fullName>
        <label>CodDefUsuario</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodProd__c</fullName>
        <description>Código do sistema (Módulo)</description>
        <inlineHelpText>Código do sistema (Módulo)</inlineHelpText>
        <label>CodProd</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodUs__c</fullName>
        <label>CodUs</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Id__c</fullName>
        <externalId>true</externalId>
        <label>Internal Id</label>
        <length>46</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>UDC_Tabela</label>
    <nameField>
        <label>Descricao1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC_Tabela</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WS03_SalesOrderHandlerInterface_AR_TEST.cls
/**********************************************
 Dev: Juan Pablo Cubo Version: 1
**********************************************/
 /********************************************************************************
*
* MIGRACION LICENCIAS
* AUTHOR: ZIMMIC                     DATE: 16/11/2016
*
********************************************************************************/

@isTest(seeAllData=true)
public with sharing class WS03_SalesOrderHandlerInterface_AR_TEST {

    static testMethod void testBrTestCalculations(){
        LAT_BR_PriceCalculation lpc = new LAT_BR_PriceCalculation();
        LAT_BR_PriceCalculation.valueObject test = new LAT_BR_PriceCalculation.valueObject();
        LAT_BR_PriceCalculation.BusinessServiceException_x test2 = new LAT_BR_PriceCalculation.BusinessServiceException_x();
        LAT_BR_PriceCalculation.messageValueObject test3 = new LAT_BR_PriceCalculation.messageValueObject();
        LAT_BR_PriceCalculation.e1MessageList test4 = new LAT_BR_PriceCalculation.e1MessageList();
        LAT_BR_PriceCalculation.errorRecords test5 = new LAT_BR_PriceCalculation.errorRecords();
        LAT_BR_PriceCalculation.e1Message test6 = new LAT_BR_PriceCalculation.e1Message();
        LAT_BR_PriceCalculation.discountAndChargeDetailsOutput test7 = new LAT_BR_PriceCalculation.discountAndChargeDetailsOutput();
        LAT_BR_PriceCalculation.priceCatalogueDetailsOutput test8 = new LAT_BR_PriceCalculation.priceCatalogueDetailsOutput();





        // lpc.BusinessServiceException_x;
        // lpc.messageValueObject;
        // lpc.e1MessageList;
    }

    static testMethod void SalesOrderHandlerInterfaceTest(){

		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		Opportunity opp = null;
		OpportunityLineItem oli = null;
		User usuario = null;
		Product2 produto = null;
		Pricebook2 pricebook = null;
		PricebookEntry pbe = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new Product2();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.IsActive = true;
			produto.CD_Unit__c = 'UN';
			produto.Internal_id__c = '146';
			produto.QT_lead_time__c = 5;
			produto.SKU__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('Product2', 'BRA_Standard');
			insert produto;

			//Recupera o catalogo de preço padrão
			List<Pricebook2> catalogoPreco = [SELECT Id FROM Pricebook2 WHERE IsStandard = true limit 1];

			//Cria um pricebookEntry e adiciona o produto criado no catalogo de preço padrão.
			PricebookEntry entradaCatalogoPreco = new PricebookEntry();
			entradaCatalogoPreco.Pricebook2Id = catalogoPreco[0].Id;
			entradaCatalogoPreco.Product2Id = produto.Id;
			entradaCatalogoPreco.UnitPrice = 1000.00;
			entradaCatalogoPreco.IsActive = true;
			entradaCatalogoPreco.UseStandardPrice = false;
			insert entradaCatalogoPreco;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('Opportunity','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new Opportunity();
			opp.Name = 'Opp TESTE COTA';
			opp.closeDate = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.AccountId = acc.Id;
			opp.StageName = 'Novo Pedido';
			insert opp;

			//Cria um novo produto da oportunidade.
			oli = new OpportunityLineItem();
			oli.PricebookEntryId = entradaCatalogoPreco.Id;
			oli.OpportunityId = opp.Id;
			oli.UnitPrice = 12;
			oli.Quantity = 12;
			oli.Campo_de_formatacao__c = 'Preço Base - Cond. Pagto com ICMS|1|133,33|1933,12|15464,96#Desconto PRB|1|-71,81|-1041,18|-8329,43#Valor NF PRB|1|61,52|891,94|7135,53#Desconto Faseamento|1|0,00|0,00|0,00#Desconto FOB|1|0,00|0,00|0,00#PIS|1|0,00|0,00|0,00#COFINS|1|0,00|0,00|0,00#Valor Mercadoria|1|61,52|891,94|7135,53#IPI|1|0,00|0,00|0,00#Valor Mercadoria + IPI|1|61,52|891,94|7135,53#Substitução Tributaria|1|8,75|126,90|1015,2#Valor Total NF|1|70,27|1018,84|8150,74';
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
            WS03_SalesOrderHandlerInterface_AR.isForCC();
        	System.Test.startTest();
        	Utils.setMigrationDoneTest(false);
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterfaceFuture(lIdOpp);
            LAT_LATOpportunity_CodigoAcaoCancelado.isForCC();
			System.Test.stopTest();
		}
	}
    static testMethod void SalesOrderHandlerInterfaceTestB(){
        Utils.setMigrationDoneTest(true);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		LAT_Opportunity__c opp = null;
		LAT_OpportunityLineItem__c oli = null;
		User usuario = null;
		LAT_Product__c produto = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new LAT_Product__c();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.LAT_IsActive__c = true;
			produto.LAT_CDUnit__c = 'UN';
			produto.LAT_ExternalId__c = '146';
			produto.LAT_QTLeadTime__c = 5;
			produto.LAT_Sku__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('LAT_Product__c', 'BRA_Standard');
			insert produto;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('LAT_Opportunity__c','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new LAT_Opportunity__c();
			opp.Name = 'Opp TESTE COTA';
			opp.LAT_CloseDate__c = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.LAT_Account__c = acc.Id;
			opp.LAT_StageName__c = 'Novo Pedido';
			insert opp;

			//Cria um novo produto da oportunidade.
			oli = new LAT_OpportunityLineItem__c();
			oli.LAT_Product__c = produto.Id;
			oli.LAT_Opportunity__c = opp.Id;
			oli.LAT_UnitPrice__c = 12;
			oli.LAT_Quantity__c = 12;
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			System.Test.startTest();
        	Utils.setMigrationDoneTest(true);
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest2(){
        Utils.setMigrationDoneTest(false);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		Opportunity opp = null;
		OpportunityLineItem oli = null;
		User usuario = null;
		Product2 produto = null;
		Pricebook2 pricebook = null;
		PricebookEntry pbe = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new Product2();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.IsActive = true;
			produto.CD_Unit__c = 'UN';
			produto.Internal_id__c = '146';
			produto.QT_lead_time__c = 5;
			produto.SKU__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('Product2', 'BRA_Standard');
			insert produto;

			//Recupera o catalogo de preço padrão
			List<Pricebook2> catalogoPreco = [SELECT Id FROM Pricebook2 WHERE IsStandard = true limit 1];

			//Cria um pricebookEntry e adiciona o produto criado no catalogo de preço padrão.
			PricebookEntry entradaCatalogoPreco = new PricebookEntry();
			entradaCatalogoPreco.Pricebook2Id = catalogoPreco[0].Id;
			entradaCatalogoPreco.Product2Id = produto.Id;
			entradaCatalogoPreco.UnitPrice = 1000.00;
			entradaCatalogoPreco.IsActive = true;
			entradaCatalogoPreco.UseStandardPrice = false;
			insert entradaCatalogoPreco;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('Opportunity','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new Opportunity();
			opp.Name = 'Opp TESTE COTA';
			opp.closeDate = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.AccountId = acc.Id;
			opp.StageName = 'Novo Pedido';
			insert opp;

			//Cria um novo produto da oportunidade.
			oli = new OpportunityLineItem();
			oli.PricebookEntryId = entradaCatalogoPreco.Id;
			oli.SenttoApproveDiscount_AR__c = true;
			oli.OpportunityId = opp.Id;
			oli.UnitPrice = 12;
			oli.Quantity = 12;
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			System.Test.startTest();
        	Utils.setMigrationDoneTest(false);
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest2B(){

        Utils.setMigrationDoneTest(true);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		LAT_Opportunity__c opp = null;
		LAT_OpportunityLineItem__c oli = null;
		User usuario = null;
		LAT_Product__c produto = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');


		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new LAT_Product__c();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.LAT_IsActive__c = true;
			produto.LAT_CDUnit__c = 'UN';
			produto.LAT_ExternalId__c = '146';
			produto.LAT_QTLeadTime__c = 5;
			produto.LAT_Sku__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('LAT_Product__c', 'BRA_Standard');
			insert produto;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('LAT_Opportunity__c','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new LAT_Opportunity__c();
			opp.Name = 'Opp TESTE COTA';
			opp.LAT_CloseDate__c = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.LAT_Account__c = acc.Id;
			opp.LAT_StageName__c = 'Novo Pedido';
			insert opp;


			//Cria um novo produto da oportunidade.
			oli = new LAT_OpportunityLineItem__c();
			oli.LAT_Product__c = produto.Id;
			oli.LAT_AR_SentToApproveDiscount__c = true;
			oli.LAT_Opportunity__c = opp.Id;
			oli.LAT_UnitPrice__c = 12;
			oli.LAT_Quantity__c = 12;
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			System.Test.startTest();
        	Utils.setMigrationDoneTest(true);
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest3(){

		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		Opportunity opp = null;
		OpportunityLineItem oli = null;
		User usuario = null;
		Product2 produto = null;
		Pricebook2 pricebook = null;
		PricebookEntry pbe = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new Product2();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.IsActive = true;
			produto.CD_Unit__c = 'UN';
			produto.Internal_id__c = '146';
			produto.QT_lead_time__c = 5;
			produto.SKU__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('Product2', 'BRA_Standard');
			insert produto;

			//Recupera o catalogo de preço padrão
			List<Pricebook2> catalogoPreco = [SELECT Id FROM Pricebook2 WHERE IsStandard = true limit 1];

			//Cria um pricebookEntry e adiciona o produto criado no catalogo de preço padrão.
			PricebookEntry entradaCatalogoPreco = new PricebookEntry();
			entradaCatalogoPreco.Pricebook2Id = catalogoPreco[0].Id;
			entradaCatalogoPreco.Product2Id = produto.Id;
			entradaCatalogoPreco.UnitPrice = 1000.00;
			entradaCatalogoPreco.IsActive = true;
			entradaCatalogoPreco.UseStandardPrice = false;
			insert entradaCatalogoPreco;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('Opportunity','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new Opportunity();
			opp.Name = 'Opp TESTE COTA';
			opp.closeDate = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.AccountId = acc.Id;
			opp.StageName = 'Novo Pedido';
			insert opp;

			//Cria um novo produto da oportunidade.
			oli = new OpportunityLineItem();
			oli.PricebookEntryId = entradaCatalogoPreco.Id;
			oli.OpportunityId = opp.Id;
			oli.UnitPrice = 12;
			oli.Quantity = 12;
			oli.CD_Action__c = 'a';
			oli.NR_order_line__c = '1';
			oli.LAT_SkuText__c = '123';
			insert oli;


			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			Test.startTest();
			//Utils.setMigrationDoneTest(false);
			//WS03_SalesOrderHandlerInterface_AR.SalesOrderInterfaceFuture(lIdOpp);
			Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest3B(){

        Utils.setMigrationDoneTest(true);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		LAT_Opportunity__c opp = null;
		LAT_OpportunityLineItem__c oli = null;
		User usuario = null;
		LAT_Product__c produto = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new LAT_Product__c();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.LAT_IsActive__c = true;
			produto.LAT_CDUnit__c = 'UN';
			produto.LAT_ExternalId__c = '146';
			produto.LAT_QTLeadTime__c = 5;
			produto.LAT_Sku__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('LAT_Product__c', 'BRA_Standard');
			insert produto;


			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('LAT_Opportunity__c','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new LAT_Opportunity__c();
			opp.Name = 'Opp TESTE COTA';
			opp.LAT_CloseDate__c = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.LAT_Account__c = acc.Id;
			opp.LAT_StageName__c = 'Novo Pedido';
			insert opp;


			//Cria um novo produto da oportunidade.
			oli = new LAT_OpportunityLineItem__c();
			oli.LAT_Product__c = produto.Id;
			oli.LAT_AR_SentToApproveDiscount__c = true;
			oli.LAT_Opportunity__c = opp.Id;
			oli.LAT_UnitPrice__c = 12;
			oli.LAT_Quantity__c = 12;
			oli.LAT_CDAction__c = 'a';
			oli.LAT_NROrderLine__c = '1';
			oli.LAT_SkuText__c = '123';
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			System.Test.startTest();
			Utils.setMigrationDoneTest(true);
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest4(){
		Utils.setMigrationDoneTest(false);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		Opportunity opp = null;
		OpportunityLineItem oli = null;
		User usuario = null;
		Product2 produto = null;
		Pricebook2 pricebook = null;
		PricebookEntry pbe = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new Product2();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.IsActive = true;
			produto.CD_Unit__c = 'UN';
			produto.Internal_id__c = '146';
			produto.QT_lead_time__c = 5;
			produto.SKU__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('Product2', 'BRA_Standard');
			insert produto;

			//Recupera o catalogo de preço padrão
			List<Pricebook2> catalogoPreco = [SELECT Id FROM Pricebook2 WHERE IsStandard = true limit 1];

			//Cria um pricebookEntry e adiciona o produto criado no catalogo de preço padrão.
			PricebookEntry entradaCatalogoPreco = new PricebookEntry();
			entradaCatalogoPreco.Pricebook2Id = catalogoPreco[0].Id;
			entradaCatalogoPreco.Product2Id = produto.Id;
			entradaCatalogoPreco.UnitPrice = 1000.00;
			entradaCatalogoPreco.IsActive = true;
			entradaCatalogoPreco.UseStandardPrice = false;
			insert entradaCatalogoPreco;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('Opportunity','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new Opportunity();
			opp.Name = 'Opp TESTE COTA';
			opp.closeDate = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.AccountId = acc.Id;
			opp.StageName = 'Mobile Order';
			opp.Type = 'SV - Free Goods (Sales)';
			opp.Origem_do_pedido__c = 'APP';
			insert opp;
			System.Test.startTest();
			//Cria um novo produto da oportunidade.
			oli = new OpportunityLineItem();
			oli.PricebookEntryId = entradaCatalogoPreco.Id;
			oli.OpportunityId = opp.Id;
			oli.UnitPrice = 12;
			oli.Quantity = 12;
			oli.CD_Action__c = 'a';
			oli.NR_order_line__c = '1';
			oli.LAT_SkuText__c = '123';
			oli.cd_line_status__c = '400';
			oli.SenttoApproveDiscount_AR__c = false;


			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');

			Utils.setMigrationDoneTest(false);
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest5(){
		Utils.setMigrationDoneTest(false);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		Opportunity opp = null;
		OpportunityLineItem oli = null;
		User usuario = null;
		Product2 produto = null;
		Pricebook2 pricebook = null;
		PricebookEntry pbe = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new Product2();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.IsActive = true;
			produto.CD_Unit__c = 'UN';
			produto.Internal_id__c = '146';
			produto.QT_lead_time__c = 5;
			produto.SKU__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('Product2', 'BRA_Standard');
			insert produto;

			//Recupera o catalogo de preço padrão
			List<Pricebook2> catalogoPreco = [SELECT Id FROM Pricebook2 WHERE IsStandard = true limit 1];

			//Cria um pricebookEntry e adiciona o produto criado no catalogo de preço padrão.
			PricebookEntry entradaCatalogoPreco = new PricebookEntry();
			entradaCatalogoPreco.Pricebook2Id = catalogoPreco[0].Id;
			entradaCatalogoPreco.Product2Id = produto.Id;
			entradaCatalogoPreco.UnitPrice = 1000.00;
			entradaCatalogoPreco.IsActive = true;
			entradaCatalogoPreco.UseStandardPrice = false;
			insert entradaCatalogoPreco;

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('Opportunity','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new Opportunity();
			opp.Name = 'Opp TESTE COTA';
			opp.closeDate = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.AccountId = acc.Id;
			opp.StageName = 'Mobile Order';
			opp.Origem_do_pedido__c = 'APP';
			insert opp;
			System.Test.startTest();
			//Cria um novo produto da oportunidade.
			oli = new OpportunityLineItem();
			oli.PricebookEntryId = entradaCatalogoPreco.Id;
			oli.OpportunityId = opp.Id;
			oli.UnitPrice = 12;
			oli.Quantity = 12;
			oli.CD_Action__c = 'a';
			oli.NR_order_line__c = '1';
			oli.LAT_SkuText__c = '123';
			oli.SenttoApproveDiscount_AR__c = true;


			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');

			Utils.setMigrationDoneTest(false);
			WS03_SalesOrderHandlerInterface_AR.SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest5B(){

        Utils.setMigrationDoneTest(true);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		LAT_Opportunity__c opp = null;
		LAT_OpportunityLineItem__c oli = null;
		User usuario = null;
		LAT_Product__c produto = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new LAT_Product__c();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.LAT_IsActive__c = true;
			produto.LAT_CDUnit__c = 'UN';
			produto.LAT_ExternalId__c = '146';
			produto.LAT_QTLeadTime__c = 5;
			produto.LAT_Sku__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('LAT_Product__c', 'BRA_Standard');
			insert produto;

			System.Test.startTest();

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('LAT_Opportunity__c','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new LAT_Opportunity__c();
			opp.Name = 'Opp TESTE COTA';
			opp.LAT_CloseDate__c = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.LAT_Account__c = acc.Id;
			opp.LAT_StageName__c = 'Mobile Order';
			opp.LAT_OrderOrigin__c = 'APP';
			insert opp;

			opp.LAT_StageName__c = 'Approved';
			WS03_SalesOrderHandlerInterface_AR.isProcessing = false;
			update opp;

			//Cria um novo produto da oportunidade.
			oli = new LAT_OpportunityLineItem__c();
			oli.LAT_Product__c = produto.Id;
			oli.LAT_AR_SentToApproveDiscount__c = false;
			oli.LAT_Opportunity__c = opp.Id;
			oli.LAT_UnitPrice__c = 12;
			oli.LAT_Quantity__c = 12;
			oli.LAT_CDAction__c = 'a';
			oli.LAT_NROrderLine__c = '1';
			oli.LAT_SkuText__c = '123';
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			Utils.setMigrationDoneTest(true);
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
		}
	}

	static testMethod void SalesOrderHandlerInterfaceTest6B(){

        Utils.setMigrationDoneTest(true);
		//Declaração de variáveis.
		Account acc = null;
		UDC__c regional, bandeira, cidade = null;
		Profile perfil = null;
		LAT_Opportunity__c opp = null;
		LAT_OpportunityLineItem__c oli = null;
		User usuario = null;
		LAT_Product__c produto = null;
		List<RecordType> listRecType = null;
		List<String> developerName = null;
		Map<String, String> mapRecType = null;
		String idAccount = null;
		String idOpportunity = null;
		Id idRecTypeUDC = RecordTypeForTest.getRecType('UDC__c', 'BRA_Standard');

		//Recupera os IDS de tipo de registro.
		idAccount = RecordTypeForTest.getRecType('Account','Off_Trade');

		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

		System.runAs(thisUser){
			//Recupera o ID do perfil desejado.
			usuario = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR');
		}

		System.runAs(usuario){
			//Cria nova UDC.
			regional = new UDC__c();
			regional.CodDefUsuario__c = '4546';
			regional.CodProd__c= '01';
			regional.CodUs__c= '01';
			regional.Internal_Id__c   = '1234';
			regional.RecordTypeId = idRecTypeUDC;
			insert regional;

			//Cria nova UDC.
			bandeira = new UDC__c();
			bandeira.CodDefUsuario__c = '179';
			bandeira.CodProd__c= '01';
			bandeira.CodUs__c= '06';
			bandeira.Internal_Id__c   = '1236';
			bandeira.RecordTypeId = idRecTypeUDC;
			insert bandeira;

			//Cria novo Account.
			acc = new Account();
			acc.OwnerId = usuario.Id;
			acc.Name = 'ProdutosOppVerificaCotaExistenteTeste';
			acc.CNPJ__c = '48843971000120';
			acc.Type = 'Outros';
			acc.RecordTypeId = idAccount;
			acc.Status__c = 'Cliente cadastrado no JDE';
			acc.Agency__c = '000';
			acc.Checking_account__c = '000';
			acc.Current_account__c = '0';
			acc.Corporate_Name__c = 'Teste';
			acc.Channel__c = 'Off Trade';
			//acc.Regional__c = regional.Id;
			acc.Frequency_of_Visits__c = 'Semanal';
			acc.Client_code_AN8__c = '557798';
			acc.Price_Group__c = '1';
			//acc.Customer_Flag__c = bandeira.Id;
			insert acc;

			//produto = [Select Id, Name, Sku__c From Product2 Where Sku__c = '146' AND Qtlimit 1];

			produto = new LAT_Product__c();
			produto.Name = 'Cloud2b - Produto - AtualizarEventoProdutosOportunidade';
			produto.LAT_IsActive__c = true;
			produto.LAT_CDUnit__c = 'UN';
			produto.LAT_ExternalId__c = '146';
			produto.LAT_QTLeadTime__c = 5;
			produto.LAT_Sku__c = '444';
			produto.RecordTypeId = RecordTypeForTest.getRecType('LAT_Product__c', 'BRA_Standard');
			insert produto;

			System.Test.startTest();

			//Recupera os IDS de tipo de registro.
			idOpportunity = RecordTypeForTest.getRecType('LAT_Opportunity__c','OPP_1_NewOrder_ARG');

			//Cria nova oportunidade.
			opp = new LAT_Opportunity__c();
			opp.Name = 'Opp TESTE COTA';
			opp.LAT_CloseDate__c = System.today()+1;
			opp.RecordTypeId = idOpportunity;
			opp.LAT_Account__c = acc.Id;
			opp.LAT_StageName__c = 'Mobile Order';
			opp.LAT_OrderOrigin__c = 'APP';
			insert opp;


			//Cria um novo produto da oportunidade.
			oli = new LAT_OpportunityLineItem__c();
			oli.LAT_Product__c = produto.Id;
			oli.LAT_AR_SentToApproveDiscount__c = true;
			oli.LAT_Opportunity__c = opp.Id;
			oli.LAT_UnitPrice__c = 12;
			oli.LAT_Quantity__c = 12;
			oli.LAT_CDAction__c = 'a';
			oli.LAT_NROrderLine__c = '1';
			oli.LAT_SkuText__c = '123';
			insert oli;

			String lIdOpp = opp.Id;
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterface(lIdOpp);
			WS03_SalesOrderHandlerInterface_AR.getConnectionParameter('Argentina');
			Utils.setMigrationDoneTest(true);
			WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(lIdOpp);
			System.Test.stopTest();
            PriceCalculationInterface.isForCC(); 
		}
	}

}