objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Actuals__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Actuals (€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_DelivAttachments__c</fullName>
        <label>MMPJ_TOPG_DelivAttachments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ForecastBudget__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Forecast Budget (€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjManagAttachments__c</fullName>
        <label>MMPJ_TOPG_ProjManagAttachments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsiQCv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectTopic__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MMPJ_TOPG_ProjectType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product Launch</fullName>
                </value>
                <value>
                    <fullName>Media Campaign</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Off-trade place</fullName>
                </value>
                <value>
                    <fullName>On-trade place</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectType__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Development</fullName>
                </value>
                <value>
                    <fullName>Co-Development</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_ProjectDescriptionPDFCtrl.cls
public with sharing class MMPJ_TOPG_ProjectDescriptionPDFCtrl{
public MMPJ_TOPG_Project__c Project{get;set;}

public  MMPJ_TOPG_ProjectDescriptionPDFCtrl(){
Project=ProjectValues();
}

public MMPJ_TOPG_Project__c  ProjectValues(){
String ProjectId =ApexPages.currentPage().getParameters().get('ProjectId'); 
MMPJ_TOPG_Project__c theProject = [select id,name,MMPJ_TOPG_StartDate__c
                                                ,MMPJ_TOPG_EndDate__c
                                                ,MMPJ_TOPG_ProjectType__c
                                                ,MMPJ_TOPG_ProjectTopic__c
                                                ,MMPJ_TOPG_ForecastBudget__c
                                                ,MMPJ_TOPG_ProjectOwner__c
                                                ,MMPJ_TOPG_Actuals__c
                                                ,MMPJ_TOPG_Description__c
                                                ,MMPJ_TOPG_DelivAttachments__c
                                                ,MMPJ_TOPG_ProjManagAttachments__c
                                  from MMPJ_TOPG_Project__c where id=:ProjectId];
return theProject;
}
}