objects/MMPJ_TOPG_MoMLineItem__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_IsHighlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MMPJ TOPGUN</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RelatedProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MoM Line Item</label>
    <nameField>
        <displayFormat>MOM-LI-{000000}</displayFormat>
        <label>MoM Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MoM Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ExpectedDate__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Expected date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Highlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for the TOP GUN Project</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Rank__c</fullName>
        <description>Sorting the related list on Project</description>
        <label>MMPJ_TOPG_Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP02_RAID.cls
public class MMPJ_TOPG_AP02_RAID {    
    //When a RAID is updated the corresponding lineIem should be updated
    public static void updateMOMLineItem(Map<Id,MMPJ_TOPG_RAID__c> mapLineItemAndRAIDToUpdateLineItem){
         List<MMPJ_TOPG_MoMLineItem__c> listLineItemToUpdate = new List<MMPJ_TOPG_MoMLineItem__c >();
         Set<ID> setRaidIDToDelete = new Set<ID>();
         List<MMPJ_TOPG_MoMLineItem__c> listRelatedLineItem = new List<MMPJ_TOPG_MoMLineItem__c>();
         listRelatedLineItem =  [Select MMPJ_TOPG_When__c , MMPJ_TOPG_IsHighlight__c  , MMPJ_TOPG_Rank__c , MMPJ_TOPG_RelatedProject__c , MMPJ_TOPG_WhoC__c , MMPJ_TOPG_RAID__c , MMPJ_TOPG_WhoU__c 
                                  From  MMPJ_TOPG_MoMLineItem__c 
                                  Where id IN: mapLineItemAndRAIDToUpdateLineItem.KeySet()];
         for(MMPJ_TOPG_MoMLineItem__c  lineItem : listRelatedLineItem ){
             MMPJ_TOPG_RAID__c raid = mapLineItemAndRAIDToUpdateLineItem.get(lineItem.id);
             if (raid != null){      
                 lineItem.MMPJ_TOPG_When__c = raid.MMPJ_TOPG_ExpectedDate__c  ;
                 lineItem.MMPJ_TOPG_IsHighlight__c  = raid.MMPJ_TOPG_Highlight__c     ;
                 lineItem.MMPJ_TOPG_Rank__c = raid.MMPJ_TOPG_Rank__c  ;
                 lineItem.MMPJ_TOPG_RAID__c = raid.MMPJ_TOPG_raid__c  ;                
                 lineItem.MMPJ_TOPG_WhoC__c = raid.MMPJ_TOPG_Contact__c   ;
                 lineItem.MMPJ_TOPG_WhoU__c = raid.MMPJ_TOPG_User__c  ;
                 listLineItemToUpdate.add(lineItem);
             }
             System.debug('??raid: ' + raid);
             //if the raid field of RAID = None and it is related to a project then this raid should be removed
             if (String.ISBLANK(raid.MMPJ_TOPG_raid__c )){   
                 setRaidIDToDelete.add(raid.id);
             }
        }
        
        if(listLineItemToUpdate.size() > 0){
            update(listLineItemToUpdate);
        }
        
        List<MMPJ_TOPG_RAID__c> listRaidToDelete = new List<MMPJ_TOPG_RAID__c>();
        listRaidToDelete = [Select id 
                            From MMPJ_TOPG_RAID__c 
                            Where ID IN:setRaidIDToDelete ];
        if(listRaidToDelete.size() > 0){
            delete(listRaidToDelete);
        } 
    }
}