objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Interaction__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Interaction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical interaction</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MinuteOfMeeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>Minutes_of_Meeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <label>MMPJ_TOPG_RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <label>MMPJ_TOPG_Topic</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Minute of Meeting</label>
    <nameField>
        <displayFormat>MOM-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Minutes of Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minutes of Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MoMLineItem__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_IsHighlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MMPJ TOPGUN</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MinutesofMeeting__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Minute of Meeting</label>
        <referenceTo>MMPJ_TOPG_MinuteOfMeeting__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RelatedProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Topic</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>MoM Line Item</label>
    <nameField>
        <displayFormat>MOM-LI-{000000}</displayFormat>
        <label>MoM Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MoM Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsiQCv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ExpectedDate__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Expected date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project --</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Status__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>On Going</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP01_Task_Test.cls
@isTest
public class MMPJ_TOPG_AP01_Task_Test {
     private static  Datetime myDT = Datetime.now();
     private static String  mailPrefix = myDT.format('ddMMyyyy');
     static testMethod void updateMOMLineItemTest(){
        Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(Username = mailPrefix+'-test@supervisor.com', email = mailPrefix+'-test@supervisor.com', profileID = adminProfile.id, IsActive = true, LastName='Supervisor', Alias='sup', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US'); 
        insert u;
        //create market 
        MMPJ_TOPG_Market__c market = new MMPJ_TOPG_Market__c();
        market.Name='France ID';
        insert market;
        //create brand 
        MMPJ_TOPG_Brand__c brand= new MMPJ_TOPG_brand__c();
        brand.Name='testBrand';
        insert brand;
        
        RecordType rt = [Select id,Name 
                         From RecordType 
                         Where SobjectType='MMPJ_TOPG_MoMLineItem__c' and Name='Line Item Project' Limit 1];
                         
        //insert project 
        MMPJ_TOPG_Project__c project = new MMPJ_TOPG_Project__c();
        project.name = 'testProject';
        project.MMPJ_TOPG_StartDate__c = System.today() - 20;
        project.MMPJ_TOPG_EndDate__c = System.today() + 10;
        project.MMPJ_TOPG_ProjectOwner__c = u.id;  
        insert (project);
        
        //insert meeting 
        MMPJ_TOPG_Meeting__c meeting = new MMPJ_TOPG_Meeting__c();
        meeting.MMPJ_TOPG_Title__c ='meeting';
        meeting.MMPJ_TOPG_StartDate__c =Date.newInstance(2016,11,11);
        meeting.MMPJ_TOPG_EndDate__c =Date.newInstance(2016,11,11);
        meeting.MMPJ_TOPG_Interaction__c = 'Call';
        insert meeting;

        //insert minutes of meeting
        MMPJ_TOPG_MinuteOfMeeting__c minutes = new MMPJ_TOPG_MinuteOfMeeting__c();
        minutes.MMPJ_TOPG_Status__c='Draft';
        minutes.MMPJ_TOPG_Title__c ='Test minutes';
        minutes.MMPJ_TOPG_Topic__c='Test minutes';
        minutes.MMPJ_TOPG_RAID__c='Action';
        minutes.MMPJ_TOPG_Meeting__c = meeting.id;
        insert minutes;      
        
         
        //insert RAID
        MMPJ_TOPG_Raid__c raid = new MMPJ_TOPG_Raid__c ();
        raid.MMPJ_TOPG_Title__c='test Raid';
        raid.MMPJ_TOPG_ExpectedDate__c = System.today();
        raid.MMPJ_TOPG_Status__c = 'Planned';
        raid.MMPJ_TOPG_RAID__c='Action';
        raid.MMPJ_TOPG_Project__c = project.id;
        raid.MMPJ_TOPG_User__c = u.id;
        insert(raid);
         
        MMPJ_TOPG_Raid__c raid1 = new MMPJ_TOPG_Raid__c ();
        raid1.MMPJ_TOPG_Title__c='test Raid';
        raid1.MMPJ_TOPG_ExpectedDate__c = System.today();
        raid1.MMPJ_TOPG_Status__c = 'Planned';
        raid1.MMPJ_TOPG_RAID__c='Action';
        raid1.MMPJ_TOPG_Project__c = project.id;
        raid1.MMPJ_TOPG_User__c = u.id;
        insert(raid1);
         
         //insert mom line item
        MMPJ_TOPG_MoMLineItem__c momItem = new MMPJ_TOPG_MoMLineItem__c();
        momItem.MMPJ_TOPG_Topic__c= 'Topic Mom';
        momItem.RecordTypeId  = rt.id;
        momItem.MMPJ_TOPG_When__c = System.today();
        momItem.MMPJ_TOPG_MinutesofMeeting__c= minutes.id;
        momItem.MMPJ_TOPG_RAID__c='Action';
        momItem.MMPJ_TOPG_IsHighlight__c = true;
        momItem.MMPJ_TOPG_RelatedProject__c=project.id;
        momItem.MMPJ_TOPG_WhoU__c = u.id;
        insert (momItem);  
         
         //insert mom line item
        MMPJ_TOPG_MoMLineItem__c momItem1 = new MMPJ_TOPG_MoMLineItem__c();
        momItem1.MMPJ_TOPG_Topic__c= 'Topic Mom';
        momItem1.RecordTypeId  = rt.id;
        momItem1.MMPJ_TOPG_When__c = System.today();
        momItem1.MMPJ_TOPG_MinutesofMeeting__c= minutes.id;
        momItem1.MMPJ_TOPG_RAID__c='Action';
        momItem1.MMPJ_TOPG_IsHighlight__c = true;
        momItem1.MMPJ_TOPG_RelatedProject__c=project.id;
        momItem1.MMPJ_TOPG_RAID__c = raid1.id;
        momItem1.MMPJ_TOPG_WhoU__c = u.id;
        insert (momItem1);  
         
        MMPJ_TOPG_MoMLineItem__c momItem2 = new MMPJ_TOPG_MoMLineItem__c();
        momItem2.MMPJ_TOPG_Topic__c= 'Topic Mom';
        momItem2.RecordTypeId  = rt.id;
        momItem2.MMPJ_TOPG_When__c = System.today();
        momItem2.MMPJ_TOPG_MinutesofMeeting__c= minutes.id;
        momItem2.MMPJ_TOPG_RAID__c='Action';
        momItem2.MMPJ_TOPG_IsHighlight__c = true;
       // momItem2.MMPJ_TOPG_RAID__c = raid.id;
        momItem2.MMPJ_TOPG_RelatedProject__c=project.id;
        momItem2.MMPJ_TOPG_RAID__c = raid1.id;
        momItem2.MMPJ_TOPG_WhoU__c = u.id;
        insert (momItem2);  
         
        MMPJ_TOPG_MoMLineItem__c momItem3 = new MMPJ_TOPG_MoMLineItem__c();
        momItem3.MMPJ_TOPG_Topic__c= 'Topic Mom';
        momItem3.RecordTypeId  = rt.id;
        momItem3.MMPJ_TOPG_When__c = System.today();
        momItem3.MMPJ_TOPG_MinutesofMeeting__c= minutes.id;
        momItem3.MMPJ_TOPG_RAID__c='Action';
        momItem3.MMPJ_TOPG_IsHighlight__c = false;       
        momItem3.MMPJ_TOPG_RelatedProject__c=project.id;
        momItem3.MMPJ_TOPG_RAID__c = raid1.id;
        momItem3.MMPJ_TOPG_WhoU__c = u.id;
        insert (momItem3);  
         
         //task
         Task Tache = new Task();
            if(raid.MMPJ_TOPG_User__c != null)
                Tache.OwnerId = raid.MMPJ_TOPG_User__c;
            else
            Tache.Whoid= raid.MMPJ_TOPG_Contact__c;
            Tache.Description = raid.MMPJ_TOPG_Description__c;
            Tache.ActivityDate = raid.MMPJ_TOPG_ExpectedDate__c;
            Tache.WhatId = raid.id;
            Tache.Status = raid.MMPJ_TOPG_Status__c;
            Tache.Subject = raid.MMPJ_TOPG_Title__c;
            Tache.MMPJ_TOPG_ProjectRaid__c = true;
            Tache.MMPJ_TOPG_ProjectChanged__c = true;
            insert Tache; 
         
         Task TacheMomItem = new Task();
            if(momItem.MMPJ_TOPG_WhoU__c != null)
                TacheMomItem.OwnerId = momItem.MMPJ_TOPG_WhoU__c;
            else
            TacheMomItem.Whoid=  momItem.MMPJ_TOPG_WhoU__c;
            TacheMomItem.Description = 'Description';
            TacheMomItem.ActivityDate = momItem.MMPJ_TOPG_When__c;
            TacheMomItem.WhatId = momItem.id;
            TacheMomItem.Status = 'Planned';
            TacheMomItem.Subject = 'Title';
            TacheMomItem.MMPJ_TOPG_ProjectRaid__c = true;
            TacheMomItem.MMPJ_TOPG_ProjectChanged__c = true;
            insert TacheMomItem; 
         
        Test.StartTest();       
        List<Task> listTask = new List<Task>();
          List<MMPJ_TOPG_MoMLineItem__c> listMomItems = new List<MMPJ_TOPG_MoMLineItem__c>();
         listMomItems = [Select id
                     From MMPJ_TOPG_MoMLineItem__c where id =: momItem1.id];
         listMomItems[0].MMPJ_TOPG_RAID__c= null;
        listMomItems[0].MMPJ_TOPG_RelatedProject__c = project.id;
          update(listMomItems);
         
         
         listMomItems = [Select id
                     From MMPJ_TOPG_MoMLineItem__c where id =: momItem2.id];
        listMomItems[0].MMPJ_TOPG_RAID__c= raid.id;
        listMomItems[0].MMPJ_TOPG_RelatedProject__c = null;
          update(listMomItems);
         
          listMomItems = [Select id
                     From MMPJ_TOPG_MoMLineItem__c where id =: momItem3.id];
         listMomItems[0].MMPJ_TOPG_RAID__c= raid.id;
         listMomItems[0].MMPJ_TOPG_RelatedProject__c = null;
          update(listMomItems);
         
        listTask = [Select id, WhatId 
                     From Task where WhatId IN (:momItem.id,:raid.id)];
        System.assertequals(listTask.size(), 2);    
        listTask[0].ActivityDate = System.today() + 2;
        //listTask[1].ActivityDate = System.today() + 2;
        MMPJ_TOPG_AP02_MomLineItem.isFirstTime = true;
        MMPJ_TOPG_AP03_Raid.isFirstTime = true;
        Map<Id,Task> mapLineItemAndTaskToUpdateLineItem = new Map<Id,Task>();
        mapLineItemAndTaskToUpdateLineItem.put(momItem.id,TacheMomItem);
        mapLineItemAndTaskToUpdateLineItem.put(raid.id,Tache);
        MMPJ_TOPG_AP01_Task.updateMOMLineItem(mapLineItemAndTaskToUpdateLineItem);
        MMPJ_TOPG_AP01_Task.updateRAID(mapLineItemAndTaskToUpdateLineItem);
        update(listTask);
        Test.StopTest();    
     }
}