objects/MMPJ_TOPG_Brand__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Market__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Interaction__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Interaction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical interaction</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MinuteOfMeeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Highlight__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>Minutes_of_Meeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <label>MMPJ_TOPG_RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <label>MMPJ_TOPG_Topic</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Minute of Meeting</label>
    <nameField>
        <displayFormat>MOM-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Minutes of Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minutes of Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MoMLineItem__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Topic</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>MoM Line Item</label>
    <nameField>
        <displayFormat>MOM-LI-{000000}</displayFormat>
        <label>MoM Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MoM Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsiQCv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ExpectedDate__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Expected date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Highlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for the TOP GUN Project</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project --</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Status__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>On Going</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP03_RAID_Test.cls
@isTest
public class MMPJ_TOPG_AP03_RAID_Test {
     private static  Datetime myDT = Datetime.now();
     private static String  mailPrefix = myDT.format('ddMMyyyy');
     static testMethod void createTaskTest(){
        Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(Username = mailPrefix+'-test@supervisor.com', email = mailPrefix+'-test@supervisor.com', profileID = adminProfile.id, IsActive = true, LastName='Supervisor', Alias='sup', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US'); 
        insert u;
        //create market 
        MMPJ_TOPG_Market__c market = new MMPJ_TOPG_Market__c();
        market.Name='France ID';
        insert market;
        //create brand 
        MMPJ_TOPG_Brand__c brand= new MMPJ_TOPG_brand__c();
        brand.Name='testBrand';
        insert brand;
        
        RecordType rt = [Select id,Name 
                         From RecordType 
                         Where SobjectType='MMPJ_TOPG_MoMLineItem__c' and Name='Line Item Project' Limit 1];
                         
        //insert project 
        MMPJ_TOPG_Project__c project = new MMPJ_TOPG_Project__c();
        project.name = 'testProject';
        project.MMPJ_TOPG_StartDate__c= System.today()-10;
        project.MMPJ_TOPG_EndDate__c= System.today()+20;
        project.MMPJ_TOPG_ProjectOwner__c=u.id;  
        insert (project);
        
        //insert meeting 
        MMPJ_TOPG_Meeting__c meeting = new MMPJ_TOPG_Meeting__c();
        meeting.MMPJ_TOPG_Title__c ='meeting';
        meeting.MMPJ_TOPG_StartDate__c =System.today()-20;
        meeting.MMPJ_TOPG_EndDate__c =System.today()+15;
        meeting.MMPJ_TOPG_Interaction__c = 'Call';
        insert meeting;

        //insert minutes of meeting
        MMPJ_TOPG_MinuteOfMeeting__c minutes = new MMPJ_TOPG_MinuteOfMeeting__c();
        minutes.MMPJ_TOPG_Status__c='Draft';
        minutes.MMPJ_TOPG_Title__c ='Test minutes';
        minutes.MMPJ_TOPG_Topic__c='Test minutes';
        minutes.MMPJ_TOPG_RAID__c='Action';
        minutes.MMPJ_TOPG_Meeting__c = meeting.id;
        insert minutes;
       
        //insert RAIDs
        MMPJ_TOPG_Raid__c raid = new MMPJ_TOPG_Raid__c ();
        raid.MMPJ_TOPG_Title__c='test Raid';
        raid.MMPJ_TOPG_ExpectedDate__c = System.today();
        raid.MMPJ_TOPG_Status__c = 'Planned';
        raid.MMPJ_TOPG_RAID__c='Action';
        raid.MMPJ_TOPG_Project__c = project.id;
        raid.MMPJ_TOPG_User__c = u.id;
        raid.MMPJ_TOPG_Highlight__c = false;
         
        MMPJ_TOPG_Raid__c raid2 = new MMPJ_TOPG_Raid__c ();
        raid2.MMPJ_TOPG_Title__c ='test Raid';
        raid2.MMPJ_TOPG_ExpectedDate__c = System.today();
        raid2.MMPJ_TOPG_Status__c = 'Planned';
        raid2.MMPJ_TOPG_RAID__c ='Action';
        raid2.MMPJ_TOPG_Project__c = project.id;
        raid2.MMPJ_TOPG_User__c = null;
        
         MMPJ_TOPG_Raid__c raid3 = new MMPJ_TOPG_Raid__c ();
        raid3.MMPJ_TOPG_Title__c ='test Raid';
        raid3.MMPJ_TOPG_ExpectedDate__c = System.today();
        raid3.MMPJ_TOPG_Status__c = 'Planned';
        raid3.MMPJ_TOPG_RAID__c ='Action';
        raid3.MMPJ_TOPG_Project__c = project.id;
        raid3.MMPJ_TOPG_User__c = null;
        List <MMPJ_TOPG_RAID__c> listRAID = new List<MMPJ_TOPG_Raid__c>();
        listRAID.add(raid);
        listRAID.add(raid2);
        listRAID.add(raid3);
        insert(new List<MMPJ_TOPG_Raid__c>{raid, raid2,raid3});         
         
          //task         
         
         Task Tache = new Task();
            if(raid.MMPJ_TOPG_User__c != null)
                Tache.OwnerId = raid.MMPJ_TOPG_User__c;
            else
            Tache.Whoid= raid.MMPJ_TOPG_Contact__c;
            Tache.Description = raid.MMPJ_TOPG_Description__c;
            Tache.ActivityDate = raid.MMPJ_TOPG_ExpectedDate__c;
            Tache.WhatId = raid.id;
            Tache.Status = raid.MMPJ_TOPG_Status__c;
            Tache.Subject = raid.MMPJ_TOPG_Title__c;
            Tache.MMPJ_TOPG_ProjectRaid__c = true;
            Tache.MMPJ_TOPG_ProjectChanged__c = true;
            insert Tache; 
         
          //task
         Task Tache1 = new Task();
            if(raid.MMPJ_TOPG_User__c != null)
                Tache.OwnerId = raid2.MMPJ_TOPG_User__c;
            else
            Tache1.Whoid= raid2.MMPJ_TOPG_Contact__c;
            Tache1.Description = raid2.MMPJ_TOPG_Description__c;
            Tache1.ActivityDate = raid2.MMPJ_TOPG_ExpectedDate__c;
            Tache1.WhatId = raid2.id;
            Tache1.Status = raid2.MMPJ_TOPG_Status__c;
            Tache1.Subject = raid2.MMPJ_TOPG_Title__c;
            Tache1.MMPJ_TOPG_ProjectRaid__c = true;
            Tache1.MMPJ_TOPG_ProjectChanged__c = true;
            insert Tache1;          
       	    Test.StartTest();      
            MMPJ_TOPG_AP03_Raid.isFirstTime = true;
       
            MMPJ_TOPG_AP03_RAID.createTask(listRAID);
            MMPJ_TOPG_AP03_RAID.deleteTask(new Set<ID>{raid3.id});
            Map<Id,MMPJ_TOPG_RAID__c> mapRAID = new Map<Id,MMPJ_TOPG_RAID__c> ();
            mapRAID.put(Tache1.id,raid2);
            mapRAID.put(Tache.id,raid);
            mapRAID.put(Tache.id,raid2);
            MMPJ_TOPG_AP03_RAID.updateTask(mapRAID);
        Test.StopTest();    
     }
}