objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_BMC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>BMC</label>
        <referenceTo>MMPJ_TOPG_BMC__c</referenceTo>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Detail_Line_Topic__c</fullName>
        <label>MMPJ_TOPG_Detail_Line_Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Market Performance</fullName>
                </value>
                <value>
                    <fullName>Place / Channel</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Promotion / Communication</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_NoAgenda__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Agenda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MinuteOfMeeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_BMC__c</fullName>
        <formula>MMPJ_TOPG_Meeting__r.MMPJ_TOPG_BMC__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BMC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_End_Date__c</fullName>
        <label>Minute End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>Minutes_of_Meeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <label>MMPJ_TOPG_RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <label>MMPJ_TOPG_Topic</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Minute of Meeting</label>
    <nameField>
        <displayFormat>MOM-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Minutes of Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minutes of Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_MoMLineItem__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Action_Title__c</fullName>
        <label>Action Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_IsHighlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MMPJ TOPGUN</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MinutesofMeeting__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Minute of Meeting</label>
        <referenceTo>MMPJ_TOPG_MinuteOfMeeting__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RelatedProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Topic</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MoM Line Item</label>
    <nameField>
        <displayFormat>MOM-LI-{000000}</displayFormat>
        <label>MoM Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MoM Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_TechEndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_TechStartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_CockPitRiskController.cls
public with sharing class MMPJ_TOPG_CockPitRiskController {
public Date StartDate{get;set;}
public Date EndDate{get;set;}
public list<SelectOption> AllMarkets{get;set;}
public list<SelectOption> SelectedMarkets{get;set;}
public list<SelectOption> AllBrands{get;set;}
public list<SelectOption> TotalBrand{get;set;}
public list<SelectOption> SelectedBrands{get;set;}
public list<MMPJ_TOPG_MoMLineItem__c> ListHighlightMeetings{get;set;}
public map<String,MMPJ_TOPG_RAID__c > MapListMoMLineItemAction{get;set;}    
public  MMPJ_TOPG_RAID__c Raid{get;set;}
public Integer SizeMultipicklist {get;set;}
public Boolean actionDone{get;set;}

/*public list<SelectOption> listBrands{
        get;
        set{    
            system.debug('valueeeeeee =='+value);        
            if(value != null && value.size() > 0 ){
                listBrands = value;

                SelectedBrands.clear();
              system.debug('AllBrands ==='+AllBrands);
                system.debug('listBrands==='+listBrands);
                for(SelectOption tempBrand : AllBrands){
                    for(SelectOption tempBrand2 : listBrands){
                        if(tempBrand.getLabel() == tempBrand2.getLabel()){
                           SelectedBrands.add(tempBrand);
                            break;
                        }
                    }
                }               
            }
        }
    }*/
    public list<SelectOption> listMarkets{
        get;
        set{            
            if(value != null && value.size() > 0  ){
                listMarkets = value;
                SelectedMarkets.clear();
                for(SelectOption tempMarket : AllMarkets){
                    for(SelectOption tempMarket2 : listMarkets){
                         String marketName=tempMarket2.getLabel();
                        String  tempMarketName=marketName.substring(0,marketName.indexOfIgnoreCase(' ',0));    
                        if(tempMarket.getLabel() == tempMarketName){
                            SelectedMarkets.add(tempMarket);
                            break;
                        }
                    }
                }                
            
        }
    }}
 //constructor   
public MMPJ_TOPG_CockPitRiskController (){
 AllMarkets = new list<selectoption>();
 AllBrands = new list<selectoption>();
 TotalBrand = new list<selectoption>();
 SelectedMarkets= new list<selectoption>();
 SelectedBrands= new list<selectoption>();
 ListHighlightMeetings = new list<MMPJ_TOPG_MoMLineItem__c>();
 Raid= new MMPJ_TOPG_RAID__c();
 MapListMoMLineItemAction = new map<String,MMPJ_TOPG_RAID__c >();
 
 //set Date by default for start Date and end Date
  DateTime dtStart=System.today().addMonths(-1);
  DateTime dtEnd=System.today().addMonths(+1);
 Date DateStart=date.newinstance(dtStart.year(), dtStart.month(), dtStart.day());
 Date dateEnd=date.newinstance(dtEnd.year(), dtEnd.month(), dtEnd.day());
 Date firstDayOfLastMonth=DateStart.toStartOfMonth();
 Integer numberOfDays = Date.daysInMonth(dateEnd.year(), dateEnd.month());
  Date lastDayOfMonth = Date.newInstance(dateEnd.year(), dateEnd.month(), numberOfDays);
 Raid.MMPJ_TOPG_TechStartDate__c=firstDayOfLastMonth; 
 raid.MMPJ_TOPG_TechEndDate__c =lastDayOfMonth;
 SizeMultipicklist=15; 

getAllMarketsData();
getAllBrandsData();     
}
public list<SelectOption> getAllMarketsData(){
 List <SelectOption> lstMarkets = new List <SelectOption>();
 Set <SelectOption>SetMarket = new Set<SelectOption>(); 
      allMarkets.add(new SelectOption('All Markets', 'All Markets'));
      //  used befor Evol makert = BMC now  =>  for(MMPJ_TOPG_Market__c market : [SELECT Name FROM MMPJ_TOPG_Market__c order by name asc])
     for(MMPJ_TOPG_BMC__c bmc : [SELECT Name FROM MMPJ_TOPG_BMC__c order by name asc])
         allMarkets.add(new SelectOption(bmc.Name, bmc.Name));
         
return lstMarkets; 
}
public list<SelectOption> getAllBrandsData(){
 List <SelectOption> lstBrands = new List <SelectOption>();
 Set <SelectOption> SetBrands = new Set<SelectOption>(); 
  
      for(MMPJ_TOPG_Brand__c brand : [SELECT Name FROM MMPJ_TOPG_Brand__c order by name asc])
        allBrands.add(new SelectOption(brand.Name, brand.Name));
return lstBrands ; 
}

public pageReference applySearch(){
actionDone=true;
system.debug(' in applySearch==');
if (raid!=null){
    StartDate=Raid.MMPJ_TOPG_TechStartDate__c;
    EndDate=Raid.MMPJ_TOPG_TechEndDate__c;  
}
Set <String> lstFilterMarket  = new Set <String>();
Set <String> lstFilterBrand  = new Set <String>(); 
String brandfilter ='';
String Marketfilter ='';
    if (SelectedBrands.size()>0){
        brandfilter  = fitlerData(SelectedBrands);
    }
    if (SelectedMarkets.size()>0){
        Marketfilter  = fitlerData(SelectedMarkets);
    }
 
system.debug('Start Date =='+startDate );
system.debug('End Date =='+EndDate );
system.debug('Marketfilter =='+Marketfilter );
system.debug('brandfilter =='+brandfilter );
    
  String queryhighMeeting ='select id,name,'+
                            'MMPJ_TOPG_IsHighlight__c'+
                            ',MMPJ_TOPG_RAID__c'+
                            ',MMPJ_TOPG_RelatedProject__c'+
                            ',MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__c'+
       						',MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_End_Date__c'+ 
                            ',MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_Title__c'+
                            ',MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_NoAgenda__c'+
       						',MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_EndDate__c'+ 
                            ',MMPJ_TOPG_Title__c'+
                            ',MMPJ_TOPG_WhoU__c'+
                            ',MMPJ_TOPG_WhoC__c'+
                            ',MMPJ_TOPG_Topic__c '+
                            ',MMPJ_TOPG_When__c '+
       						',MMPJ_TOPG_Comment__c '+
       						',MMPJ_TOPG_Action_Title__c '+ 
       						',MMPJ_TOPG_Detail_Line_Topic__c '+ 
                          'from MMPJ_TOPG_MoMLineItem__c'+
                           ' where MMPJ_TOPG_IsHighlight__c=true'+
                           ' and MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_EndDate__c>=:startDate'+
                           ' and MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_EndDate__c<=:endDate ';
                           /* if (brandfilter!='' && !brandfilter.contains('All Brands') ){     
                               queryhighMeeting += ' and MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_BMC__r.MMPJ_TOPG_Brand__r.name in ('+brandfilter+')';
                             }   */
                             if (Marketfilter!='' && !Marketfilter.contains('All Markets')){
                               queryhighMeeting += ' and MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_BMC__r.name in ('+Marketfilter+')';
                             }
     queryhighMeeting +=' order by MMPJ_TOPG_MinutesofMeeting__r.MMPJ_TOPG_Meeting__r.MMPJ_TOPG_EndDate__c Desc '; 
      system.debug ('queryhighMeeting =='+queryhighMeeting );                       
    if(!String.isEmpty(Marketfilter)){
         ListHighlightMeetings=Database.query(queryhighMeeting);  
        // load meeting's Todo data  
	for(MMPJ_TOPG_RAID__c raid: [select id,	MMPJ_TOPG_Title__c, MMPJ_TOPG_LineItem__c,MMPJ_TOPG_LineItem__r.name,MMPJ_TOPG_LineItem__r.MMPJ_TOPG_Topic__c,MMPJ_TOPG_LineItem__r.MMPJ_TOPG_Action_Title__c from MMPJ_TOPG_RAID__c where MMPJ_TOPG_LineItem__c !=null]){
    // ListRaids.add(raid);
     system.debug('==============in load data for raid object============');
     system.debug('raid of MomLineItem.name =='+raid.MMPJ_TOPG_LineItem__r.name );
     system.debug('raid of MomLineItem.topic =='+raid.MMPJ_TOPG_LineItem__r.MMPJ_TOPG_Topic__c );
     system.debug('raid of MomLineItem.ActionTitle =='+raid.MMPJ_TOPG_LineItem__r.MMPJ_TOPG_Action_Title__c );
     system.debug('raid id  =='+raid.MMPJ_TOPG_LineItem__c );
     MapListMoMLineItemAction.put(raid.MMPJ_TOPG_LineItem__c,raid);
     } 
    }else{
        ListHighlightMeetings.clear();
        MapListMoMLineItemAction.clear();
    }
                                                
return null;
}
public String fitlerData(List <selectOption> theList){
String result =' ';
for (SelectOption sel :theList){
        result+=  '\''+sel.getValue() +'\'';
    break;
    }
    if (theList.size()>1){
        for (SelectOption sel :theList){
            result+=  ',\''+sel.getValue() +'\'';
        }
    }
return result ;
}

}