objects/MMPJ_TOPG_Brand__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Market__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsiQCv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_ProjectMilestone__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_A__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>A</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Date__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MMPJ_Status__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Done/Go</fullName>
                </value>
                <value>
                    <fullName>No Go</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MilestoneTitle__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Milestone Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_LoadMileStoneController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class MMPJ_TOPG_LoadMileStoneController_Test {
    
		private static  Datetime myDT = Datetime.now();
     	private static String  mailPrefix = myDT.format('ddMMyyyy');
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(Username = mailPrefix+'-test-supervisor@pernod-ricard.com', email = mailPrefix+'-test-supervisor@pernod-ricard.com', profileID = adminProfile.id, IsActive = true, LastName='Supervisor', Alias='sup', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US'); 
        insert u;
        
          MMPJ_TOPG_Market__c market = new MMPJ_TOPG_Market__c();
        market.Name='France ID';
        insert market;
        //create brand 
        MMPJ_TOPG_Brand__c brand= new MMPJ_TOPG_brand__c();
        brand.Name='testBrand';
        insert brand;
        
         //insert project 
        MMPJ_TOPG_Project__c project = new MMPJ_TOPG_Project__c();
        project.name = 'testProject';
        project.MMPJ_TOPG_StartDate__c= Date.newInstance(2016,11,11);
        project.MMPJ_TOPG_EndDate__c= Date.newInstance(2016,12,12);
        project.MMPJ_TOPG_ProjectOwner__c=u.id;  
        insert project;
        
        MMPJ_TOPG_ProjectMilestone__c miles = new MMPJ_TOPG_ProjectMilestone__c();
        miles.MMPJ_TOPG_A__c='Brand';
        miles.MMPJ_TOPG_Date__c= Date.newInstance(2016,12,12);
        miles.MMPJ_TOPG_MilestoneTitle__c ='Test miles';
        miles.MMPJ_TOPG_Project__c = project.id;
        miles.MMPJ_TOPG_MMPJ_Status__c='Planned';
        insert miles;
        MMPJ_TOPG_ProjectMilestone__c miles2 = new MMPJ_TOPG_ProjectMilestone__c();
        miles2.MMPJ_TOPG_A__c='Brand';
        miles2.MMPJ_TOPG_Date__c= Date.newInstance(2016,12,12);
        miles2.MMPJ_TOPG_MilestoneTitle__c ='Test miles2';
        miles2.MMPJ_TOPG_Project__c = project.id;
        miles2.MMPJ_TOPG_MMPJ_Status__c='Planned';
        
         
       MMPJ_TOPG_LoadMileStoneController mmpj = new MMPJ_TOPG_LoadMileStoneController();
           Test.startTest();
           mmpj.project=project;
           Boolean bool = mmpj.ShowSaveMessage;
           Boolean bool2 = mmpj.isEditMode;
           mmpj.getMilesFromCustom();
           mmpj.saveMilestones();
           mmpj.addMileStone();
           mmpj.deletetMileStone();
           mmpj.hideMilesStonePopup();
           mmpj.MoveUpMilesStones();
           mmpj.LeavingMilestones();
           mmpj.SelectedCounter= 0;
           mmpj.EditMileStones();
           mmpj.ChangeRACI();
           Test.stopTest();
    }
}