objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_ProjectTopic__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MMPJ_TOPG_ProjectType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product Launch</fullName>
                </value>
                <value>
                    <fullName>Media Campaign</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Off-trade place</fullName>
                </value>
                <value>
                    <fullName>On-trade place</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectType__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Development</fullName>
                </value>
                <value>
                    <fullName>Co-Development</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_ProjectMilestone__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Date__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MMPJ_TOPG_IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MMPJ_Status__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Done/Go</fullName>
                </value>
                <value>
                    <fullName>No Go</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MilestoneTitle__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Milestone Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Rank__c</fullName>
        <description>Ordering the project milestones related list.</description>
        <label>MMPJ_TOPG_Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP01_MileStones.cls
public with sharing class MMPJ_TOPG_AP01_MileStones
{

public static void createDefaultMileStones(List <MMPJ_TOPG_Project__c> lstProjects){    
    List <MMPJ_TOPG_ProjectMilestone__c>lstmilestones= new List<MMPJ_TOPG_ProjectMilestone__c>();
    List <String> lstDefaultMilestones1 = new List <String>
    {'18 Months: Concept and pricing presentation'
    ,'12 Months: Look and feel, sampling and financials'
    ,'6 Months: Toolkit','Launch'
    };
    List <String> lstDefaultMilestones2 = new List <String>
    {'Briefing Big idea'
    ,'Idea Development'
    ,'Workshop Localization'
    ,'Campaign Shaping'
    ,'Production'
    };
     List <String> lstDefaultMilestones3 = new List <String>
    {'Briefing Design Development'
    ,'Design validation'
    ,'Mock-Up Production'
    ,'Design finalization'
    ,'Production'
    ,'Shipping'
    ,'Distribution in market'
    };
    List <String> lstDefaultMilestones4 = new List <String>
    {'Deadline for information spreadsheet'
    ,'Pre-submission deadline for offers'
    ,'Tasting approval process'
    ,'Samples submission for tasting'
    ,'Tasting'
    ,'Tasting results'
    ,'Order details'
    };
    if (Trigger.isUpdate){
    system.debug('in update');
    
   }
    Integer rankId=0;
    
    for (MMPJ_TOPG_Project__c project : lstProjects){   
     rankId=0;
     //insert default mileStones     
     if (project.MMPJ_TOPG_ProjectType__c=='Central Development' && project.MMPJ_TOPG_ProjectTopic__c =='Product')
     {
         for (String mileName :lstDefaultMilestones1)
         {
              createDefaultsMilestones(lstmilestones,mileName,project.id,rankId);
              rankId++;
         }    
     }
     else if (project.MMPJ_TOPG_ProjectType__c=='Co-Development' && project.MMPJ_TOPG_ProjectTopic__c =='Media Campaign'){
        for (String mileName :lstDefaultMilestones2)
         {
             createDefaultsMilestones(lstmilestones,mileName,project.id,rankId);
             rankId++;
         }
    }
    else if (project.MMPJ_TOPG_ProjectType__c=='Co-Development' && project.MMPJ_TOPG_ProjectTopic__c =='Product Launch')
    {
        for (String mileName :lstDefaultMilestones3)
         {
            createDefaultsMilestones(lstmilestones,mileName,project.id,rankId);
            rankId++;
         }
    }
    else if (project.MMPJ_TOPG_ProjectType__c=='Pitch')
    {
        for (String mileName :lstDefaultMilestones4)
         {
            createDefaultsMilestones(lstmilestones,mileName,project.id,rankId);
            rankId++;
         }
    }
 } 
    system.debug('lstmilestones =='+lstmilestones.size());   
    insert lstmilestones;
}

public static void createDefaultsMilestones(List<MMPJ_TOPG_ProjectMilestone__c>lstmilestones,String mileName,String projectId,Integer rankId)
 {
    MMPJ_TOPG_ProjectMilestone__c mile = new MMPJ_TOPG_ProjectMilestone__c();
    mile.name=mileName;
    mile.MMPJ_TOPG_MilestoneTitle__c=mileName;
    mile.MMPJ_TOPG_Project__c=projectId;
    mile.MMPJ_TOPG_IsDefault__c=true;
    mile.MMPJ_TOPG_MMPJ_Status__c='Planned';
    mile.MMPJ_TOPG_Date__c=System.Today();
    mile.MMPJ_TOPG_Rank__c=rankId;
    lstmilestones.add(mile);  
 } 
}