objects/MMPJ_TOPG_MoMLineItem__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_IsHighlight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MMPJ TOPGUN</description>
        <label>Highlight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RelatedProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Topic__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Topic</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_WhoU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MoM_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MoM Line Item</label>
    <nameField>
        <displayFormat>MOM-LI-{000000}</displayFormat>
        <label>MoM Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MoM Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ExpectedDate__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Expected date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Rank__c</fullName>
        <description>Sorting the related list on Project</description>
        <label>MMPJ_TOPG_Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Status__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>On Going</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP01_Task.cls
public class MMPJ_TOPG_AP01_Task {    
    //When a task is updated the corresponding lineIem should be updated
    public static void updateMOMLineItem(Map<Id,Task> mapLineItemAndTaskToUpdateLineItem){
         List<MMPJ_TOPG_MoMLineItem__c> listLineItemToUpdate = new List<MMPJ_TOPG_MoMLineItem__c >();
         List<MMPJ_TOPG_MoMLineItem__c> listRelatedLineItem = new List<MMPJ_TOPG_MoMLineItem__c>();
         listRelatedLineItem =  [Select MMPJ_TOPG_When__c , MMPJ_TOPG_IsHighlight__c  , MMPJ_TOPG_Rank__c , MMPJ_TOPG_RelatedProject__c , MMPJ_TOPG_WhoC__c , MMPJ_TOPG_RAID__c , MMPJ_TOPG_WhoU__c 
                                  From  MMPJ_TOPG_MoMLineItem__c 
                                  Where id IN: mapLineItemAndTaskToUpdateLineItem.KeySet()];
         for(MMPJ_TOPG_MoMLineItem__c  lineItem : listRelatedLineItem ){
             Task task = mapLineItemAndTaskToUpdateLineItem.get(lineItem.id);
             if (task!= null){
                 lineItem.MMPJ_TOPG_WhoU__c = task.OwnerId ;
                 lineItem.MMPJ_TOPG_WhoC__c = task.WhoId ;
                 lineItem.MMPJ_TOPG_Topic__c = task.Description ;
                 lineItem.MMPJ_TOPG_When__c = task.ActivityDate ;
                 lineItem.id = task.WhatId;
                 lineItem.MMPJ_TOPG_Title__c = task.Subject;
    
                 listLineItemToUpdate.add(lineItem);
             }
        }
        
        if(listLineItemToUpdate.size() > 0){
            update(listLineItemToUpdate);
        }
    }
    //When a task is updated the corresponding RAID should be updated
    public static void updateRAID(Map<Id,Task> mapLineItemAndTaskToUpdateLineItem){
         List<MMPJ_TOPG_RAID__c> listRaidToUpdate = new List<MMPJ_TOPG_RAID__c >();
         List<MMPJ_TOPG_RAID__c> listRelatedRaid = new List<MMPJ_TOPG_RAID__c>();
         listRelatedRaid =  [Select MMPJ_TOPG_User__c,MMPJ_TOPG_Contact__c, MMPJ_TOPG_ExpectedDate__c, MMPJ_TOPG_Description__c, MMPJ_TOPG_Status__c, MMPJ_TOPG_Title__c  
                                  From  MMPJ_TOPG_RAID__c 
                                  Where id IN: mapLineItemAndTaskToUpdateLineItem.KeySet()];
         for(MMPJ_TOPG_RAID__c  raid : listRelatedRaid ){
             Task task = mapLineItemAndTaskToUpdateLineItem.get(raid.id);
             if (task!= null){
             	raid.MMPJ_TOPG_User__c = task.OwnerId ;
                raid.MMPJ_TOPG_Contact__c = task.WhoId ;
                raid.MMPJ_TOPG_Description__c = task.Description ;
                raid.MMPJ_TOPG_ExpectedDate__c  = task.ActivityDate ;
                raid.MMPJ_TOPG_Status__c = task.Status;
       			raid.MMPJ_TOPG_Title__c = task.Subject;
    
                listRaidToUpdate.add(raid);
             }
        }
        
        if(listRaidToUpdate.size() > 0){
            update(listRaidToUpdate);
        }
    }
}