objects/MMPJ_TOPG_BMC__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app (Old BMC label  renamed to maket)</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Brand__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Market__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_BMC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>BMC</label>
        <referenceTo>MMPJ_TOPG_BMC__c</referenceTo>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Interaction__c</fullName>
        <description>MMPJ TOPGUN</description>
        <label>Interaction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical interaction</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Outlet__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>Market</label>
        <referenceTo>MMPJ_TOPG_Market__c</referenceTo>
        <relationshipName>Outlets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>Partner</label>
        <referenceTo>MMPJ_TOPG_Partner__c</referenceTo>
        <relationshipName>Outlets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet</label>
    <nameField>
        <label>Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Partner__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>MMPJ_TOPG_Brand__c</referenceTo>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>MMPJ_TOPG_Market__c</referenceTo>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Distribution Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Visit__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_BMC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>BMC</label>
        <referenceTo>MMPJ_TOPG_BMC__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Bench_Currency__c</fullName>
        <label>Benchmark Currency</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_MMPJVisitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MMPJ Visitor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>MMPJ_TOPG_Market__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>Outlet Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MMPJ_TOPG_Outlet__c.MMPJ_TOPG_Market__c</field>
                <operation>equals</operation>
                <valueField>$Source.MMPJ_TOPG_Market__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MMPJ_TOPG_Outlet__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disribution Partner</label>
        <referenceTo>MMPJ_TOPG_Partner__c</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StatementDate__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassVR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, user will bypass all validation rules and all look-up filters.</description>
        <inlineHelpText>If checked, user will bypass all validation rules and all look-up filters.</inlineHelpText>
        <label>Bypass Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_NewVisitController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class MMPJ_TOPG_NewVisitController_Test {
    private static  Datetime myDT = Datetime.now();
    private static String  mailPrefix = myDT.format('ddMMyyyy');
static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
          Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(Username = mailPrefix+'-NPLsupervisor@pernod-ricard.com', email = mailPrefix+'-supervisor@pernod-ricard.com', profileID = adminProfile.id, IsActive = true, LastName='Supervisor', Alias='sup', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US',BypassVR__c=true); 
       //System.runAs(u) {
        //create market 
        MMPJ_TOPG_Market__c market = new MMPJ_TOPG_Market__c();
        market.Name='mumm';
        insert market;
       
       //create brand
         MMPJ_TOPG_BRAND__c brand = new MMPJ_TOPG_BRAND__c();
     brand.name='Martell';
     insert brand;
     
        //create outlet
        MMPJ_TOPG_Outlet__c outlet = new MMPJ_TOPG_Outlet__c();
        outlet.Name='test outlet';
        outlet.MMPJ_TOPG_Market__c =market.id;
        insert outlet;
      
       MMPJ_TOPG_Outlet__c outlet2 = new MMPJ_TOPG_Outlet__c();
        outlet2.Name='test outlet';
        outlet2.MMPJ_TOPG_Market__c=market.id;
        //insert outlet;
      //create partner      
      MMPJ_TOPG_Partner__c partner = new MMPJ_TOPG_Partner__c();
      partner.Name='partner1';
      partner.MMPJ_TOPG_Market__c=market.id;
      insert partner;
  
     

       
       MMPJ_TOPG_BMC__c bmcTest = new MMPJ_TOPG_BMC__c ();
            bmcTest.name='bmcTest';
    		//BTO => delete Market fomr BMC
           // bmcTest.MMPJ_TOPG_Market__c=market.id;
           // bmcTest.MMPJ_TOPG_Brand__c=brand.id;
       insert bmcTest ;
       //lkp to user
       // create visit 
       MMPJ_TOPG_Visit__c visit = new MMPJ_TOPG_Visit__c();
       visit.name= 'test visit';
       visit.MMPJ_TOPG_StatementDate__c=date.newInstance(1990, 11, 21);
       visit.MMPJ_TOPG_MMPJVisitor__c=u.id;
       visit.MMPJ_TOPG_Outlet__c=outlet.id;
       visit.MMPJ_TOPG_PARTNER__c=partner.id;
       visit.MMPJ_TOPG_MMPJVisitor__c=u.id;
       visit.MMPJ_TOPG_BMC__c = bmcTest.id;
       visit.MMPJ_TOPG_Market__c= market.id;
       visit.MMPJ_TOPG_Bench_Currency__c='Euro';
       insert visit;
        
        MMPJ_TOPG_Meeting__c  meeting = new MMPJ_TOPG_Meeting__c ();
        meeting.MMPJ_TOPG_BMC__c = bmcTest.id;
        Meeting.MMPJ_TOPG_Interaction__c = 'test';
        insert meeting;
        
         MMPJ_TOPG_Visit__c visit2 = new MMPJ_TOPG_Visit__c();
       visit2.name= 'test visit2';
       visit2.MMPJ_TOPG_StatementDate__c=date.newInstance(1990, 11, 21);
       visit2.MMPJ_TOPG_MMPJVisitor__c=u.id;
       visit2.MMPJ_TOPG_Outlet__c=outlet.id;
       visit2.MMPJ_TOPG_PARTNER__c=partner.id;
       visit.MMPJ_TOPG_Market__c= market.id;
       visit2.MMPJ_TOPG_MMPJVisitor__c=u.id;
       visit2.MMPJ_TOPG_BMC__c = bmcTest.id;
       visit2.MMPJ_TOPG_Bench_Currency__c='Euro'; 
       
        ApexPages.StandardController sc = new ApexPages.StandardController(bmcTest);
           MMPJ_TOPG_NewVisitController mmpj = new MMPJ_TOPG_NewVisitController();
           Test.startTest();
            //mmpj.BMC =bmcTest;
            mmpj.editVisitId =visit.id;
            mmpj.meeting=meeting;
            mmpj.tempRichText='test';
            mmpj.ListVisits  = new list<MMPJ_TOPG_Visit__c >();
            mmpj.ListVisits.add(visit);
            mmpj.LoadVisits();
            mmpj.visitPopup =visit;
            mmpj.ShowVisitPopup();
            mmpj.editVisitId =visit.id;
            mmpj.AutomatePartnerFunction();
            mmpj.EditVisit();
            mmpj.outletPopup=outlet2;
            mmpj.hideVisitPopup();
            mmpj.NewOultetPopup();
            mmpj.SelectedRadioId =visit.id;
            mmpj.saveComment();
            mmpj.SaveOutlet();
            mmpj.SaveNewOutlet();
            mmpj.editVisitId =visit.id;
            mmpj.visitPopup=visit2;
            //mmpj.BMC=bmcTest;
            mmpj.SaveVisit();
            mmpj.SaveNewVisit();
            mmpj.DelVisit();
            Test.stopTest();
//}
}
}