objects/MMPJ_TOPG_BMC__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app (Old BMC label  renamed to maket)</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Brand__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Market__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_BMC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MMPJ TOPGUN</description>
        <label>BMC</label>
        <referenceTo>MMPJ_TOPG_BMC__c</referenceTo>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project_Brand__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>MMPJ_TOPG_Brand__c</referenceTo>
        <relationshipName>Project_Brands</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <label>Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Project_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Brand</label>
    <nameField>
        <displayFormat>PB-{00000}</displayFormat>
        <label>Project_Brand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project_Market__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <label>Market</label>
        <referenceTo>MMPJ_TOPG_Market__c</referenceTo>
        <relationshipName>Project_Markets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <label>Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Project_Markets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Market</label>
    <nameField>
        <displayFormat>PM-{00000}</displayFormat>
        <label>Project_Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Markets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Meeting</label>
        <referenceTo>MMPJ_TOPG_Meeting__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project --</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_RAID__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>RAID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_AP01_RAID.cls
public with sharing class MMPJ_TOPG_AP01_RAID{

    public static void updateProjMarketAndBrand(List <MMPJ_TOPG_Project__c> lstProjects){
        system.debug('in trigger ==========');
        List <Id> listProjectsIds = new List <Id>();
        for (MMPJ_TOPG_Project__c proj : lstProjects){
            listProjectsIds.add(proj.id); 
        }
        system.debug('listProjectsIds =='+listProjectsIds);
        //list of Project Brands 
        List<MMPJ_TOPG_Project_Brand__c> lstProjectsBrand = [select id
                                                            ,MMPJ_TOPG_Brand__c
                                                            ,MMPJ_TOPG_Project__c 
                                                            from MMPJ_TOPG_Project_Brand__c
                                                            where MMPJ_TOPG_Project__c  in:listProjectsIds];
        // get list ids of brands
        List<id> lstBrandIds = new list <id>();
        for  (MMPJ_TOPG_Project_Brand__c projBrand :lstProjectsBrand)
        {
            lstBrandIds.add(projBrand.MMPJ_TOPG_Brand__c) ;
        }

        //list of Project Markets 
        List<MMPJ_TOPG_Project_Market__c> lstProjectsMarket = [select id
                                                                ,MMPJ_TOPG_Market__c
                                                                ,MMPJ_TOPG_Project__c 
                                                                from MMPJ_TOPG_Project_Market__c
                                                                where MMPJ_TOPG_Project__c  in:listProjectsIds];
        //get list ids of Market
        List<id> lstMarketIds = new list<id>();                                                    
        for  (MMPJ_TOPG_Project_Market__c projMarket :lstProjectsMarket)
        {
            lstMarketIds.add(projMarket.MMPJ_TOPG_Market__c);
        }
        // list of names for the brands and markets                                                          
        List<MMPJ_TOPG_Brand__c> lstbrandsNames =[select  name from MMPJ_TOPG_Brand__c where id  in:lstBrandIds ];
        List<MMPJ_TOPG_Market__c> lstMarketsNames =[select name from MMPJ_TOPG_Market__c where id in:lstMarketIds ];

        //list of raids to be updated
        List <MMPJ_TOPG_RAID__c>lstRaidToUpdate = new List<MMPJ_TOPG_RAID__c>();
        for (MMPJ_TOPG_RAID__c raid : [select id ,MMPJ_TOPG_Project__c,MMPJ_TOPG_Brand__c,MMPJ_TOPG_Market__c from MMPJ_TOPG_RAID__c where MMPJ_TOPG_Project__c in:listProjectsIds]) {
            // if raids is linked to project
            //set it empty before re use it
            raid.MMPJ_TOPG_Brand__c='';
            if (raid.MMPJ_TOPG_Project__c!=null){
                for (MMPJ_TOPG_Brand__c brand :lstbrandsNames){
                    if (raid.MMPJ_TOPG_Brand__c!=null && !raid.MMPJ_TOPG_Brand__c.contains(brand.name)){
                        raid.MMPJ_TOPG_Brand__c=raid.MMPJ_TOPG_Brand__c+';'+brand.name;
                    }
                    else
                    {
                        raid.MMPJ_TOPG_Brand__c=brand.name+';';
                    } 
                }
                //set it empty before re use it 
                raid.MMPJ_TOPG_Market__c='';
                for (MMPJ_TOPG_Market__c market :lstMarketsNames){
                    if (raid.MMPJ_TOPG_Market__c!=null && !raid.MMPJ_TOPG_Market__c.contains(market.name)){
                        raid.MMPJ_TOPG_Market__c=raid.MMPJ_TOPG_Market__c+';'+market.name;
                    }
                    else {
                        raid.MMPJ_TOPG_Market__c=market.name+';';
                    }
                }  
            }
            lstRaidToUpdate.add(raid);
        }  
        // update list of raids 
        if (lstRaidToUpdate.size()>0)
            update lstRaidToUpdate;

        system.debug('out  trigger =========='); 
    }
    //BTO no objet market and brand on BMC
   /* public static void updateBMCMarketAndBrand(List <MMPJ_TOPG_BMC__c> lstBMCs){
        List <Id> lstBMCIds = new List <Id>();
        for (MMPJ_TOPG_BMC__c bmc:lstBMCs){
            lstBMCIds.add(bmc.id); 
        }
        //list of BMC's Market and Brands                                                     
        List <MMPJ_TOPG_BMC__c> lstBMCBrandAndMarkets = [select id,MMPJ_TOPG_Brand__r.name,MMPJ_TOPG_Market__r.name from MMPJ_TOPG_BMC__c where id in:lstBMCIds ];
        List <MMPJ_TOPG_RAID__c>lstRaidToUpdate = new List<MMPJ_TOPG_RAID__c>();
        for (MMPJ_TOPG_RAID__c raid : [select id ,MMPJ_TOPG_Project__c,MMPJ_TOPG_Brand__c,MMPJ_TOPG_Market__c,MMPJ_TOPG_Meeting__c from MMPJ_TOPG_RAID__c]) {
            // if raids is linked to meeting
            if (raid.MMPJ_TOPG_Meeting__c!=null){
                for (MMPJ_TOPG_BMC__c brandMarket :lstBMCBrandAndMarkets ){
                    if(raid.MMPJ_TOPG_Brand__c!=null && !raid.MMPJ_TOPG_Brand__c.contains(brandMarket.MMPJ_TOPG_Brand__r.name))
                    { 
                        raid.MMPJ_TOPG_Brand__c=raid.MMPJ_TOPG_Brand__c+';'+brandMarket.MMPJ_TOPG_Brand__r.name;
                    }
                    else{
                        raid.MMPJ_TOPG_Brand__c=brandMarket.MMPJ_TOPG_Brand__r.name+';';
                    }
                    if (raid.MMPJ_TOPG_Market__c!=null && !raid.MMPJ_TOPG_Market__c.contains(brandMarket.MMPJ_TOPG_Market__r.name)){
                        raid.MMPJ_TOPG_Market__c=raid.MMPJ_TOPG_Market__c+';'+brandMarket.MMPJ_TOPG_Market__r.name;
                    }
                    else{
                        raid.MMPJ_TOPG_Market__c=brandMarket.MMPJ_TOPG_Market__r.name+';';
                    }     
                    lstRaidToUpdate.add(raid); 
                }
            }
        }
        update lstRaidToUpdate;
    } */
    public static void updateRaidsMarketAndBrand(List <MMPJ_TOPG_RAID__c> lstRaids){
        List<Id> lstProjectsOfRaidIds = new List <Id>();
        List<Id> lstMeetingsRaidIds = new List <Id>();
        List<MMPJ_TOPG_Meeting__c> lstMeetings = new List <MMPJ_TOPG_Meeting__c>();
        for (MMPJ_TOPG_RAID__c raid:lstRaids){
            lstProjectsOfRaidIds.add(raid.MMPJ_TOPG_Project__c); 
            lstMeetingsRaidIds.add(raid.MMPJ_TOPG_Meeting__c); 
        }
        /*lstMeetings =[select id
        ,name
        ,MMPJ_TOPG_BMC__r.MMPJ_TOPG_Brand__r.name
        ,MMPJ_TOPG_BMC__r.MMPJ_TOPG_Market__r.name 
        from MMPJ_TOPG_Meeting__c where id in:lstMeetingsRaidIds ];*/
        //list of Project Brands 
        List<MMPJ_TOPG_Project_Brand__c> lstProjectsBrand = [select id
                                                            ,MMPJ_TOPG_Brand__c
                                                            ,MMPJ_TOPG_Project__c 
                                                            from MMPJ_TOPG_Project_Brand__c
                                                            where MMPJ_TOPG_Project__c  in:lstProjectsOfRaidIds];
        // get list ids of brands
        List<id> lstBrandIds = new list <id>();
        for  (MMPJ_TOPG_Project_Brand__c projBrand :lstProjectsBrand)
        {
            lstBrandIds.add(projBrand.MMPJ_TOPG_Brand__c) ;
        }

        //list of Project Markets 
        List<MMPJ_TOPG_Project_Market__c> lstProjectsMarket = [select id
                                                              ,MMPJ_TOPG_Market__c
                                                              ,MMPJ_TOPG_Project__c 
                                                               from MMPJ_TOPG_Project_Market__c
                                                               where MMPJ_TOPG_Project__c  in:lstProjectsOfRaidIds];
        //get list ids of Market
        List<id> lstMarketIds = new list<id>();                                                    
        for  (MMPJ_TOPG_Project_Market__c projMarket :lstProjectsMarket)
        {
            lstMarketIds.add(projMarket.MMPJ_TOPG_Market__c);
        }
        // list of names for the brands and markets                                                          
        List<MMPJ_TOPG_Brand__c> lstbrandsNames =[select  name from MMPJ_TOPG_Brand__c where id  in:lstBrandIds ];
        List<MMPJ_TOPG_Market__c> lstMarketsNames =[select name from MMPJ_TOPG_Market__c where id in:lstMarketIds ];
        for (MMPJ_TOPG_RAID__c raid:lstRaids){
            if (raid.MMPJ_TOPG_Project__c!=null){
                for (MMPJ_TOPG_Brand__c brand :lstbrandsNames){
                    if (raid.MMPJ_TOPG_Brand__c!=null && !raid.MMPJ_TOPG_Brand__c.contains(brand.name)){
                        raid.MMPJ_TOPG_Brand__c=raid.MMPJ_TOPG_Brand__c+';'+brand.name;
                    }
                    else
                    {
                        raid.MMPJ_TOPG_Brand__c=brand.name+';';
                    } 
                }
                for (MMPJ_TOPG_Market__c market :lstMarketsNames){
                    if (raid.MMPJ_TOPG_Market__c!=null && !raid.MMPJ_TOPG_Market__c.contains(market.name)){
                        raid.MMPJ_TOPG_Market__c=raid.MMPJ_TOPG_Market__c+';'+market.name;
                    }
                    else {
                        raid.MMPJ_TOPG_Market__c=market.name+';';
                    }
                }  
            }
            //BTO => begin : BMC Brand removing 
           /* else if (raid.MMPJ_TOPG_Meeting__c!=null){
                for (MMPJ_TOPG_Meeting__c meeting :lstMeetings)
                {
                    String brandName =meeting.MMPJ_TOPG_BMC__r.MMPJ_TOPG_Brand__r.name;
                    String marketName =meeting.MMPJ_TOPG_BMC__r.MMPJ_TOPG_Market__r.name;
                    if (raid.MMPJ_TOPG_Brand__c!=null && !raid.MMPJ_TOPG_Brand__c.contains(brandName))
                    {
                        raid.MMPJ_TOPG_Brand__c=raid.MMPJ_TOPG_Brand__c+';'+brandName;
                    }
                    else
                    {
                        raid.MMPJ_TOPG_Brand__c=brandName+';';
                    }
                   } 
            }*/
            //BTO => End : BMC Brand removing
        }
    }
}