objects/MMPJ_TOPG_Meeting__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <label>MMPJ_TOPG_Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All brands</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell &amp; Perrier-Jouët</fullName>
                </value>
                <value>
                    <fullName>Mumm &amp; Perrier-Jouët</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_Project__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Actuals__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Actuals (€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_DelivAttachments__c</fullName>
        <label>MMPJ_TOPG_DelivAttachments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ForecastBudget__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Forecast Budget (€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_NewProjectType__c</fullName>
        <description>The new project Type to use to create classical project or Product project</description>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Classical Project</fullName>
                    <default>true</default>
                    <label>Classical Project</label>
                </value>
                <value>
                    <fullName>Product Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Product__c</fullName>
        <description>Used for the TOP GUN project</description>
        <label>Product</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjManagAttachments__c</fullName>
        <label>MMPJ_TOPG_ProjManagAttachments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsiQCv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectTopic__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MMPJ_TOPG_ProjectType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product Launch</fullName>
                </value>
                <value>
                    <fullName>Media Campaign</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Off-trade place</fullName>
                </value>
                <value>
                    <fullName>On-trade place</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_ProjectType__c</fullName>
        <description>Used for TOP GUN Project</description>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Development</fullName>
                </value>
                <value>
                    <fullName>Co-Development</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_ProjectMilestone__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_A__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>A</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_C__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>C</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Date__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_ProjectTeamMember__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>used for the TOP GUN Project</description>
        <label>Project --</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for th TOP GUN Project</description>
        <label>Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Who__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Who</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <label>Project Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MMPJ_TOPG_RAID__c.object
<CustomObject>
    <description>Used for MMPJ TopGun app</description>
    <fields>
        <fullName>MMPJ_TOPG_Brand__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Mumm</fullName>
                </value>
                <value>
                    <fullName>Martell</fullName>
                </value>
                <value>
                    <fullName>Perrier-Jouet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Description__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Market__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Market</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the TOP GUN Project</description>
        <label>Project --</label>
        <referenceTo>MMPJ_TOPG_Project__c</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_Title__c</fullName>
        <description>Used for the TOP GUN Project</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMPJ_TOPG_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID{000000}</displayFormat>
        <label>RAID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMPJ_TOPG_NewProjectExt.cls
public with sharing class MMPJ_TOPG_NewProjectExt {
    
    public MMPJ_TOPG_Project__c theProject{get;set;}
    public integer saveComplete{get;set;}
    public string newtabTobe {get;set;}
    public string newTab{get;set;}
            
    public MMPJ_TOPG_NewProjectExt(ApexPages.StandardController controller) {
        theProject = (MMPJ_TOPG_Project__c)controller.getRecord();

        if(theProject == null || theProject.Id == null){
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a valid project.'));
        }
      else{
            theProject = [SELECT Id, Name, MMPJ_TOPG_Actuals__c,  MMPJ_TOPG_Brand__c, MMPJ_TOPG_Description__c, MMPJ_TOPG_EndDate__c, MMPJ_TOPG_ForecastBudget__c, MMPJ_TOPG_Market__c, MMPJ_TOPG_Product__c, MMPJ_TOPG_ProjectOwner__c, MMPJ_TOPG_ProjectTopic__c, MMPJ_TOPG_ProjectType__c, MMPJ_TOPG_StartDate__c,MMPJ_TOPG_DelivAttachments__c,MMPJ_TOPG_ProjManagAttachments__c,owner.email,MMPJ_TOPG_NewProjectType__c
                            ,(SELECT Id, Name, MMPJ_TOPG_Contact__c, MMPJ_TOPG_Title__c, MMPJ_TOPG_User__c, MMPJ_TOPG_Who__c FROM Project_Team_Members__r)
                            ,(SELECT Id, Name, MMPJ_TOPG_A__c, MMPJ_TOPG_C__c, MMPJ_TOPG_Date__c, MMPJ_TOPG_DeliverableDescription__c, MMPJ_TOPG_Flag__c, MMPJ_TOPG_I__c, MMPJ_TOPG_MilestoneTitle__c, MMPJ_TOPG_Project__c, MMPJ_TOPG_R__c, MMPJ_TOPG_RemainingTime__c, MMPJ_TOPG_MMPJ_Status__c, MMPJ_TOPG_Rank__c,MMPJ_TOPG_IsDefault__c  FROM Milestones__r ORDER BY MMPJ_TOPG_Rank__c)
                            ,(SELECT Id, Name,lastModifiedDate,createdBy.name,createdBy.id,ContentType from Attachments)
                            ,(SELECT Id, Name, MMPJ_TOPG_Brand__c, MMPJ_TOPG_Desc__c, MMPJ_TOPG_Description__c, MMPJ_TOPG_ExpectedDate__c, MMPJ_TOPG_Flag__c, MMPJ_TOPG_Highlight__c, MMPJ_TOPG_Market__c, MMPJ_TOPG_Meeting__c, MMPJ_TOPG_Meeting__r.name, MMPJ_TOPG_Project__c, MMPJ_TOPG_RAID__c, MMPJ_TOPG_Responsible__c, MMPJ_TOPG_Status__c, MMPJ_TOPG_Title__c, MMPJ_TOPG_Rank__c, MMPJ_TOPG_Contact__c, MMPJ_TOPG_User__c,MMPJ_TOPG_LineItem__c FROM RAIDs__r ORDER BY MMPJ_TOPG_Rank__c)
                            FROM MMPJ_TOPG_Project__c
                            WHERE Id =:theProject.Id
                        ];
       }
        saveComplete= 0;
        newTab = 'Description';
        string TabName = ApexPages.currentPage().getParameters().get('TabName');
        if(!String.IsBlank(TabName))
            newTab = TabName; 
    }
    
    public void SetNewTabValue()
    {
        newTab = newTabTobe;
        system.debug('&&&& theProject.Milestones__r ' + theProject.Milestones__r);
        if(theProject.id != null && theProject.Milestones__r.size() < 1)
        {
            
            theProject =[SELECT Id, Name, MMPJ_TOPG_Actuals__c,  MMPJ_TOPG_Brand__c, MMPJ_TOPG_Description__c, MMPJ_TOPG_EndDate__c, MMPJ_TOPG_ForecastBudget__c, MMPJ_TOPG_Market__c, MMPJ_TOPG_Product__c, MMPJ_TOPG_ProjectOwner__c, MMPJ_TOPG_ProjectTopic__c, MMPJ_TOPG_ProjectType__c, MMPJ_TOPG_StartDate__c,MMPJ_TOPG_DelivAttachments__c,MMPJ_TOPG_ProjManagAttachments__c,owner.email
                            ,(SELECT Id, Name, MMPJ_TOPG_Contact__c, MMPJ_TOPG_Title__c, MMPJ_TOPG_User__c, MMPJ_TOPG_Who__c FROM Project_Team_Members__r)
                            ,(SELECT Id, Name, MMPJ_TOPG_A__c, MMPJ_TOPG_C__c, MMPJ_TOPG_Date__c, MMPJ_TOPG_DeliverableDescription__c, MMPJ_TOPG_Flag__c, MMPJ_TOPG_I__c, MMPJ_TOPG_MilestoneTitle__c, MMPJ_TOPG_Project__c, MMPJ_TOPG_R__c, MMPJ_TOPG_RemainingTime__c, MMPJ_TOPG_MMPJ_Status__c, MMPJ_TOPG_Rank__c,MMPJ_TOPG_IsDefault__c  FROM Milestones__r ORDER BY MMPJ_TOPG_Rank__c)
                            ,(SELECT Id, Name,lastModifiedDate,createdBy.name,createdBy.id,ContentType from Attachments)
                            ,(SELECT Id, Name, MMPJ_TOPG_Brand__c, MMPJ_TOPG_Desc__c, MMPJ_TOPG_Description__c, MMPJ_TOPG_ExpectedDate__c, MMPJ_TOPG_Flag__c, MMPJ_TOPG_Highlight__c, MMPJ_TOPG_Market__c, MMPJ_TOPG_Meeting__c, MMPJ_TOPG_Meeting__r.name, MMPJ_TOPG_Project__c, MMPJ_TOPG_RAID__c, MMPJ_TOPG_Responsible__c, MMPJ_TOPG_Status__c, MMPJ_TOPG_Title__c, MMPJ_TOPG_Rank__c, MMPJ_TOPG_Contact__c, MMPJ_TOPG_User__c,MMPJ_TOPG_LineItem__c FROM RAIDs__r ORDER BY MMPJ_TOPG_Rank__c)
                            FROM MMPJ_TOPG_Project__c
                            WHERE Id =:theProject.Id
                        ];
            system.debug('&&&& theProject.Milestones__r ' + theProject.Milestones__r);
        }
    }
// public PageReference MoveUpMileStones() {
       // if(MileStonesCounter > 0)
            //listMileStones.add(SelectedTodoCounter-1, listTodos.remove(SelectedTodoCounter));

        //LoadTodo();
       // return null;
   // }
}