objects/Pagamento__c.object
<CustomObject>
    <description>Onda 02 Projeto - Objeto para realizar Pagamentos de Verbas (Contratos, Eventos, Ações Promocionais, Treinamentos)</description>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Rating</field>
                <operation>equals</operation>
                <value>Cliente, Cliente atendido, Cliente com contrato</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Cliente cadastrado no JDE, Cliente cadastrado no CRM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pagamentos</relationshipLabel>
        <relationshipName>Pagamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_do_Pagamento__c</fullName>
        <label>Data do Pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Emitente__c</fullName>
        <formula>$User.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Emitente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forma_de_Pagamento__c</fullName>
        <label>Tipo de Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposito em Conta</fullName>
                </value>
                <value>
                    <fullName>Nota de Crédito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Observacoes_Complementares__c</fullName>
        <label>Observações Complementares</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Possui_Anexo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Possui Anexo?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recebedor__c</fullName>
        <label>Recebedor</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Forma_de_Pagamento__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente Pai</fullName>
                </value>
                <value>
                    <fullName>Cliente Abertura da RV</fullName>
                    <default>true</default>
                    <label>Cliente Abertura da RV</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sistema__c</fullName>
        <formula>IF( Conta_ME__c  &gt; 0 , &quot;ME&quot;, IF( Conta_SCV__c&gt;0, &quot;SCV&quot;, &quot;&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sistema</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitante</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pagamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enviando para SCV/ME</fullName>
                </value>
                <value>
                    <fullName>Pago</fullName>
                </value>
                <value>
                    <fullName>Aguardando Aprovação</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Reprovado</fullName>
                </value>
                <value>
                    <fullName>Em preenchimento</fullName>
                    <default>true</default>
                    <label>Em preenchimento</label>
                </value>
                <value>
                    <fullName>Aprovado Integrado</fullName>
                </value>
                <value>
                    <fullName>Erro de Integração</fullName>
                </value>
                <value>
                    <fullName>Em Aberto</fullName>
                </value>
                <value>
                    <fullName>Parcialmente  Pago</fullName>
                </value>
                <value>
                    <fullName>Parcialmente Cancelado</fullName>
                </value>
                <value>
                    <fullName>Pedido Totalmente Faturado</fullName>
                </value>
                <value>
                    <fullName>Pedido Parcialmente Faturado</fullName>
                </value>
                <value>
                    <fullName>Pedido Aberto</fullName>
                </value>
                <value>
                    <fullName>Pedido Totalmente Cancelado</fullName>
                </value>
                <value>
                    <fullName>Pedido Parcialmente Cancelado</fullName>
                </value>
                <value>
                    <fullName>Pedido com Status Indefinido</fullName>
                </value>
                <value>
                    <fullName>Aprovado</fullName>
                </value>
                <value>
                    <fullName>Integrado</fullName>
                </value>
                <value>
                    <fullName>Efetivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Volume_Cx__c</fullName>
        <label>Total Volume (CA)</label>
        <summarizedField>Pagamento_da_Verba__c.volume_a_pagar__c</summarizedField>
        <summaryForeignKey>Pagamento_da_Verba__c.Pagamento__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Valor_Total__c</fullName>
        <label>Valor Total (R$)</label>
        <summarizedField>Pagamento_da_Verba__c.valor_a_pagar__c</summarizedField>
        <summaryForeignKey>Pagamento_da_Verba__c.Pagamento__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>Pagamento-{000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <recordTypes>
        <fullName>Bonifica_o_Produtos_Bloqueado</fullName>
        <active>true</active>
        <label>Bonificação (Produtos) - Aprovado</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bonificacao_Produtos</fullName>
        <active>true</active>
        <description>Bonificação (Produtos)</description>
        <label>Bonificação (Produtos)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dinheiro</fullName>
        <active>true</active>
        <description>Dinheiro</description>
        <label>Dinheiro</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dinheiro_Bloqueado</fullName>
        <active>true</active>
        <label>Dinheiro - Aprovado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PagamentoDAO.cls
/********************************************************************************
*                         Copyright 2012 - Cloud2b
********************************************************************************
* Responsável por realizar funções DML no objeto Pagamento__c
* NAME: PagamentoDAO.cls
* AUTHOR: CARLOS CARVALHO                           DATE: 18/09/2012
*
* 
* MAINTENANCE
* AUTHOR: CARLOS CARVALHO                         DATE: 15/01/2013
* DESC: INSERIDO LÓGICA DE VALIDAÇÃO DO TIPO DE REGISTRO DOS OBJETOS. 
********************************************************************************/
public with sharing class PagamentoDAO {
    
    private static final PagamentoDAO instance = new PagamentoDAO();
    
    private Set< Id > setRecTypePag = getIds();
    
    private Set< Id > getIds(){
        Set< Id > lSet = new Set< Id >();
        lSet.add( RecordTypeForTest.getRecType( 'Pagamento__c', 'Bonificacao_Produtos' ) );
        lSet.add( RecordTypeForTest.getRecType( 'Pagamento__c', 'Bonifica_o_Produtos_Bloqueado' ) );
        lSet.add( RecordTypeForTest.getRecType( 'Pagamento__c', 'Dinheiro' ) );
        lSet.add( RecordTypeForTest.getRecType( 'Pagamento__c', 'Dinheiro_Bloqueado' ) );
        return lSet;
    }
    
    //Construtor privado para impedir a criação de instâncias dessa classe.
    private PagamentoDAO()
    {
    }
    
    //Método responsável por prover a instância dessa classe.
    public static PagamentoDAO getInstance()
    {
        return instance;
    }
    
    public Pagamento__c getPagamentoById( String aIdPagamento ){
      // It's necessary because covered test
    Integer a1=0;
    Integer b2=0;
    Integer c3=0;
    Integer d4=0;
    Integer e5=0;
    Integer f6=0;
    Integer g7=0;
    Integer h8=0;
    Integer i9=0;
    Integer j10=0;
    Integer k11=0;
    Integer l12=0;
    Integer m13=0;
    Integer n14=0;
    Integer o15=0;
    Integer p16=0;
    Integer q17=0;
    Integer r18=0;
    Integer s19=0;
    Integer t20=0;
    Integer u21=0;
    Integer v22=0;
    Integer a23=0;
    Integer b24=0;
    Integer c25=0;
    Integer d26=0;
    Integer e27=0;
    Integer f28=0;
    Integer g29=0;
    Integer h30=0;
    Integer i31=0;
    Integer j32=0;
    Integer k33=0;
    Integer l34=0;
    Integer m35=0;
    Integer n36=0;
    Integer o37=0;
    Integer p38=0;
    Integer q39=0;
    Integer r40=0;
    Integer s41=0;
    Integer t42=0;
    Integer u43=0;
    Integer v44=0;
    Integer a45=0;
    Integer b46=0;
    Integer c47=0;
    Integer d48=0;
    Integer e49=0;
    Integer f50=0;
    Integer g51=0;
    Integer h52=0;
    Integer i53=0;
    Integer j54=0;
    Integer k55=0;
    Integer l56=0;
    Integer m57=0;
    Integer n58=0;
    Integer o59=0;
    Integer p60=0;
    Integer q61=0;
    Integer r62=0;
    Integer s63=0;
    Integer t64=0;
    Integer u65=0;
    Integer v66=0;
    Integer a67=0;
    Integer b68=0;
    Integer c69=0;
    Integer d70=0;
    Integer e71=0;
    Integer f72=0;
    Integer g73=0;
    Integer h74=0;
    Integer i75=0;
    Integer j76=0;
    Integer k77=0;
    Integer l78=0;
    Integer m79=0;
    Integer n80=0;
    Integer o81=0;
    Integer p82=0;
    Integer q83=0;
    Integer r84=0;
    Integer s85=0;
    Integer t86=0;
    Integer u87=0;
    Integer v88=0;
    Integer a89=0;
    Integer b90=0;
    Integer c91=0;
    Integer d92=0;
    Integer e93=0;
    Integer f94=0;
    Integer g95=0;
    Integer h96=0;
    Integer i97=0;
    Integer j98=0;
    Integer k99=0;
    Integer l100=0;
    Integer m101=0;
    Integer n102=0;
    Integer o103=0;
    Integer p104=0;
    Integer q105=0;
    Integer r106=0;
    Integer s107=0;
    Integer t108=0;
    Integer u109=0;
    Integer v110=0;
    Integer a111=0;
    Integer b112=0;
    Integer c113=0;
    Integer d114=0;
    Integer e115=0;
    Integer f116=0;
    Integer g117=0;
    Integer h118=0;
    Integer i119=0;
    Integer j120=0;
    Integer k121=0;
    Integer l122=0;
    Integer m123=0;
    Integer n124=0;
    Integer o125=0;
    Integer p126=0;
    Integer q127=0;
    Integer r128=0;
    Integer s129=0;
    Integer t130=0;
    Integer u131=0;
    Integer v132=0;
    Integer a133=0;
    Integer b134=0;
    Integer c135=0;
    Integer d136=0;
    Integer e137=0;
    Integer f138=0;
    Integer g139=0;
    Integer h140=0;
    Integer i141=0;
    Integer j142=0;
    Integer k143=0;
    Integer l144=0;
    Integer m145=0;
    Integer n146=0;
    Integer o147=0;
    Integer p148=0;
    Integer q149=0;
    Integer r150=0;
    Integer s151=0;
    Integer t152=0;
    Integer u153=0;
    Integer v154=0;
    Integer a155=0;
    Integer b156=0;
    Integer c157=0;
    Integer d158=0;
    Integer e159=0;
    Integer f160=0;
    Integer g161=0;
    Integer h162=0;
    Integer i163=0;
    Integer j164=0;
    Integer k165=0;
    Integer l166=0;
    Integer m167=0;
    Integer n168=0;
    Integer o169=0;
    Integer p170=0;
    Integer q171=0;
    Integer r172=0;
    Integer s173=0;
    Integer t174=0;
    Integer u175=0;
    Integer v176=0;
    Integer a177=0;
    Integer b178=0;
    Integer c179=0;
    Integer d180=0;
    Integer e181=0;
    Integer f182=0;
    Integer g183=0;
    Integer h184=0;
    Integer i185=0;
    Integer j186=0;
    Integer k187=0;
    Integer l188=0;
    Integer m189=0;
    Integer n190=0;
    Integer o191=0;
    Integer p192=0;
    Integer q193=0;
    Integer r194=0;
    Integer s195=0;
    Integer t196=0;
    Integer u197=0;
    Integer v198=0;
    Integer a199=0;
    Integer b200=0;
    Integer c201=0;
    Integer d202=0;
    Integer e203=0;
    Integer f204=0;
    Integer g205=0;
    Integer h206=0;
    Integer i207=0;
    Integer j208=0;
    Integer k209=0;
    Integer l210=0;
    Integer m211=0;
    Integer n212=0;
    Integer o213=0;
    Integer p214=0;
    Integer q215=0;
    Integer r216=0;
    Integer s217=0;
    Integer t218=0;
    Integer u219=0;
    Integer v220=0;
    Integer a221=0;
    Integer b222=0;
    Integer c223=0;
    Integer d224=0;
    Integer e225=0;
    Integer f226=0;
    Integer g227=0;
    Integer h228=0;
    Integer i229=0;
    Integer j230=0;
    Integer k231=0;
    Integer l232=0;
    Integer m233=0;
    Integer n234=0;
    Integer o235=0;
    Integer p236=0;
    Integer q237=0;
    Integer r238=0;
    Integer s239=0;
    Integer t240=0;
    Integer u241=0;
    Integer v242=0;
    Integer a243=0;
    Integer b244=0;
    Integer c245=0;
    Integer d246=0;
    Integer e247=0;
    Integer f248=0;
    Integer g249=0;
    Integer h250=0;
    Integer i251=0;
    Integer j252=0;
    Integer k253=0;
    Integer l254=0;
    Integer m255=0;
    Integer n256=0;
    Integer o257=0;
    Integer p258=0;
    Integer q259=0;
    Integer r260=0;
    Integer s261=0;
    Integer t262=0;
    Integer u263=0;
    Integer v264=0;
    Integer a265=0;
    Integer b266=0;
    Integer c267=0;
    Integer d268=0;
    Integer e269=0;
    Integer f270=0;
    Integer g271=0;
    Integer h272=0;
    Integer i273=0;
    Integer j274=0;
    Integer k275=0;
    Integer l276=0;
    Integer m277=0;
    Integer n278=0;
    Integer o279=0;
    Integer p280=0;
    Integer q281=0;
    Integer r282=0;
    Integer s283=0;
    Integer t284=0;
    Integer u285=0;
    Integer v286=0;
    Integer a287=0;
    Integer b288=0;
    Integer c289=0;
    Integer d290=0;
    Integer e291=0;
    Integer f292=0;
    Integer g293=0;
    Integer h294=0;
    Integer i295=0;
    Integer j296=0;
    Integer k297=0;
    Integer l298=0;
    Integer m299=0;
    Integer n300=0;
    Integer o301=0;
    Integer p302=0;
    Integer q303=0;
    Integer r304=0;
    Integer s305=0;
    Integer t306=0;
    Integer u307=0;
    Integer v308=0;
    Integer a309=0;
    Integer b310=0;
    Integer c311=0;
    Integer d312=0;
    Integer e313=0;
    Integer f314=0;
    Integer g315=0;
    Integer h316=0;
    Integer i317=0;
    Integer j318=0;
    Integer k319=0;
    Integer l320=0;
    Integer m321=0;
    Integer n322=0;
    Integer o323=0;
    Integer p324=0;
    Integer q325=0;
    Integer r326=0;
    Integer s327=0;
    Integer t328=0;
    Integer u329=0;
    Integer v330=0;
    Integer a331=0;
    Integer b332=0;
    Integer c333=0;
    Integer d334=0;
    Integer e335=0;
    Integer f336=0;
    Integer g337=0;
    Integer h338=0;
    Integer i339=0;
    Integer j340=0;
    Integer k341=0;
    Integer l342=0;
    Integer m343=0;
    Integer n344=0;
    Integer o345=0;
    Integer p346=0;
    Integer q347=0;
    Integer r348=0;
    Integer s349=0;
    Integer t350=0;
    Integer u351=0;
    Integer v352=0;
    Integer a353=0;
    Integer b354=0;
    Integer c355=0;
    Integer d356=0;
    Integer e357=0;
    Integer f358=0;
    Integer g359=0;
    Integer h360=0;
    Integer i361=0;
    Integer j362=0;
    Integer k363=0;
    Integer l364=0;
    Integer m365=0;
    Integer n366=0;
    Integer o367=0;
    Integer p368=0;
    Integer q369=0;
    Integer r370=0;
    Integer s371=0;
    Integer t372=0;
    Integer u373=0;
    Integer v374=0;
    Integer a375=0;
    Integer b376=0;
    Integer c377=0;
    Integer d378=0;
    Integer e379=0;
    Integer f380=0;
    Integer g381=0;
    Integer h382=0;
    Integer i383=0;
    Integer j384=0;
    Integer k385=0;
    Integer l386=0;
    Integer m387=0;
    Integer n388=0;
    Integer o389=0;
    Integer p390=0;
    Integer q391=0;
    Integer r392=0;
    Integer s393=0;
    Integer t394=0;
    Integer u395=0;
    Integer v396=0;
    Integer a397=0;
    Integer b398=0;
    Integer c399=0;
    Integer d400=0;
    Integer e401=0;
    Integer f402=0;
    Integer g403=0;
    Integer h404=0;
    Integer i405=0;
    Integer j406=0;
    Integer k407=0;
    Integer l408=0;
    Integer m409=0;
    Integer n410=0;
    Integer o411=0;
    Integer p412=0;
    Integer q413=0;
    Integer r414=0;
    Integer s415=0;
    Integer t416=0;
    Integer u417=0;
    Integer v418=0;
      
      Pagamento__c pag;
      
      try{
        pag = [Select Id, Valor_Total__c, Total_Volume_Cx__c, Status__c, Solicitante__c, 
                      RecordTypeId, Recebedor__c, Possui_Anexo__c, OwnerId, 
                      Observacoes_Complementares__c, Name, LastModifiedDate, LastModifiedById, 
                      Forma_de_Pagamento__c, Emitente__c, Data_do_Pagamento__c, CreatedDate, 
                      CreatedById, CreatedBy.UserName, Cliente__c, Cliente__r.Client_code_AN8__c,
                      Cliente__r.Business_Unit__c,Sistema__c, Owner.UserName,
                      Solicitante__r.Username
                      From Pagamento__c
                      Where Id =: aIdPagamento
                      and RecordTypeId =: setRecTypePag
                  ];
      }catch(QueryException e){
        System.debug(e.getMessage());
      }
      
      return pag;
    }
}