objects/Parcela__c.object
<CustomObject>
    <label>Parcela</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Número da parcela</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcelas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RCP_Receipt_ARG__c.object
<CustomObject>
    <label>LAT Receipt</label>
    <nameField>
        <label>Receipt No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Receipts</pluralLabel>
    <recordTypes>
        <fullName>RCP_ReceiptGeneratedDepositDone_AR</fullName>
        <active>true</active>
        <label>Receipt generated deposit done AR</label>
    </recordTypes>
    <recordTypes>
        <fullName>RCP_ReceiptGeneratedDepositDone_UY</fullName>
        <active>true</active>
        <label>Receipt generated deposit done UY</label>
    </recordTypes>
    <recordTypes>
        <fullName>RCP_ReceiptGeneratedDepositPending_AR</fullName>
        <active>true</active>
        <label>Receipt generated deposit pending AR</label>
    </recordTypes>
    <recordTypes>
        <fullName>RCP_ReceiptGeneratedDepositPending_UY</fullName>
        <active>true</active>
        <label>Receipt generated deposit pending UY</label>
    </recordTypes>
    <recordTypes>
        <fullName>Receipt_withholding_certificates_AR</fullName>
        <active>true</active>
        <label>Receipt withholding certificates AR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Titulos__c.object
<CustomObject>
    <fields>
        <fullName>ActualDeliveryDate_AR__c</fullName>
        <description>Actual delivery date provided by Logistics via interface to JDE</description>
        <label>Actual Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cliente__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Títulos em aberto</relationshipLabel>
        <relationshipName>Titulos_de_cobranca</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_id_pk__c</fullName>
        <externalId>true</externalId>
        <label>Internal_id_pk</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>codigoCia__c</fullName>
        <label>Código companhia</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dataEmissao__c</fullName>
        <label>Data emissão</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dataVencimentoAtual__c</fullName>
        <label>Data vencimento</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dataVencimentoOriginal__c</fullName>
        <label>Data venc. original</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>numeroDocumento__c</fullName>
        <label>No. documento</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>observacoesTitulo__c</fullName>
        <label>Observação</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>parcela__c</fullName>
        <label>Parcela</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>valorOriginalTitulo__c</fullName>
        <label>Valor original título</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>valorSaldo__c</fullName>
        <label>Valor Saldo</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VFC01_ReceiptSelectController_AR_TEST.cls
/*******************************************************************************************
*   Company:Valuenet    Developer:   Tomás Etchegaray               Date:05/04/2013        *
*******************************************************************************************/
@isTest
public with sharing class VFC01_ReceiptSelectController_AR_TEST {
    
@isTest (seealldata=true)   
    static void unitTest() {
        
        string recordOffTradeArg = Global_RecordTypeCache.getRtId('Account'+'ACC_1_OffTrade_ARG');
        
        Account acc = new Account(
        RecordTypeId = recordOffTradeArg, 
        CNPJ__c = '20354266645',
        Name = 'testAccount',
        Type = 'Prospect_ARG',
        Corporate_Name__c = 'test',
        Channel_Type__c = 'Direto',
        Segmentation_Type_on_trade__c = 'Restaurant_ARG',
        Sub_Channel__c = 'Delicatessen',
        AddressLine1_AR__c= 'test',
        Shipping_Neighbourhood__c = 'test',
        Revenue_Neighbourhood__c = 'test',
        Billing_Neighbourhood__c ='test',
        Shipping_Country__c ='test',
        Revenue_Country__c ='test',
        Billing_Country__c ='test'
        );
        
        insert acc;
        test.startTest();
         Titulos__c tit = new Titulos__c(
         
         Cliente__c = acc.id,
         Internal_id_pk__c= 'asd',
         codigoCia__c = '123',
         dataVencimentoAtual__c = date.today(),
         dataVencimentoOriginal__c = date.today(),
         dataEmissao__c = date.today(),
         ActualDeliveryDate_AR__c = date.today(),
         numeroDocumento__c = 123,
         observacoesTitulo__c = 'ASD',
         valorOriginalTitulo__c = 123,
         valorSaldo__c = 123,
         parcela__c = '123'
         );
         
         insert tit;
         
      //  ApexPages.standardController TestController = new ApexPages.standardController(acc.id);
        
        Apexpages.currentPage().getParameters().put('idAcc', acc.Id); 
        Apexpages.currentPage().getParameters().put('idArray', tit.Id);
        
        
        VFC01_ReceiptSelectController_AR TestController = new VFC01_ReceiptSelectController_AR();
        string record = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c'+'RCP_ReceiptGeneratedDepositDone_AR');
        TestController.value = record;
        TestController.doContinue();
        TestController.cancel();
        test.stopTest();
        
    }
@isTest (seealldata=true)
    static void unitTest2() {
        
        string recordOffTradeArg = Global_RecordTypeCache.getRtId('Account'+'ACC_1_OffTrade_ARG');
        
        Account acc = new Account(
        RecordTypeId = recordOffTradeArg, 
        CNPJ__c = '20354266645',
        Name = 'testAccount',
        Type = 'Prospect_ARG',
        Corporate_Name__c = 'test',
        Channel_Type__c = 'Direto',
        Segmentation_Type_on_trade__c = 'Restaurant_ARG',
        Sub_Channel__c = 'Delicatessen',
        AddressLine1_AR__c= 'test',
        Shipping_Neighbourhood__c = 'test',
        Revenue_Neighbourhood__c = 'test',
        Billing_Neighbourhood__c ='test',
        Shipping_Country__c ='test',
        Revenue_Country__c ='test',
        Billing_Country__c ='test'
        );
        
        insert acc;
        
         Titulos__c tit = new Titulos__c(
         
         Cliente__c = acc.id,
         Internal_id_pk__c= 'asd',
         codigoCia__c = '123',
         dataVencimentoAtual__c = date.today(),
         dataVencimentoOriginal__c = date.today(),
         dataEmissao__c = date.today(),
         ActualDeliveryDate_AR__c = date.today(),
         numeroDocumento__c = 123,
         observacoesTitulo__c = 'ASD',
         valorOriginalTitulo__c = 123,
         valorSaldo__c = 123,
         parcela__c = '123'
         );
         
         insert tit;
         
      //  ApexPages.standardController TestController = new ApexPages.standardController(acc.id);
        
        Apexpages.currentPage().getParameters().put('idAcc', acc.Id); 
        Apexpages.currentPage().getParameters().put('idArray', tit.Id);
        
        
        VFC01_ReceiptSelectController_AR TestController = new VFC01_ReceiptSelectController_AR();
        string record = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c'+'RCP_ReceiptGeneratedDepositPending_AR');
        TestController.value = record;
        TestController.doContinue();
        test.startTest();
        record = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c'+'Receipt_withholding_certificates_AR');
        TestController.value = record;
        TestController.doContinue();
        record = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c'+'RCP_ReceiptGeneratedDepositDone_UY');
        TestController.value = record;
        TestController.doContinue();
        record = Global_RecordTypeCache.getRtId('RCP_Receipt_ARG__c'+'RCP_ReceiptGeneratedDepositPending_UY');
        TestController.value = record;
        TestController.doContinue();
        TestController.decodeMessage('ENTITY_IS_LOCKED');
        TestController.decodeMessage('REQUIRED_FIELD_MISSING');
        TestController.decodeMessage('blahblahblah');
        test.stopTest();
    }

}