objects/Planejamento__c.object
<CustomObject>
    <fields>
        <fullName>Ano_de_Referencia__c</fullName>
        <label>Ano de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                    <label>2014</label>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>M_s_de_Ref_rencia__c</fullName>
        <label>Mês de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Nome do Planejamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamentos de Visitas</pluralLabel>
    <recordTypes>
        <fullName>LAT_MX_PLV_NewPlanning</fullName>
        <active>true</active>
        <label>MX New Planning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAT_MX_PlansVisitsAutomatically__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if visits should be generated automatically for this user when a Planing is created.</description>
        <label>Planea Visitas Automaticamente?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <fields>
        <fullName>Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Visitas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_da_Visita__c</fullName>
        <label>Data da Visita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hora_da_Visita__c</fullName>
        <label>Hora da Visita</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>00:00</fullName>
                </value>
                <value>
                    <fullName>01:00</fullName>
                </value>
                <value>
                    <fullName>02:00</fullName>
                </value>
                <value>
                    <fullName>03:00</fullName>
                </value>
                <value>
                    <fullName>04:00</fullName>
                </value>
                <value>
                    <fullName>05:00</fullName>
                </value>
                <value>
                    <fullName>06:00</fullName>
                </value>
                <value>
                    <fullName>07:00</fullName>
                </value>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
                <value>
                    <fullName>19:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_MX_ClienteChannel__c</fullName>
        <label>Client Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Trade</fullName>
                </value>
                <value>
                    <fullName>Off Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_MX_Type__c</fullName>
        <label>Type MX</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>LAT_MX_ClienteChannel__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Activity Negotiation - On Trade</fullName>
                </value>
                <value>
                    <fullName>Activity Negotiation - Off Trade</fullName>
                </value>
                <value>
                    <fullName>Sales Negotiation</fullName>
                </value>
                <value>
                    <fullName>Follow Up - On Trade</fullName>
                </value>
                <value>
                    <fullName>Follow Up - Off Trade</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Relationship - On Trade</fullName>
                </value>
                <value>
                    <fullName>Relationship - Off Trade</fullName>
                </value>
                <value>
                    <fullName>Prospecting - On Trade</fullName>
                </value>
                <value>
                    <fullName>Prospecting - Off Trade</fullName>
                </value>
                <value>
                    <fullName>Negociación - Catalogación</fullName>
                </value>
                <value>
                    <fullName>Negociación - Cuota de volumen</fullName>
                </value>
                <value>
                    <fullName>Negociación - Instrucción de Operación</fullName>
                </value>
                <value>
                    <fullName>Negociación - Seguimiento al plan</fullName>
                </value>
                <value>
                    <fullName>Negociación - Entrega de incentivos</fullName>
                </value>
                <value>
                    <fullName>Supervisar activaciones - Activación</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Uniformes</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad – Menú</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Coctelería</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Mantenimiento</fullName>
                </value>
                <value>
                    <fullName>Negociación - Catalogación Off</fullName>
                </value>
                <value>
                    <fullName>Negociación - Cuota de volumen Off</fullName>
                </value>
                <value>
                    <fullName>Negociación - Instrucción Operación Off</fullName>
                </value>
                <value>
                    <fullName>Negociación - Seguimiento al plan Off</fullName>
                </value>
                <value>
                    <fullName>Negociación - Entrega de incentivos Off</fullName>
                </value>
                <value>
                    <fullName>Supervisar activaciones - Activación Off</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Uniformes Off</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad – Menú Off</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Coctelería Off</fullName>
                </value>
                <value>
                    <fullName>Revisar visibilidad - Mantenimiento Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planejamento__c</fullName>
        <label>Planejamento</label>
        <referenceTo>Planejamento__c</referenceTo>
        <relationshipLabel>Visitas</relationshipLabel>
        <relationshipName>Visitas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resumo_da_Visita__c</fullName>
        <label>Action Plan / Visit Goal</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <recordTypes>
        <fullName>LAT_MX_VTS_PlannedVisit</fullName>
        <active>true</active>
        <label>MX Planned Visit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_MX_AP01_Visita_TEST.cls
@isTest 

public with sharing class LAT_MX_AP01_Visita_TEST {

    static testMethod void unitTest() {

        User u = new User();
        u = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX_Creditos y Cobranzas');
        insert u;
        User u2 = new User();
        u2 = LAT_TestUserAdmin.userWithAdminPorf ('Nome3','Sobrenome3','NSobre3','nome3@sobrenome.com','PriceCalculationInterface3@mail.com','133jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u2.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_Vendedor');
        u2.LAT_MX_PlansVisitsAutomatically__c = true;
        insert u2;
        test.startTest();
        
        System.runAs(u2){
                
        String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
        
        Account acc = new Account(
            Name = 'TEST',
            AccountNumber = '1000', 
            Type = 'Payer',
            Phone = '1-11-1111-1111',
            Fax = '11-1111-1111',
            Notes__c = 'TEST',
            AddressLine1_AR__c = 'TEST',
            CNPJ__c = 'LOZM701213E52',
            Corporate_Name__c = 'TEST',
            Channel__c = 'WS',
            Segmentation_Type_on_trade__c = 'MOP',
            Frequency_of_Visits__c = 'Mensual',
            RecordTypeId = rtOffMX
        );
        insert acc;
        
        String rtpla = Global_RecordTypeCache.getRtId('Planejamento__c' + 'LAT_MX_PLV_NewPlanning');
        
        Planejamento__c pla = new Planejamento__c(
            RecordTypeId = rtpla,
            Name = 'test',
            Ano_de_Referencia__c = string.ValueOf(date.today().year()), 
            M_s_de_Ref_rencia__c = 'Dezembro'
        );
        insert pla;
    

        
            String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
            Visitas__c visit = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit;
       
        
        //String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
        Visitas__c visit2 = new Visitas__c(
            Conta__c = acc.Id,
            Name = 'test',
            Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
            Hora_da_Visita__c = '08:00',
            Planejamento__c = pla.Id,
            Resumo_da_Visita__c = 'test',
            LAT_MX_ClienteChannel__c = 'Off Trade',
            LAT_MX_Type__c = 'Collections'        
        );
        insert visit2;
         }
        
        test.stopTest();  

        
    }

    static testMethod void unitTest2() {

        User u = new User();
        u = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX_Creditos y Cobranzas');
        insert u;
        User u2 = new User();
        u2 = LAT_TestUserAdmin.userWithAdminPorf ('Nome3','Sobrenome3','NSobre3','nome3@sobrenome.com','PriceCalculationInterface3@mail.com','133jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u2.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_Vendedor');
        u2.LAT_MX_PlansVisitsAutomatically__c = true;
        insert u2;
        test.startTest();
        Visitas__c visit;
        
        System.runAs(u){
                
            String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
            
            Account acc = new Account(
                Name = 'TEST',
                AccountNumber = '1000', 
                Type = 'Payer',
                Phone = '1-11-1111-1111',
                Fax = '11-1111-1111',
                Notes__c = 'TEST',
                AddressLine1_AR__c = 'TEST',
                CNPJ__c = 'LOZM701213E52',
                Corporate_Name__c = 'TEST',
                Channel__c = 'WS',
                Segmentation_Type_on_trade__c = 'MOP',
                Frequency_of_Visits__c = 'Mensual',
                RecordTypeId = rtOffMX
            );
            insert acc;
            
            String rtpla = Global_RecordTypeCache.getRtId('Planejamento__c' + 'LAT_MX_PLV_NewPlanning');
            
            Planejamento__c pla = new Planejamento__c(
                RecordTypeId = rtpla,
                Name = 'test',
                Ano_de_Referencia__c = string.ValueOf(date.today().year()), 
                M_s_de_Ref_rencia__c = 'Dezembro'
            );
            insert pla;
        

            
            String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
            visit = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit;
         


           
            
            //String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
                
            Visitas__c visit2 = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit2;
            List<Visitas__c> lista = new List<Visitas__c>();
            lista.add(visit);
            lista.add(visit2);
            LAT_MX_AP01_Visita.deleteValidation(lista);
        }
        visit.LAT_MX_Type__c = 'Collections;Follow Up - On Trade';
        update visit;
        test.stopTest();  

        
    }
    static testMethod void unitTestB() {

        Utils.setMigrationDoneTest(true);
        User u = new User();
        u = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_CreditosyCobranzas');
        insert u;
        User u2 = new User();
        u2 = LAT_TestUserAdmin.userWithAdminPorf ('Nome3','Sobrenome3','NSobre3','nome3@sobrenome.com','PriceCalculationInterface3@mail.com','133jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u2.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_Vendedor');
        u2.LAT_MX_PlansVisitsAutomatically__c = true;
        insert u2;
        
        test.startTest();

        Utils.setMigrationDoneTest(true);        
        System.runAs(u2){
                
        String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
        
        Account acc = new Account(
            Name = 'TEST',
            AccountNumber = '1000', 
            Type = 'Payer',
            Phone = '1-11-1111-1111',
            Fax = '11-1111-1111',
            Notes__c = 'TEST',
            AddressLine1_AR__c = 'TEST',
            CNPJ__c = 'LOZM701213E52',
            Corporate_Name__c = 'TEST',
            Channel__c = 'WS',
            Segmentation_Type_on_trade__c = 'MOP',
            Frequency_of_Visits__c = 'Mensual',
            RecordTypeId = rtOffMX
        );
        insert acc;
        
        String rtpla = Global_RecordTypeCache.getRtId('Planejamento__c' + 'LAT_MX_PLV_NewPlanning');
        
        Planejamento__c pla = new Planejamento__c(
            RecordTypeId = rtpla,
            Name = 'test',
            Ano_de_Referencia__c = string.ValueOf(date.today().year()), 
            M_s_de_Ref_rencia__c = 'Dezembro'
        );
        insert pla;
    

        
            String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
            Visitas__c visit = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit;
       
        
        //String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
        Visitas__c visit2 = new Visitas__c(
            Conta__c = acc.Id,
            Name = 'test',
            Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
            Hora_da_Visita__c = '08:00',
            Planejamento__c = pla.Id,
            Resumo_da_Visita__c = 'test',
            LAT_MX_ClienteChannel__c = 'Off Trade',
            LAT_MX_Type__c = 'Collections'        
        );
        insert visit2;
         }
        
        test.stopTest();  

        
    }

    static testMethod void unitTest2B() {

        Utils.setMigrationDoneTest(true);
        User u = new User();
        u = LAT_TestUserAdmin.userWithAdminPorf ('Nome2','Sobrenome2','NSobre2','nome2@sobrenome.com','PriceCalculationInterface@mail.com','123jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_CreditosyCobranzas');
        insert u;
        User u2 = new User();
        u2 = LAT_TestUserAdmin.userWithAdminPorf ('Nome3','Sobrenome3','NSobre3','nome3@sobrenome.com','PriceCalculationInterface3@mail.com','133jjjuuu2','ISO-8859-1','GMT','en_Us','en_Us','234','BR'); 
        u2.profileId = LAT_GlobalProfileCache.getProfileIdByName('LAT_MX2_Vendedor');
        u2.LAT_MX_PlansVisitsAutomatically__c = true;
        insert u2;
        test.startTest();

        Utils.setMigrationDoneTest(true);
        Visitas__c visit;
        
        System.runAs(u){
                
            String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
            
            Account acc = new Account(
                Name = 'TEST',
                AccountNumber = '1000', 
                Type = 'Payer',
                Phone = '1-11-1111-1111',
                Fax = '11-1111-1111',
                Notes__c = 'TEST',
                AddressLine1_AR__c = 'TEST',
                CNPJ__c = 'LOZM701213E52',
                Corporate_Name__c = 'TEST',
                Channel__c = 'WS',
                Segmentation_Type_on_trade__c = 'MOP',
                Frequency_of_Visits__c = 'Mensual',
                RecordTypeId = rtOffMX
            );
            insert acc;
            
            String rtpla = Global_RecordTypeCache.getRtId('Planejamento__c' + 'LAT_MX_PLV_NewPlanning');
            
            Planejamento__c pla = new Planejamento__c(
                RecordTypeId = rtpla,
                Name = 'test',
                Ano_de_Referencia__c = string.ValueOf(date.today().year()), 
                M_s_de_Ref_rencia__c = 'Dezembro'
            );
            insert pla;
        

            
            String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
            
            visit = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit;
         


           
            
            //String rtvis = Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_PlannedVisit');
                
            Visitas__c visit2 = new Visitas__c(
                Conta__c = acc.Id,
                Name = 'test',
                Data_da_Visita__c = date.newInstance(date.today().year(),12,31),
                Hora_da_Visita__c = '08:00',
                Planejamento__c = pla.Id,
                Resumo_da_Visita__c = 'test',
                LAT_MX_ClienteChannel__c = 'Off Trade',
                LAT_MX_Type__c = 'Collections'        
            );
            insert visit2;
            List<Visitas__c> lista = new List<Visitas__c>();
            lista.add(visit);
            lista.add(visit2);
            LAT_MX_AP01_Visita.deleteValidation(lista);
        }
        visit.LAT_MX_Type__c = 'Collections;Follow Up - On Trade';
        update visit;
        test.stopTest();  

        
    }
}