objects/Planejamento__c.object
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Nome do Planejamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamentos de Visitas</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <fields>
        <fullName>Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Visitas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_da_Visita__c</fullName>
        <label>Data da Visita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hora_da_Visita__c</fullName>
        <label>Hora da Visita</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>00:00</fullName>
                </value>
                <value>
                    <fullName>01:00</fullName>
                </value>
                <value>
                    <fullName>02:00</fullName>
                </value>
                <value>
                    <fullName>03:00</fullName>
                </value>
                <value>
                    <fullName>04:00</fullName>
                </value>
                <value>
                    <fullName>05:00</fullName>
                </value>
                <value>
                    <fullName>06:00</fullName>
                </value>
                <value>
                    <fullName>07:00</fullName>
                </value>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
                <value>
                    <fullName>19:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planejamento__c</fullName>
        <label>Planejamento</label>
        <referenceTo>Planejamento__c</referenceTo>
        <relationshipLabel>Visitas</relationshipLabel>
        <relationshipName>Visitas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resumo_da_Visita__c</fullName>
        <label>Action Plan / Visit Goal</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Semana__c</fullName>
        <formula>MOD(FLOOR( ( Data_da_Visita__c -DATEVALUE(text(year( Data_da_Visita__c))+&quot;-&quot;+text(month(Data_da_Visita__c))+ &quot;-01&quot; ))/7),52)+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Semana</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <recordTypes>
        <fullName>BRA_Standard</fullName>
        <active>true</active>
        <description>Brazil standard record type</description>
        <label>BRA Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditaVisitasController.cls
/********************************************************************************
*                         Copyright 2012 - Cloud2b
********************************************************************************
* Controller da pagina 
* NAME: EditaVisitasController.cls
* AUTHOR: ROGÉRIO ALVARENGA                       DATE: 
*
*
* MAINTENANCE: INSERIDO LÓGICA DE VALIDAÇÃO DO TIPO DE REGISTRO DOS OBJETOS.
* AUTHOR: CARLOS CARVALHO                         DATE: 14/01/2013 
********************************************************************************/
public class EditaVisitasController {
      /*
      public static List<Visitas__c> getVisitas() {
          Id idRecTypeVis = RecordTypeForTest.getRecType( 'Visitas__c', 'BRA_Standard' );
          
          return [ SELECT Id, Conta__c, Data_da_Visita__c,Hora_da_Visita__c,Planejamento__c,Resumo_da_Visita__c, Semana__c
              FROM Visitas__c WHERE RecordTypeId =: idRecTypeVis ];
      }
      */
}