objects/PRH_Brand_Criteria__c.object
<CustomObject>
    <description>Brand Criteria</description>
    <fields>
        <fullName>PRH_Collect__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collect</label>
        <referenceTo>PRH_Collect__c</referenceTo>
        <relationshipLabel>Le Cercle Brands</relationshipLabel>
        <relationshipName>Le_Cercle_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Le Cercle Brands</label>
    <nameField>
        <displayFormat>BCN-{000000000}</displayFormat>
        <label>Brand Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Le Cercle Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PRH_Brand_Luxury_Brand__c.object
<CustomObject>
    <description>PRE - Iconic Platform</description>
    <fields>
        <fullName>PRH_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This box is checked if the Iconic Brand is Active</inlineHelpText>
        <label>Active Brand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRH_Competitor_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor Brand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRH_PIM_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used for integration with SFA</description>
        <externalId>true</externalId>
        <label>PIM ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PRH_Sequence__c</fullName>
        <label>Sequence</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Iconic Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iconic Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PRH_Collect__c.object
<CustomObject>
    <description>Le Cercle Iconic Platform Application Object</description>
    <fields>
        <fullName>PRH_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRH_Number_of_Pernod_Ricard_products__c</fullName>
        <label>Number of Pernod Ricard products</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Collect</label>
    <nameField>
        <displayFormat>PRHC-{00000000}</displayFormat>
        <label>Collect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PRH_Competitor_Brands__c.object
<CustomObject>
    <fields>
        <fullName>PRH_Collect__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collect</label>
        <referenceTo>PRH_Collect__c</referenceTo>
        <relationshipLabel>Competitor Brands</relationshipLabel>
        <relationshipName>Competitor_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor Brand</label>
    <nameField>
        <displayFormat>CB-{0000000000}</displayFormat>
        <label>Competitor Brands Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PRH_Luxury_Accounts__c.object
<CustomObject>
    <description>PRH - Iconic Platform</description>
    <fields>
        <fullName>PRH_Account_Region__c</fullName>
        <label>Account Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PR EMEA</fullName>
                </value>
                <value>
                    <fullName>PR Asia</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>PR Winemakers</fullName>
                </value>
                <value>
                    <fullName>PR North America</fullName>
                </value>
                <value>
                    <fullName>PR LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRH_High_Networth_Individuals__c</fullName>
        <defaultValue>false</defaultValue>
        <label>High Networth Individuals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRH_Number_of_Pernod_Ricard_products__c</fullName>
        <label>Number of Pernod Ricard products</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRH_Owner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Only applicable to France, default Owner is from Pernod, Owner 2 stores the sales rep of Ricard</description>
        <label>Owner 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PRH_Luxury_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRH_Suppress_and_archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress</label>
        <type>Checkbox</type>
    </fields>
    <label>Iconic Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iconic Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PRH_BatchBrandCreationForCollectsTest.cls
// Le Cercle application - evolution LCS-11 - January 2017
// Test class for batch that create Competitor and Le Cercle brands linked to collects
@isTest(SeeAllData = false) 
private class PRH_BatchBrandCreationForCollectsTest {
	
	@testSetup static void setUpData() {
        List<PRH_Luxury_Accounts__c> iconicAccounts = new List<PRH_Luxury_Accounts__c>();
        PRH_Luxury_Accounts__c acc;
		DateTime dt = DateTime.now(); 
		String dateTimeStr = dt.format('YYMMDD_hhmmss'); 
		List<PRH_Collect__c> listOfNewCollects = new List<PRH_Collect__c >();
		Profile adminp = [select id from profile where Name = 'System Administrator' limit 1];    
        System.debug('dateTimeStr : '+ dateTimeStr);
        
        // Creation of 5 users (iconic account's owners)
        Profile p = [SELECT Id FROM Profile WHERE Name='PRH_Iconic_Platform']; 
        User u1 = new User(Alias = 'user1', Email='PRH_testuser1'+dateTimeStr+'@prhtestorg.com', 
            EmailEncodingKey='UTF-8', LastName='TestingUser1', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PRH_testuser1'+dateTimeStr+'@prhtestorg.com');
        insert u1;
        User u2 = new User(Alias = 'user2', Email='PRH_testuser2'+dateTimeStr+'@prhtestorg.com', 
            EmailEncodingKey='UTF-8', LastName='TestingUser2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PRH_testuser2'+dateTimeStr+'@prhtestorg.com');
        insert u2;
        User u3 = new User(Alias = 'user3', Email='PRH_testuser3'+dateTimeStr+'@prhtestorg.com', 
            EmailEncodingKey='UTF-8', LastName='TestingUser3', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PRH_testuser3'+dateTimeStr+'@prhtestorg.com');
        insert u3;

		User user1 = [SELECT Name, Id FROM User WHERE (UserName LIKE 'PRH_testuser1%') LIMIT 1];
		User user2 = [SELECT Name, Id FROM User WHERE (UserName LIKE 'PRH_testuser2%') LIMIT 1];
		User user3 = [SELECT Name, Id FROM User WHERE (UserName LIKE 'PRH_testuser3%') LIMIT 1];

		System.debug('==> user1.Id : '+ user1.Id);
		System.debug('==> user2.Id : '+ user2.Id);
		System.debug('==> user3.Id : '+ user3.Id);
		        
		User ic_myUser = [SELECT Id FROM User WHERE Email LIKE 'PRH_testuser3%prhtestorg.com' LIMIT 1];
        System.runAs(ic_myUser) { 
            
            // Creation of some Iconic Brands		
			PRH_Brand_Luxury_Brand__c ib1 = new PRH_Brand_Luxury_Brand__c();
            ib1.Name = 'Martell XO';
			ib1.PRH_Competitor_Brand__c = false;
			ib1.PRH_Sequence__c = 'LCEB0001';
			ib1.PRH_PIM_ID__c = 'PIM001';
			ib1.PRH_Active__c = true;
            ib1.recordTypeId = Schema.SObjectType.PRH_Brand_Luxury_Brand__c.getRecordTypeInfosByName().get('Luxury Account - Pernod').getRecordTypeId();
            insert ib1;
			
			PRH_Brand_Luxury_Brand__c ib2 = new PRH_Brand_Luxury_Brand__c();
            ib2.Name = 'PJ Belle Epoque and above';
			ib2.PRH_Competitor_Brand__c = false;
			ib2.PRH_Sequence__c = 'LCEB0002';
			ib2.PRH_PIM_ID__c = 'PIM002';
			ib2.PRH_Active__c = true;
            ib2.recordTypeId = Schema.SObjectType.PRH_Brand_Luxury_Brand__c.getRecordTypeInfosByName().get('Luxury Account - Pernod').getRecordTypeId();
            insert ib2;
			
			PRH_Brand_Luxury_Brand__c ib3 = new PRH_Brand_Luxury_Brand__c();
            ib3.Name = 'Dom Perignon';
			ib3.PRH_Competitor_Brand__c = true;
			ib3.PRH_Sequence__c = 'COMP0001';
			ib3.PRH_PIM_ID__c = 'PIMC001';
			ib3.PRH_Active__c = true;
            ib3.recordTypeId = Schema.SObjectType.PRH_Brand_Luxury_Brand__c.getRecordTypeInfosByName().get('Luxury Account - Competitor').getRecordTypeId();
            insert ib3;
            
			// Creation of the Iconic Accounts
			for (Integer i=0; i < 6; i++) { 
				if (i < 3) {
					acc = new PRH_Luxury_Accounts__c(
						Name = 'Fraccount-'+i,
                        PRH_High_Networth_Individuals__c = false,
						PRH_Suppress_and_archive__c = false,
						PRH_Account_Region__c = 'PR LATAM'
					);
					iconicAccounts.add(acc); 
				} else {
					acc = new PRH_Luxury_Accounts__c(
						Name = 'Zoo-'+i,
						PRH_High_Networth_Individuals__c = false,
						PRH_Suppress_and_archive__c = false
						//PRH_Number_of_Pernod_Ricard_products__c = 1
					);
					iconicAccounts.add(acc); 
				}
			}	
			insert iconicAccounts;
			
			PRH_Luxury_Accounts__c accountToUpdate; 
            try {         
                // Update account 
                accountToUpdate =  
                    [SELECT Name, Id FROM PRH_Luxury_Accounts__c WHERE (Name LIKE 'Fraccount-2%') LIMIT 1]; 
                // Update the owner and owner2
                accountToUpdate.OwnerId = user1.Id;
                accountToUpdate.PRH_Owner_2__c = user2.Id;
                // Make the update call
                update accountToUpdate; 
				
				// Update account 
                accountToUpdate =  
                    [SELECT Name, Id FROM PRH_Luxury_Accounts__c WHERE (Name LIKE 'Zoo-5%') LIMIT 1]; 
                // Update the owner and owner2
                accountToUpdate.OwnerId = user1.Id;
                accountToUpdate.PRH_Owner_2__c = user2.Id;
                // Make the update call
                update accountToUpdate; 
            } catch(DmlException e) { 
                System.debug('An unexpected error has occurred: ' + e.getMessage());  
            }		
		}
    }
    
	@isTest static void Test_PRH_BatchBrandCreationForCollects() {
        
        User ic_myUser = [SELECT Id FROM User WHERE Email LIKE 'PRH_testuser3%prhtestorg.com' LIMIT 1];
		System.debug('==> Test_PRH_BatchBrandCreationForCollects() ic_myUser : '+ ic_myUser);
		
        System.runAs(ic_myUser) {         	
			System.Test.startTest(); 
			
            List<PRH_Competitor_Brands__c> newCompetitorBrandsListbefore = [SELECT Id, Name FROM PRH_Competitor_Brands__c];
            System.debug('==> newCompetitorBrandsListbefore : '+ newCompetitorBrandsListbefore);
			System.assertEquals(6,newCompetitorBrandsListbefore.size());
            
            PRH_ManageCollectsForIconicAcc action = new PRH_ManageCollectsForIconicAcc();
            action.ManageCreationOfCollectsForIconicAcc();
            
			Database.executeBatch(new PRH_BatchBrandCreationForCollects());
			
			System.Test.stopTest(); 
			
            List<PRH_Collect__c> listActiveColl = [Select id From PRH_Collect__c Where PRH_Active__c=true ];
            System.debug('==> listActiveColl.size() : '+ listActiveColl.size());
            
			List<PRH_Competitor_Brands__c> newCompetitorBrandsList = [SELECT Id, Name FROM PRH_Competitor_Brands__c where PRH_Collect__c In :listActiveColl ];
            System.debug('==> newCompetitorBrandsList : '+ newCompetitorBrandsList);
			System.assertEquals(6,newCompetitorBrandsList.size());

			List<PRH_Brand_Criteria__c> newLeCercleBrandsList = [SELECT Id, Name FROM PRH_Brand_Criteria__c  where PRH_Collect__c In :listActiveColl];
			System.assertEquals(newLeCercleBrandsList.size(),12);
		}   	
    }
    
    @isTest static void Test_PRH_ScheduleBatchBrandsCreationForCollects() {
        
        User ic_myUser = [SELECT Id FROM User WHERE Email LIKE 'PRH_testuser1%prhtestorg.com' LIMIT 1];
		System.debug('==> Test_PRH_ScheduleBatchBrandsCreationForCollects() ic_myUser : '+ ic_myUser);
		
        System.runAs(ic_myUser) {         	
			System.Test.startTest(); 
			
			String CRON_EXP = '0 0 0 2 3 ? 2098';
			String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, new PRH_ScheduleBatchBRCreationForCollects()); 
			
			CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];

			System.assertEquals(CRON_EXP, ct.CronExpression); 
			System.assertEquals(0, ct.TimesTriggered);
			
			System.Test.stopTest(); 
		}   	
    }
}